### ISSUE TITLE
doc: Clarify the interaction of TestActorRef with Persistent actor

### ISSUE THREAD

**Issue by giampaolotrapasso** [akka/akka#18061] opened 2015-07-23 13:11 UTC
Please clarify in Testing documentation that using TestActorRef with a PersistentActor (or with a AtLeastOnceDelivery trait mixed-in) leads to an unexpected behavior and must be avoided.

TestActorRef forces the CallingThreadDispatcher, which does not mix well with Actors which need to perform work in the background like the indicated cases. 

This issue comes from this conversation on user list. https://groups.google.com/forum/#!topic/akka-user/r_WW2FUZajo

**Comment by ktoso** [comment] 2015-07-23 13:14
Hi @giampaolotrapasso,
sounds like a duplicate of https://github.com/akka/akka/issues/15569 which was resolved by https://github.com/akka/akka/pull/17940 already.

Is there something you're missing from that docs update?

**Comment by giampaolotrapasso** [comment] 2015-07-23 13:24
Sorry, my bad.

**Comment by ktoso** [comment] 2015-07-23 13:25
No problem, thanks for raising the problem!
In case the added docs don't address your confusion please let us know

**Comment by giampaolotrapasso** [comment] 2015-07-23 13:32
My humble suggestions: 
- the information is in a light blue box (note), maybe a warning level would make it more visible. (Testing page)
- don't know if it's good to report the warning also in the Persistence page of documentation (Testing section).

**Comment by ktoso** [comment] 2015-07-27 11:46
Good points; adding it to the testing section of persistence makes a lot of sense - thanks!

**Closed** 2015-08-14 11:49 UTC
Labels: 3 - in progress, t:docs, t:persistence
