### ISSUE TITLE
Handling chunked responses for http requests in akka 2.4.3

### ISSUE THREAD

**Issue by cmbaxter** [akka/akka#20248] opened 2016-04-06 14:05 UTC
I think this might be a regression between 2.4.2 and 2.4.3.  In akka 2.4.3, I'm consuming a http service that is sending back a chunked response, but it's a single chunk and the response header indicates

`Connection: close`

In this case, I can not force the response entity to strict via `.toStrict` as it always just times out saying it is still waiting for more data.  If I hit another one of the chunking services that I am consuming that does have multiple chunks in a large response, it works correctly, I think because the connection header is:

`Connection: keep-alive`

So I think something happened between 2.4.2 and 2.4.3 where if you consume a http service and you get back a single chunked response and the connection is closed by the server that it fails.  Both cases (single chunk, closed and multi chunk, keep-alive) worked in akka 2.4.2.

**Comment by ktoso** [comment] 2016-04-06 14:12
Thanks for reporting, would you be able to put together something the likes of a reproducer to speed up finding the cause of this?

**Comment by 2beaucoup** [comment] 2016-04-06 14:20
Could be the same as #20236.

**Comment by cmbaxter** [comment] 2016-04-06 14:45
@ktoso, @2beaucoup, I agree that this issue is most likely the same as https://github.com/akka/akka/issues/20236.  Do you still want me to try and come up with a self contained example showing the issue?

**Comment by ktoso** [comment] 2016-04-06 14:48
I totally forgot the other issue had a reproducer, let's try that one for now.

**Comment by MartinSeeler** [comment] 2016-04-07 12:44
Since the other issue only metnions HTTP 1.0, I think this is no the same. I encountered the same issue with HTTP 1.1.

**Comment by ktoso** [comment] 2016-04-07 12:47
Please read the other issue in detail @MartinSeeler – title is misleading, it affects both versions.

**Comment by ktoso** [comment] 2016-04-07 12:47
Closing this one as duplicate of #20236 (will fix title there, also PR already done to fix this)

**Closed by ktoso** 2016-04-07 12:47 UTC
Labels: 1 - triaged, 2 - pick next, bug, t:http, t:http:client
