### ISSUE TITLE
ArteryUpdSendConsistencyWithThreeLanes

### ISSUE THREAD

**Issue by johanandren** [akka/akka#27954] opened 2019-10-09 15:25 UTC
Three failed tests:

 * Artery must be able to identify a remote actor and ping it
 * Artery must be able to send messages concurrently preserving order
 * Artery must be able to send messages with actorSelection concurrently preserving order

https://jenkins.akka.io:8498/job/akka-nightly/7003/

**Comment by patriknw** [comment] 2019-10-10 09:26
Can't see anything obvious here. The initial Identify doesn't make it.

```
[info] - must be able to identify a remote actor and ping it *** FAILED *** (5 seconds, 111 milliseconds)
[WARN] [10/09/2019 04:03:45.642] [systemB-akka.actor.default-dispatcher-19] [akka://systemB/user/otherEcho1] received dead letter from Actor[akka://ArteryUpdSendConsistencyWithThreeLanesSpec/system/testActor-1148#-579967067]: 72
[info]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:528)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:510)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:509)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:928)
[info]   at akka.remote.artery.AbstractRemoteSendConsistencySpec.$anonfun$new$2(RemoteSendConsistencySpec.scala:76)
```

**Comment by jrudolph** [comment] 2019-10-28 09:51
Same three tests failed here:

https://jenkins.akka.io:8498/job/akka-nightly/7058/

This might be a duplicate of #25609 and #27580

**Comment by raboof** [comment] 2020-01-15 12:17
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/18682/

**Comment by jrudolph** [comment] 2020-01-20 12:13
https://jenkins.akka.io:8498/job/akka-artery-aeron-udp-remote-tests/261/testReport/junit/akka.remote.artery/ArteryUpdSendConsistencyWithThreeLanesSpec/Artery_must_be_able_to_identify_a_remote_actor_and_ping_it/

**Comment by chbatey** [comment] 2020-03-06 07:46
https://jenkins.akka.io:8498/job/akka-nightly-2.13/463/consoleFull

**Comment by patriknw** [comment] 2020-04-27 06:44
and here https://jenkins.akka.io:8498/job/akka-artery-aeron-udp-remote-tests/359

note that it's in the startup "identify a remote actor and ping it"

**Comment by renatocaval** [comment] 2020-04-28 09:59
I have the impression we are duplicating messages and some messages are leaking to the next test. 

Here is what we have in the latest log:

**Failed**
```scala
[info] - must be able to identify a remote actor and ping it *** FAILED *** (5 seconds, 189 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
```
No message after 5 seconds, seems to get lost.

**Passed**
```scala
[info] - must not send to remote re-created actor with same name (2 seconds, 14 milliseconds)
```
This test passed. All expectations were fine. So, message from previous test (eg: ActorIdentity) really got lost. 


**Failed**
```scala
[info] - must be able to send messages concurrently preserving order *** FAILED *** (7 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected success, found ActorIdentity(None,Some(Actor[akka://systemB@localhost:43018/user/echoC#-959494829]))
```

This really looks like a duplication. When we are expecting `success`, we have already consumed `ActorIdentity` from `echoC`. How is it possible that the probe is seeing that again? 


**Failed**

```scala
[info] - must be able to send messages with actorSelection concurrently preserving order *** FAILED *** (340 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected success2, found success
```

Finally, here it seems that a `success` message from previous test just leaked into the next one.

**Comment by renatocaval** [comment] 2020-04-28 11:09
I'm wondering if the first `ActorIdentity ` message is somehow getting absurdly delayed. 

Then the second test just got the chance to not be disturbed by it. 

The message arrives when we were on the third test and since we only check the type, not the content, we consumed it on the first part, when we are reading the actor selection. That explains why we later get a `ActorIdentity` for `echoC`. 

And because the third test failed, there is a `success` message that leaks to the nest.

**Comment by chbatey** [comment] 2020-05-04 06:26
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/589/testReport/junit/akka.remote.artery/ArteryUpdSendConsistencyWithThreeLanesSpec/

**Comment by patriknw** [comment] 2020-08-17 12:12
Related or duplicate of https://github.com/akka/akka/issues/29465

**Comment by raboof** [comment] 2022-02-21 14:48
let's close this one and follow it as #29465

**Closed by raboof** 2022-02-21 14:48 UTC
Labels: failed, t:remoting:artery
