### ISSUE TITLE
A way to fail ask Future from response message

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25781] opened 2018-10-11 10:32 UTC
Untyped Status.Failure can't be used as reply message since it's typically not the right type.

We can add a:

```scala
trait AskFailure {
  def reason: String
}
```

that can be used for reply messages that should be treated as ask failures.

I think this is mostly needed for compatibility (make migration easier) and we should not encourage usage of this for business validation errors.

**Comment by johanandren** [comment] 2018-10-11 11:22
I think that if we have it, people most certainly use it for their validation errors, so we must also make that we don't encourage it very clear with docs etc.

**Comment by viktorklang** [comment] 2018-10-11 12:30
I suspect AskFailure as defined in this Issue won't be enough since current Status.Failure accepts an Exception type? (I'm thinking for migration for instance)

**Comment by renatocaval** [comment] 2018-10-11 12:38
Would `abstract class AskFailure(msg: String) extends Exception(msg)` help?

Then a user can define

```scala
sealed Confirmation
case object Accepted extends Confirmation
class Reject(reason: String) extends AskFailure(reason) with Confirmation
```

**Comment by patriknw** [comment] 2018-10-11 12:43
Serializing exceptions is a pain so that is something I want to discourage even more, but I can understand the point of compatibility.

```scala
trait AskFailure {
  def reason: Any
}

class AskException(message: String, reason: Any) extends RuntimeException
```

if the `reason` is a `Throwable` we fail the Future with that exception, otherwise we fail the Future with `AskException(s"bla, bla, caused by ${reply.reason}", reply.reason)`

**Comment by viktorklang** [comment] 2018-10-11 12:43
@renatocaval No, I don't think so—right now they user can send any Throwable (even throwables which are cached/singletons, or Throwables that they do not create or cannot extend).
May I suggest that the first course of action is to define what the feature should be able to support? :)

**Comment by renatocaval** [comment] 2018-10-11 12:45
About encouraging the usage or `AskFailure` for general purpose.

Why should we be so opinionated about how people should deal with errors? 

This can be of great help in cases where different `ask`s are combined in an for-comprehension. 

It's the different between this...

```scala
for {
_ <- actor1 ? Foo
_ <- actor2 ? Bar
_ <- actor2 ? Baz
} yield. ...
```

and this...

```scala
def handleError(res: Futue[MyError] = {
  res.collect { 
     case MyError => throw new RuntimeException() 
     case other => other
  }
}
for {
_ <- handleError(actor1 ? Foo)
_ <- handleError(actor2 ? Bar)
_ <- handleError(actor2 ? Baz)
} yield. ...
```

From a pragmatic perspective, I would prefer, as a user, to define in my protocol that Futures completed with messages of type `MyError` are failed futures and not have to handle that over and over again.

**Comment by viktorklang** [comment] 2018-10-11 15:02
@renatocaval But with the `handleError` solution you now have to first learn that pattern, and the stacktrace of the exception is completely different.

**Comment by renatocaval** [comment] 2018-10-12 08:36
I think you didn't mean "but with the `handleError`", but "in addition, with the `handleError`". 

I find the `handleError` solution a bad one. I didn't think about the stacktrace though. I was more thinking on how to shortcircuit the `flatMap`. 

On the other hand, if the intention is to just shortcircuit, then the stacktrace is less relevant. The problem is more when you fail the `Future` at call site and pass it over.

**Comment by liutaon** [comment] 2019-10-16 01:05
# Classic actor

It’s simple to reply exception to sender in classic actor.

```scala
class MyActor extends Actor {
  def receive: Receive = {
    case "Bomb" => Future.failed(new Exception("Error")).pipeTo(sender())
  }
}

ref.ask("Bomb").mapTo[String].andThen {
  case Success(value) => println("Pong: " + value)
  case Failure(ex)    => println("Error: " + ex) // time out or other exception
}
```

# Typed Actor

It's more *complex* to reply exception in typed actor. 

Is there an easy way to do it? 

```scala
sealed trait Reply
final case class ReplySuccess(pong: String) extends Reply
final case class ReplyError(exception: String) extends Reply

sealed trait Request
final case class PingRequest(ping: String, replyTo: ActorRef[Reply]) extends Request

def apply: Behavior[Request] = Behaviors.setup { context =>
  Behaviors.receiveMessage {
    case PingRequest("Bomb", replyTo) =>
      replyTo ! ReplyError("Error")
      Behaviors.same
  }
}

ref.ask[Reply](r => PingRequest("Bomb", r)).andThen {
  case Success(ReplySuccess(value)) => println("Pong: " + value)
  case Success(ReplyError(ex))      => println("Error: " + ex)
  case Failure(ex)                  => println("Error: " + ex) // time out
}
```

**Comment by patriknw** [comment] 2019-10-16 12:02
Your example with `Reply`, `ReplySuccess` and  `ReplyError` is good. It models the message protocol explicitly, which is fundamental in Akka Typed. It shows that there can be an error that needs to be handled. There could be several different types of errors that need different treatment.

If you want to treat the `ReplyError` as a failed future on the client side you can do that:
```
val result: Future[ReplySuccess] = ref.ask[Reply](r => PingRequest("Bomb", r)).map {
        case s: ReplySuccess => s
        case e: ReplyError   => throw new RuntimeException(e.exception)
      }
```

(or with flatMap if throwing is not desired)

The difference is that it's the requestor that decides instead of the destination. Note that the destination shouldn't really have to care about if the message was sent with an ask or a tell, which it kind of does in the Classic example when replying with the special Status.Failure message.

The parent child forward can be done with:
```
ref ! req
```

`forward` is only sugar on top of `ref.tell(req, sender())` and since the `sender()` is now explicitly in the message instead the message can be sent on to the next actor with ordinary `!`.

**Comment by bdoyle0182** [comment] 2019-11-26 00:32
This seems like a rather obtuse way to implement failure handling for external asks for typed actors. For each behavior you're making the user make a parent reply type. This seems like something that should be built in to asks when almost always you're going to need more granular failure handling than just an ask timeout. Maybe have a behavior type that adds in failure handling by creating that boiler plate reply code for the behavior?

**Comment by bdoyle0182** [comment] 2019-11-26 19:29
I created a generic object that can be used for processing external ask replies simply and with reusability. We're only using this for local asks so we don't have to deal with serialization. For anyone that comes across this issue...

```
object TypedAskReply {

  sealed trait Reply[T]

  private case class ReplySuccess[T](response: T) extends Reply[T]
  private case class ReplyFailure[T](throwable: Throwable) extends Reply[T]

  def unwrapReply[T](reply: Future[Reply[T]])(implicit ec: ExecutionContext): Future[T] = {
    reply.map({
      case ReplySuccess(value) => value
      case ReplyFailure(throwable) => throw throwable
    })
  }
}
```

Then to use for an ask...

```
case class ProcessRequest(replyTo: ActorRef[Reply[String]])

// generic message handling just for example
Behaviors.receiveMessage { message: ProcessRequest => {
    if (sendSuccess) {
      message.replyTo ! ReplySuccess("success") 
    } else {
      message.replyTo ! ReplyFailure(new Exception("failure"))
    }
  }
}

//in an external actor
val senderRef = sender()
val typedAsk: Future[Reply[String]] = processRequestActor ? (ProcessRequest(_))
unwrapReply(typedAsk) pipeTo senderRef
```

...senderRef gets back the future as a successful string or failed throwable

**Comment by patriknw** [comment] 2019-12-10 12:36
Thanks for sharing. That is good because then you have declared that the message types of the `Reply` can be `ReplySuccess` and `ReplyFailure`.

`case class ReplySuccess[+T](response: T)` isn't a good message for an actor to receive because it can't see the difference of `ReplySuccess[Foo]` and `ReplySuccess[Bar]`, but it works for ask.

It will be difficult to generally serialize/deserialize `ReplyFailure[+T](throwable: Throwable)` (in a secure way), but works if specific serializers for the used exceptions are defined.  Akka has [support for a few exception types](https://github.com/akka/akka/blob/87b94b65fd1ad5ccf9b0cf5b7080e2dc3f181d74/akka-remote/src/main/resources/reference.conf#L103-L116).

**Comment by bdoyle0182** [comment] 2020-01-29 18:25
Yea I should have been more explicit that it's strictly for handling responses to asks. You shouldn't be building your actors with these as message types they handle as you said.

**Comment by johanandren** [comment] 2020-07-29 13:39
I think this is covered by StatusReply and askWithStatus #29133

**Comment by renatocaval** [comment] 2020-08-26 08:06
I'm closing this one as it's introduced in #29190

**Closed by renatocaval** 2020-08-26 08:06 UTC
Labels: 1 - triaged, t:typed
