### ISSUE TITLE
Akka Http Streams don't seem to reliably call downstream complete

### ISSUE THREAD

**Issue by ddispaltro** [akka/akka#18511] opened 2015-09-17 23:34 UTC
I think I may have found a bug in akka streams.  I specifically am having trouble with akka streams not completing.  I have an example repo which is the bare minimum I needed to reproduce the problem.  I couldn't reproduce the issue with a simpler `Source` so I wanted to use persistent query as a way to simulate an infinite stream.

The example repo is [here](https://github.com/ddispaltro/streamstest) it took a couple of times restarting the process and connecting to `http://127.0.0.1:9000/live` and disconnecting to have the `onDownstreamFinish` stop firing.

Let me know if you need more info.  I was working on gitter with @ktoso

**Comment by jrudolph** [comment] 2015-09-18 08:02
This seems very similar to the situation I recently filed as #18482. The problem is that you can only detect that the other side has stopped reading (i.e. that it has let go of its socket) by actively sending a packet to the other side. So, if you don't send anything you will not figure out that the other side is gone. If the other side is just not answering any more, you cannot find out at all, if it will reappear ant continue reading some time later. See #18482 for the proposed solutions.

**Comment by ktoso** [comment] 2015-09-18 08:03
Yeah, I can confirm is as Johannes describes. Here the query does not write
anymore, so we get into this situation.

Will look at the other tichet (traveling now)

**Comment by ddispaltro** [comment] 2015-09-18 18:06
This is it, perfectly explained.  All my results are now consistent with this.  @ktoso I owe you on sticking with this.  So I guess timeout stuff will help lingering streams, right? Basically no messages received in a period of time will kill a stream?

**Comment by ktoso** [comment] 2015-09-18 23:21
Correct, we're thinking on how to best expose this currently. Thanks for bringing up this problem scenario!

**Comment by ktoso** [comment] 2016-05-19 01:18
Closing behaviours have been worked on and we'll do some more, closing as not actionable per-se here

**Closed** 2016-05-19 01:18 UTC
Labels: obsolete – reopen if necessary, t:http
