### ISSUE TITLE
[akka-http] formFields directive only works with requests containing HttpEntity.Strict

### ISSUE THREAD

**Issue by rklaehn** [akka/akka#19506] opened 2016-01-18 13:56 UTC
When using a `formFields` directive with a large post request that has a non-strict HttpEntity, the request fails with the following error:

```
The form field 'imageId' was malformed:
Substream Source cannot be materialized more than once
```

Here is a reproducer https://gist.github.com/rklaehn/d4d3ee43443b0f4741fb

When using this with a large image upload, you will get the exception mentioned above. When transforming the HttpEntity to strict (see UploadHandlerToStrict.scala), everything works as expected.

Note that the code below also fails when uploading a large image. So this is unrelated to the  uploadedFile directive. The large image is just the cause for a non-strict HttpEntity to be produced by the browser.

```scala
  val route: Route = {
    (path("resize") & post) {
      formFields('imageId, 'sizes, 'rotate ? "normal") { (imageId, sizesStr, rotateStr) =>
        complete("ok")
      }
    }
  } ~ getFromResourceDirectory("web")
```

**Comment by jrudolph** [comment] 2016-01-18 18:48
This is probably a duplicate of #18591.

**Comment by jrudolph** [comment] 2016-09-08 16:35
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Closed by jrudolph** 2016-09-08 16:35 UTC
Labels: bug, t:http, t:http:server
