### ISSUE TITLE
Unicode alias from → to -> in FSM

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20233] opened 2016-04-05 10:08 UTC
As noticed by @bwmcadams in https://github.com/akka/akka/pull/19746

**Comment by ktoso** [comment] 2016-04-05 10:09
Need to fix it to unblock scalariform move.

**Comment by ktoso** [comment] 2016-04-05 14:41
MiMa mislead me...

**Comment by patriknw** [comment] 2016-06-03 05:25
Duplicate of https://github.com/akka/akka/issues/19772

**Closed by patriknw** 2016-06-03 05:25 UTC
Labels: 1 - triaged, t:core
