### ISSUE TITLE
Add GetClusterShardRegionState

### ISSUE THREAD

**Issue by jamesmulcahy** [akka/akka#19550] opened 2016-01-21 01:57 UTC
GetClusterShardRegionStats exists to get stats from all the ShardRegions, this yields a member-by-member view of (regionId -> sharedCount).

GetShardRegionState can be sent to a specific region, to get region specific (shardId -> entityId) information.

It'd would be awesome if there was a GetClusterShardRegionState variant, like we have for stats.  There are times when it's useful to be able to query where a given entity exists within the cluster.

**Comment by johanandren** [comment] 2016-01-21 09:37
That was excluded on purpose since we expect sharding to be used with very big numbers of actors which could potentially overload the cluster and we do not want to encourage dangerous things like that. 

See discussion here
https://github.com/akka/akka/pull/18543#discussion_r40403292 and here #18714

If this is what you want it is not too hard to code up yourself (which should also make you more aware of the consequences in your specific application). Closing as duplicate of #18714

**Closed by johanandren** 2016-01-21 09:37 UTC

**Comment by patriknw** [comment] 2016-01-22 07:01
+1, Johan

**Comment by jamesmulcahy** [comment] 2016-01-22 18:56
Thanks for the reply, I understand your reasoning here.  In our case, the number of shards is modest, and so I don't have much concern about taking the "manual" approach myself.  Reading the comments in #18543, Patrick suggests the interfaces return 'Addresses' rather than ActorPaths, and that does indeed seem to be what the 2.4-SNAPSHOT APIs expose today.  I'm unsure however to use an 'Address'.  Could someone help me understand how I can take an Address and route a message to the ShardRegions on those nodes to manually make the request I'm after?

I'm not looking for a worked code example, just a 'Take a look at API xxx' or similar.   RootActorPath looks handy here, but I still need some way of identifying the path to the remote shard regions, I think?

Thanks in advance!

**Comment by patriknw** [comment] 2016-02-02 13:05
`context.actorSelection(RootActorPath(addr) / "user" / "foo" / "bar") ! Identify(id)`

**Comment by jamesmulcahy** [comment] 2016-03-09 06:32
For the benefit of anyone else who wants to try and do this, the specific path you need to target (instead of "user" / "foo" / "bar") is "system" / "sharding" / typeName
