### ISSUE TITLE
possibly support “linear” fan-out operators

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18598] opened 2015-09-29 15:47 UTC
like
~~~
source.broadcast(
  src => src.map(...).to(Sink...),
  src => src.filter(...).to(Sink...))
~~~

**Comment by drewhk** [comment] 2015-09-29 15:48
Duplicate of

**Closed** 2015-09-29 15:48 UTC
Labels: t:stream

**Comment by rkuhn** [comment] 2015-09-29 15:50
Hmm, why didn’t yours show up on my Bee?

**Comment by drewhk** [comment] 2015-09-29 15:56
sorry, I won ;)
