### ISSUE TITLE
Ask pattern needs a (ActorRef => Any) variant for Streams mapAsync support

### ISSUE THREAD

**Issue by DomBlack** [akka/akka#17747] opened 2015-06-16 14:11 UTC
Akka's general advice (and requirement with the akka-typed) is for protocols which need a response to include the `ActorRef` of where to send the response to.

For instance:
```scala
case class GetJob(jobID: Long, sender: ActorRef) extends WorkerProtocol
```

This works fine when your inside an actor and can send a request with `self` as the sender, however in Akka streams if you need to do something as part of the flow with a stage like `JobID => JobData` it is recommended to use a mapAsync (See @rkuhn comments on #16985).

However the existing ask pattern does not allow us access to the `ActorRef` which is created for the ask, meaning we cannot use the recommended approach on Non-typed actors. (Typed actors have their own ask pattern, which already supports this: https://github.com/akka/akka/blob/master/akka-typed/src/main/scala/akka/typed/Ask.scala#L38)

Could the non-typed Ask patten, also get a; `def ?(f: ActorRef => Any)` method to allow future proofing against akka-typed in streams?

**Comment by rkuhn** [comment] 2015-06-16 14:50
This is a duplicate of #15819, but thanks for the additional use-case!

**Closed** 2015-06-16 14:52 UTC
