### ISSUE TITLE
Http DSL: produce specific rejections from PathMatchers that unmarshal a type

### ISSUE THREAD

**Issue by agemooij** [akka/akka#18733] opened 2015-10-16 17:25 UTC
There was this question on the `spray/spray` Gitter channel:

> I there any way to create path("guid" / JavaUUID) { } which would match UUID and if it is not properly formatted UUID, it would reject request with Bad Request?

The `rawPathPrefix` directive [always rejects with an empty rejection list](https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-1.0/akka-http/src/main/scala/akka/http/scaladsl/server/directives/PathDirectives.scala#L37) while it might be very useful for users to provide some kind of unmarshalling rejection when a `PathMatcher` fails during conversion. This allows the user to handle those rejections at the level that they need, either by wrapping with the `handleRejections` directive or by letting the rejection bubble up to the default handler.

Of course this might interfere with the current way that 404/NotFound is currently handled so those rejections might have to be cancelled at some level? Might be a tricky one to achieve without deep changes.

**Comment by ktoso** [comment] 2016-05-19 00:55
Nice idea, would be a cool contrib

**Comment by kwyczesany** [comment] 2016-06-08 10:30
I would like to try to solve this issue. Let me know if i understand the task correctly. 

- If a somebody will provide a parameter to the path then in case of some kind of a parsing error the rejection should have some additional information? Could I use `MalformedQueryParamRejection` class to do this? 

- If there is no parameter provided to the path then should I just reject without any information ?

Regarding the 404, I'm not sure if this change could affect the `NotFound` handling ?

**Comment by agemooij** [comment] 2016-06-08 10:43
Yeah, the "normal" way to reject paths is using an empty rejection list, even if the path matcher contains extractions that produce exceptions or errors. The idea is to: 

- create a new specialized rejection type, something like `PathMatcherExtractionFailed`
- adjust path concatenation to cancel that rejection (or allow it through without negative side effects) so the next path in the chain is still tried in the same way as now
- add support for this rejection in the default rejection handler so that when it bubbles out of a path chain (i.e. when all paths have failed to match). The big question si what to do by default in such a case of course. A 404 would be weird but a 400 would also be weird because you did try other paths.

All of this will allow users to at least deal with invalid paths in a custom way should they want to. At the moment this is impossible.

**Comment by ktoso** [comment] 2016-06-08 13:40
Just as @agemooij explained :-)
Let us know if you have any further questions - I've marked it as in proghress.

**Comment by kwyczesany** [comment] 2016-06-20 11:52
I am struggling with this issue and I have a problem with distinguishing when the path is not found and when it have some parsing errors. I've tried to add another object extending `Matching`, something like `Unextracted` to let me know which situation  i'm facing. But the problem is that the implementation of `PathMatcher` works on `Option` and when something goes wrong, I'll loose information about the reasons because the only result is `None`. I'm wondering if using a `Try` would be more helpful here? Any hints would be highly appreciated, because I'm kind of stuck here.

**Comment by ktoso** [comment] 2016-09-08 19:29
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Closed by ktoso** 2016-09-08 19:29 UTC
Labels: 3 - in progress, community, nice-to-have (low-prio), t:http, t:http:server:dsl
