### ISSUE TITLE
Document use of DetachedContext.pushAndPull from onUpstreamFinished

### ISSUE THREAD

**Issue by jroper** [akka/akka#18285] opened 2015-08-21 03:57 UTC
If using a `DetachedStage`, and, when upstream finishes, you are holding downstream and want to push something downstream, it seems (and maybe I'm wrong, but my code seems to work) that it is ok to use `pushAndPull` to do this.  But that seems completely unintuitive, since I would expect a `pull` to fail if the stream is finishing.  So, either `ctx.push()` (and `ctx.pushAndFinish()`) should be allowed from `DetachedStage.onUpstreamFinish()` to handle the case where you want to push when you're holding downstream (currently they are not because `onUpstreamFinish` must return a termination directive), or it should be documented that `ctx.pushAndPull()` is allowed to be used from `ctx.onUpstreamFinish()`.

**Comment by drewhk** [comment] 2015-08-25 12:01
Nothing else other than finish(), fail() or absorbTermination() is allowed to be called from onUpstreamFinish(). You need to handle everything in the next onPull operation, which will happen if you are holding the downstream.

**Comment by jroper** [comment] 2015-08-26 00:25
My understanding is, if you are holding downstream, that means you received an `onPull`, and you returned `ctx.holdDownstream`, which means that you can't receive another `onPull` until you push downstream.  So that's not right, if you are holding downstream, you will not get an `onPull`, as that would violate the rules, you would end up with demand for two elements if you received a second `onPull`.

**Comment by drewhk** [comment] 2015-08-26 08:31
> So that's not right, if you are holding downstream, you will not get an onPull, as that would violate the rules, you would end up with demand for two elements if you received a second onPull.

The purpose of absorbTermination() is to recover possibly missed activation tokens (i.e. to avoid hanging the stage forever). The rules (which need to be better documented, yes, there is already explanation for the PushPullStage: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/stream-customize.html#Completion_handling) are:
 - if you are a PushPullStage, and your last call was .pull, you will get an onPull, since you will never get a push from the upstream ever, so an event needs to be triggered, which is onPull
 - if you are a PushPullStage, and your last call was push, nothing will happens, as the downstream will eventually call a pull
 - if you are a DetachedStage and you are holding the downstream, then to avoid hanging, an onPull will be called to reinject the token you were holding to give a chance to react to the event
 - if you are a DetachedStage and you are not holding the downstream then nothing will happen, downstream will pull eventually

The reason why you cannot push or pull directly form completion handlers is exactly because the backpressure state is not certain as the completion events can arrive independently of backpressure state. absorbTermination() checks this state and invokes onPull if necessary.

**Comment by drewhk** [comment] 2015-08-26 08:35
This is probably a duplicate of https://github.com/akka/akka/issues/17803

**Comment by jroper** [comment] 2015-08-26 22:03
Ah I didn't see that.  So now the question I have is why my code works with a `pushAndPull` in `onUpstreamFinish`... perhaps it's not reaching that code.

**Closed** 2015-08-26 22:04 UTC
Labels: 1 - triaged, t:docs, t:stream

**Comment by drewhk** [comment] 2015-08-27 06:19
umm, pushAndPull cannot return a compatible type with what onUpstreamFinish expects (if it does, then it is a bug). Are you using AsyncStage or DetachedStage?

**Comment by jroper** [comment] 2015-08-28 01:45
`DetachedStage`.  From `DetachedContext`:

```scala
  def pushAndPull(elem: Out): FreeDirective
```

`pushAndPull` is a free directive so can be returned from anywhere, including `onUpstreamFinish`.
