### ISSUE TITLE
distributed-data  role must be set

### ISSUE THREAD

**Issue by joa23** [akka/akka#25436] opened 2018-08-05 03:52 UTC
Version: akka-distributed-data_2.12-2.5.14
Problem:
Documentation states:
```
 # Replicas are running on members tagged with this role.
  # All members are used if undefined or empty.
  role = ""
```

However when leaving role empthy or comment this section out replicator messages going into the deadletter box.
```
[INFO] [08/04/2018 20:50:57.874] [ClusterSystem-akka.actor.default-dispatcher-12] [akka://ClusterSystem/system/ddataReplicator] Message [akka.cluster.ddata.Replicator$Internal$Status] from Actor[akka://ClusterSystem@127.0.0.1:2552/system/ddataReplicator#-1036898133] to Actor[akka://ClusterSystem/system/ddataReplicator] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://ClusterSystem/system/ddataReplicator]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

As soon I set the role in my case to role="compute" I do not see this and other deadletters (read, update, change etc) and my code is working as expected.

**Comment by patriknw** [comment] 2018-08-15 06:16
@joa23 I tried to reproduce by adding `akka.cluster.roles = ["compute"]` to the [ReplicatorSpec](https://github.com/akka/akka/blob/master/akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/ReplicatorSpec.scala). I expected it to fail if there was an issue as you describe, but it doesn't. Could you create a minimized example or test to reproduce the issue?

**Comment by jrudolph** [comment] 2019-06-25 15:54
Thanks for reporting this issue, @joa. Closing for now because we couldn't reproduce it. Let us know if you are still affected.

**Closed by jrudolph** 2019-06-25 15:54 UTC

**Comment by joa** [comment] 2019-06-25 16:05
Not the @joa you mentioned in your issue. cc @joa23

**Comment by jrudolph** [comment] 2019-06-26 09:51
Sorry for the noise, @joa, must have selected the wrong suggestion.
