### ISSUE TITLE
FAILED: SystemMessageDeliveryNoPassiveRetryGate

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21971] opened 2016-12-08 12:07 UTC
https://jenkins.akka.io:8498/job/akka-nightly/3937/consoleFull

```
[info] SystemMessageDeliveryNoPassiveRetryGate:
Coroner Thread Count starts at 94 in akka.remote.transport.SystemMessageDeliveryNoPassiveRetryGate
[info] Remoting passive connections off
[WARN] [12/07/2016 01:43:21.627] [SystemMessageDeliveryStressTest-akka.remote.default-remote-dispatcher-15] [akka.gremlin.trttl.tcp://SystemMessageDeliveryStressTest@127.0.1.1:54566/system/endpointManager/reliableEndpointWriter-akka.gremlin.trttl.tcp%3A%2F%2FsystemB%40127.0.1.1%3A53435-0] Association with remote system [akka.gremlin.trttl.tcp://systemB@127.0.1.1:53435] has failed, address is now gated for [500] ms. Reason: [Association failed with [akka.gremlin.trttl.tcp://systemB@127.0.1.1:53435]] Caused by: [Simulated failure of association to trttl.tcp://systemB@127.0.1.1:53435]
[WARN] [12/07/2016 01:43:21.627] [systemB-akka.remote.default-remote-dispatcher-26] [akka.gremlin.trttl.tcp://systemB@127.0.1.1:53435/system/endpointManager/reliableEndpointWriter-akka.gremlin.trttl.tcp%3A%2F%2FSystemMessageDeliveryStressTest%40127.0.1.1%3A54566-0] Association with remote system [akka.gremlin.trttl.tcp://SystemMessageDeliveryStressTest@127.0.1.1:54566] has failed, address is now gated for [500] ms. Reason: [Association failed with [akka.gremlin.trttl.tcp://SystemMessageDeliveryStressTest@127.0.1.1:54566]] Caused by: [Simulated failure of association to trttl.tcp://SystemMessageDeliveryStressTest@127.0.1.1:54566]
[WARN] [12/07/2016 01:43:22.152] [SystemMessageDeliveryStressTest-akka.actor.default-dispatcher-4] [akka://SystemMessageDeliveryStressTest/system/endpointManager/reliableEndpointWriter-akka.gremlin.trttl.tcp%3A%2F%2FsystemB%40127.0.1.1%3A53435-1] unhandled message from Actor[akka://SystemMessageDeliveryStressTest/system/endpointManager#1549298059]: Ungate
[WARN] [12/07/2016 01:43:22.152] [systemB-akka.actor.default-dispatcher-19] [akka://systemB/system/endpointManager/reliableEndpointWriter-akka.gremlin.trttl.tcp%3A%2F%2FSystemMessageDeliveryStressTest%40127.0.1.1%3A54566-0] unhandled message from Actor[akka://systemB/system/endpointManager#488884493]: Ungate
[info] - must guaranteed delivery and message ordering despite packet loss  *** FAILED *** (548 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected 0, found 100
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:388)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:373)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[info]   at akka.remote.transport.SystemMessageDeliveryStressTest$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$4.apply$mcVI$sp(SystemMessageDeliveryStressTest.scala:171)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[info]   at akka.remote.transport.SystemMessageDeliveryStressTest$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SystemMessageDeliveryStressTest.scala:169)
[info]   at akka.remote.transport.SystemMessageDeliveryStressTest$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SystemMessageDeliveryStressTest.scala:145)
[info]   at akka.remote.transport.SystemMessageDeliveryStressTest$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SystemMessageDeliveryStressTest.scala:145)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:59)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:59)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:59)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
[ERROR] [12/07/2016 01:43:22.220] [SystemMessageDeliveryStressTest-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(SystemMessageDeliveryStressTest)] exception while executing timer task (akka.remote.RemoteTransportExceptionNoStackTrace)
[ERROR] [12/07/2016 01:43:22.235] [systemB-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(systemB)] exception while executing timer task (akka.remote.RemoteTransportExceptionNoStackTrace)
```

**Comment by patriknw** [comment] 2016-12-09 12:47
Duplicate of #21684

**Closed by patriknw** 2016-12-09 12:47 UTC
Labels: 1 - triaged, failed, t:remoting:artery
