### ISSUE TITLE
FAILED: FlowSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20074] opened 2016-03-18 15:42 UTC
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/5516/

```
] - must call future subscribers' onError when all subscriptions were cancelled *** FAILED *** (3 seconds, 29 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during fishForMessage, hint:
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.recv$1(TestKit.scala:397)
[info]   at akka.testkit.TestKitBase$class.fishForMessage(TestKit.scala:401)
[info]   at akka.testkit.TestKit.fishForMessage(TestKit.scala:734)
[info]   at akka.stream.testkit.StreamTestKit$PublisherProbeSubscription.expectCancellation(StreamTestKit.scala:644)
[info]   at akka.stream.scaladsl.FlowSpec$$anonfun$2$$anonfun$apply$mcV$sp$21$$anon$14.<init>(FlowSpec.scala:527)
[info]   at akka.stream.scaladsl.FlowSpec$$anonfun$2$$anonfun$apply$mcV$sp$21.apply$mcV$sp(FlowSpec.scala:523)
[info]   at akka.stream.scaladsl.FlowSpec$$anonfun$2$$anonfun$apply$mcV$sp$21.apply(FlowSpec.scala:523)
[info]   at akka.stream.scaladsl.FlowSpec$$anonfun$2$$anonfun$apply$mcV$sp$21.apply(FlowSpec.scala:523)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:57)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:57)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
```

**Comment by ktoso** [comment] 2016-03-18 15:43
Likely just timing

**Comment by 2m** [comment] 2016-03-31 08:25
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/309/consoleFull

**Comment by drewhk** [comment] 2016-05-03 12:07
I am not sure this is just timing. Why would it take 3 seconds to propagate a downstream cancellation to the upstream via the fanout processor. This can be a genuine bug.

**Comment by drewhk** [comment] 2016-05-10 14:25
So what I tried to reproduce the issue is that I added a Debug tracing+messing function to `ActorProcessorImpl`:

```scala
  var reorder = true
  override protected[akka] def aroundReceive(receive: Receive, msg: Any): Unit = {
    if (msg.isInstanceOf[T] && reorder) {
      reorder = false
      self ! msg
    } else {
      println(msg)
      super.aroundReceive(receive, msg)
    }
  }
```

Where I tried to replace T with the various message types that the actor receives during this test. It also prints the events that happen. No reordering seems to reproduce the failure so far, so the only thing I can conclude right now is that:
 - there is a race somewhere since this fails very sporadically, not reproducable locally
 - the race must be somewhere else since I checked all the relevant reorderings for this actor.

**Comment by drewhk** [comment] 2016-05-10 14:52
I put this back as I have no clue what could have gone wrong. There wasn't any new failures since end of March. I propose to wait one more month and close this ticket if the issue does not come back.

**Comment by patriknw** [comment] 2016-05-10 14:55
sounds good

**Comment by drewhk** [comment] 2016-05-24 12:22
I close this now.

**Closed by drewhk** 2016-05-24 12:22 UTC
Labels: 1 - triaged, failed
