### ISSUE TITLE
SnapshotOffer received by persistent actor is not the latest snapshot

### ISSUE THREAD

**Issue by kongk** [akka/akka#24649] opened 2018-03-02 13:11 UTC
For actors extending AbstractPersistentActor, sometimes we see snapshots where the highest sequence number is not in the latest snapshot filename - which is not a problem. But on restarting the actor-system, instead of the latest snapshot (the snapshot with the highest timestamp), the snapshot with the highest sequence number is offered to the persistent actor. This will occur over and over again upon restarting.

We are using the LocalSnapshotStore, and the persistent actors override the recovery method with:
`@Override
	public Recovery recovery() {return Recovery.create(SnapshotSelectionCriteria.latest());}`
	
According to documentation it "selects the latest (= youngest) snapshot"

To me it looks like the issue is related to ordering in SnapshotMetadata, where sequenceNr is checked before timestamp:
`if (a eq b) false
    else if (a.persistenceId != b.persistenceId) a.persistenceId.compareTo(b.persistenceId) < 0
    else if (a.sequenceNr != b.sequenceNr) a.sequenceNr < b.sequenceNr
    else if (a.timestamp != b.timestamp) a.timestamp < b.timestamp
    else false`
    
I had expected the lines with timestamp and sequenceNr to be swapped, like:
`...
else if (a.timestamp != b.timestamp) a.timestamp < b.timestamp
else if (a.sequenceNr != b.sequenceNr) a.sequenceNr < b.sequenceNr...`
	
Or is it intended to work so?

I tested most with akka version 2.5.1, but it also seems to be an issue in 2.5.11, while scala version is 2.11.

In my concrete case, the snapshots files are:
-rw-r--r-- 1 akka akka    200 Mar  2 13:58 snapshot-f4ac8f75bfeecd13e54737a1ae5ac50353561092-1338-1519995529132
-rw-r--r-- 1 akka akka 454548 Feb 28 12:22 snapshot-f4ac8f75bfeecd13e54737a1ae5ac50353561092-18114-1519816935085

I consider this as an important issue, because it potentially corrupts data and is not bringing the actor into the correct state after restart, and I hope for your help.

**Comment by johanandren** [comment] 2018-03-02 13:13
What journal are you using?

**Comment by johanandren** [comment] 2018-03-02 13:14
Ah, LocalSnapshotStore I see now, missed that.

**Comment by johanandren** [comment] 2018-03-02 13:30
This should be covered by this test case: https://github.com/akka/akka/blob/009214ae07708e8144a279e71d06c4a504907e31/akka-persistence-tck/src/main/scala/akka/persistence/snapshot/SnapshotStoreSpec.scala#L136 ) - but from a quick skim I can't see that it actually writes the same sequence number twice.

**Comment by kongk** [comment] 2018-03-02 13:54
But in the test case you mention, it seems to me that the latest snapshot also has the highest sequenceNr (or maybe all the snapshots have the same timestamp?):
` 1 to 5 map { i ⇒
val metadata = SnapshotMetadata(pid, i + 10)...`

Maybe a test where there is a difference in the timestamps of the snapshots (I may be missing something here, since I am a not a scala developer)

**Comment by johanandren** [comment] 2018-03-02 14:12
Looking again the metadata/snapshot with sequence number 4 is written earlier in the test case `"load the most recent snapshot"`, so it does verify that when there are two snapshots for the same sequence number the newer/younger one is used - so I don't think there is an issue with the ordering implementation here.

One issue could explain your issue is that when snapshotting is done and the timestamp is created `System.currentTimeMillis` is used, and this is not guaranteed to be monotonic - it may be returning a lower value because of system clock adjusting drift (a NTP daemon for example) or when changing between daylight savings time and not.

**Comment by raboof** [comment] 2018-03-02 14:15
It should never happen that a snapshot from February has a higher sequence number than a snapshot from March, though, right?

**Comment by kongk** [comment] 2018-03-02 14:38
I do not agree that the younger one is used. If you look at the SnapshotMetadata ordering, it checks sequenceNr before timestamp. Hence it never checks the timestamp if the sequence numbers are not the same. The test only uses the youngest because the sequence number is the highest on the youngest snapshot.

With regards to the comment from @raboof - in my case the snapshot from February actually has a higher sequence number than the snapshot from March. When writing sequenceNr i refer to the number in the filename, which is the one being parsed to sequenceNr. In my example it is 18114 in the older snapshot and 1338 in the younger. Those are not files I created for the purpose, the files are created by the actor-system running on a server.

**Comment by johanandren** [comment] 2018-03-02 15:58
Ok, I missed out on that the sequence number is different, so choosing the highest sequence number is how it is supposed to work, the timestamp is only to distinguish if you have multiple snapshots for the same sequence number. The mystery is then how you can have gotten a lower sequence number on a snapshot that is a few days after the previous one, not how they are sorted on the loading side.

Are you sure there isn't anything weird going on in the application, such as multiple persistent entities for the same entity id or such?

**Comment by kongk** [comment] 2018-03-02 16:41
So the journal and the snapshot could be out of sync? And hence the latest snapshot is not used as far as I understand you. And the youngest snapshot does not mean the latest saved snapshot but the snapshot with the highest sequence number?

Anyway, it is difficult to say whether something weird is going on. I do believe the server was under heavy load and hence had to be restarted. Also older snapshots are deleted after receiving SaveSnapshotSuccess. But there is only one instance of the actor that does the persisting per persistenceId.

**Comment by patriknw** [comment] 2018-03-05 15:26
Let us know if you find anything more, otherwise I suggest that we close this since it works as designed. The sequence number should always be increasing and is the only thing we can completely rely on. Clocks can go backwards.

**Comment by kongk** [comment] 2018-03-08 08:18
OK, I still do not know why the sequence numbers are not always increasing then in the snapshot filenames. I tend to think I would have preferred using the actually youngest snapshot determined by timestamp in this situation, since the latest snapshot as far as I can see is most likely to reflect the latest state of the journal, and I regard it is highly unlikely that the timestamp would decrease on a server using the LocalSnapshotStore.

**Comment by patriknw** [comment] 2018-03-08 09:37
As I said, timestamps are not guaranteed to be monotonically increasing (clocks can be change backwards in time). I'm closing this now, but feel free to create a new ticket or re-open if you find a way to reproduce the sequence number issue.

**Closed by patriknw** 2018-03-08 09:37 UTC

**Comment by raboof** [comment] 2018-03-08 09:44
@kongk the sequence numbers should always increase - if that does not seem to be the case for you then that is the problem. Could it be you at some point manually removed all events, effectively resetting the sequence number?

**Comment by kongk** [comment] 2018-03-08 11:06
Ok, thanks @raboof, I will hunt the reason for sequence numbers not increasing and come back if I find out something.
