### ISSUE TITLE
java.lang.VerifyError: using spark with akka

### ISSUE THREAD

**Issue by blyncsy-david-lewis** [akka/akka#21596] opened 2016-09-29 17:12 UTC
I receive a VerifyError when trying to use akka 2.4.10 with spark 2.0.0.
I would like to use akka-http to create a json api for interacting with spark, but since I've upgraded to akka 2.4 I get this verify error.

At first I thought it was caused by http-experimental or some other dependency in my large project, but I was able to reproduce it with only spark and akka.

I created an app with this code:

<pre><code>package com.blyncsy.test

import akka.actor.{Actor, ActorSystem, Props}
import akka.pattern.ask
import akka.util.Timeout

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._

/**
  * Created by David Lewis on 9/29/16.
  *
  */
object AkkaTest {
  def main(args: Array[String]): Unit = {
    implicit val timeout: Timeout = 10.seconds
    val system = ActorSystem()
    val ref = system.actorOf(Props[TestActor])
    (ref ? "wtf!") map { x =>
      println(x)
      sys.exit()
    }
  }
}

class TestActor extends Actor {
  override def receive: Receive = {
    case x => sender ! s"received: $x"
  }
}</code></pre>

The only dependencies in the project are:
"org.apache.spark" %% "spark-core" % "2.0.0" % "provided"
and
"com.typesafe.akka" %% "akka-actor" % "2.4.10"

I build an assembly jar using sbt assembly, and try to submit it to spark using spark-submit with master: local[*]
I receive this error:

<pre><code>Exception in thread "main" java.lang.VerifyError: Inconsistent stackmap frames at branch target 152
Exception Details:
  Location:
    akka/dispatch/Mailbox.processAllSystemMessages()V @152: getstatic
  Reason:
    Type top (current frame, locals[9]) is not assignable to 'akka/dispatch/sysmsg/SystemMessage' (stack map, locals[9])
  Current Frame:
    bci: @131
    flags: { }
    locals: { 'akka/dispatch/Mailbox', 'java/lang/InterruptedException', 'akka/dispatch/sysmsg/SystemMessage', top, 'akka/dispatch/Mailbox', 'java/lang/Throwable', 'java/lang/Throwable' }
    stack: { integer }
  Stackmap Frame:
    bci: @152
    flags: { }
    locals: { 'akka/dispatch/Mailbox', 'java/lang/InterruptedException', 'akka/dispatch/sysmsg/SystemMessage', top, 'akka/dispatch/Mailbox', 'java/lang/Throwable', 'java/lang/Throwable', top, top, 'akka/dispatch/sysmsg/SystemMessage' }
    stack: { }
  Bytecode:
    0x0000000: 014c 2ab2 0132 b601 35b6 0139 4db2 013e
    0x0000010: 2cb6 0142 9900 522a b600 c69a 004b 2c4e
    0x0000020: b201 3e2c b601 454d 2db9 0148 0100 2ab6
    0x0000030: 0052 2db6 014b b801 0999 000e bb00 e759
    0x0000040: 1301 4db7 010f 4cb2 013e 2cb6 0150 99ff
    0x0000050: bf2a b600 c69a ffb8 2ab2 0132 b601 35b6
    0x0000060: 0139 4da7 ffaa 2ab6 0052 b600 56b6 0154
    0x0000070: b601 5a3a 04a7 0091 3a05 1905 3a06 1906
    0x0000080: c100 e799 0015 1906 c000 e73a 0719 074c
    0x0000090: b200 f63a 08a7 0071 b201 5f19 06b6 0163
    0x00000a0: 3a0a 190a b601 6899 0006 1905 bf19 0ab6
    0x00000b0: 016c c000 df3a 0b2a b600 52b6 0170 b601
    0x00000c0: 76bb 000f 5919 0b2a b600 52b6 017a b601
    0x00000d0: 80b6 0186 2ab6 018a bb01 8c59 b701 8e13
    0x00000e0: 0190 b601 9419 09b6 0194 1301 96b6 0194
    0x00000f0: 190b b601 99b6 0194 b601 9ab7 019d b601
    0x0000100: a3b2 00f6 3a08 b201 3e2c b601 4299 0026
    0x0000110: 2c3a 09b2 013e 2cb6 0145 4d19 09b9 0148
    0x0000120: 0100 1904 2ab6 0052 b601 7a19 09b6 01a7
    0x0000130: a7ff d62b c600 09b8 0109 572b bfb1     
  Exception Handler Table:
    bci [290, 307] => handler: 120
  Stackmap Table:
    append_frame(@13,Object[#231],Object[#177])
    append_frame(@71,Object[#177])
    chop_frame(@102,1)
    full_frame(@120,{Object[#2],Object[#231],Object[#177],Top,Object[#2],Object[#177]},{Object[#223]})
    full_frame(@152,{Object[#2],Object[#231],Object[#177],Top,Object[#2],Object[#223],Object[#223],Top,Top,Object[#177]},{})
    append_frame(@173,Object[#357])
    full_frame(@262,{Object[#2],Object[#231],Object[#177],Top,Object[#2]},{})
    same_frame(@307)
    same_frame(@317)

	at akka.dispatch.Mailboxes.<init>(Mailboxes.scala:33)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:620)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:100)
	at com.blyncsy.test.AkkaTest$.main(AkkaTest.scala:17)
	at com.blyncsy.test.AkkaTest.main(AkkaTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)</code></pre>

Any help would be appreciated, I'd very much like to use akka-http instead of spray. (using akka 2.3.9 seems to work fine)

**Comment by 102** [comment] 2016-09-29 17:16
@blyncsy-david-lewis Hi there, could you please enclose log snippets with triple backtick next time? (At least to avoid mentioning people you don't want to mention). Thanks for attention

**Comment by blyncsy-david-lewis** [comment] 2016-09-29 18:18
Sorry about that, I'm unfamiliar with the syntax. Updated.

**Comment by ktoso** [comment] 2016-09-30 09:31
Could you print your classpath, in sbt you can `show libraryDependencies` etc?
Spark does not include Akka since a few versions, so I don't really think it's a Spark thing.
Akka by itself is binary compatible between those versions as well

**Comment by blyncsy-david-lewis** [comment] 2016-09-30 18:20
After printing the classpath as you asked I realized my test case was not as pure as I thought. I'd accidentally pulled in some common settings from another project which included some shading using sbt-assembly. After some more experimentation I've found that the issue was caused by doing any shading, along with having akka 2.4.10.

Here is my library path with 2.4.10: 
<pre><code>List(org.scoverage:scalac-scoverage-runtime_2.11:1.0.4:provided, org.scoverage:scalac-scoverage-plugin_2.11:1.0.4:provided, org.brianmckenna:wartremover:0.13:plugin->default(compile), org.scala-lang:scala-library:2.11.8, com.typesafe.akka:akka-actor:2.4.10, org.apache.spark:spark-core:2.0.0:provided)</code></pre>

and here is my project definition:
<pre><code>lazy val `akka-spark-test` = (project in file("akka-spark-test"))
  .settings(Seq(
    libraryDependencies ++= Seq(
      "com.typesafe.akka" %% "akka-actor" % "2.4.10",
      Deps.spark
    ),
    scalaVersion := "2.11.8",
    assemblyShadeRules in assembly := Seq(
      ShadeRule.rename("org.json4s.**" -> "com.blyncsy.shaded.org.json4s.@1").inAll
    )))</code></pre>

my sbt assembly version is 0.14.3

I realize this is probably not directly an akka issue, but it seems something changed from 2.3 to 2.4 that is causing this problem.

**Comment by ktoso** [comment] 2016-10-05 14:52
It's hard to attempt debugging this esp. since akka itself did not change anything here and I don't see how even different versions might end up here, and Spark in 2.0 does not include Akka, nor do I see any binary incompatibility here... I'm going to close the issue, as it's not an Akka issue, however feel free to ask the community on akka-user or gitter.im/akka/akka for help debugging this.

**Closed by ktoso** 2016-10-05 14:52 UTC

**Comment by jrudolph** [comment] 2017-02-07 18:20
Seems to be a bug in sbt-assembly. See https://github.com/sbt/sbt-assembly/issues/205. It's easy to reproduce by using sbt-assembly on a project that uses sbt-assembly and defines an arbitrary shading rule.

**Comment by eed3si9n** [comment] 2017-02-16 23:36
sbt-assembly 0.14.4 is released with the fix - https://github.com/sbt/sbt-assembly/releases/tag/v0.14.4

**Comment by ktoso** [comment] 2017-02-16 23:37
Awesome, thanks a lot Eugene!

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 17 February 2017 at 00:36:37, eugene yokota (notifications@github.com)
wrote:

sbt-assembly 0.14.4 is released with the fix -
https://github.com/sbt/sbt-assembly/releases/tag/v0.14.4

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/issues/21596#issuecomment-280500086>, or mute
the thread

**Comment by eed3si9n** [comment] 2017-02-16 23:44
I just did the release part. @karol-brejna-i and @pomadchin did the actual solving and fixing.

**Comment by danielhodder** [comment] 2017-11-01 00:02
This issue also happens if you're using the maven-shade-plugin. We hit the same issue with the maven-shade-plugin at version 2.4.3. Updating the plugin to 3.0.0 made this error go away.
