### ISSUE TITLE
Aeron files are not properly cleaned up

### ISSUE THREAD

**Issue by mbknor** [akka/akka#20623] opened 2016-05-25 07:24 UTC
Version: 2.4-ARTERY-M1

I have started one cluser node trying to connect to one other node that is not started yet.

```
09:18:07.346 ERROR  akkaSrc=akka.remote.artery.Association(akka://bluebox)  Outbound control stream to artery://bluebox@localhost:11065 failed. Restarting it. Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms - akka.remote.artery.Association(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-15, thrd=bluebox-akka.actor.default-dispatcher-4, lgr=a.r.a.Association(akka://bluebox) 
akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms
09:18:07.396 ERROR  akkaSrc=akka.remote.artery.Association(akka://bluebox)  Outbound message stream to artery://bluebox@localhost:11065 failed. Restarting it. Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms - akka.remote.artery.Association(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-9, thrd=bluebox-akka.actor.default-dispatcher-8, lgr=a.r.a.Association(akka://bluebox) 
akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms
09:18:14.899 ERROR  akkaSrc=akka.remote.artery.ArteryTransport(akka://bluebox)  Aeron error: 2 observations from 2016-05-25 09:18:11.900+0200 to 2016-05-25 09:18:11.907+0200 for:
 .lang.IllegalStateException: could not delete file C:\Users\mokj\AppData\Local\Temp\aeron-mokj-00561b0a-7753-4c07-9f5d-8c14eff8e6d1\publications\UDP-00000000-0-7f000001-11065-F913AF4F-3-4.logbuffer
	at io.aeron.driver.buffer.MappedRawLog.close(MappedRawLog.java:135)
	at io.aeron.driver.NetworkPublication.close(NetworkPublication.java:161)
	at io.aeron.driver.DriverConductor.onClosePublication(DriverConductor.java:270)
	at io.aeron.driver.cmd.CloseNetworkPublicationCmd.execute(CloseNetworkPublicationCmd.java:32)
	at io.aeron.driver.DriverConductor.onDriverConductorCmd(DriverConductor.java:836)
	at io.aeron.driver.DriverConductor$$Lambda$37/1731526546.accept(Unknown Source)
	at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:106)
	at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:174)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:106)
	at java.lang.Thread.run(Thread.java:745)
     - akka.remote.artery.ArteryTransport(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-10, thrd=bluebox-akka.actor.default-dispatcher-10, lgr=a.r.a.ArteryTransport(akka://bluebox) 
09:18:22.407 ERROR  akkaSrc=akka.remote.artery.Association(akka://bluebox)  Outbound control stream to artery://bluebox@localhost:11065 failed. Restarting it. Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms - akka.remote.artery.Association(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-8, thrd=bluebox-akka.actor.default-dispatcher-15, lgr=a.r.a.Association(akka://bluebox) 
akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms
09:18:22.464 ERROR  akkaSrc=akka.remote.artery.Association(akka://bluebox)  Outbound message stream to artery://bluebox@localhost:11065 failed. Restarting it. Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms - akka.remote.artery.Association(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-11, thrd=bluebox-akka.actor.default-dispatcher-10, lgr=a.r.a.Association(akka://bluebox) 
akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [artery://bluebox@localhost:11065] did not complete within 15000 ms
09:18:29.910 ERROR  akkaSrc=akka.remote.artery.ArteryTransport(akka://bluebox)  Aeron error: 4 observations from 2016-05-25 09:18:11.900+0200 to 2016-05-25 09:18:26.912+0200 for:
 .lang.IllegalStateException: could not delete file C:\Users\mokj\AppData\Local\Temp\aeron-mokj-00561b0a-7753-4c07-9f5d-8c14eff8e6d1\publications\UDP-00000000-0-7f000001-11065-F913AF4F-3-4.logbuffer
	at io.aeron.driver.buffer.MappedRawLog.close(MappedRawLog.java:135)
	at io.aeron.driver.NetworkPublication.close(NetworkPublication.java:161)
	at io.aeron.driver.DriverConductor.onClosePublication(DriverConductor.java:270)
	at io.aeron.driver.cmd.CloseNetworkPublicationCmd.execute(CloseNetworkPublicationCmd.java:32)
	at io.aeron.driver.DriverConductor.onDriverConductorCmd(DriverConductor.java:836)
	at io.aeron.driver.DriverConductor$$Lambda$37/1731526546.accept(Unknown Source)
	at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:106)
	at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:174)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:106)
	at java.lang.Thread.run(Thread.java:745)
     - akka.remote.artery.ArteryTransport(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-6, thrd=bluebox-akka.actor.default-dispatcher-6, lgr=a.r.a.ArteryTransport(akka://bluebox) 
```

**Comment by patriknw** [comment] 2016-05-25 08:00
That is expected if you have not started the destination yet. We should adjust the logging, though. `HandshakeTimeoutException` should probably not be logged at error level.

I don't know why Aeron can't remove the file when the association is stopped (`onClosePublication`).

Thanks for reporting.

**Comment by mbknor** [comment] 2016-05-25 08:06
Yes.. I agree that the error is expected.. Maybe bad description from my side, but the point of the ticket was the file-related exception with stacktrace.

Thanks for looking into it

**Comment by drewhk** [comment] 2016-05-25 08:08
Windows does not allow deletion of files if they are in use, that might be related here?

**Comment by mbknor** [comment] 2016-05-25 11:55
I'm not sure if it is related, but I just had to delete aprox 16 GB of aeron-temp files in  c:\Users\mokj\AppData\Local\Temp\
which has been generated and left alone during my testing of aeron this morning.

**Comment by drewhk** [comment] 2016-09-08 09:42
No it is not fixed. I take this now as it pollutes my Temp directory which is very annoying.

**Comment by drewhk** [comment] 2016-09-08 12:01
Seems like the CNC file is still kept mapped, and hence Windows rejects deleting it. Filed a ticket in Aeron as I don't see how we can safely fix this ourselves: https://github.com/real-logic/Aeron/issues/276

**Comment by patriknw** [comment] 2016-09-21 13:46
@drewhk is this fixed now, or is there something more?

**Comment by drewhk** [comment] 2016-09-21 14:14
No, fixed.

**Closed** 2016-09-21 14:14 UTC
Labels: 3 - in progress, t:remoting:artery

**Comment by mbknor** [comment] 2016-11-01 13:22
I've just tested with **"com.typesafe.akka" %% "akka-remote" % "2.4.12"**, and it works somewhat better:

On windows:
I start one node in a cluster with two seed-nodes.
When artery cannot connect to the second seedNode it logs this:

	14:16:15.579 ERROR  akkaSrc=akka.remote.artery.Association(akka://bluebox)  Outbound message stream to [akka://bluebox@127.0.0.1:11065] failed. Restarting it. Handshake with [akka://bluebox@127.0.0.1:11065] did not complete within 20000 ms - akka.remote.artery.Association(akka://bluebox), akkaThrd=bluebox-akka.remote.default-remote-dispatcher-6, thrd=bluebox-akka.actor.default-dispatcher-13, lgr=akka.remote.artery.Association(akka://bluebox) 
	akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [akka://bluebox@127.0.0.1:11065] did not complete within 20000 ms
	14:16:15.594 ERROR  akkaSrc=akka.remote.artery.Association(akka://bluebox)  Outbound control stream to [akka://bluebox@127.0.0.1:11065] failed. Restarting it. Handshake with [akka://bluebox@127.0.0.1:11065] did not complete within 20000 ms - akka.remote.artery.Association(akka://bluebox), akkaThrd=bluebox-akka.remote.default-remote-dispatcher-8, thrd=bluebox-akka.actor.default-dispatcher-16, lgr=akka.remote.artery.Association(akka://bluebox) 
	akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [akka://bluebox@127.0.0.1:11065] did not complete within 20000 ms
	14:16:22.906 ERROR  akkaSrc=akka.remote.artery.ArteryTransport(akka://bluebox)  Aeron error: 2 observations from 2016-11-01 14:16:20.095+0100 to 2016-11-01 14:16:20.111+0100 for:
	 .lang.IllegalStateException: could not delete file C:\Users\username\AppData\Local\Temp\aeron-username-bluebox-a568d5ff-f0ee-4c85-933e-d64dbf8af902\publications\UDP-00000000-0-7f000001-11065-78FF9606-2-4.logbuffer
		at io.aeron.driver.buffer.MappedRawLog.close(MappedRawLog.java:122)
		at io.aeron.driver.NetworkPublication.close(NetworkPublication.java:172)
		at io.aeron.driver.DriverConductor.onClosePublication(DriverConductor.java:269)
		at io.aeron.driver.cmd.CloseNetworkPublicationCmd.execute(CloseNetworkPublicationCmd.java:32)
		at io.aeron.driver.DriverConductor.onDriverConductorCmd(DriverConductor.java:924)
		at io.aeron.driver.DriverConductor$$Lambda$60/1874641016.accept(Unknown Source)
		at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:106)
		at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:175)
		at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
		at java.lang.Thread.run(Thread.java:745)
	     - akka.remote.artery.ArteryTransport(akka://bluebox), akkaThrd=bluebox-akka.actor.default-dispatcher-11, thrd=bluebox-akka.actor.default-dispatcher-11, lgr=akka.remote.artery.ArteryTransport(akka://bluebox) 


The folder 'publications' contains two files of 50MB each (basically only containing zeros).

It is not able to delete the files as show in exception above.

If I gracefully stop the app, the whole **\aeron-username-bluebox-a568d5ff-f0ee-4c85-933e-d64dbf8af902**-folder is successfully deleted. If I just kill the app, then the folder is left alone.

**Comment by patriknw** [comment] 2016-11-01 15:34
@mbknor Thanks for reporting. I see now from the stack trace that this is from a "normal" close of the Aeron publication. We focused on all the scenarios when stopping the application/jvm.

Do you mind creating a new issue, since this one is closed and part of a release already.

**Comment by patriknw** [comment] 2016-11-02 07:17
@mbknor Just to make sure I didn't misunderstood. You see this error log without shutting down the application? It happens by itself after ~ 30 seconds after startup? Does it happen every time or is it difficult to reproduce?
