### ISSUE TITLE
Akka Http routing with parameters (issue with ParamMagnet?)

### ISSUE THREAD

**Issue by LukaszTrojanowski** [akka/akka#20636] opened 2016-05-26 11:06 UTC
Tested on akkaVersion 2.4.4

Routing with multiple parameters doesn't work as described in the [documentation](http://doc.akka.io/docs/akka/2.4.6/scala/http/routing-dsl/directives/parameter-directives/parameters.html). 

The following code, from the documentation wouldn't compile. The ide shows the message

> "Too many arguments for method parameters(ParameterDirectives.ParamMagnet)."

`val route =
  parameters('color, 'backgroundColor) { (color, backgroundColor) =>
    complete(s"The color is '$color' and the background is '$backgroundColor'")
  }`

**Comment by ktoso** [comment] 2016-05-26 11:08
What scala version? That sounds like a known Scala 2.10 bug.

You can `import ParameterDirectives.ParamMagnet` to fix it on 2.10.
On 2.11+ it should just work

**Comment by LukaszTrojanowski** [comment] 2016-05-26 12:38
That's weird. I already use Scala 2.11.7

**Comment by ktoso** [comment] 2016-05-26 15:53
Does the mentioned import workaround help or not?

**Comment by LukaszTrojanowski** [comment] 2016-05-27 15:03
Unfortunately it doesn't.

**Comment by ktoso** [comment] 2016-05-30 11:17
Please post a self contained reproducer, would make it a lot easier to try to locate the issue :-)
Help us help you 😉

**Comment by LukaszTrojanowski** [comment] 2016-05-30 15:01
Here you go. https://github.com/LukaszTrojanowski/akka-http-parameters-example

**Comment by ktoso** [comment] 2016-05-30 15:06
I'm sorry but cannot reproduce.

```
ktoso @ 月~/code
$ git clone https://github.com/LukaszTrojanowski/akka-http-parameters-example.git
Cloning into 'akka-http-parameters-example'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 12 (delta 0), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (12/12), done.
Checking connectivity... done.
ktoso @ 月~/code
$ cd akka-http-parameters-example/
ktoso @ 月~/code/akka-http-parameters-example [master]
$ sbt shell
compile
[info] Set current project to akka-http-parameters-example (in build file:/Users/ktoso/code/akka-http-parameters-example/)
> compile
[info] Updating {file:/Users/ktoso/code/akka-http-parameters-example/}akka-http-parameters-example...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /Users/ktoso/code/akka-http-parameters-example/target/scala-2.11/classes...
[warn] there were two deprecation warnings; re-run with -deprecation for details
[warn] one warning found
[success] Total time: 6 s, completed 30-May-2016 17:04:43
> test:compile
[success] Total time: 0 s, completed 30-May-2016 17:04:48
> show scalaVersion
[info] 2.11.8
> run
[info] Running init.Main
Server online at http://localhost:8080/
Press RETURN to stop...

[success] Total time: 2 s, completed 30-May-2016 17:05:13
```

**Comment by LukaszTrojanowski** [comment] 2016-05-30 15:20
<Smashes head on desk> It's underlined by Intellijs intelisens (or how they call it) but does compile and work. Sorry for the trouble.

**Comment by ktoso** [comment] 2016-05-30 15:42
Report a code highlighting issue on the JetBrains issue tracker instead: https://youtrack.jetbrains.com/issues/IDEA (categorize under the scala plugin) :-)
I also use Intellij and it looks good there, maybe you're on some old or too-bleeding-edge version of the Scala plugin?

**Comment by ktoso** [comment] 2016-05-30 15:42
Happy hakking! Closing issue as it does indeed compile, even if tooling was confused – I wonder which version of intellij it was?

**Closed by ktoso** 2016-05-30 15:42 UTC
Labels: 1 - triaged, easy-to-contribute, t:http, t:http:server:dsl

**Comment by LukaszTrojanowski** [comment] 2016-05-30 15:54
Was on version 16.1.0 after the update to 16.1.2 everything is alright. Anyways, many thanks for your help.
