### ISSUE TITLE
Akka TCP on server side might not signal Closed events on Windows if client goes away silently

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#17000] opened 2015-03-05 09:07 UTC
We need a better workaround than the one in #15766

**Comment by patriknw** [comment] 2015-03-25 15:57
this is a duplicate of #16295, I guess

**Comment by drewhk** [comment] 2015-04-01 11:14
Superceded by ticket: https://github.com/akka/akka/issues/17122

**Closed by drewhk** 2015-04-01 11:14 UTC
Labels: 2 - pick next, bug
