### ISSUE TITLE
NullPointerException thrown in akka.stream.stage.GraphStageLogic.afterPostStop

### ISSUE THREAD

**Issue by CatTail** [akka/akka#25537] opened 2018-08-28 06:38 UTC
I'm using akka and akka-stream version `2.5.13`, my use case is [create an akka stream for every gRPC streaming request](https://github.com/btlines/grpcakkastream/blob/master/runtime/src/main/scala/grpc/akkastreams/GrpcAkkaStreamsServerCalls.scala#L35).

It seems that in https://github.com/akka/akka/blob/d5b2aea176f86436959886fdb156147655f2bbd9/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala#L1215, `asyncCallbacksInProgress` is null.

```
2018-08-10 08:45:53,419 [ERROR] from akka.actor.RepointableActorRef in analytics-ingestion-production-akka.actor.default-dispatcher-4 - Error during postStop in [ActorOutputBoundary(port=Fold.out(1476858011), demand=0, finished=false)]: null
java.lang.NullPointerException: null
        at akka.stream.stage.GraphStageLogic.afterPostStop(GraphStage.scala:1216)
        at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:572)
        at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:552)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:382)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run$$original(Mailbox.scala:225)
        at akka.dispatch.Mailbox.run(Mailbox.scala:32)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by raboof** [comment] 2018-08-28 07:16
Actually it seems the exception is thrown at the line below that line, `inProgress.nonEmpty`. That suggests `afterPostStop` was called twice. It looks like that shouldn't happen. I haven't looked closely yet, but the `tryPull` from the observer in https://github.com/btlines/grpcakkastream/blob/master/runtime/src/main/scala/grpc/akkastreams/GrpcGraphStage.scala#L15 looks suspicious, are you sure that shouldn't be wrapped in an AsyncCallback?

**Comment by jrudolph** [comment] 2019-06-25 16:00
Closing for now. Let us know if you are still affected and whether fixing the problem that @raboof mentioned had any effect.

**Closed by jrudolph** 2019-06-25 16:00 UTC
Labels: 0 - new

**Comment by iishyfishyy** [comment] 2020-10-22 17:30
I'm experiencing the same problem while using Akka's `RetryFlow.withBackoff`.

The issue only seems to happen when wrapping a Flow that uses `mapAsync`. 

To reproduce it, you can execute,

```
Source.single(1).via(
    RetryFlow.withBackoff(
        Duration.ofSeconds(1),
        Duration.ofSeconds(10),
        0.2,
        5,
        Flow.of(Integer.class).mapAsync(1, input -> {
            System.out.println("Flow trigger at " + Instant.now().toString());
            if (input % 2 == 0) {
                return  CompletableFuture.completedFuture(1);
            }
            return CompletableFuture.completedFuture(-1);
        }),
        (input, result) -> {
            if (result == -1) {
                System.out.println("Retry at " + Instant.now().toString());
                return Optional.of(input);
            }
            System.out.println("Continue at " + Instant.now().toString());
            return Optional.empty();
        }
    )
)
.runWith(Sink.foreach(i -> System.out.println("Reach sink with value " + i + " at " + Instant.now().toString())), ACTOR_SYSTEM)
.toCompletableFuture()
.get();
```

Changing `mapAsync` to `map` doesn't result in the NPE.

**Comment by jrudolph** [comment] 2020-10-26 08:54
Hi @iishyfishyy, can you post the exact version and the stack trace you are seeing?

**Comment by jrudolph** [comment] 2021-04-29 10:07
> Hi @iishyfishyy, can you post the exact version and the stack trace you are seeing?

@iishyfishyy since we got another report about this, it would be great if you could share more information about how to reproduce this exactly. I tried your code on current master but no exception happens.
