### ISSUE TITLE
Make PersistentActor fail on PersistenceFailure (persist)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17573] opened 2015-05-26 12:53 UTC

**Comment by patriknw** [comment] 2015-05-26 15:14
One question, how do we stop the actor even though the supervisor says resume? @rkuhn

**Comment by smlin** [comment] 2015-05-26 15:44
I have two different cases with failures on `persist` action. 
The first one is when I'm trying to persist a message while storage is unavailable - in this case the message will be persisted later and resuming by supervisor is normal.
The second one is when I check with the message serializer that it can deserialize a serialized message (I don't want to store messages if serializer cannot deserialize them) - in this case the message will never be serialized and resuming by supervisor is bad. 
So I think it must be a user choice.

**Comment by rkuhn** [comment] 2015-05-26 15:57
@smlin “message will be persisted later” is not saying anything since the machine can crash in between. This means that before persistence has been successful the Actor cannot continue to do other work, its state is in limbo. For the case that persistent storage is temporarily unavailable the Journal does not need to signal a Failure, it can (and should) just retry. Therefore I see no reason why this concern should be burdened upon the user. In essence this ticket means to define the semantics of WriteMessageFailure to be fatal, which has implications both for PersistentActor and for the Journal implementation.

@patriknw When throwing the exception we can also set a flag in the PersistentActor that it checks in aroundReceive and terminates appropriately.

**Comment by smlin** [comment] 2015-05-26 20:55
@rkuhn When I say "message will be persisted later" I mean "when sender will send message to the PersistentActor again". But if this message was not serializable then I want to notify sender and don't want to kill PersistentActor.
I think you will say that my serializer must be able to serialize any message or I must check serializability of the message  before to persist it. But I can not to serialize any message, really. And do attempts to serialize a message twice (before `persist` + inside a serializer) - this is simple strange and redundantly.
I think problem here is that message is a part of application (user defined) logic and only user knows that WriteMessageFailure is fatal or not fatal. So a user must have ability  to catch WriteMessageFailure without stopping the PersistentActor.
Thank you for answers.

**Comment by ktoso** [comment] 2015-05-26 20:58
>  But if this message was not serializable then I want to notify sender and don't want to kill PersistentActor.

This sounds like command sourcing, which we recommend against. The messages you persist originate from a transformation of "incoming command => `[0..n].times persist((event_i))`". Since this sounds more like validation, why not perform the validation explicitly (get serializer, try serialize) instead of riding the persistence failures for this purpose?

**Comment by rkuhn** [comment] 2015-05-26 21:04
There are two issues with this argument:

* The first is that you’ll probably assume that a persistence failure means that the event was not persisted, but there is a third case—persistence could not be confirmed and we just don’t know whether it is on disk somewhere or not. The simplest way to model this is to signal only the presence or absence of positive confirmation, which means that the absence can mean anything wrt. the correspondence of the PersistentActor’s internal state and the state on disk. Therefore the only consistent action is to stop and start over, synchronizing the state again.

* The problem with events not being serializable points more in a different direction: when emitting an event, the PersistentActor is in full control what objects that entails, so it can ensure that such failures do not happen unless the PersistentActor itself is buggy (in which case stopping the actor is not enough ;-) ). This goes in the same direction as @ktoso points out.

**Comment by smlin** [comment] 2015-05-26 22:39
@ktoso  You are right. But how I wrote before in such case for each message will be two serialization attempts. Not serializable messages is happens very rarely, so it is not effectively. And suppose that my messages stored in oracle where DBAs have their own vision of restrictions of stored data. How I must validate messages in such case? Of course last case is slightly fabulous, but it is a real-world case too:( Now I do not use Oracle, but anyway.

@rkuhn " the PersistentActor is in full control what objects that entails." In a theory a practice is a equivalent of theory. But full control does not mean that you can do this. You can not hammer a nail without a hammer, but nail is in your full control. 
@rkuhn Of course an internal state of the PersistentActor after WriteMessageFailure will be recovered (and anyway I want handle WriteMessageFailure ). But It is possible that in this case the performance is strongly degraded. 
Suppose that some strange system failure is happened and all messages become are the not being serializable. If the PersistentActor will be recover a state after each message then is very bad. But if not then PersistentActor will be able to respond for queries without any overtime. 

@rkuhn @ktoso I know that you guys are know the right akka-way, but it is very scary that I can not catch exception from the called method. When I try to persist data to any db then I can catch any db exception - why I can not do this with Akka?

**Comment by patriknw** [comment] 2015-05-27 05:56
This ticket is related (duplicate?) of #16524. Originally raised that issue because I think there are too many ways to handle errors in PersistentActor. That is difficult for user to understand and complicates the implementation.

I think that just removing the `PersistenceFailure` message and only have supervision is the right way to go. That would be easy to understand and the current implementation would also be simplified (all this mess with intercepting the `unhandled` would go away). I don't see a compelling reason for removing the [support for resume](https://github.com/akka/akka/commit/9b5a446).

**Comment by rkuhn** [comment] 2015-05-27 08:12
@smlin I might misunderstand what you are saying, but it seems that your use-case is to just store some arbitrary data in a database. This is not the purpose of PersistentActor, the purpose is that the Actor emits only events that describe its internal state changes, so I maintain that serialization failures are simple bugs of that PersistentActor. There are much better solutions for storing arbitrary data, look for example at slick/slick for ways of doing that; here it is completely up to you to handle (transient) failures because there are also no semantic guarantees coupling the Actor and the database. For a PersistentActor this is different, the event-sourcing abstraction we provide has a clearly limited scope and therefore provides a consistent package of functionality. A PersistentActor that cannot persist can also not be an Actor … an Actor with a DB connection has a lot more freedom.

One thing could be considered, though: when locally rejecting an Event for some reason we definitely know that the persistent state has not changed. Should we allow the PersistentActor to handle this case? This does make the whole concept more complicated, so we’d need some good reasons for doing this and we’ll need a consistent way of presenting this in the API.

**Comment by smlin** [comment] 2015-05-27 09:17
@rkuhn I try store exactly the internal state changes. But part of those changes come from outside the PersistentActor. Unlike FSM it is not determined what changes can be. 

"the purpose is that the Actor emits only events that describe its internal state changes" - This seems like you are saying that Actor must emits only events based just on data, generated inside Actor himself.

I do not understand why you want make a PersistenceFailure fatal for PersistentActor. Sorry.
I propose stop this conversation:)

**Comment by patriknw** [comment] 2015-06-18 10:28
fixed in https://github.com/akka/akka/pull/17634

**Closed** 2015-06-18 10:28 UTC
Labels: 3 - in progress, t:persistence

**Comment by patriknw** [comment] 2015-06-26 11:37
@smlin In the end we added support for event rejections (e.g. serialization errors). It will be part of 2.4-M2 (to be released today). http://doc.akka.io/docs/akka/snapshot/scala/persistence.html#Failures

**Comment by smlin** [comment] 2015-06-26 14:18
@patriknw Thank you!
