### ISSUE TITLE
Automatic server-side SSL configuration

### ISSUE THREAD

**Issue by ramanalv** [akka/akka#20867] opened 2016-07-01 20:35 UTC
Servers HttpsConnectionContext is not necessarily need be created manually as documented [here](http://doc.akka.io/docs/akka/2.4.7/scala/http/server-side-https-support.html#serversidehttps-scala).  This approach deviates from Client-Side support and limits the possible configuration options even though there is no difference as per SSL configuration is concerned.

Interestingly  the same configuration also works for Server-Side Https support as well.
 Akka's transitive dependency of ssl-config has a bug that causing SSLHandshake failure for Server-Side support. By fixing that bug, Server-Side Https support is working out-of-the-box.

The issue which causes Server-Side https support non-functional is [here](https://github.com/typesafehub/ssl-config/issues/43).

Here is snippet of the code:

`val httpsContext = Http().createServerHttpsContext(AkkaSSLConfig(system))
            Http().bind(host, port,httpsContext)`

**Comment by ktoso** [comment] 2016-07-03 17:48
> The issue which causes Server-Side https support non-functional is here.

This is fixed by https://github.com/typesafehub/ssl-config/pull/42/commits/c17d514dae23f8bdcdcbd85e676bcb2351f2de98#diff-f8fe48fe767e9f7262dd05d650304469R35 I believe.

Using SSLConfig for configuring the server "seemingly works", but is the wrong thing to do. 
Please see other tickets ( https://github.com/akka/akka/issues/20381 ) on the same subject – help would be very welcome, core team can't work on this right now - thanks a lot!

**Comment by ktoso** [comment] 2016-07-03 17:48
Closing this as duplicate of https://github.com/akka/akka/issues/20381

**Closed** 2016-07-03 17:48 UTC
Labels: t:http, t:http:core, t:http:server
