### ISSUE TITLE
give users more options in the starting behavior of distributed data with durable storage

### ISSUE THREAD

**Issue by Zhen-hao** [akka/akka#29947] opened 2021-01-13 13:32 UTC
Currently, the distributed data local replicator behaves like the following.
1. the replicator first tries to load everything stored in the local durable storage.
2. if there is any deserialization failure, the replicator crashes, or keep retrying.
the concequence is that the replicator does not participate in the ddata cluster and does not handle any commands.

It would be great if users can specify in the config file which durable keys must be fully loaded during (re)starting. For other keys that are not among these, the replicator should just log an error and ignore the deserialization failure. 

one example that can benefit from this is to use ddata as a schema registry. at starting time, only the schema files stored with a `schema` durable key need to be 100% loaded, the other serializers will rely on the loaded schemas to deserialize data in other durable keys.

**Comment by patriknw** [comment] 2021-01-14 13:12
I guess this was an accidental duplicate of https://github.com/akka/akka/issues/29948

**Closed by patriknw** 2021-01-14 13:12 UTC
