### ISSUE TITLE
Don't clear self when restarting

### ISSUE THREAD

**Issue by msfrank** [akka/akka#17805] opened 2015-06-22 21:34 UTC
documentation page /akka-docs/rst/general/jmm.rst has the following incorrect code block:

```
 18   // Completely safe, "self" is OK to close over
 19   // and it's an ActorRef, which is thread-safe
 20   Future { expensiveCalculation() } onComplete { f => self ! f.value.get }
```

this should be removed or explicitly marked as an incorrect usage, not correct usage.

**Comment by ktoso** [comment] 2015-06-23 05:23
Closing over self is legal and valid.
What you probably mean is closing over sender, which indeed is not valid, but that's something else.

**Comment by drewhk** [comment] 2015-06-23 07:21
@ktoso, see the discussion on the ML

**Comment by drewhk** [comment] 2015-06-23 07:23
i.e. after the original actor died, calling the closed over self() will result in DeadLetters being returned. This might or might not be fine (after all, even if you share the result of self() the message will end up in DeadLetters anyway). While not completely incorrect, the documentation is misleading.

**Comment by ktoso** [comment] 2015-06-23 08:17
Ok, cought up with the mailing list, I see what is meant here now.

Yeah we can improve it on it.
Thanks for bringing it up!

**Comment by patriknw** [comment] 2015-06-25 12:16
The problem is restarting. I agree that it is unintuitive that self changes because of a restart, given that it is defined as a `val`. I wonder if the nulling isn't too aggressive. We should investigate if that nulling is really needed for restarts.

**Comment by drewhk** [comment] 2015-06-25 12:17
but wait, isn't self defined on the ActorCell? That is not nulled when restarted, it is actually a val in Cell.

**Comment by drewhk** [comment] 2015-06-25 12:20
And in the trait Actor:

    implicit final val self = context.self //MUST BE A VAL, TRUST ME

**Comment by patriknw** [comment] 2015-06-25 12:21
and it is not nulled by reflection?

then I must have misunderstood the reproducer provided in the mailing list

**Comment by drewhk** [comment] 2015-06-25 12:25
Ah, it does via reflection. Sneaky. But not to null, but deadLetters. I don't know why we do that for restarts though, I don't see what it buys.

**Comment by patriknw** [comment] 2015-06-25 12:27
eactly

**Comment by fredfp** [comment] 2015-06-26 22:28
I'm the original poster of the ML thread.

As @patriknw pointed out, my main problem was indeed restarting.

If the restarting behavior is not changed, I'd like to see the doc updated to illustrate how to send a message to self in a Future's callback. It is something I do very often in my code and I always referred to the section of the doc quoted above stating that it is safe to close over self.

The second piece of code I sent to the ML was about using the Scheduler. After reading the above comments, I could restate the problem saying that context might be set to null too aggressively on restart. If it is not, I'd love to find a clarification of how to use Akka's scheduler in Future callbacks:
- is there a safe way (other than through the Actor's context) to get a reference to the ActorSystem and its scheduler?
- as some of scheduler's methods have implicit ExecutionContext and sender ActorRef parameters, is there a safe way to schedule sending a message to self other than by explicitly giving those parameters in order to avoid implicit usage of context.dispatcher and context.self?

**Comment by patriknw** [comment] 2015-07-01 15:26
After some review and debugging of the internals my conclusion is that there is no reason for changing self to deadLetters when the actor is restarted.

**Comment by drewhk** [comment] 2015-07-01 15:27
I think the same. Sending to that actorref will result in the message arriving to deadletters anyway after the actor has terminated. I mean the situation is exactly the same as if someone retains the ActorRef long after the original actor has been stopped.

**Comment by patriknw** [comment] 2015-07-01 15:31
yes, and we also hold on to the same ActorRef anyway from the new instance

**Closed** 2015-07-03 13:53 UTC
Labels: t:core
