### ISSUE TITLE
Error encountered while processing system message acknowledgement buffer: [-1 {}] ack: ACK[0, {}]

### ISSUE THREAD

**Issue by salehkhazaei** [akka/akka#24654] opened 2018-03-04 03:28 UTC
Hi,

We have a cluster of multiple nodes running and one of the nodes have been quarantined from the cluster due to this error:

![image](https://user-images.githubusercontent.com/9839920/36941832-7bad9438-1f79-11e8-879b-55ae7924333b.png)

Akka version: 2.5.6

I couldn't find out whether it's a bug or not.
BTW, the quarantined node ran actor system shutdown process yet the process was running.

**Comment by johanandren** [comment] 2018-03-05 07:56
Looks like we've seen it in a failing test once as well: https://github.com/akka/akka/issues/23838#issuecomment-354790372

**Comment by jpeel** [comment] 2018-04-02 18:17
We are seeing this in 2.5.11 when using legacy remoting.

**Comment by johanandren** [comment] 2018-04-03 07:16
If you can reproduce with debug logs enabled that would be helpful!

**Comment by ktoso** [comment] 2018-04-06 09:40
Marked as pick next and attempting to get more logs

**Comment by mohsenkashi** [comment] 2018-09-05 05:33
same problem in **akka 2.5.16** :
```
2018/09/05 08:13:31 +0430 - [ERROR] - from akka.remote.Remoting in rh-trade-api-akka.actor.default-dispatcher-150 
Association to [akka.tcp://application@127.0.0.1:3558] with UID [1774979215] irrecoverably failed. Quarantining address.
java.lang.IllegalStateException: Error encountered while processing system message acknowledgement buffer: [0 {0}] ack: ACK[1, {}]
	at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:309)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:207)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	^Cat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: Highest SEQ so far was 0 but cumulative ACK is 1
	at akka.remote.AckedSendBuffer.acknowledge(AckedDelivery.scala:104)
	at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:304)
	... 12 common frames omitted
```

I don't use cluster in my project and I use akka-actor + akka-remote in my project

**Comment by johanandren** [comment] 2018-09-05 07:48
@mohsenkashi If you can reproduce with debug logs enabled and share those that would be very helpful

**Comment by mohsenkashi** [comment] 2018-09-09 11:11
@johanandren 
there is my log with debug level
```
2018/09/09 15:39:31 +0430 - [DEBUG] - from akka.remote.EndpointWriter in rh-trade-api-akka.actor.default-dispatcher-4 
Disassociated [akka.tcp://rh-trade-api@192.168.2.214:9553] -> [akka.tcp://application@127.0.0.1:3564]

2018/09/09 15:39:31 +0430 - [ERROR] - from akka.remote.Remoting in rh-trade-api-akka.actor.default-dispatcher-4 
Association to [akka.tcp://application@127.0.0.1:3562] with UID [1474228365] irrecoverably failed. Quarantining address.
java.lang.IllegalStateException: Error encountered while processing system message acknowledgement buffer: [0 {0}] ack: ACK[2, {}]
	at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:309)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:207)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: Highest SEQ so far was 0 but cumulative ACK is 2
	at akka.remote.AckedSendBuffer.acknowledge(AckedDelivery.scala:104)
	at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:304)
	... 12 common frames omitted

2018/09/09 15:39:31 +0430 - [WARN] - from akka.remote.Remoting in rh-trade-api-akka.actor.default-dispatcher-4 
Association to [akka.tcp://application@127.0.0.1:3562] having UID [1474228365] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote ActorSystem must be restarted to recover from this situation.

2018/09/09 15:39:31 +0430 - [DEBUG] - from akka.remote.EndpointWriter in rh-trade-api-akka.actor.default-dispatcher-4 
Disassociated [akka.tcp://rh-trade-api@192.168.2.214:9553] <- [akka.tcp://application@127.0.0.1:3562]

2018/09/09 15:39:31 +0430 - [DEBUG] - from akka.remote.EndpointWriter in rh-trade-api-akka.actor.default-dispatcher-4 
Disassociated [akka.tcp://rh-trade-api@192.168.2.214:9553] <- [akka.tcp://application@127.0.0.1:3562]

2018/09/09 15:39:31 +0430 - [DEBUG] - from akka.remote.transport.ProtocolStateActor in rh-trade-api-akka.actor.default-dispatcher-4 
Association between local [tcp://rh-trade-api@192.168.2.214:9553] and remote [tcp://rh-trade-api@192.168.81.31:41370] was disassociated because the ProtocolStateActor was stopped normally
```

**Comment by patriknw** [comment] 2018-09-10 12:36
Do you see this in the logs?
```
was disassociated because the existing writable association was replaced by a new incoming one
```
possibly on the other node than the one that logged IllegalArgumentException

**Comment by patriknw** [comment] 2018-09-10 18:05
@mohsenkashi Do you know what the system did before this? Restarting a node with the same hostname:port I assume?

I would recommend that you try Artery with TCP. It shouldn't have these kind of race conditions and we have better possibilities to fix any issues there. https://doc.akka.io/docs/akka/current/remoting-artery.html

**Comment by patriknw** [comment] 2019-04-15 06:22
It hurts me to close an issue like this without being able to fix it, but given the difficulties of reproducing, tracking down the root cause, and fix this without introducing other regression I think that is what we have to do. Artery TCP is ready for production since 2.5.22 and I would recommend updating to that if this is still causing trouble.

**Closed by patriknw** 2019-04-15 06:22 UTC
Labels: 1 - triaged, bug, t:remoting

**Comment by He-Pin** [comment] 2026-06-24 05:02
## This bug still exists in Apache Pekko (as of 2026-06-24)

We encountered this in production and traced it to a race condition in classic remoting's `ReliableDeliverySupervisor`.

### Root Cause

When a new inbound connection replaces an existing one (same address, new UID):

1. `GotUid(newUid)` → `uid.exists(_ != receivedUid)` → `reset()` clears `AckedSendBuffer` and resets `seqCounter` to 0 / `maxSeq` to `SeqNo(-1)`
2. `resendAll()` fires, resending all messages with fresh sequence numbers
3. A **stale ACK** from the old connection's `AckedReceiveBuffer` arrives in-flight, carrying `cumulativeAck` referencing old sequence numbers (e.g. `ACK[1, {}]`)
4. `AckedSendBuffer.acknowledge()` throws `IllegalArgumentException("Highest SEQ so far was 0 but cumulative ACK is 1")`
5. `ReliableDeliverySupervisor` catches it and throws `HopelessAssociation` → **quarantine**

### Fix

We have a fix in Apache Pekko (branch `fix/classic-remoting-stale-ack-3126`):

**`AckedSendBuffer.acknowledge()`**: Instead of throwing when `cumulativeAck > maxSeq`, return the buffer unchanged (stale ACK is a no-op).

**`ReliableDeliverySupervisor`**: Detect stale ACKs before calling `acknowledge()`, log a warning, and skip processing. The `resendNacked()` call is also skipped since `GotUid` → `resendAll()` already covers retransmission.

**NACK safety**: NACKs in stale ACKs are also safely ignored because: (1) NACKs are always `< cumulativeAck` (invariant from `extractDeliverable`), (2) after `reset()` all messages are reassigned new sequence numbers via `resendAll()`, so old NACKs reference obsolete sequence numbers, (3) the periodic `AttemptSysMsgRedelivery` timer provides retransmission redundancy.

### Workaround (no code change)

Switch to Artery TCP, which has a completely separate `SystemMessageDelivery` implementation with incarnation-based stale detection:
```
pekko.remote.enabled-transports = ["pekko.remote.artery.tcp"]
```

The original Akka team's recommendation to use Artery remains the best path forward. For users still on classic remoting, the above fix resolves the race condition.
