### ISSUE TITLE
One node seems to quarantine the rest of the cluster every quarantine-after-silence interval.

### ISSUE THREAD

**Issue by cerko2** [akka/akka#26426] opened 2019-02-21 12:40 UTC
We are using 2.5.19 and seem to have gotten into state where one node would quarantine 2 other nodes(3 node cluster) every 2 days(default quarantine-after-silence), the network is healthy and the cluster is working fine.  
After some digging around it seems like there is a lingering maxSilenceTimer triggering quarantine even
when the network is healthy.
This seems related to #20523, I believe this is actually a regression introduced by https://github.com/akka/akka/pull/23129/
The ActorsLeakSpec test seems to be hitting this issue but is not checking whether there is a lingering
timer getting triggered, hence its not failing.

The logs for the test seem to be fine in 2.4.7 - 2.4.18 however 2.4.19 onwards where i believe the regression
happened this started to be appear in the logs:
[ERROR] [02/21/2019 10:27:15.576] [ActorsLeakSpec-akka.remote.default-remote-dispatcher-7] [akka.remote.Remoting] Association to [akka.trttl.tcp://remote@127.0.1.1:45507] with UID [789766452] irrecoverably failed. Quarantining address.
java.util.concurrent.TimeoutException: Remote system has been silent for too long. (more than 8.333333333333334E-4 hours)
	at akka.remote.ReliableDeliverySupervisor$$anonfun$idle$1.applyOrElse(Endpoint.scala:377)
	
Which I believe is whats happening with our cluster

**Comment by patriknw** [comment] 2019-02-22 11:26
Thanks for reporting. I'm slightly confused about what versions you are referring to. You mention both 2.5.19 and 2.4.7 - 2.4.18, 2.4.19?

**Comment by cerko2** [comment] 2019-02-22 11:31
In production we have hit this on 2.5.19.
I then noticed there was already a similar issue #20523 which introduced the part of ActorLeakSpec test that was reproducing it.
After I tried to run it on 2.5.19 and noticed it was showing similar behavior as we have seen in production.
After trying a bunch of different version I found out that it started showing this behaviour after the changes that were introduced in 2.4.19.

**Comment by patriknw** [comment] 2019-03-18 10:33
@cerko2 I have tried a few things in a test to explore `quarantine-after-silence`. So far I'm only seeing expected behavior. As long as there are attempts to send messages it is not triggering the quarantine "Remote system has been silent for too long", i.e. not idle.

How can there be no attempts to send messages to these nodes in your cluster?

I need more information to be able to debug this, and let's focus on your production issue with version 2.5.19 or later. Can you share logs? Can you reproduce it, setting quarantine-after-silence to a few minutes.

**Comment by cerko2** [comment] 2019-03-19 14:44
Unfortunately I dont have logs atm as this seems to happen randomly. Only way I came close to reproducing was via running ActorsLeakSpec which seems to log the mentioned exception in similar fashion it happened to us(which makes me believe its a regression introduced by #23129).
I will ask around whether its possible to get debug logs from that site.(although I suspect we may be out of luck)

**Comment by helena** [comment] 2019-05-07 13:05
I am just starting to look into this further, after @patriknw's initial. To clarify, @cerko2 the `ActorsLeakSpec` still reproduces this issue for you but for us it does not, Patrik has only seen the expected behavior it seems.

**Comment by cerko2** [comment] 2019-05-09 11:02
Yes that is correct, I was able to see an endpoint getting quarantined when running ActorsLeakSpec with the changes that were introduced with #23129. Without them ActorsLeakSpec didnt quarantine any endpoint. I can atleast provide logs from the test run if needed, unfortunately my request for debug logs from the production environment fell on deaf ears.

**Comment by tnevrekar** [comment] 2019-12-09 08:25
folks we are seeing the same issue in one of our deployments. Is there a known workaround for this issue? @cerko2  did increasing the quarantine-after-silence back to 5d help prevent this failure?

**Comment by helena** [comment] 2019-12-09 13:46
Hi @tnevrekar would it be possible for you to provide a simple replicator?

**Comment by patriknw** [comment] 2020-10-19 15:42
Closing, since the strong recommendation is to use [Artery](https://doc.akka.io/docs/akka/current/remoting-artery.html)

**Closed by patriknw** 2020-10-19 15:42 UTC
Labels: 1 - triaged, bug, t:remoting
