### ISSUE TITLE
OutOfMemory after update to akka 2.6.11

### ISSUE THREAD

**Issue by nilius** [akka/akka#29966] opened 2021-01-20 13:45 UTC
Hi! With the update 2.6.11 we getting OutOfMemory exceptions in our software in two unrelated pods. When we downgrade to 2.6.10 the OOMs go away.

Analyzing at the memory dumps, the OOMs seem to be related to flatMapConcat. 

This is the flow in the simpler program:
```
  def files: Future[immutable.Seq[FileMetadata]] = ???
  def readFile(fileMetadata: FileMetadata): Source[ByteString, NotUsed] = ???

  def processFiles: Source[SomeResultType, Future[NotUsed]] = {
    Source
      .futureSource { files.map(Source(_)) }
      .flatMapConcat { fileMetadata =>
        logger.info(s"Creating Source for $fileMetadata")
        processFile(fileMetadata)
      }
  }

  def processFile(file: FileMetadata): Source[SomeResultType, NotUsed] = {
    readFile(file)
      .via(JsonFraming.objectScanner(maximumObjectLength = 10000))
      .map(_.decodeString("UTF-8"))
      .map(Json.parse(_).validate[SomeResultType])
      .alsoTo(logValidationErrors)
      .collect { case JsSuccess(value, _) =>
        metrics.productConnectionsValid.inc()
        value.copy(datei_name = file.filename)
      }
  }
  
"com.lightbend.akka"         %% "akka-stream-alpakka-s3"             % "2.0.2",
"com.lightbend.akka"         %% "akka-stream-alpakka-json-streaming" % "2.0.2",
"com.typesafe.akka"          %% "akka-slf4j"                         % "2.6.11",
"com.typesafe.akka"          %% "akka-actor"                         % "2.6.11",
"com.typesafe.akka"          %% "akka-stream"                        % "2.6.11",
```

While analyzing the heap dumps, we noticed that a large portion of the objects are attached to an instance of FlattenMerge.
Objects that run through the flow are also attached to this ObjectGraph, these should actually disappear through a GarbageCollection. But they seem to become more and more over the time.
Also many instances of akka.stream.stage.GraphStageLogic$SubSinkInlet are attached to this graph.

![heap](https://user-images.githubusercontent.com/286575/105182568-7769a400-5b2d-11eb-9fac-20c981767451.png)

Reading the change log for 2.6.11, we see two changes that might be related to the memory issues we are experiencing:
* https://github.com/akka/akka/commit/8c0ffe3b2ab7a193ebc3a1bd13c82be1f551d7cd?branch=8c0ffe3b2ab7a193ebc3a1bd13c82be1f551d7cd&diff=split
* Update jackson-databind to 2.10.5.1

Best regards, Fabian Nilius

**Comment by ruchirj** [comment] 2021-01-22 12:29
We are seeing similar behavior while using `flatMapMerge` where a heap dump shows an accumulation in `FlattenMerge` objects which goes away once we pin back to 2.6.10.

**Comment by johanandren** [comment] 2021-01-22 12:44
Yes, we have found the issue and a PR with a fix is waiting to be merged, the problem surfaces in FlattenMerge but is caused by internals related to substreams.

**Closed** 2021-01-25 14:36 UTC
Labels: 3 - in progress, bug, t:stream

**Comment by patriknw** [comment] 2021-01-25 14:51
@nilius could you look for a new snapshot and and try that tomorrow (or later). We probably want to release a new Akka patch version soon because of this bug but would be great to have confirmation that it works in your application.
See https://doc.akka.io/docs/akka/current/project/links.html#snapshots-repository

**Comment by markarasev** [comment] 2021-01-26 08:51
In my case the snapshot `2.6.11+11-0bf29fd2` solves the issue, good job!

**Comment by patriknw** [comment] 2021-01-26 09:28
Thanks for verifying @markarasev

**Comment by nilius** [comment] 2021-01-26 14:02
Looks good now, thanks for the fix.
Note that it wasn't sufficient to update akka-stream-lib, I also had to update akka-actor and akka-slf4j (don't know which was relevant).

**Comment by caraboides** [comment] 2021-01-26 16:59
2.6.11+11-0bf29fd2 fixed the issue. The heap dump looks fine now, i found no suspicious items anymore.
