### ISSUE TITLE
exclude snippets

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22921] opened 2017-05-12 09:26 UTC
In rst we sometimes used the `exclude` like in actors.rst:
```
.. includecode:: code/jdocs/actor/ActorDocTest.java#context-actorOf
   :exclude: plus-some-behavior
```

```java
  //#context-actorOf
  public class FirstActor extends AbstractActor {
    final ActorRef child = getContext().actorOf(Props.create(MyActor.class), "myChild");
    
    //#plus-some-behavior
    @Override
    public Receive createReceive() {
      return receiveBuilder()
        .matchAny(x -> getSender().tell(x, getSelf()))
        .build();
    }
    //#plus-some-behavior
  }
  //#context-actorOf
```

This is lost in new .md
```
@@snip [ActorDocTest.java]($code$/java/jdocs/actor/ActorDocTest.java) { #context-actorOf }
```

@bantonsson You showed me a xml example of how that could be done, but I still don't understand what I need to do for an example like this?

**Comment by patriknw** [comment] 2017-05-12 09:29
ah, now I get see, it must be written as:
```java
  //#context-actorOf
  public class FirstActor extends AbstractActor {
    final ActorRef child = getContext().actorOf(Props.create(MyActor.class), "myChild");
    
    //#context-actorOf
    //#plus-some-behavior
    @Override
    public Receive createReceive() {
      return receiveBuilder()
        .matchAny(x -> getSender().tell(x, getSelf()))
        .build();
    }
    //#plus-some-behavior
    //#context-actorOf
  }
  //#context-actorOf
```

**Comment by pvlugter** [comment] 2017-05-17 22:07
Yes, replacing excluded sections with a placeholder comment was a useful feature that we added for includecode for sphinx. Play doc snippets also have other features, like special comments to drop the next n lines, or replacing the next line with different text. Might be easy enough to get the excludes into the paradox snippets.

**Comment by Captain1653** [comment] 2021-08-09 19:51
The issue is really old. is it still needed? I have found  the example with `//#context-actorOf` . It is written in "old" way. I can fix the issue if you will show me some direction.

**Comment by raboof** [comment] 2021-08-10 07:19
> The issue is really old. is it still needed?

I think it makes sense to close this here. It still would be nice to have, but it's already tracked on the paradox side and we're not in urgent need of a solution.

> I have found the example with `//#context-actorOf`. It is written in "old" way.

In this case it looks OK to me, I think it was just used as an example above.

**Closed by raboof** 2021-08-10 07:19 UTC
Labels: 1 - triaged, help wanted, t:docs
