### ISSUE TITLE
`Access-Control-Allow-Origin` should be renderable in responses

### ISSUE THREAD

**Issue by cppexpert** [akka/akka#19763] opened 2016-02-12 14:24 UTC
I believe it's a bug. My api server needs to set [Access-Control-Allow-Origin](https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala#L222-L235) in responses. It's not happening because default value of  `ModeledHeader.renderInResponses` is `false`. I get following warning in log

```
2016-02-12 17:24:25.899 +0300 WARN  HTTP header 'Access-Control-Allow-Origin: *' is not allowed in responses
```

**Comment by johanandren** [comment] 2016-02-15 20:58
That has been fixed in the latest RC of 2.4.2, please upgrade.
Duplicate of: #19674

**Closed by johanandren** 2016-02-15 20:58 UTC
