### ISSUE TITLE
Type safer Receptionist/ServiceKey

### ISSUE THREAD

**Issue by dilation** [akka/akka#24362] opened 2018-01-19 13:44 UTC
Currently the (typed) `Receptionist` uses a `ClassTag` to differentiate services. Thus, there is no difference between, e.g., `Option[Int]` and `Option[String]`. This can cause the wrong type of messages to be delivered to actors (which in turn causes a `ClassCastException`). AFAICT this could be avoided by using something like a `TypeTag` (although it probably wouldn't be trivial, due to the difference between `=:=` and `==`).

**Comment by johanandren** [comment] 2018-01-19 17:02
I think there are additional problems having parameterized types as protocols for actors though, so even if it might be good to fix this we should in no way encourage doing that.

**Comment by rkuhn** [comment] 2018-03-10 07:27
Seconded: never use types from the standard library as message types, in particular not generic ones. An actor cannot really breathe if you don’t give it a proper language to speak, so please add that single line to give a proper name to your message that conveys an optional value. Ideally there should be two case classes, one that wraps a value, and one that properly names the semantics of sending “nothing” (because sending a `None` really does not make sense).

**Comment by rkuhn** [comment] 2018-03-10 07:28
I propose to close this issue.

**Comment by dilation** [comment] 2018-03-10 10:55
The problem is not really standard library types, and not even generic types. It's that `ClassTag` is not a proper representation of a Scala type (it's not even a proper representation of a Java type). (And of course, it can be worked around by defining a wrapper class.)

**Comment by rkuhn** [comment] 2018-03-10 11:53
What you are saying is true, and what I said is that a proper type is not the right thing to use here: what is needed is an agreed name for the entry point to a protocol. A ClassTag is a perfectly valid carrier for such a name, indeed the fact the it loses erased type parameters is a feature here, not a bug. Since the distinction cannot be expressed at compile time, maybe we should add a runtime check to reject parametric types.

**Comment by ktoso** [comment] 2018-03-12 01:14
Agreeing with @johanandren and @rkuhn here; it is strongly discouraged to send top level messages with type parameters for a number of reasons, including pattern matching not being able to properly deal with those `T`'s anyway etc.

You can build your small wrapper on top of the lower level if you want to though. Closing as we won't be addressing it in the core library

**Closed by ktoso** 2018-03-12 01:14 UTC
Labels: 0 - new, t:typed
