### ISSUE TITLE
setReceiveTimeout issue on persistenct actor since 2.4.7

### ISSUE THREAD

**Issue by gbrd** [akka/akka#20738] opened 2016-06-07 09:38 UTC
Since akka 2.4.7 (and #20698), setting receive timeout in prestart does not work in persistent actor.
If I set it in receiveRecover/RecoveryCompleted, it works.

I did not analyse the code but I saw in EventSourced  class that a "previousRecieveTimeout" is backuped and restored, maybe it does not work well in some cases ?

**Comment by johanandren** [comment] 2016-06-07 09:58
The #20698 breaks setting timeouts in the `receiveRecover` block, it saves a pre-existing receive timeout (if set in the constructor of the actor for example) and restores that in the end, so setting a timeout in the `receiveBlock` will currently effectively disable the recover-timeout as well as be lost when recovery completes.

**Comment by gbrd** [comment] 2016-06-07 11:35
If i called setReceiveTimeout in preStart and wait ReceiveTimeout message in receiveCommand, it seems not work.

**Comment by johanandren** [comment] 2016-06-07 12:14
Yeah, exactly, #20698 tries to safe guard against recovery never completing by setting a receive timeout when recovery starts, it then also saves the pre-existing receive timeout and at the end of recovery reinstates that. So during `receiveCommand` it will break that usage.

We didn't expect anyone to actually do this, but we may have to change how this was solved anyway for other reasons. (Ping @patriknw)

**Comment by johanandren** [comment] 2016-06-07 13:11
Hey @gbrd can you please explain your use case for setting a receive timeout in `receiveRecover` (to help us prioritize this ticket)? Thanks.

**Comment by patriknw** [comment] 2016-06-07 13:17
We have to change to custom scheduling for this instead of using receive timeout, but for now it would be great if you can use 2.4.6 or keep track of the timeout in a var during recovery and then set the real receive timeout when recovery has completed.

We should follow up on this next rather immediately though, so it should be fixed in 2.4.7.

**Comment by patriknw** [comment] 2016-06-07 13:17
marking it as a bug since it's kind of a regression

**Comment by johanandren** [comment] 2016-06-07 13:19
Correction, it should be fixed in 2.4.8 :)

**Comment by patriknw** [comment] 2016-06-07 13:28
:-)

**Comment by gbrd** [comment] 2016-06-07 14:35
hum.  settings the receive timeout in receiveRecover  (on reception of RecoveryCompleted) is the workarround actually, and it works.
(setting it in preStart seems not work in 2.4.7)

**Closed** 2016-06-09 12:58 UTC
Labels: 3 - in progress, bug, t:persistence
