### ISSUE TITLE
Failed: akka.discovery.dns.DnsDiscoverySpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#26983] opened 2019-05-21 08:03 UTC
https://jenkins.akka.io:8498/job/akka-nightly/6577/testReport/junit/akka.discovery.dns/DnsDiscoverySpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

```
Error Message

com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/f9cf42d79cbc1254741b84679dd06a9854406dd02a82aa93f6fd74f910bf3ec8/start: 500, body: {"message":"driver failed programming external connectivity on endpoint akka-test-dns-akka.discovery.dns.DnsDiscoverySpec (18e4c4421e6469d8eed588514d36d4968dfc57da2b30bb9158886890a81d164b): Error starting userland proxy: listen udp 0.0.0.0:40911: bind: address already in use"} 

Stacktrace

sbt.ForkMain$ForkError: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/f9cf42d79cbc1254741b84679dd06a9854406dd02a82aa93f6fd74f910bf3ec8/start: 500, body: {"message":"driver failed programming external connectivity on endpoint akka-test-dns-akka.discovery.dns.DnsDiscoverySpec (18e4c4421e6469d8eed588514d36d4968dfc57da2b30bb9158886890a81d164b): Error starting userland proxy: listen udp 0.0.0.0:40911: bind: address already in use"}

	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2820)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2714)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:763)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:748)
	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:743)
	at akka.io.dns.DockerBindDnsService.atStartup(DockerBindDnsService.scala:76)
	at akka.io.dns.DockerBindDnsService.atStartup$(DockerBindDnsService.scala:27)
	at akka.discovery.dns.DnsDiscoverySpec.atStartup(DnsDiscoverySpec.scala:43)
	at akka.testkit.AkkaSpec.beforeAll(AkkaSpec.scala:87)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at akka.testkit.AkkaSpec.run(AkkaSpec.scala:61)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sbt.ForkMain$ForkError: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1020)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more

```

**Comment by chbatey** [comment] 2019-05-28 09:40
The issue is that the docker container is started with a host port mapping that may be taken. If we could create the docker container before the actor system is created then we can use the docker ip and not do the host port mapping

**Comment by johanandren** [comment] 2019-11-26 08:34
https://jenkins.akka.io:8498/job/akka-release-2.5/152/testReport/junit/akka.discovery.dns/DnsDiscoverySpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by johanandren** [comment] 2020-03-03 08:52
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/19048/testReport/junit/akka.discovery.dns/DnsDiscoverySpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by johanandren** [comment] 2021-05-03 06:50
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8711/

**Comment by johanandren** [comment] 2021-06-28 12:23
https://jenkins.akka.io:8498/job/akka-nightly-2.13/936/testReport/junit/akka.discovery.dns/DnsDiscoverySpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by patriknw** [comment] 2022-02-21 10:39
closing as old

**Closed by patriknw** 2022-02-21 10:39 UTC
Labels: 1 - triaged, failed
