### ISSUE TITLE
akka-streams is not included to main jar of 2.4.2-RC1 build

### ISSUE THREAD

**Issue by cppexpert** [akka/akka#19649] opened 2016-01-30 16:19 UTC
It seems like akka-streams is not included to main jar (akka-actor) contrary to [http://akka.io/news/2016/01/26/akka-2.4.2-RC1-released.html](statement) in the blog post of 2.4.2-RC1 release. Is it typo or am I missing something ?

**Comment by drewhk** [comment] 2016-01-30 17:00
Hi,

As far as I see nothing says there that they are included in the
akka-actor.jar. They are a separate artifact:
https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22akka-stream_2.11%22

-Endre

**Comment by cppexpert** [comment] 2016-01-30 17:46
Ah I see.

Could you please also clarify should I use 2.4.2-RC1 or 2.0.3 versions for `akka-http-experimental`, `akka-http-spray-json-experimental` and others ?

**Comment by johanandren** [comment] 2016-02-01 07:06
Hi @cppexpert

This depends on what you want, 2.0.3 is stable, while 2.4.2-RC1 is a release candidate, in other words an early release of 2.4.2 that is released to get help from community and projects consuming akka to find bugs and problems before we craft the final 2.4.2 release.

Please use gitter or the mailing list for questions in the future, I'll close this ticket as it is not a bug or an idea for a feature but more of a question.

**Closed by johanandren** 2016-02-01 07:06 UTC
