### ISSUE TITLE
ReliableDeliverySupervisor actor leak, when cluster remote watcher quarantine the corresponding address  

### ISSUE THREAD

**Issue by MQ-EL** [akka/akka#20523] opened 2016-05-14 09:53 UTC
One node always quarantine another one in the cluster environment every 5 days, but the network environment is ok.

 It seems the timeout(```quarantine-after-silence```) of the idle RDS make another, has the same address, active RDS quarantined, every ```quarantine-after-silence``` defined period.

**Comment by zorowonder** [comment] 2016-05-16 06:10
Hi,I would like to interpret this question by operating simple steps below:

1.Start up two nodes, A and B, in the same cluster. B is the seed node of this cluster.
	(Here we stand on the perspective of B to discribe the scenario in the next steps.)
	The A successfully associates to B with an UID, uid-0, 
	and then B instantiates the RDS-0(ReliableDeliverySupervisor)corresponding to uid-0.
	`SystemMessage` like `Watch` will send through RDS-0 from B's cluster layer to A because I also config the cluster sharding and this is an important point.
	
2.Stop the A by a simple shutting down.
	B detects the disassociation and stop the actors of RDS-0. But RDS-0 sent `SystemMessage` before, 
	it keeps alive and continues to send the message that aim to get association with A from B's cluster layer.
	
3.Start up A again.(The step 2 and 3 are operated very closly like a Restart)
	The A successfully associates to B with a new UID, uid-1. 
	B's `EndpointManager` receives `InboundAssociation` from A, and then stop the RDS-0 because of different UID.
	The RDS-1 corresponding to uid-1 is now be instantiated.
	B's `EndpointManager` receives the `Quarantine` from cluster layer to stop the RDS that corresponding to uid-0.
	The codes in `Remoting` from line 543 to line 556 work well as expected.The logic goes into last case in line 552, do nothing.
	But the codes in `Remoting` from line 593 to line 596 seems to do the wrong operation.
	code:

		uidToQuarantineOption foreach { uid =>
			endpoints.markAsQuarantined(address, uid, Deadline.now + settings.QuarantineDuration)
			eventPublisher.notifyListeners(QuarantinedEvent(address, uid))
		}

The function `markAsQuarantined` just add a pair, (addressOfA -> Quarantined(uid, timeOfRelease)), 
	to the map which will improperly override the pair, (addressOfA -> Pass(...)).
	Although cluster layer means to quarantine the uid-0, the address here is unique to represent A. 
	The operation wrongly mark the RDS-1 which has the same address with RDS-0 as `Quarantined` state.
	RDS-1 is still alive but we can not use it to send message to A because we lost it ActorRef.
	So RDS-2 is generated to send message to A.
	Now the message from A is received through RDS-1 and the message to A is sent through RDS-2.
	
4.Stop the A and wait for B to mark A as Unreachable, then start A again.
	This time the RDS-1 will throw an exception to stop because it does not send a `SystemMessage` due to cluster layer lost the ActorRef of RDS-1.
	And RDS-1's exception will escalate to `EndpointManager`, and then will wrongly modify the `addressToWritable` map in the `EndpointRegistry` of `EndpointManager` so that the pair, (addressOfA -> Pass(RDS-2,...), is overrided.
	RDS-2 will lost and leak. And RDS-3 will be generated.
	After a period(`quarantine-after-silence`),the `quarantine-after-silence` here is set to 120s for a quick test, 
	RDS-2 become idle and throw the exception, `TooLongIdle`, to free itself.
	The exception will also affect the RDS-3 marking it as quarantined making the cluster unavailable.
	When we restart the A(B do not restart ever) to recover this problem, RDS-3 will affact the RDS-4.
	
It seems complicated, and thanks for your patience to read my comment.

**Comment by zorowonder** [comment] 2016-05-16 09:40
Here is the log:
Two UID appears in the log, 685772901 and -1447034877.

> [2016-04-28 17:07:51.750] | broker-akka.actor.default-dispatcher-4 | ERROR |  | [] | [] | [akka.remote.Remoting] | Association to [akka.tcp://broker@129.1.6.12:6666] with UID [**685772901**] irrecoverably failed. Quarantining address.
java.util.concurrent.TimeoutException: Remote system has been silent for too long. (more than 0.03333333333333333 hours)
	at akka.remote.ReliableDeliverySupervisor$$anonfun$idle$1.applyOrElse(Endpoint.scala:367) ~[com.typesafe.akka.akka-remote_2.11-2.4.2.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:192) ~[com.typesafe.akka.akka-remote_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.7.jar:na]
[2016-04-28 17:07:51.751] | broker-akka.actor.default-dispatcher-4 | WARN |  | [] | [] | [akka.remote.Remoting] | Association to [akka.tcp://broker@129.1.6.12:6666] having UID [**685772901**] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote actorsystem must be restarted to recover from this situation.
[2016-04-28 17:07:52.297] | broker-akka.actor.default-dispatcher-5 | DEBUG |  | [] | [] | [akka.remote.EndpointWriter] | Associated [akka.tcp://broker@129.1.99.1:8888] -> [akka.tcp://broker@129.1.6.12:6666]
[2016-04-28 17:07:52.724] | broker-akka.actor.default-dispatcher-23 | ERROR |  | [] | [] | [akka.remote.Remoting] | Association to [akka.tcp://broker@129.1.6.12:6666] with UID [**-1447034877**] irrecoverably failed. Quarantining address.
java.lang.IllegalStateException: Error encountered while processing system message acknowledgement buffer: [-1 {}] ack: ACK[0, {}]
	at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:291) ~[com.typesafe.akka.akka-remote_2.11-2.4.2.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:192) ~[com.typesafe.akka.akka-remote_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [com.typesafe.akka.akka-actor_2.11-2.4.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.7.jar:na]
Caused by: java.lang.IllegalArgumentException: Highest SEQ so far was -1 but cumulative ACK is 0
	at akka.remote.AckedSendBuffer.acknowledge(AckedDelivery.scala:103) ~[com.typesafe.akka.akka-remote_2.11-2.4.2.jar:na]
	at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:287) ~[com.typesafe.akka.akka-remote_2.11-2.4.2.jar:na]
	... 11 common frames omitted
[2016-04-28 17:07:52.724] | broker-akka.actor.default-dispatcher-23 | WARN |  | [] | [] | [akka.remote.Remoting] | Association to [akka.tcp://broker@129.1.6.12:6666] having UID [**-1447034877**] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote actorsystem must be restarted to recover from this situation.
[2016-04-28 17:07:52.724] | broker-akka.actor.default-dispatcher-23 | WARN |  | [] | [] | [akka.cluster.ClusterCoreDaemon] | Cluster Node [akka.tcp://broker@129.1.99.1:8888] - Marking node as TERMINATED [akka.tcp://broker@129.1.6.12:6666], due to quarantine
[2016-04-28 17:07:52.725] | broker-akka.actor.default-dispatcher-23 | INFO |  | [] | [] | [akka.cluster.Cluster(akka://broker)] | Cluster Node [akka.tcp://broker@129.1.99.1:8888] - Marking unreachable node [akka.tcp://broker@129.1.6.12:6666] as [Down]
[2016-04-28 17:07:52.725] | broker-akka.actor.default-dispatcher-23 | DEBUG |  | [] | [] | [akka.remote.EndpointWriter] | Disassociated [akka.tcp://broker@129.1.99.1:8888] -> [akka.tcp://broker@129.1.6.12:6666]
[2016-04-28 17:07:52.738] | broker-akka.actor.default-dispatcher-23 | INFO |  | [] | [] | [akka.cluster.Cluster(akka://broker)] | Cluster Node [akka.tcp://broker@129.1.99.1:8888] - Ignoring received gossip status from unreachable [UniqueAddress(akka.tcp://broker@129.1.6.12:6666,**-1447034877**)] 
[2016-04-28 17:07:53.269] | broker-akka.actor.default-dispatcher-21 | WARN |  | [] | [] | [akka.remote.EndpointWriter] | AssociationError [akka.tcp://broker@129.1.99.1:8888] -> [akka.tcp://broker@129.1.6.12:6666]: Error [Invalid address: akka.tcp://broker@129.1.6.12:6666] [
akka.remote.InvalidAssociation: Invalid address: akka.tcp://broker@129.1.6.12:6666
Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system has a UID that has been quarantined. Association aborted.
]

**Comment by zorowonder** [comment] 2016-05-17 09:24
Reproducer:

Test code:

```scala

object RDSLeakNodeBTest extends App{

  val configOfB = ConfigFactory.parseString(
    """
      | akka.actor.provider = "akka.cluster.ClusterActorRefProvider"
      | akka.loglevel = DEBUG
      | akka.remote.netty.tcp.hostname = "127.0.0.1"
      | akka.remote.netty.tcp.port = 8888
      | akka.remote.quarantine-after-silence = 60 s
      | akka.cluster.roles = ["test-b"]
      | akka.cluster.seed-nodes = ["akka.tcp://test@127.0.0.1:8888"]
      | akka.extensions = ["akka.cluster.sharding.ClusterSharding"]
      | akka.cluster.sharding.role = "test-b"
      | akka.persistence.journal.plugin = "akka.persistence.journal.inmem"
      | akka.persistence.snapshot-store.plugin = ""
      |
    """.stripMargin)

  // For test here, any setting is ok
  case class TestEnvelope(dst: String, message: AnyRef)

  val extractEntityId: ExtractEntityId = {case _@TestEnvelope(dst, msg) ⇒ (dst, msg)}

  val extractShardId: ExtractShardId = {case TestEnvelope(dst: String, msg: Any) ⇒ dst.## % 100 toString}

  class TestEntity extends Actor {
    override def receive: Receive = {case x ⇒}
  }

  def props = {Props(classOf[TestEntity])}

  val system = ActorSystem("test", configOfB)

  Cluster(system) registerOnMemberUp {
    // start to trigger the `SystemMessage`
    ClusterSharding(system).start(
      typeName = "b",
      entityProps = props,
      settings = ClusterShardingSettings(system),
      extractEntityId = extractEntityId,
      extractShardId = extractShardId)
  }

}

```

```scala

object RDSLeakNodeATest extends App{

  val configOfA = ConfigFactory.parseString(
    """
      | akka.actor.provider = "akka.cluster.ClusterActorRefProvider"
      | akka.loglevel = DEBUG
      | akka.remote.netty.tcp.hostname = "127.0.0.1"
      | akka.remote.netty.tcp.port = 6666
      | akka.remote.quarantine-after-silence = 60 s
      | akka.cluster.roles = ["test-a"]
      | akka.cluster.seed-nodes = ["akka.tcp://test@127.0.0.1:8888"]
      | akka.extensions = ["akka.cluster.sharding.ClusterSharding"]
      |
    """.stripMargin)

  // For test here, any setting is ok
  case class TestEnvelope(dst: String, message: AnyRef)

  val extractEntityId: ExtractEntityId = {case _@TestEnvelope(dst, msg) ⇒ (dst, msg)}

  val extractShardId: ExtractShardId = {case TestEnvelope(dst: String, msg: Any) ⇒ dst.## % 100 toString}

  val system = ActorSystem("test", configOfA)

  Cluster(system) registerOnMemberUp {
    // start region to trigger the `SystemMessage`
    val region = ClusterSharding(system).startProxy("b", Some("test-b"), extractEntityId, extractShardId)
  }
}

```

Operating Steps:
1.Run `RDSLeakNodeBTest`
2.Run `RDSLeakNodeATest`
3.When cluster's members are all [UP], Restart `RDSLeakNodeATest`
4.When cluster's members are all [UP] again, Stop `RDSLeakNodeATest`
5.Wait for `RDSLeakNodeBTest`'s log printing the info that describe marking Node A as Unreachable, may be a few seconds, and then Start `RDSLeakNodeATest`
6.Wait for the log in `RDSLeakNodeBTest` about 60 seconds(`quarantine-after-silence` = 60 s here)

Then the exception should appear.

**Comment by drewhk** [comment] 2016-05-23 09:33
Yes, the problem seems real. Thank you for reporting and the very detailed analysis!

**Comment by patriknw** [comment] 2016-05-30 12:14
Thanks guys!

**Closed by patriknw** 2016-05-30 12:14 UTC
Labels: 1 - triaged, bug, t:remoting
