### ISSUE TITLE
akka-typed-experimental should depend on akka-testkit in scope "test"

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#21916] opened 2016-11-30 18:07 UTC
currently:

https://repo1.maven.org/maven2/com/typesafe/akka/akka-typed-experimental_2.11/2.4.14/akka-typed-experimental_2.11-2.4.14.pom

`akka-typed-experimental` depends on `akka-testkit` in scope "compile"

**Comment by ktoso** [comment] 2016-11-30 18:09
Whoop :O Would you submit a fix if possible?

**Comment by patriknw** [comment] 2016-11-30 18:44
This is a duplicate of https://github.com/akka/akka/issues/21524
It's a bit more work than just changing the scope of the dependency, but it should be done.
Contribution to the other ticket is of course welcome.

**Closed by patriknw** 2016-11-30 18:44 UTC
Labels: 1 - triaged, community, t:build
