### ISSUE TITLE
Example code missing in documentation

### ISSUE THREAD

**Issue by matthewadams** [akka/akka#19941] opened 2016-03-02 20:06 UTC
At http://doc.akka.io/docs/akka/2.4.2/scala/stream/stream-io.html#Connecting__REPL_Client there is code missing.  The text `ąio/StreamTcpDocSpec.scala#repl-client` appears when I think there should be a code example.

**Comment by 2m** [comment] 2016-03-03 11:25
Thanks for reporting. It is a duplicate of https://github.com/akka/akka/issues/19830 and already fixed. You can access the nighly published docs [here](http://doc.akka.io/docs/akka/snapshot/scala/stream/stream-io.html#Connecting__REPL_Client).

**Closed by 2m** 2016-03-03 11:25 UTC
