### ISSUE TITLE
document how to achieve exactly-once delivery semantics and what that means

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15688] opened 2014-08-19 13:55 UTC
Due to popular disinformation we need to document how to achieve “exactly-once” semantics e.g. as discussed in [this paper](http://static.googleusercontent.com/media/research.google.com/en/us/pubs/archive/41378.pdf). We should be clear, though, that this in fact only achieves at-least-once semantics within the framework and at-most-once semantics for then calling the user code. The difference may be subtle, but it is important to be honest about what is strictly guaranteed and what is not.

**Comment by Captain1653** [comment] 2021-08-31 19:46
The issue is really old. I have found some [Delivery Garantee](https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/distributed-pub-sub.md#delivery-guarantee) and [Message Delivery Reliability](https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/general/message-delivery-reliability.md) . Is it still needed?

**Comment by johanandren** [comment] 2021-09-01 08:26
Let's close it.

**Closed by johanandren** 2021-09-01 08:26 UTC
Labels: 1 - triaged, t:docs
