### ISSUE TITLE
FAILED: RemoteNodeShutdownAndComesBack

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17815] opened 2015-06-23 16:14 UTC
Timeout in RemoteNodeShutdownAndComesBack

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2559/consoleFull

```
//RemoteNodeShutdownAndComesBackSpec/deadLetters] received dead letter from Actor[akka://RemoteNodeShutdownAndComesBackSpec/system/remote-watcher#217843977]: Heartbeat
[JVM-1] - must properly reset system message buffer state when new system with same Address comes up *** FAILED *** (16 seconds, 55 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during fishForMessage, hint:
[JVM-1]   at scala.Predef$.assert(Predef.scala:165)
[JVM-1]   at akka.testkit.TestKitBase$class.recv$1(TestKit.scala:401)
[JVM-1]   at akka.testkit.TestKitBase$class.fishForMessage(TestKit.scala:405)
[JVM-1]   at akka.testkit.TestKit.fishForMessage(TestKit.scala:738)
[JVM-1]   at akka.remote.RemoteNodeShutdownAndComesBackSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(RemoteNodeShutdownAndComesBackSpec.scala:121)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
[JVM-1]   at akka.remote.RemoteNodeShutdownAndComesBackSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(RemoteNodeShutdownAndComesBackSpec.scala:66)
[JVM-1]   at akka.remote.RemoteNodeShutdownAndComesBackSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RemoteNodeShutdownAndComesBackSpec.scala:65)
[JVM-1]   at akka.remote.RemoteNodeShutdownAndComesBackSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RemoteNodeShutdownAndComesBackSpec.scala:65)
[JVM-1]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[JVM-1]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-1]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-1]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[JVM-1]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[JVM-1]   at akka.remote.RemoteNodeShutdownAndComesBackSpec.withFixture(RemoteNodeShutdownAndComesBackSpec.scala:50)
[JVM-1]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[JVM-1]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[JVM-1]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[JVM-1]   at akka.remote.RemoteNodeShutdownAndComesBackSpec.runTest(RemoteNodeShutdownAndComesBackSpec.scala:50)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[JVM-1]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[JVM-1]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
```

**Comment by patriknw** [comment] 2015-06-24 15:06
this is a duplicate of #17556

**Closed by patriknw** 2015-06-24 15:06 UTC
Labels: failed, t:cluster
