### ISSUE TITLE
Sugar for Sink.ignore

### ISSUE THREAD

**Issue by raboof** [akka/akka#27789] opened 2019-09-25 08:47 UTC
It is fairly common to have a source that you would like to run, ignoring the elements it outputs because your objective is already met by the effect of the last flow in the chain.

Right now this typically looks something like `mySource.map(f).via(someEffectingFlow).runWith(Sink.ignore)`. `Sink.ignore` here correctly describes what this sink does (it ignores the elements flowing into it), but it doesn't really have anything to do with what the user intended to achieve here.

It might be helpful to include a `mySource.map(f).via(someEffectingFlow).run()` sugar method (that simply runs with `Sink.ignore`)

**Comment by hepin1989** [comment] 2019-09-30 03:23
`runWithIgnore` or `run` both ok:)

**Comment by johanandren** [comment] 2019-10-10 11:57
Slightly related to #27836 perhaps

**Comment by johanandren** [comment] 2020-03-23 12:06
Duplicate of #24986

**Closed by johanandren** 2020-03-23 12:06 UTC
Labels: 1 - triaged, t:stream
