### ISSUE TITLE
OOM java heap space issue seen in akka version 2.3.14

### ISSUE THREAD

**Issue by SaiSujithReddy** [akka/akka#21472] opened 2016-09-15 23:43 UTC
Akka   :- 2.3.14 version
Set up :- OpendayLight Cluster with 3 node instance. 

Cluster setup was running for a month, with sporadic network connection issues among nodes. 
Isolated Leader / Extra leaders among the nodes are observed during the period. 

Attaching a screenshot which shows akka.remote.EndPointManager$Send retained heap, dominator tree chart, path2gc as well the list_objects with outgoing reference. 

Have you guys have seen this issue before ?

[Akka_OOM_issue_Domiator_Patch2GC_listObjects.pdf](https://github.com/akka/akka/files/475812/Akka_OOM_issue_Domiator_Patch2GC_listObjects.pdf)

**Comment by drewhk** [comment] 2016-09-16 08:26
You are sending messages faster than remoting can keep up, so the Send messages pile up in its mailbox, growing the queue out of bounds until it consumes all the heap.

**Comment by tpantelis** [comment] 2016-09-16 11:51
There wasn't a high message rate. This issue was reported by a client (a large service provider). The queue memory growth occurred over several days. We have a raft implementation that sends AppendEntries heart beat messages every 500 ms and there are 8 raft actors so there would be 16 AppendEntries messages a sec. This is normal operation and works fine. We've been able to push a couple hundred messages a sec thru akka remoting over a period of time (depending on network latency of course). 

There were network issues in the client's environment. What it looks like is that the node in question was isolated or had periodic isolation for a long period of time and the AppendEntries heart beat messages built up in the EndpointWriter's LinkedList queue. So we thought akka's queue was growing b/c it there's no remote connectivity and thus isn't draining it. I would think akka would flush its queue on disconnect/unreachability and then drop subsequent messages b/c akka has at-most-once deliver semantics (which is fine). So we tried to reproduce by purposely isolating a node and let it run for 8 hours but we didn't see any queue/memory growth.

So it appears akka remoting got into some weird state in the client's environment where it didn't flush/drop messages when disconnected/unreachable or it stopped dequeing and sending messages. 

We were hoping maybe this has been seen before and maybe fixed in 2.4.x or someone could ascertain how it could possibly happen by looking at the code.

**Comment by drewhk** [comment] 2016-09-16 12:12
> So we thought akka's queue was growing b/c it there's no remote connectivity and thus isn't draining it. 

Ok, thanks for the detailed explanation. So what remoting does is that it gates connections if heartbeats are not received for a certain period. If it gates a connection, then it also drops everything. This is how it works roughly: http://doc.akka.io/docs/akka/2.4/scala/remoting.html#Lifecycle_and_Failure_Recovery_Model

> So it appears akka remoting got into some weird state in the client's environment where it didn't flush/drop messages when disconnected/unreachable or it stopped dequeing and sending messages.

This means that a connection never timed out on missed heartbeats, but that implies that the connection was not really broken. 

It should also log if this internal queue grows too large: https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/Endpoint.scala#L712

> We were hoping maybe this has been seen before and maybe fixed in 2.4.x or someone could ascertain how it could possibly happen by looking at the code.

No, the usual reason we see if the remoting is overwhelmed, hence did we put that log statement in there. These messages can also pile up in mailbox which is the other usual culprit. All I can imagine that the connection is not completely broken (heartbeats get through), but slow enough so this queue grows out of bounds. I keep this tagged as `new` for now, we need more information to confirm the cause here.

**Comment by tpantelis** [comment] 2016-09-16 12:57
Thanks for the response and info. I figured akka would drop messages on loss of connection. In our test we added IP table rules to drop packets between the 2 nodes for port 2550 and, as I mentioned, we saw no growth.  We'll take a look at the client's log in more detail based on the info you provided and compare with the log from our run.

We have tested with high messages rates that appear to saturate remoting b/c we'll see UNREACHABLE <-> REACHABLE flapping that I believe is caused by akka's heart beat messages getting delayed enough to cause the phi accrual algorithm to flag unreachable. We didn't hit OOM though but I imagine the queue did back up but not enough to run OOM.

**Comment by SaiSujithReddy** [comment] 2016-09-19 05:00
Hi drewhk,

Attaching logs of node where we observed out of memory issue. 

[node3_logs.docx](https://github.com/akka/akka/files/479234/node3_logs.docx)

In logs certain patterns are observed where Leader cannot perform it duties because of reach-ability issues. Other nodes tried connecting node3 (new incarnation of existing node) but never joined the cluster to let leader perform its duties for a while. Quarantined node messages in logs can be correlated to the upward tick on memory usage graphs. It would be good to know on how the quarantined messages affect the OOM issue.

GC memory graph is attached. 

![gc_memory_inc_pic](https://cloud.githubusercontent.com/assets/3675345/18622924/4bc93ee2-7deb-11e6-8a80-035d97744494.PNG)

**Comment by SaiSujithReddy** [comment] 2016-09-22 20:02
Hi drewhk,

Please let us know if you need more details.

**Comment by patriknw** [comment] 2016-09-23 13:04
I'd recommend that you update to latest version 2.3.15 or 2.4.10. We fixed some bugs in remoting in 2.3.15 https://github.com/akka/akka/milestone/80?closed=1

**Comment by patriknw** [comment] 2016-10-11 07:12
@SaiSujithReddy any update here?

**Comment by tpantelis** [comment] 2016-10-11 11:38
Patrik,

Thanks for following up. We're all set right now. We weren't able to
reproduce it so hard to tell for sure if 2.3.15 fixes it
but our client agreed to close our ticket. They haven't experience the
issue since (in fact we've only seen it that one time).

Tom

**Comment by patriknw** [comment] 2016-10-11 12:05
Thanks for the update.

**Closed by patriknw** 2016-10-11 12:05 UTC
Labels: 0 - new, t:remoting
