### ISSUE TITLE
ORMap problems when re-adding elements

### ISSUE THREAD

**Issue by jroper** [akka/akka#27428] opened 2019-07-29 02:47 UTC
Consider this:

``` scala
val original = ORMap.empty[String, ReplicatedData] :+ ("foo" -> (GCounter.empty :+ 10))
```

Now, I then remove the element `foo`, and simulate that update being merged to a second node that has the original value:

```scala
val updated1 = original remove "foo"
val node2Updated1 = original merge updated1
```

I then add `foo` again, but this time with a different CRDT value, a `PNCounter` rather than a `GCounter`, and I simulate the replication of it to the current value that node2 holds, and it works:

```scala
val updated2 = updated1 :+ ("foo" -> PNCounter.empty)
val node2Updated2 = node2Updated1 merge updated2
node2Updated2: akka.cluster.ddata.ORMap[String,akka.cluster.ddata.ReplicatedData] = ORMap(foo -> PNCounter(0))
```

But let's say there is a third node, and it wasn't gossipped to during this time, so it still has the original value, and then the result of the two updates is merged across:

```
scala> original merge updated2
java.lang.IllegalArgumentException: Wrong type for merging [foo] in [akka.cluster.ddata.ORMap], existing type [akka.cluster.ddata.GCounter], got [akka.cluster.ddata.PNCounter]
```

I'm not sure whether at this point the CRDT will be able to sort itself out, or if it's going to stay in this unmergable state indefinitely, I think it's the latter. At a minimum, this behaviour should be documented, warning that you should never change the type of a CRDT value in an `ORMap`.

A similar problem arises when removing and adding elements of the same type back:

```
scala>       val updated3 = (original remove "foo") :+ ("foo" -> GCounter.empty)
updated3: akka.cluster.ddata.ORMap[String,akka.cluster.ddata.ReplicatedData] = ORMap(foo -> GCounter(0))

scala>       original merge updated3
res1: akka.cluster.ddata.ORMap[String,akka.cluster.ddata.ReplicatedData] = ORMap(foo -> GCounter(10))
```

The above will eventually converge with all nodes having a counter value of 10, not zero. Effectively, the old value is resurrected when you add it back, though this is completely non deterministic, it all depends on whether that old value still exists somewhere in the cluster, and the update gets replicated to it before the remove. This also should be documented.

Though, I'm wondering whether it can be fixed. I must admit, I still don't 100% understand exactly how `ORSet` works, I think it works using tags right? So, if the `ORMap` stores the tag of the key was added with along with the CRDT value, and then the merge function either deterministically selects one of the CRDT values if the tag is not the same, or if it is the same, merges them, then that would solve the problem. This approach however would probably mean that if two nodes concurrently added a `GCounter`, those operations wouldn't be merged, one would overwrite the other. I actually think that's ok, a put should mean the value is replaced, not merged, if I do:

```scala
Map("foo" -> 5) + ("foo" -> 5)
```

I expect to get:

```scala
Map("foo" -> 5)
```

not:

```scala
Map("foo" -> 10)
```

So, why wouldn't I expect exactly the same for `ORMap`? The current behaviour where the result of two puts is merged is odd, only the result of two updates should be merged.

**Comment by jroper** [comment] 2019-07-29 03:28
Ok, I'm not sure that he version vector used in `ORSet` allows for any sensible value selection (other than perhaps oldest/newest node, which is probably not useful), but what I've described could be implemented by storing values as a last write wins register with an embedded CRDT, so, a merge is done if the timestamp/node match, otherwise, the value is replaced by the one with the latter timestamp then oldest node.

**Comment by jroper** [comment] 2019-07-29 03:34
Also, I think the timestamp used for deciding wins could be the sum of the values in the `ORSets` version vector (assume it is effectively a `GCounter`, does pruning ever make its value go down?), this would guarantee that a remove followed by a put on the same node would result in the new value, not the old, being chosen, even if the clock of the node that added the old value is skewed ahead of the new.

**Comment by jroper** [comment] 2019-07-29 04:00
The current behavior has been documented in #27429.

**Comment by helena** [comment] 2019-07-30 19:55
Checking this

**Comment by helena** [comment] 2019-07-31 00:41
Great capture @jroper.  Yes in this scenario it is possible due to disorder. I agree with @patriknw and @raboof's comments that `ORMap` is lower level and the more specific are more type constrained. That said, I think also as @raboof noted there is an issue to look at.

Should we allow a change in type of a CRDT value in an ORMap
* It seems from discussions in #27429 that the type issue is by design, given the high level implementations one should use. I agree this is worth documenting but specify the context and recommendations to use the other impls.
* We could be less lenient and disallow it on `:+` and friends vs just `merge`, but it is still possible at  raise that conflict in type state, 
* In `+/-` the value is at least of type `_ <: B`
* In `merge` we check that the mergeTo value is exact:
   - Fail in attempts to update to a `ORSet[_]` 
   - Fail if `thisValue.getClass != thatValue.getClass`

The described scenario is expecting immediate success, but node three only has `t0 -> t2` while first and second have `t0 -> t1 -> t2`. This can apply to any of the CRDT types unrelated to type.
The larger solution for rectifying a timing discrepancy, regardless of type change, might be to handle with additional overhead (we already have much/most of this)
* configurable `converge-within` tolerance
* each node seeing a conflict runs the attempt until the tolerance timeout  

I've written a test similar to yours and adding a multi-node to run without simulating the case. Will push it linking this and #27429 as part of discussion.

**Comment by helena** [comment] 2019-08-01 14:21
Had a re-think on this after looking at #27429. Given @patriknw and @raboof's thoughts I think for now the clarification in the doc is an important starting point. Though this issue should not be closed if that docs PR is merged.

**Comment by helena** [comment] 2019-08-01 14:22
Not ready to mark as triaged yet either.

**Closed** 2019-10-01 14:40 UTC
Labels: discuss, t:cluster-ddata
