### ISSUE TITLE
In akka-http-RC3 some cookies parse error can make exist cookie not recognition

### ISSUE THREAD

**Issue by huanwuji** [akka/akka#17741] opened 2015-06-16 09:39 UTC
I use code: like this optionalCookie(sessionName)
Some times it can't be found
I see the browse requset:
Cookie:JSESSIONID=E18342947CE9463A9F74F0EE12E203B3; JSESSION=6f7e4abc-9808-447b-8478-bcc999a91d5c; Hm_lvt_abd6bec572d8b044e12f13b5f135a169=1434420714; Hm_lpvt_abd6bec572d8b044e12f13b5f135a169=1434447013

It's exists, then I find the logs, has this errors:
akka.actor.ActorSystemImpl - Illegal request header: Illegal 'cookie' header: Invalid input ';', expected tchar, '\r', WSP or '=' (line 1, column 62): Hm_lvt_abd6bec572d8b044e12f13b5f135a169=1433731831,1433751982; Hm_lpvt_abd6bec572d8b044e12f13b5f135a169=1433752022

So I don't know is this cause, because we add the script in html, this is a website statistics javascript.
    var _hmt = _hmt || [];
    (function () {
        var hm = document.createElement("script");
        hm.src = "//hm.baidu.com/hm.js?abd6bec572d8b044e12f13b5f135a169";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
I delete this code,start with 'Hm_' cookie not add, then it's become normal.

**Comment by rkuhn** [comment] 2015-06-16 11:25
This is a duplicate of #16828.

**Closed by rkuhn** 2015-06-16 11:25 UTC
