### ISSUE TITLE
When trying to roll out versions between 2.4 to 2.5 in cluster the dc setting requirement fails

### ISSUE THREAD

**Issue by ktoso** [akka/akka#25496] opened 2018-08-20 02:08 UTC
When rolling out to 2.5 from a 2.4 cluster, _which technically is not guaranteed to work but we can try to make it not fail on simple things_, the:

```
akka.actor.OneForOneStrategy: DataCenter undefined, should not be possible
java.lang.IllegalStateException: DataCenter undefined, should not be possible
at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
```

fails. I think it may be safe to assume it is dc-default, since 2.4 has no idea about DCs in any case.

I'll propose a PR

**Comment by patriknw** [comment] 2018-08-20 13:58
I confirmed that this is an issue in 2.5.6 but works in 2.5.9 since the serializer adds the default (we probably fixed in 2.5.7, can't find the issue).

**Closed by patriknw** 2018-08-20 13:58 UTC
Labels: t:cluster, t:cluster:dc
