### ISSUE TITLE
Clustering issues leading to all nodes being downed.

### ISSUE THREAD

**Issue by fredfp** [akka/akka#31095] opened 2022-01-27 09:59 UTC
We had a case where an issue on a single node lead to the whole akka-cluster being taken down.

### Here's a summary of what happened: 
1. Healthy cluster made of 20ish nodes, running on k8s
2. Node A: encounters issues, triggers CoordinatedShutdown
3. Node A: experiences high CPU usage, maybe GC pause 
4. Node A: sees B as unreachable, broadcasts it (B is certainly reachable, but detected as such because of high CPU usage, GC pause, or similar issues)
5. Cluster state: A Leaving, B seen unreachable by A, all the other nodes are Up
6. Leader can currently not perform its duties (remove A), reachability status (B seen unreachable by A)
7. Node A: times out some coordinated shutdown phases. Hypothesis: timed out because leader could not remove A.
8. Node A: finishes coordinated shutdown nonetheless.
9. hypothesis - Node A: quarantined associations to other cluster nodes
10. Nodes B, C, D, E: SBR took decision DownSelfQuarantinedByRemote and is downing [...] including myself
11. hypothesis - Node B, C, D, E: quarantined associations to other cluster nodes
12. in a few steps, all remaining cluster nodes down themselves: SBR took decision DownSelfQuarantinedByRemote
13. the whole cluster is down

### Discussions, potential issues:

Considering the behaviour of CoordinatedShutdown (phases can time out and shutdown continues), shouldn't the leader ignore unreachabilities added by a Leaving node and be allowed to perform its duties?
At step 6 above, the Leader was blocked from removing A, but A still continued its shutdown process. The catastrophic ending could have been stopped here.

DownSelfQuarantinedByRemote: @patriknw 's [comment](https://github.com/akka/akka/pull/29737#discussion_r515906571) seems spot on.
At step 9, nodes B, C, D, E should probably not take into account the `Quarantined` from a node that is Leaving.

DownSelfQuarantinedByRemote: another case where Patrik's [comment](https://github.com/akka/akka/pull/29737#discussion_r515906571) also seems to apply, `Quarantined` from nodes downing themselves because of DownSelfQuarantinedByRemote should probably not be taken into account.

At steps 10 and 12. Any cluster singletons running on affected nodes wouldn't be gracefully shutdown using the configured termination message. This is probably the right thing to do but I'm adding this note here nonetheless.

**Comment by yufei-cai** [comment] 2022-03-07 13:45
Hi, our cluster of ~33 members running Akka 2.6.18 downed itself twice due to DownSelfQuarantinedByRemote decisions made by every member.
Could it be related to this issue?

Incident 1:
- The cluster was performing rolling update such that 1 cluster member restarts every 30 second. All surviving cluster members chose DownSelfQuarantinedByRemote simultaneously 3 times over 12 minutes. The cluster members ran as Kubernetes pods. Each time after the cluster was downed, Kubernetes restarted the members, which formed a new cluster via bootstrapping.

Incident 2:
- [Kured](https://github.com/weaveworks/kured) restarted the VMs on which the cluster was running. Kured restarted the VMs one by one after cordoning and draining them. Simultaneous DownSelfQuarantinedByRemote decisions were made after some but not all VM restarts. Kubernetes restarted the pods after each downing and the pods formed new clusters via bootstrapping.

We upgraded to Akka 2.6.18 in January 2022. Rolling updates and VM restarts happened many times since and did not usually cause every member to choose DownSelfQuarantinedByRemote.

**Comment by patriknw** [comment] 2022-03-09 08:09
Would it be possible reproduce the incidents and share logs from all pods with us? Would be helpful if it could be reproduced with as few members as possible to reduce the amount of logs to analyze.

**Comment by fredfp** [comment] 2022-03-22 20:12
@patriknw what logs would you like to see? I did a quite minute analysis to extract my summary above, I might still be able to recover some more if you tell me what you need (bulk extraction didn't work last I tried).

**Comment by nodefactory-bk** [comment] 2022-03-29 08:03
I'm seeing similar behaviour since we upgraded to akka 2.6.17.
Running in kubernetes if one application in the cluster runs rolling updates and there is a load spike every other app sometimes downs itself with DownSelfQuarantinedByRemote.

Unfortunately due to issues with our kubernetes logging it is very time consuming getting the logs and I can't reproduce it in a controlled manner since it happens randomly and mostly in production =/
However what I do see is it starting with ONE node quarantineing many other nodes, and then those nodes in turn start quarantineing others.
One example of this is:
`2022-03-29 08:50:10.673  Other node [akka://prod@10.12.10.129:2552#5857564371663152447] quarantined this node.`
which is repeated for all nodes in the cluster. 
But that node was already downed and shutting down 5 seconds earlier:
`2022-03-29 08:50:05.840 Cluster Node [akka://prod@10.12.10.129:2552] - Node has been marked as DOWN. Shutting down myself`
Thus the ONE cluster node that was having problems quarantined all others and took down the cluster.

This is the view of the cluster from "10.12.10.129" just before it started shutting itself down:
```
2022-03-29 08:50:05.817 Cluster state:
  My roles: john,dc-default
  Seen roles: holly,fritz,resellersvc,john,theo,ellis,payson-api,nakatomi,uli,dc-default,adminsvc,tenantrepo,powell,thornburg,marvin,gruber,connectorsvc
  Members Exiting count=1:
    akka://prod@10.12.11.138:2552 - dc-default, john
  Members Down count=1:
    akka://prod@10.12.10.129:2552 - dc-default, john
  Members Up count=33:
    akka://prod@10.12.0.12:2552 - dc-default, nakatomi, tenantrepo
    akka://prod@10.12.0.13:2552 - connectorsvc, dc-default, gruber
    akka://prod@10.12.0.14:2552 - dc-default, powell
    akka://prod@10.12.0.15:2552 - dc-default, john
    akka://prod@10.12.10.124:2552 - dc-default, uli
    akka://prod@10.12.10.126:2552 - adminsvc, dc-default, marvin, resellersvc
    akka://prod@10.12.10.127:2552 - connectorsvc, dc-default, gruber
    akka://prod@10.12.10.128:2552 - dc-default, ellis
    akka://prod@10.12.11.139:2552 - dc-default, uli
    akka://prod@10.12.11.140:2552 - adminsvc, dc-default, marvin, resellersvc
    akka://prod@10.12.11.141:2552 - dc-default, payson-api
    akka://prod@10.12.3.18:2552 - dc-default, thornburg
    akka://prod@10.12.3.91:2552 - dc-default, nakatomi, tenantrepo
    akka://prod@10.12.3.92:2552 - connectorsvc, dc-default, gruber
    akka://prod@10.12.3.93:2552 - dc-default, powell
    akka://prod@10.12.3.94:2552 - dc-default, holly
    akka://prod@10.12.3.95:2552 - dc-default, theo
    akka://prod@10.12.5.118:2552 - dc-default, john
    akka://prod@10.12.5.127:2552 - dc-default, fritz
    akka://prod@10.12.5.128:2552 - dc-default, theo
    akka://prod@10.12.5.129:2552 - dc-default, payson-api
    akka://prod@10.12.6.17:2552 - dc-default, thornburg
    akka://prod@10.12.6.91:2552 - dc-default, nakatomi, tenantrepo
    akka://prod@10.12.6.92:2552 - connectorsvc, dc-default, gruber
    akka://prod@10.12.6.93:2552 - dc-default, theo
    akka://prod@10.12.6.94:2552 - dc-default, ellis
    akka://prod@10.12.8.163:2552 - dc-default, uli
    akka://prod@10.12.8.164:2552 - adminsvc, dc-default, marvin, resellersvc
    akka://prod@10.12.8.165:2552 - connectorsvc, dc-default, gruber
    akka://prod@10.12.8.166:2552 - dc-default, powell
    akka://prod@10.12.8.167:2552 - dc-default, holly
    akka://prod@10.12.8.168:2552 - dc-default, ellis
    akka://prod@10.12.8.21:2552 - dc-default, thornburg
  UNREACHABLE:
    akka://prod@10.12.11.138:2552 - dc-default, john
    akka://prod@10.12.3.93:2552 - dc-default, powell
```

Is it possible to disable DownSelfQuarantinedByRemote for now?

**Comment by source-nerd** [comment] 2022-04-13 09:22
We are facing same thing - running ~50 Node Akka Cluster and experiencing DownSelfQuarantinedByRemote quite frequently, Any update on the issue?

**Closed** 2023-08-18 07:29 UTC
Labels: t:cluster, bug

**Comment by patriknw** [comment] 2023-09-20 11:20
Also backported to 2.8.5
