### ISSUE TITLE
FAILED: FileUploadDirectivesExamplesSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20727] opened 2016-06-06 09:37 UTC
https://jenkins.akka.io:8498/job/akka-nightly/3387/consoleFull

```
[info] - uploadedFile *** FAILED *** (1 second, 69 milliseconds)
[info]   Request was neither completed nor rejected within 1 second (FileUploadDirectivesExamplesSpec.scala:35)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest$class.failTest(TestFrameworkInterface.scala:24)
[info]   at docs.http.scaladsl.server.RoutingSpec.failTest(RoutingSpec.scala:12)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.failNeitherCompletedNorRejected(RouteTestResultComponent.scala:94)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.rawResponse(RouteTestResultComponent.scala:59)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.response(RouteTestResultComponent.scala:40)
[info]   at akka.http.scaladsl.testkit.RouteTest$class.response(RouteTest.scala:62)
[info]   at docs.http.scaladsl.server.RoutingSpec.response(RoutingSpec.scala:12)
[info]   at akka.http.scaladsl.testkit.RouteTest$class.status(RouteTest.scala:80)
[info]   at docs.http.scaladsl.server.RoutingSpec.status(RoutingSpec.scala:12)
[info]   at docs.http.scaladsl.server.directives.FileUploadDirectivesExamplesSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(FileUploadDirectivesExamplesSpec.scala:35)
[info]   at docs.http.scaladsl.server.directives.FileUploadDirectivesExamplesSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FileUploadDirectivesExamplesSpec.scala:35)
[info]   at docs.http.scaladsl.server.directives.FileUploadDirectivesExamplesSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FileUploadDirectivesExamplesSpec.scala:35)
[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[info]   at akka.http.scaladsl.testkit.RouteTest$$anonfun$check$1.apply(RouteTest.scala:57)
[info]   at akka.http.scaladsl.testkit.RouteTest$$anonfun$check$1.apply(RouteTest.scala:57)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.$tilde$greater(RouteTestResultComponent.scala:51)
[info]   at 
```

**Comment by pjazdzewski1990** [comment] 2016-06-13 13:23
Hi @drewhk Is this issue up for grabs? If it is, could you add more details to it? I would like to fix it, if it's still an issue (current `master` looks good). Thanks

**Comment by 2beaucoup** [comment] 2016-06-18 20:58
Duplicate of #19792?

**Comment by ktoso** [comment] 2016-06-19 00:09
Yeah seems like a reappearance of same issue.
Keeping this open though as the previous one was worked on and merged before (for easier tracking when what was merged or worked on)

**Comment by drewhk** [comment] 2016-06-19 12:26
Hi @pjazdzewski1990 yes, these FAILURE tickets are up for grab in general. These tickets are usually filed when we have a nightly Jenkins test failure somewhere. The "failed" tag basically implies the following procedure:
 - look at the failure in detail (by default the ticket just marks the fact of failure)
 - try to understand the nature of the failure. Can be a real bug, can be a wrong test case, can be just a too tight timeout
 - solve the issue, or add more details to the ticket (what was the result of investigation)

We just usually omit these steps from the ticket description as they are always the same for those tagged "failed".

**Closed** 2016-08-09 16:03 UTC
Labels: 3 - in progress, failed, t:docs, t:http
