### ISSUE TITLE
akka-http: Cancelling an HttpResponse's entity stream should close the TCP connection

### ISSUE THREAD

**Issue by mspielberg** [akka/akka#18010] opened 2015-07-16 00:46 UTC
In 1.0-RC4, if a client cancels the entity Source of an HttpResponse (e.g. with take(), or .runWith(Sink.cancelled),), akka-http continues to consume the response from the network, discarding the content, and continues to use the connection for future requests. This can be very expensive for a large response body that the client decides early it is not interested in consuming.

#17403 addresses clients not consuming the response entity at all. This ticket is intended to address the performance problems of using Sink.ignore when the response entity may be very large.

This may stem from the use of splitWhen in OutgoingConnectionBlueprint, which isolates cancellation of the substreams from cancellation of the overarching request stream. If I understand correctly #16870 originally looked to add configuration for how substream cancellation is propagated, but was closed as invalid in favor of another approach not described in that issue.

**Comment by rkuhn** [comment] 2015-08-30 14:07
duplicate of #18203?

**Comment by drewhk** [comment] 2015-09-10 10:20
This is because the TCP stream implementation treats cancel() as ignore. This is necessary because:
 - There is no protocol action at the TCP level to "stop reading"
 - if you treat cancel as simply not reading, compared to reading but ignoring it, then you will never get the completion events from NIO.

The only closing action that actually translates to TCP connetion close events are the closing of the write side.

**Comment by drewhk** [comment] 2015-09-10 10:21
there needs to be some element in the HTTP pipeline then that captures upstream cancellation and turns into downstream completion if this is a desired functionality.

**Comment by mspielberg** [comment] 2015-09-10 20:54
If it helps, this is a blocker for my organization to adopt akka-http. Our use case involves multi-GB HTTP transfers where cancellation is common (e.g. streaming video). With the current behavior we're seeing network interfaces getting saturated with data that is immediately discarded.

To be clear, the desired behavior is that cancelling the response entity should result in a RST being sent to the server and the entire TCP connection being torn down. If translating cancellation of the write side into completing the read side results in a FIN to the server, this is insufficient since the server may continue sending data into the half-closed TCP connection.

**Comment by drewhk** [comment] 2015-09-11 10:39
@mspielberg 

> To be clear, the desired behavior is that cancelling the response entity should result in a RST being sent to the server and the entire TCP connection being torn down.

It is not a good idea to map `cancel()` to RST because a Flow cancellation and completion can be in a race to reach the TCP connection flow, which would mean that a normal completion would nondeterministically turn into an abort or half-close then abort

> If translating cancellation of the write side into completing the read side results in a FIN to the server, this is insufficient since the server may continue sending data into the half-closed TCP connection.

There are two options here:
 - fail the write side (onError) instead of completing normally (onComplete) and that will turn into a RST
 - use the `halfClose=false` setting on the connection (I think this is not exposed in HTTP only TCP, but we can change that) which will use the Java socket `close()` method, which is a mystery for me since it is kind-of a "full-close" although there is no such thing in TCP. It seems to be a mix of half-close and RST depending on the situation, but it is a mystery for me to be honest.

Currently what you need is to turn the cancellation to failing the write side.

> If it helps, this is a blocker for my organization to adopt akka-http.

Just fail the write-side stream and it will do a RST. Unfortunately cancel() cannot be turned to RST without serious unintended consequences do to the limitations of TCP, NIO and potential blocking clients.

I can probably put together a stage to do this more easily, i.e. take a bidirectional Flow and turn it into a Source that translates cancellation to failing the write side of the original Flow (and completing it normally once the read side completes normally). Maybe that is the proper solution here?

**Comment by mspielberg** [comment] 2015-09-11 18:22
>It is not a good idea to map cancel() to RST because a Flow cancellation and completion can be in a race to reach the TCP connection flow, which would mean that a normal completion would nondeterministically turn into an abort or half-close then abort

I'm referring to cancel()ing the Source representing the response entity in an HttpResponse instance. I'm not entirely clear how a cancel() would race against a close() in this context. Isn't consumption of this Source entirely under the application's control?

>which will use the Java socket close() method, which is a mystery for me since it is kind-of a "full-close" although there is no such thing in TCP. It seems to be a mix of half-close and RST depending on the situation, but it is a mystery for me to be honest.

I believe the JVM maps this to a shutdown(fd, SHUT_RDWR) call, although I'm not certain. As I understand it this tells the kernel to do a half-close of its write side (FIN), and send RST if any further data is received from the remote side or if there is unread data in the kernel receive buffers.

>Just fail the write-side stream and it will do a RST.

We're using the automatic client connection pooling mechanism exposed by the methods cachedHostConnectionPool, superPool, singleRequest, etc. When using this mechanism we don't have easy access to the Flow that represents the particular connection associated with a given HttpResponse, so unless I'm missing something I don't think we have the ability to fail the write side.

>Unfortunately cancel() cannot be turned to RST without serious unintended consequences do to the limitations of TCP, NIO and potential blocking clients.

Can you elaborate? Again, the distinction between cancel() on the Flow representing the HttpResponse's entity vs. cancel() on the Flow representing the TCP connection may be meaningful here.

**Comment by drewhk** [comment] 2015-09-11 19:24
> I'm referring to cancel()ing the Source representing the response entity in an HttpResponse instance. I'm not entirely clear how a cancel() would race against a close() in this context. Isn't consumption of this Source entirely under the application's control?

Well, there is an asymmetry here with the single connection Flow and the pooled or per request versions. You are right, this is not a simple mapping between the TCP connection and the HTTP connection.

> I believe the JVM maps this to a shutdown(fd, SHUT_RDWR) call, although I'm not certain. As I understand it this tells the kernel to do a half-close of its write side (FIN), and send RST if any further data is received from the remote side or if there is unread data in the kernel receive buffers.

Ok, that confirms my suspicion then. 

> When using this mechanism we don't have easy access to the Flow that represents the particular connection associated with a given HttpResponse, so unless I'm missing something I don't think we have the ability to fail the write side.

You are right, I have not considered that.

> Again, the distinction between cancel() on the Flow representing the HttpResponse's entity vs. cancel() on the Flow representing the TCP connection may be meaningful here.

Yep, this is different, I totally agree. In that context mapping the response cancel() to actually RST makes total sense. (I always tend to think of the HTTP stuff as simple wrappers around a TCP Flow, but with the pools that is entirely different matter)

/cc @sirthias @jrudolph

**Comment by drewhk** [comment] 2015-09-11 19:27
Btw, this really seems to be a duplicate of: https://github.com/akka/akka/issues/18203

**Comment by ataraxer** [comment] 2016-01-20 08:22
Since there haven't been any progress so far and this change is rather important for us to migrate to Akka HTTP I've attempted to fix it in #19528. I would be grateful if someone could take a look at it at this stage to comment on proposed API changes and check some implementation details.

**Comment by drewhk** [comment] 2016-02-04 11:55
I am closing this one in favor of #18203, and the PR https://github.com/akka/akka/pull/19528/files should solve this and that one soon.

**Closed by drewhk** 2016-02-04 11:55 UTC
Labels: 3 - in progress, t:http, t:http:client, t:http:core
