### ISSUE TITLE
Cluster sharding entities are not being restarted when coordinator is moved to another node (continued from #21892)

### ISSUE THREAD

**Issue by lukas-phaf** [akka/akka#22064] opened 2016-12-23 15:16 UTC
This is related to #21892. I still see some problems, and @patriknw asked me to open a new issue for it.

I also ran into this #21892 bug in 2.4.14, and used 2.4.11 to avoid it. I tested this in 2.4.16.

The entities are now indeed restarted when the coordinator recovers on another node, but I did find a case where this is not working. I am using a cluster of 4 nodes, with `akka.cluster.min-nr-of-members = 3`. If I crash the oldest node, the shard coordinator is recovered on the second node, and the entities are restarted on the surviving nodes. If I now crash the node with the new shard coordinator (leaving 2 nodes), the shard coordinator is indeed recovered on one of the two remaining nodes, but the entities are not restarted.

If I repeat the same experiment with `akka.cluster.min-nr-of-members` not set, the entities are restarted after the second coordinator recovery. 

So my conclusion is that entities are not restarted on coordinator recovery if the remaining number of nodes is below `akka.cluster.min-nr-of-members`.

I do not see the same problem in 2.4.11.

**Comment by patriknw** [comment] 2017-01-03 18:51
@lukas-phaf You said "after the second failover of the coordinator there were only 2 nodes left".
Then it is expected that it will not allocate new shards or start previously remembered shards, or did I misunderstand something? When you add another node to the cluster again it should start those shards.

**Comment by lukas-phaf** [comment] 2017-01-04 07:18
@patriknw I thought the intention of the `akka.cluster.min-nr-of-members` flag was to only affect startup of the cluster, not during fault recovery. From the documentation:
```   
    # Minimum required number of members before the leader changes member status
    # of 'Joining' members to 'Up'. Typically used together with
    # 'Cluster.registerOnMemberUp' to defer some action, such as starting actors,
    # until the cluster has reached a certain size.
    min-nr-of-members = 1
```
Also, see [Clusster Sharding documentation](http://doc.akka.io/docs/akka/2.4/scala/cluster-sharding.html#Startup_after_minimum_number_of_members).

To me, it makes sense not to allocate shards on cluster startup, to avoid rebalancing as soon as other nodes join. But if there is a node failure in a running cluster, shouldn't the goal be to keep the cluster alive (especially when `rememberEntities` flag is true)?

I also note that the current behavior is different from 2.4.11. In 2.4.11, the shards we reallocated and entities restarted, even if the remaining number of nodes was lower then `akka.cluster.min-nr-of-members`.

**Comment by patriknw** [comment] 2017-01-04 07:54
The behavior is different from 2.4.11 because this feature was introduced in Cluster Sharding in 2.4.12.

The behavior is similar with the Cluster membership. If you use `min-nr-of-members=5` and have a cluster of 5 members, then remove 2 to have 3 remaining. If you at that point join 1 node it will not be moved to `Up` until you join 1 more node and reach a total of 5.

For example it might not be possible to run all entities on too few nodes because they will be overloaded and crash.

However, I understand your point and thinking if we could add another setting to support that mode. The problem is that the Coordinator can't see the difference of a first start or a start due to failover. I have to think about it. Perhaps you or someone else has brilliant idea of how to solve that?

**Comment by lukas-phaf** [comment] 2017-01-06 15:19
Thanks for the explanation. That explains why it 'worked' in 2.4.11, it was just ignoring my `min-nr-of-members` setting.

I'll have to take a long look at the code to even begin to understand how the sharding is implemented. When I have some time, I'll try to do that.

Without even looking at the code, a quick suggestion for Cluster membership would be: if any of the nodes in the cluster are `Up`, it can not be a first start.


Can you clarify one thing? You write 

> The problem is that the Coordinator can't see the difference of a first start or a start due to failover.

I don't understand why that is relevant here. I crashed one node, going down from 3 to 2. What I am looking for is that the shards on the crashed node are moved to the existing nodes. So the signal that it would react to is loosing a node, not the start of a node. What am I missing?

**Comment by patriknw** [comment] 2017-01-11 13:31
I'm referring to start of the sharding coordinator singleton instance, not start of a node.

**Comment by helena** [comment] 2019-06-25 14:26
Hi, we will close this due to it being a long time since any new activity has been added for it. If you have further questions, you can go to http://discuss.akka.io. Thanks

**Closed by helena** 2019-06-25 14:26 UTC
