### ISSUE TITLE
FAILED akka.remote.artery.RemoteSendConsistencyWithThreeLanesSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21624] opened 2016-10-04 22:47 UTC
https://jenkins.akka.io:8498/job/akka-nightly/3747/consoleFull

```
Coroner Thread Count starts at 104 in akka.remote.artery.RemoteSendConsistencyWithThreeLanesSpec
[info] Artery
[info] - must be able to identify a remote actor and ping it *** FAILED *** (5 seconds, 116 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:472)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:454)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:814)
[info]   at akka.remote.artery.AbstractRemoteSendConsistencySpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(RemoteSendConsistencySpec.scala:57)
[info]   at akka.remote.artery.AbstractRemoteSendConsistencySpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(RemoteSendConsistencySpec.scala:48)
```

**Comment by patriknw** [comment] 2016-10-11 06:42
https://jenkins.akka.io:8498/job/akka-nightly/3764/consoleFull

**Comment by jrudolph** [comment] 2016-11-22 12:51
Another one here: https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/542/consoleFull

**Comment by johanandren** [comment] 2016-11-28 08:04
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7850/consoleFull

**Comment by 2m** [comment] 2016-11-29 09:12
https://jenkins.akka.io:8498/job/akka-nightly/3914/consoleFull

**Comment by johanandren** [comment] 2016-11-29 11:47
Tangent PR caused by these failures: #21904

**Comment by 2m** [comment] 2016-12-01 08:48
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/551/consoleFull

**Comment by patriknw** [comment] 2016-12-01 09:23
This is test is too annoying. Could you mark it as ignored, @2m .
We have several things to improve around parallel lanes and it probably doesn't make sense to try to investigate this failure until we do those tasks.

**Comment by johanandren** [comment] 2017-01-30 22:24
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4591/consoleText

**Comment by jrudolph** [comment] 2017-02-07 12:07
https://jenkins.akka.io:8498/job/akka-nightly/4117/consoleFull

**Comment by patriknw** [comment] 2017-11-10 19:47
Pasting a failed debug log before I forget:

```
[info] RemoteSendConsistencyWithThreeLanesSpec:
Coroner Thread Count starts at 42 in akka.remote.artery.RemoteSendConsistencyWithThreeLanesSpec
[info] Artery
# associate akka://systemB@localhost:38708
[DEBUG] [11/04/2017 17:08:32.802] [pool-1-thread-1-ScalaTest-running-RemoteSendConsistencyWithThreeLanesSpec] [akka.remote.artery.Association(akka://ArteryMultiNodeSpec)] Starting outbound control stream to [akka://systemB@localhost:38708]
[DEBUG] [11/04/2017 17:08:32.844] [pool-1-thread-1-ScalaTest-running-RemoteSendConsistencyWithThreeLanesSpec] [akka.remote.artery.Association(akka://ArteryMultiNodeSpec)] Starting outbound message stream to [akka://systemB@localhost:38708] with [3] lanes
[DEBUG] [11/04/2017 17:08:32.895] [aeron-client-conductor] [akka.remote.artery.ArteryTransport(akka://systemB)] onAvailableImage from 127.0.0.1:59879 session 1609567808
[DEBUG] [11/04/2017 17:08:32.915] [systemB-akka.remote.default-remote-dispatcher-11] [Decoder(akka://systemB)] Decoded message but unable to record hits for compression as no remoteAddress known. No association yet?
[DEBUG] [11/04/2017 17:08:32.916] [systemB-akka.remote.default-remote-dispatcher-11] [InboundHandshake$$anon$2(akka://systemB)] # control stream HandshakeReq(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666,akka://systemB@localhost:38708)
# associate akka://ArteryMultiNodeSpec@localhost:45417
[DEBUG] [11/04/2017 17:08:32.916] [systemB-akka.remote.default-remote-dispatcher-11] [akka.remote.artery.Association(akka://systemB)] Starting outbound control stream to [akka://ArteryMultiNodeSpec@localhost:45417]
[DEBUG] [11/04/2017 17:08:32.950] [systemB-akka.remote.default-remote-dispatcher-11] [akka.remote.artery.ArteryTransport(akka://systemB)] onAvailableImage from 127.0.0.1:59879 session 1609567809
[DEBUG] [11/04/2017 17:08:32.951] [systemB-akka.remote.default-remote-dispatcher-6] [Decoder(akka://systemB)] Decoded message but unable to record hits for compression as no remoteAddress known. No association yet?
[DEBUG] [11/04/2017 17:08:32.951] [systemB-akka.remote.default-remote-dispatcher-6] [Decoder(akka://systemB)] Decoded message but unable to record hits for compression as no remoteAddress known. No association yet?
[DEBUG] [11/04/2017 17:08:32.951] [systemB-akka.remote.default-remote-dispatcher-6] [Decoder(akka://systemB)] Decoded message but unable to record hits for compression as no remoteAddress known. No association yet?
# association setUID akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666
[DEBUG] [11/04/2017 17:08:32.951] [systemB-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://systemB)] # ordinary stream HandshakeReq(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666,akka://systemB@localhost:38708)
[DEBUG] [11/04/2017 17:08:32.951] [systemB-akka.remote.default-remote-dispatcher-12] [InboundHandshake$$anon$2(akka://systemB)] # ordinary stream HandshakeReq(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666,akka://systemB@localhost:38708)
[DEBUG] [11/04/2017 17:08:32.952] [systemB-akka.actor.default-dispatcher-2] [akka.remote.artery.Association(akka://systemB)] # akka://systemB@localhost:38708#-3985324623073706976 completeHandshake akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666
[DEBUG] [11/04/2017 17:08:32.952] [systemB-akka.actor.default-dispatcher-4] [akka.remote.artery.Association(akka://systemB)] # akka://systemB@localhost:38708#-3985324623073706976 completeHandshake akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666
[DEBUG] [11/04/2017 17:08:32.952] [systemB-akka.remote.default-remote-dispatcher-10] [InboundHandshake$$anon$2(akka://systemB)] # ordinary stream HandshakeReq(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666,akka://systemB@localhost:38708)
[DEBUG] [11/04/2017 17:08:32.986] [systemB-akka.remote.default-remote-dispatcher-11] [akka.remote.artery.Association(akka://systemB)] Starting outbound message stream to [akka://ArteryMultiNodeSpec@localhost:45417] with [3] lanes
[DEBUG] [11/04/2017 17:08:32.986] [systemB-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://systemB)] # ordinary stream HandshakeReq(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666,akka://systemB@localhost:38708)
[DEBUG] [11/04/2017 17:08:32.986] [systemB-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://systemB)] # ordinary stream HandshakeReq(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666,akka://systemB@localhost:38708)
[DEBUG] [11/04/2017 17:08:32.986] [systemB-akka.remote.default-remote-dispatcher-10] [InboundHandshake$$anon$2(akka://systemB)] # ordinary stream HandshakeReq(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666,akka://systemB@localhost:38708)
[DEBUG] [11/04/2017 17:08:32.986] [systemB-akka.remote.default-remote-dispatcher-13] [InboundHandshake$$anon$2(akka://systemB)] # ordinary stream HandshakeReq(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666,akka://systemB@localhost:38708)
[DEBUG] [11/04/2017 17:08:33.024] [systemB-akka.remote.default-remote-dispatcher-10] [InboundHandshake$$anon$2(akka://systemB)] # ordinary stream HandshakeReq(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666,akka://systemB@localhost:38708)
[DEBUG] [11/04/2017 17:08:33.024] [systemB-akka.remote.default-remote-dispatcher-13] [InboundHandshake$$anon$2(akka://systemB)] # ordinary stream HandshakeReq(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666,akka://systemB@localhost:38708)
[DEBUG] [11/04/2017 17:08:33.024] [systemB-akka.remote.default-remote-dispatcher-12] [akka.serialization.Serialization(akka://systemB)] Using serializer [akka.remote.serialization.ArteryMessageSerializer] for message [akka.remote.artery.OutboundHandshake$HandshakeRsp]
[DEBUG] [11/04/2017 17:08:33.041] [aeron-client-conductor] [akka.remote.artery.ArteryTransport(akka://ArteryMultiNodeSpec)] onAvailableImage from 127.0.0.1:58764 session -1319413839
# association setUID akka://systemB@localhost:38708#-3985324623073706976
[DEBUG] [11/04/2017 17:08:33.061] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-15] [Decoder(akka://ArteryMultiNodeSpec)] Decoded message but unable to record hits for compression as no remoteAddress known. No association yet?
[DEBUG] [11/04/2017 17:08:33.061] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-15] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # control stream HandshakeRsp(akka://systemB@localhost:38708#-3985324623073706976)
# uniqueRemoteAddress akka://systemB@localhost:38708#-3985324623073706976 completed, pending null, state ReqInProgress, isAvailable true 
# uniqueRemoteAddress akka://systemB@localhost:38708#-3985324623073706976 completed, pending null, state ReqInProgress, isAvailable true 
[DEBUG] [11/04/2017 17:08:33.062] [ArteryMultiNodeSpec-akka.actor.default-dispatcher-6] [akka.remote.artery.Association(akka://ArteryMultiNodeSpec)] # akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666 completeHandshake akka://systemB@localhost:38708#-3985324623073706976
# uniqueRemoteAddress akka://systemB@localhost:38708#-3985324623073706976 completed, pending null, state ReqInProgress, isAvailable true 
# uniqueRemoteAddress akka://systemB@localhost:38708#-3985324623073706976 completed, pending null, state ReqInProgress, isAvailable true 

[DEBUG] [11/04/2017 17:08:33.062] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # control stream HandshakeRsp(akka://systemB@localhost:38708#-3985324623073706976)
[DEBUG] [11/04/2017 17:08:33.062] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # control stream HandshakeRsp(akka://systemB@localhost:38708#-3985324623073706976)
[DEBUG] [11/04/2017 17:08:33.062] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # control stream HandshakeRsp(akka://systemB@localhost:38708#-3985324623073706976)
[DEBUG] [11/04/2017 17:08:33.062] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # control stream HandshakeRsp(akka://systemB@localhost:38708#-3985324623073706976)
[DEBUG] [11/04/2017 17:08:33.062] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # control stream HandshakeRsp(akka://systemB@localhost:38708#-3985324623073706976)
[DEBUG] [11/04/2017 17:08:33.063] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # control stream HandshakeRsp(akka://systemB@localhost:38708#-3985324623073706976)
[DEBUG] [11/04/2017 17:08:33.063] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # control stream HandshakeRsp(akka://systemB@localhost:38708#-3985324623073706976)
[DEBUG] [11/04/2017 17:08:33.063] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # control stream HandshakeRsp(akka://systemB@localhost:38708#-3985324623073706976)
[DEBUG] [11/04/2017 17:08:33.063] [systemB-akka.remote.default-remote-dispatcher-12] [InboundManifestCompression(akka://systemB)] Initializing InboundActorRefCompression for originUid [-805088107760483666]
[DEBUG] [11/04/2017 17:08:33.063] [systemB-akka.remote.default-remote-dispatcher-12] [InboundManifestCompression(akka://systemB)] Initializing InboundManifestCompression for originUid [-805088107760483666]
[DEBUG] [11/04/2017 17:08:33.065] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # control stream HandshakeRsp(akka://systemB@localhost:38708#-3985324623073706976)
[DEBUG] [11/04/2017 17:08:33.065] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # control stream HandshakeReq(akka://systemB@localhost:38708#-3985324623073706976,akka://ArteryMultiNodeSpec@localhost:45417)
[DEBUG] [11/04/2017 17:08:33.066] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [akka.serialization.Serialization(akka://ArteryMultiNodeSpec)] Using serializer [akka.remote.serialization.ArteryMessageSerializer] for message [akka.remote.artery.OutboundHandshake$HandshakeRsp]
[DEBUG] [11/04/2017 17:08:33.066] [systemB-akka.remote.default-remote-dispatcher-11] [InboundHandshake$$anon$2(akka://systemB)] # control stream HandshakeRsp(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666)
[DEBUG] [11/04/2017 17:08:33.106] [aeron-client-conductor] [akka.remote.artery.ArteryTransport(akka://ArteryMultiNodeSpec)] onAvailableImage from 127.0.0.1:58764 session -1319413838
[DEBUG] [11/04/2017 17:08:33.106] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-9] [InboundManifestCompression(akka://ArteryMultiNodeSpec)] Initializing InboundManifestCompression for originUid [-3985324623073706976]
[DEBUG] [11/04/2017 17:08:33.106] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-15] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # ordinary stream HandshakeReq(akka://systemB@localhost:38708#-3985324623073706976,akka://ArteryMultiNodeSpec@localhost:45417)
[DEBUG] [11/04/2017 17:08:33.107] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-15] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # ordinary stream HandshakeReq(akka://systemB@localhost:38708#-3985324623073706976,akka://ArteryMultiNodeSpec@localhost:45417)
[DEBUG] [11/04/2017 17:08:33.107] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-15] [InboundHandshake$$anon$2(akka://ArteryMultiNodeSpec)] # ordinary stream HandshakeReq(akka://systemB@localhost:38708#-3985324623073706976,akka://ArteryMultiNodeSpec@localhost:45417)
[DEBUG] [11/04/2017 17:08:33.107] [systemB-akka.remote.default-remote-dispatcher-11] [InboundHandshake$$anon$2(akka://systemB)] # control stream HandshakeRsp(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666)
[DEBUG] [11/04/2017 17:08:33.107] [systemB-akka.remote.default-remote-dispatcher-11] [InboundHandshake$$anon$2(akka://systemB)] # control stream HandshakeRsp(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666)
[DEBUG] [11/04/2017 17:08:33.107] [systemB-akka.remote.default-remote-dispatcher-11] [InboundHandshake$$anon$2(akka://systemB)] # control stream HandshakeRsp(akka://ArteryMultiNodeSpec@localhost:45417#-805088107760483666)
[DEBUG] [11/04/2017 17:08:33.764] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-11] [akka.serialization.Serialization(akka://ArteryMultiNodeSpec)] Using serializer [akka.serialization.JavaSerializer] for message [akka.remote.RemoteWatcher$HeartbeatTick$]
[DEBUG] [11/04/2017 17:08:33.764] [ArteryMultiNodeSpec-akka.remote.default-remote-dispatcher-15] [akka.serialization.Serialization(akka://ArteryMultiNodeSpec)] Using serializer [akka.serialization.JavaSerializer] for message [akka.remote.RemoteWatcher$ReapUnreachableTick$]
[DEBUG] [11/04/2017 17:08:33.814] [systemB-akka.remote.default-remote-dispatcher-8] [akka.serialization.Serialization(akka://systemB)] Using serializer [akka.serialization.JavaSerializer] for message [akka.remote.RemoteWatcher$ReapUnreachableTick$]
[DEBUG] [11/04/2017 17:08:33.814] [systemB-akka.remote.default-remote-dispatcher-6] [akka.serialization.Serialization(akka://systemB)] Using serializer [akka.serialization.JavaSerializer] for message [akka.remote.RemoteWatcher$HeartbeatTick$]
[info] - must be able to identify a remote actor and ping it *** FAILED *** (5 seconds, 152 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
```

Handshake exchange is looking good, but in the end the first ActorSelection message is not delivered. Don't know where it's lost or stuck.

**Comment by patriknw** [comment] 2017-11-13 11:03
getting closer, in this failure https://jenkins.akka.io:8498/job/akka-multi-node-repeat/16032/consoleText
we can see that first `Identify` message is sent

```
# firstMessage to Some(Actor[akka://systemB@localhost:41721/]): ActorSelectionMessage(Identify(None),Vector(user, echo),false)
```

and that the reply `ActorIdentity` is sent ~ 7 seconds later in a later test step.

That smells like the message is stuck in the `SendQueue` but not visible and that a later message solves it.

**Comment by johanandren** [comment] 2020-01-02 12:44
https://jenkins.akka.io:8498/job/akka-artery-aeron-udp-remote-tests/233/

**Comment by johanandren** [comment] 2020-01-02 12:54
https://jenkins.akka.io:8498/job/akka-artery-aeron-udp-remote-tests/241/

**Comment by patriknw** [comment] 2020-08-17 15:14
Related or duplicate of https://github.com/akka/akka/issues/29465

**Comment by ennru** [comment] 2020-10-22 16:12
https://jenkins.akka.io:8498/job/akka-artery-aeron-udp-remote-tests/538/testReport/

`akka.remote.artery.ArteryTcpSendConsistencyWithThreeLanesSpec`
- Artery must be able to identify a remote actor and ping it
- Artery must be able to send messages concurrently preserving order
- Artery must be able to send messages with actorSelection concurrently preserving order

**Comment by seglo** [comment] 2020-10-29 19:13
https://jenkins.akka.io:8498/job/akka-release-2.5/282/consoleText

**Comment by ignasi35** [comment] 2021-07-21 09:55
In https://jenkins.akka.io:8498/job/akka-artery-aeron-udp-remote-tests/811/console there's exact same error (same subset of tests failing and tests succeeding) than reported in https://github.com/akka/akka/issues/21624#issuecomment-714601095:


`akka.remote.artery.ArteryTcpSendConsistencyWithThreeLanesSpec`
- Artery must be able to identify a remote actor and ping it
- Artery must be able to send messages concurrently preserving order
- Artery must be able to send messages with actorSelection concurrently preserving order

**Comment by raboof** [comment] 2022-02-21 11:03
Let's close this until we see it on GHA

**Closed by raboof** 2022-02-21 11:03 UTC
Labels: 1 - triaged, failed, t:remoting:artery

**Comment by raboof** [comment] 2022-02-21 14:44
also, possible duplicate of #29465
