### ISSUE TITLE
Document/demo creating fat jars

### ISSUE THREAD

**Issue by raboof** [akka/akka#24248] opened 2018-01-05 07:55 UTC
Because of the way typesafe-config `reference.conf` files are loaded, when creating a 'fat jar' of an Akka application the `reference.conf` files need to be merged.

As this is not completely trivial it would be nice if we could document this for the popular platforms (maven, gradle, sbt-assembly, sbt-native-packager) and perhaps even provide an example project.

**Comment by 2m** [comment] 2018-01-05 08:21
Here is the [section](https://doc.akka.io/docs/akka/current/additional/deploy.html?language=scala#native-packager) in the documentation that should be revised.

**Comment by roquie** [comment] 2018-01-05 09:17
Example `build.gradle` script to merge akka configs (this can be added to documentation):

```
buildscript {
    ext.kotlin_version = '1.2.10'

    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // For build Jar file: http://imperceptiblethoughts.com/shadow/
        classpath "com.github.jengelman.gradle.plugins:shadow:2.0.2"
    }
}

group 'com.roquie.akka-gradle-fatjar-example'
version '1.0.0'

apply plugin: 'kotlin'
apply plugin: 'com.github.johnrengelman.shadow'
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    compile "io.parallec:parallec-core:0.10.6" // dependency which contains akka dependency
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

shadowJar {
    append('resource.conf') // that's all!
}
```

If your using Kotlin DSL for this, following config won't work (I don't know how to make it to work it here):

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import com.github.jengelman.gradle.plugins.shadow.transformers.AppendingTransformer

group = "com.roquie.akka-gradle-fatjar-example"
version = "1.0.0"

buildscript {
    var kotlin_version: String by extra
    kotlin_version = "1.2.10"

    repositories {
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath(kotlinModule("gradle-plugin", kotlin_version))
        // For build Jar file: http://imperceptiblethoughts.com/shadow/
        classpath("com.github.jengelman.gradle.plugins:shadow:2.0.2")
    }
}

apply {
    plugin("kotlin")
    plugin("com.github.johnrengelman.shadow")
    plugin("java")
}

val kotlin_version: String by extra

repositories {
    mavenCentral()
}

dependencies {
    compile("io.parallec:parallec-core:0.10.6")
    compile(kotlinModule("stdlib-jdk8", kotlin_version))
}

tasks {
    "shadowJar"(ShadowJar::class) {
//        transform(AppendingTransformer::class.java) {
//            resource = "reference.conf"
//        }
        append("reference.conf")
    }
}
```

Maybe someone here know how true write config for Kotlin DSL?

**Comment by roquie** [comment] 2018-01-05 09:35
Please, see this pull request https://github.com/johanandren/akka/pull/4

**Comment by roquie** [comment] 2018-01-05 10:49
I re-create project from zero and again caught the same error with loading configuration (`akka.version`), but already using vanilla-Gradle. Wtf!!? Old project called `akka-gradle-example` it's work with config with config above. Sources codes is identical. Fucking random...

**Comment by ktoso** [comment] 2018-01-05 10:50
Thanks for offering help -- please do refrain from using explicit language though, thanks in advance.

What error exactly do you mean?

**Comment by roquie** [comment] 2018-01-05 10:56
> What error exactly do you mean?
Typical error: `Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'`, while `reference.conf` configs does not merged into one.

**Comment by raboof** [comment] 2018-02-08 11:55
Turns out we already have some documentation under https://doc.akka.io/docs/akka/2.5/general/configuration.html#when-using-jarjar-onejar-assembly-or-any-jar-bundler , we should move that

**Comment by purpletech** [comment] 2018-05-31 20:37
This works for me in my build.gradle(4.7) :
plugins {
  id 'java' 
  id 'com.github.johnrengelman.shadow' version '2.0.2'
}

shadowJar {
  mergeServiceFiles('reference.conf')
}

**Comment by marcelo-s** [comment] 2019-06-13 19:02
Tried many different approaches, none work. There are multiple solutions but using scala and sbt or maven. I prefer to use gradle and after hours of trying I managed to find a solution. This is my configuration for creating an akka applications using gradle:

```
import com.github.jengelman.gradle.plugins.shadow.transformers.AppendingTransformer

plugins {
    id 'java'
    id "com.github.johnrengelman.shadow" version "5.0.0"

}

group 'com.test.cluster'
version '1.0'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}


jar {
    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
    manifest {
        attributes "Main-Class": "main.Main"
    }
}

shadowJar {
    transform(AppendingTransformer) {
        resource = 'reference.conf'
    }
    with jar
}
```
Don't forget to change your initial main class in the "manifest" "Main-Class" of the Jar task.

**Closed** 2019-06-17 11:05 UTC
Labels: help wanted, t:docs

**Comment by raboof** [comment] 2019-06-19 10:08
we don't have an example for sbt-assembly yet, filed #24248

**Comment by ldeluigi** [comment] 2020-06-19 13:03
Hope to help someone with this (it's the Gradle/Kotlin DSL version):
```kotlin
tasks.withType<ShadowJar> {
    val newTransformer = AppendingTransformer()
    newTransformer.resource = "reference.conf"
    transformers.add(newTransformer)
}
```

**Comment by raboof** [comment] 2020-06-19 13:12
@ldeluigi I saw you recommend this on gitter, could you see if https://github.com/akka/akka/pull/29274 makes sense to you?
