### ISSUE TITLE
Add ; charset=UTF-8 to application/json response headers

### ISSUE THREAD

**Issue by raam86** [akka/akka#19260] opened 2015-12-22 16:21 UTC
Although the default encoding is utf-8 it is not being added to the response header rendering: 
  "×œ× ×™×•×ª×¨ ×ž-10"
instead of 
"לא יותר מ-10"

It is a minor issue since it only impacts application/json get requests in the browser (as in put the URI in the url field and hit enter)

**Comment by ktoso** [comment] 2015-12-22 16:26
Thanks for reporting, it seems like a bug, it definitely has the charset defined, it must be something off during rendering...

Could you try out defining and using the following instead of the default one:

```
val `application/json(UTF-8)` = MediaTypes.`application/json` withCharsetRange HttpCharsets.`UTF-8`
```

and ping this ticket if this made a difference?

Thanks in advance.

**Comment by raam86** [comment] 2015-12-22 16:38
Hi I've tried the following: 
```
ContentType(MediaTypes.`application/json`,HttpCharsets.`UTF-8`) 
```
with no difference 

Also you offer throws:
```
Error:(124, 65) value withCharsetRange is not a member of akka.http.scaladsl.model.MediaType
  val `application/json(UTF-8)` = MediaTypes.`application/json` withCharsetRange HttpCharsets.`UTF-8`
```
and using: 
```
 MediaTypes.`application/json`.withCharset(HttpCharsets.`UTF-8`)
```
Won't add the header either.

Some debugging shows that `application/json` doesn't have a `definedCharset` (in file akka.http.scaladsl.model.ContentType, line 69) and the constructor won't add it 

I
                                                                ^

**Comment by ktoso** [comment] 2015-12-22 16:40
Thanks a lot for checking, will have to dig into that.
When I skimmed it it seemed to me it has the charset defined:

```
val `application/json`                                                          = awfc("json", HttpCharsets.`UTF-8`, "json")
```

Sanity check, you're on `2.0` right?

**Comment by raam86** [comment] 2015-12-22 16:54
`val akkaStreamV = "2.0-M1"`

 in build.sbt

**Comment by ktoso** [comment] 2015-12-22 16:55
That's not supported. Please update to `2.0` :-)

**Comment by raam86** [comment] 2015-12-22 16:55
Doing it as I write. Will update.

**Comment by ktoso** [comment] 2015-12-22 16:56
I say that because we did a major rework of content types recently, I think the new version may be bug-free in this case :)
Thanks for reporting and trying to update, let us know how it went (if it's fixed on 2.0)

**Comment by raam86** [comment] 2015-12-22 17:15
Updated to v 2.0 and still same result. 

btw Source.fromPublisher was a little confusing. Where can I ask why it couldn't be added as another apply?

**Comment by ktoso** [comment] 2015-12-22 17:28
Thanks for reporting, I'll have a look then. We're planning to ship a 2.0.1 so maybe this fix could make it in there.

**Comment by raam86** [comment] 2015-12-22 17:44
Great. I would be happy to help with if you can point me the right direction

**Comment by ktoso** [comment] 2015-12-22 18:30
Putting a test that would fail into ResponseRendererSpec as a PR would be awesome.
The code is on the `release-2.3-dev` branch :)

**Comment by guersam** [comment] 2015-12-23 04:30
Actually it's a browser bug, refer to #17409:

> The content-type of application/json is fixed to UTF-8 and doesn't allow a charset parameter by its spec.
>
> http://tools.ietf.org/html/rfc7158#section-11
http://stackoverflow.com/questions/13096259/can-charset-parameter-be-used-with-application-json-content-type-in-http-1-1#13098683

**Comment by ktoso** [comment] 2015-12-23 09:05
Hah, completely forgot about that, thanks @guersam!

**Comment by raam86** [comment] 2015-12-23 09:34
This bug is reproducible in all current browser versions. I agree the spec says otherwise but I can't even force adding the charset clause.

Should I still work on failing a test?

**Comment by ktoso** [comment] 2015-12-23 09:35
So not rendering UTF-8 to application/json is one thing, but why it rendered wrong is another question... 
When you use curl / httpie it renders correctly, or is it only in browsers?
Reproducer would be great in any case, thanks @raam86 !

**Comment by raam86** [comment] 2015-12-23 09:48
Curl works fine. It only affects browsers.

**Comment by raam86** [comment] 2015-12-23 09:58
@ktoso  I couldn't find ResponseRenderSpec... Should I put it here:
https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
?

**Comment by ktoso** [comment] 2015-12-23 10:03
Here https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala

-- 
Cheers,
Konrad 'ktoso’ Malawski
Akka @ Typesafe

On 23 December 2015 at 10:58:26, Raam Rosh-Hai (notifications@github.com) wrote:

@ktoso I couldn't find ResponseRenderSpec... Should I put it here:
https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
?

**Comment by jrudolph** [comment] 2015-12-23 10:35
Here's the bug report for chromium: https://code.google.com/p/chromium/issues/detail?id=438464
and for firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1166558

**Comment by ktoso** [comment] 2015-12-23 10:39
Open for 11 months and not fixed in Chrome... not very reassuring :(

**Comment by raam86** [comment] 2015-12-23 11:24
Here's the pull request https://github.com/akka/akka/pull/19272

I hope it is up to par. Please let me know if it needs fixing.

**Comment by kubukoz** [comment] 2016-01-05 19:06
@ktoso closing this one? :)

**Comment by ktoso** [comment] 2016-01-05 19:21
Yeah, I think we reached a conclusion here, for the time being.

**Closed by ktoso** 2016-01-05 19:21 UTC
Labels: 0 - new, bug, t:http
