### ISSUE TITLE
Sharding `BeginHandoff` sent to region on crashed node, rebalancing is stuck

### ISSUE THREAD

**Issue by DennisVDB** [akka/akka#29034] opened 2020-05-05 20:24 UTC
The shard rebalancing seems to get stuck when waiting for a `BeginHandOffAck` from a member that doesn't exist anymore. In our case this happens everytime the oldest member crashes.

We run a three node cluster with a split-brain resolver. For the explanation I'll call them `A`, `B`, and `C`. `A` is the oldest node in the cluster. `B` is the second oldest node.

The event timeline that leads to the issue:
(1) The oldest member `A` crashes (OOM)
(2) `B` and `C` detect the node as unreachable and decide to down it. At about the same time `A` is restarted by k8s.
(3) Simultaneously (in the same second) the new instance of `A` is promoted to `Up` and the shard-coordinator on `B` is now active (`ShardCoordinator was moved to the active state`)
(4) Rebalancing is triggered. The new instance of `A`, `B`, and `C` respond with a `BeginHandoffAck`.
(5) A minute later I see `Rebalance shard [-10] didn't complete within [1.000 min].`.
(6) Now for ever it will retry rebalancing.

My hunch on the issue:

At step (4) I'm seeing in `B`'s shard-coordinator's state (which has been logged) at least one shard region with an `ActorRef` on the _old_ instance of `A`. That shard region doesn't exist since `A` just restarted.

I observe three `BeginHandoffAck`s logs which should be enough since we have three nodes in the cluster. However, I'm not seeing the log saying all the shard regions have acked https://github.com/akka/akka/blob/0e4d41ad33dbeb00b598cb75b4d29899371bdc8c/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala#L485 This makes sense as it's still waiting for the ack from a non-existent shard-region.

What I guess is happening is linked to: https://github.com/akka/akka/blob/0e4d41ad33dbeb00b598cb75b4d29899371bdc8c/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala#L841 
When the coordinator is initialized, the (now dead) shard region living on the old instance of `A` will not be pruned from the state. The `Address` is compared and not the `UniqueAddress`. As a result, as the new instance of `A` is already part of the membership, the (now dead) shard region on the _old_ instance of `A` will stay in the coordinator's state.

However, what I don't understand is that during initialization the coordinator will `context.watch` the region. So it should eventually observe the termination. Here even instantly. Could it be that a `RebalanceTick` message is handled _before_ the `Terminated` message? It should handle the `Terminated` at some point after `RebalanceDone(false) // failed`. The coordinator tries again and to receive a reply to `HostShard` from the old instance of `A` but it gets delivered to dead-letters.

Member `C` requested a shard home of a shard that was located on the old instance of `A`. `B`, the coordinator told `C` it was located on the old instance of `A`. As a result of getting the shard home, `C` starts watching the old instance of `A`.
https://github.com/akka/akka/blob/bef03f85858782ae129657c322d267d0af0608c6/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala#L725
In the same instant `C` starts watching it receives a `Terminated`. This is the only terminated event I see. The act of getting the shard home and then `C` observing the shard region as terminated happens every time after the rebalance restarts.
https://github.com/akka/akka/blob/0e4d41ad33dbeb00b598cb75b4d29899371bdc8c/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala#L773

**Comment by patriknw** [comment] 2020-05-15 14:20
Sorry for the silence here, I have been busy with other things. Will look into this next week.

**Comment by chbatey** [comment] 2020-05-18 14:22
Hi @DennisVDB thank you for the detailed report! Would you be able to share the logs?

**Comment by patriknw** [comment] 2020-05-18 17:21
Which version of Akka is this?

Most critical here is:

> (6) Now for ever it will retry rebalancing

That is strange since the RebalanceWorker is started with a Set of region ActorRef and the question is how such ActorRef can remain in the State if it has terminated. `Terminated` should be triggered also if watching a ref on an old incarnation of node with same host:port.

Logs at DEBUG level would indeed be useful for debugging this scenario.

We could also try to optimize the rebalance for this case, but that is a secondary concern. That can be done by letting RebalanceWorker watch all regions, or better let the parent ShardCoordinator notify the RebalanceWorker when a region is terminated (since it already watches all regions).

**Comment by DennisVDB** [comment] 2020-05-18 17:24
Thanks for having a look! 

Here you can find the logs: https://gist.github.com/DennisVDB/bcf314647b66114805ea5eb83fe2ab49

It puzzles me why `Terminated` is not received by the coordinator but the regions do.

**Comment by patriknw** [comment] 2020-05-19 06:54
Thanks. I suspect that it is because we have by default disabled watch "outside" the cluster, but then I would expect a log entry "Dropped remote Watch... disabled for" or similar. Not sure which logger name it is. I think it is starting with "akka.actor.LocalActorRefProvider", but could be RemoteActorRefProvider or ClusterActorRefProvider if I'm reading that log initialization wrong.

Can you see if you find such log entry.
https://github.com/akka/akka/blob/8244f41d2e4e30e0a2f6cc71222d332e5017dbef/akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala#L352

If my suspicion is right this is a bug that we have to fix.

**Comment by DennisVDB** [comment] 2020-05-19 07:41
The message is nowhere to be found but probably because we only the debug logs enabled on `akka.cluster.sharding`.

`log.debug("{}: Region [{}] with shards [{}] terminated", typeName, ref, shards.mkString(", "))`in `ShardRegion#receiveTerminated` gets triggered so watch outside the cluster should work.

```
May 5th 2020, 15:14:34.860 +00:00 | DEBUG | transaction: Region [Actor[akka://service@10.2.15.252:25520/system/sharding/transaction#-2071219375]] with shards [34, -10, -32, -49, 8, -25, -21, -36, -46, 40, 22, 26, 37, -16, 46, 5, -35, -47, 21, 43, 6, 17, 31, -23, 20, 2, -9, -45, 29, 41, 28, -11, -6] terminated | akka.cluster.sharding.ShardRegion | akka://service@10.2.21.101:25520
-- | -- | -- | -- | --

  | May 5th 2020, 15:14:35.216 +00:00 | DEBUG | transaction: Region [Actor[akka://service@10.2.15.252:25520/system/sharding/transaction#-2071219375]] with shards [34, -10, -32, -49, 8, -25, -21, -36, -46, 40, 22, 26, 37, -16, 46, 5, -35, -47, 21, 43, 6, 17, 31, -23, 20, 2, -9, -45, 29, 41, 28, -11, -6] terminated | akka.cluster.sharding.ShardRegion | akka://service@10.2.37.26:25520
```

**Comment by patriknw** [comment] 2020-05-19 08:36
Strange, by default that is on warning level.

Note that it can be race conditions when starting up so this may not happen every time.

In your original log file there is no trace of "ShardRegion terminated".

I will try to reproduce the problem, and I have some ideas of how we should fix it.

**Comment by DennisVDB** [comment] 2020-05-19 11:16
> In your original log file there is no trace of "ShardRegion terminated".
Yes, I forgot to add these. Let me know if you need to updated logs.

**Comment by patriknw** [comment] 2020-05-19 11:59
I have been able to reproduce my hypothesis and have prepared a fix in PR https://github.com/akka/akka/pull/29092

Can you reproduce the problem, or was it one time only?
If you can reproduce it would be great if you can try the fix before we release it, since I can't be 100% sure you have seen the same problem.
Can you build Akka yourself from the branch of that PR?

**Comment by patriknw** [comment] 2020-05-19 12:04
Created issue https://github.com/akka/akka/issues/29093 for the optimization opportunity.

**Comment by DennisVDB** [comment] 2020-05-19 16:15
> Can you reproduce the problem, or was it one time only?

It happened every time the oldest node crashes so I can reproduce it. I just need to find the time to do it.

**Comment by patriknw** [comment] 2020-05-27 08:07
@DennisVDB  Merged to master. Pls re-open if you find something in your testing.

**Closed by patriknw** 2020-05-27 08:07 UTC
Labels: 3 - in progress, bug, t:cluster-sharding
