### ISSUE TITLE
Endpoint actor state is corrupted: Highest SEQ so far was -1 but cumulative ACK is 2

### ISSUE THREAD

**Issue by 2m** [akka/akka#22156] opened 2017-01-18 10:35 UTC
When node A is restarted and comes back with the new UID to node B, node B has endpoint actor state corrupted:
```
akka.actor.Actor$class.aroundReceive(Actor.scala:496)
Error encountered while processing system message acknowledgement buffer: [14
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}
] ack: ACK[378933, {}]
akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:304)
akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:203)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
akka.actor.ActorCell.invoke(ActorCell.scala:495)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
akka.dispatch.Mailbox.run(Mailbox.scala:224)
akka.dispatch.Mailbox.exec(Mailbox.scala:234)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
by: java.lang.IllegalArgumentException: Highest SEQ so far was 14 but cumulative ACK is 378933
akka.remote.AckedSendBuffer.acknowledge(AckedDelivery.scala:103)
akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:300)
akka.actor.Actor$class.aroundReceive(Actor.scala:496)
akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:203)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
akka.actor.ActorCell.invoke(ActorCell.scala:495)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
akka.dispatch.Mailbox.run(Mailbox.scala:224)
akka.dispatch.Mailbox.exec(Mailbox.scala:234)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:304)
akka.remote.AckedSendBuffer.acknowledge(AckedDelivery.scala:103)
akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:203)
akka.dispatch.Mailbox.exec(Mailbox.scala:234)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Also there is evidence that `TooLongIdle` cleanup can affect communications to the node with the same address but different UID:
```
10.30.10.29:9196|2017-01-16 13:07:38,867 ERROR [][][][][][akka.actor.default-dispatcher-23][] a.r.Remoting - Association to [akka.tcp://sys@nodeA] with UID [-1778088587] irrecoverably failed. Quarantining address.
Remote system has been silent for too long. (more than 120.0 hours)

10.30.10.29:9196|2017-01-16 13:07:38,910 ERROR [][][][][][akka.actor.default-dispatcher-71][] a.r.Remoting - Association to [akka.tcp://sys@nodeA] with UID [1685131585] irrecoverably failed. Quarantining address.
Error encountered while processing system message acknowledgement buffer: [-1 {}] ack: ACK[1187893, {}]
```

**Comment by ktoso** [comment] 2017-01-23 12:25
Marked as bug

**Comment by jrudolph** [comment] 2017-09-06 15:51
Reproducer: https://github.com/typesafehub/akka-commercial-addons/commit/44f4c1847fad30be6f9079bf489286bd952f5933

**Comment by patriknw** [comment] 2017-09-08 11:17
I also see it with that commit, debugging...

**Comment by patriknw** [comment] 2017-09-08 12:53
I have some very interesting logs. It seems like the problem is around stopping and then creating new ReliableDeliverySupervisor. Thereby the resendBuffer is reset, and then an Ack with unexpected sequence number arrives.

A workaround might be to use:
```
akka.remote.use-passive-connections = off
```

**Comment by patriknw** [comment] 2017-09-11 06:02
The scenario when this happens looks like this:

- create endpoint via inbound refuseUid None, uid 575246831
- send Watch seq=0
- receive ack seq=0
- downing, Shutting down myself
- Quarantine, stop endpoint
- create endpoint via send refuseUid Some(575246831), unconfirmed uid
  note that this will overwrite the Quarantined in endpointRegistry
- when GotUid The remote system has quarantined this system, stop endpoint
- create endpoint via inbound, refuseUid None, uid 575246831, i.e. uid is confirmed since from inbound
- receive ack seq=0
  IllegalArgumentException: Highest SEQ so far was -1 but cumulative ACK is 0

The problem is that the refuseUid is lost when the Quarantined marker is replaced by new endpoint to same address. I will rewrite how the refuseUid is kept. It's not a good idea to keep it in those policy markers.

**Comment by patriknw** [comment] 2017-09-25 14:03
This was originally reported to happen after a restart, but we couldn't reproduce that scenario. We have improved how this state is managed and had a good reproducer as described above.

**Closed** 2017-09-25 15:58 UTC
Labels: bug, t:remoting
