### ISSUE TITLE
ActorMaterializerSpec."properly shut down actors associated with it" fails

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#17849] opened 2015-06-26 11:40 UTC
~~~scala
"properly shut down actors associated with it" in {
      val m = ActorMaterializer.create(system)

      val f = Source.lazyEmpty[Int].runFold(0)(_ + _)(m)

      m.shutdown()

      an[AbruptTerminationException] should be thrownBy Await.result(f, 3.seconds)
    }
~~~

This test case fails due to a race between the construction of the graph and the termination of the materializer. Opening this as discussed in #17831

**Comment by viktorklang** [comment] 2015-06-26 11:42
Ping @drewhk

**Comment by drewhk** [comment] 2015-06-26 11:54
Actually the above test fails because of a race between the ExposedPublisher message sent to the fold actor, and the call to postStop() on that actor. If postStop is called before the actor gets its exposed Publisher instance, it cannot properly close the downstream.

**Comment by drewhk** [comment] 2015-06-26 11:55
The best reproducer is this:
    val f = Source.lazyEmpty[Int].map(identity).runWith(Sink.ignore)

**Comment by drewhk** [comment] 2015-07-27 14:49
Ok, idea is to have a graceful shutdown:
 - we don't kill immediately the supervisor actor, but instead send a special message to the children
 - children report back after shutdown
 - supervisor stops itself after all children reported, or some timeout expired

**Comment by viktorklang** [comment] 2015-07-27 14:54
Sounds like a plan!

**Comment by drewhk** [comment] 2015-10-01 11:44
Related: I disable for now the test (it is also racy, and depends on the correct solution discussed above)

    akka.http.scaladsl.ClientServerSpec "log materialization errors in `bindAndHandle`" which "are triggered in `mapMaterialized`"

when this ticket is fixed, please reenable it.

**Comment by rkuhn** [comment] 2015-12-20 20:50
@drewhk I believe this is fixed now—the test doesn’t fail for me at least.

**Comment by rkuhn** [comment] 2015-12-20 21:36
test reenabled

**Closed** 2015-12-20 21:35 UTC
Labels: bug, failed, t:stream
