### ISSUE TITLE
Streams's `withAttributes` doesn't override default attributes

### ISSUE THREAD

**Issue by 2beaucoup** [akka/akka#23649] opened 2017-09-18 16:07 UTC
I'm trying to set the supervision strategy via
```scala
.withAttributes(ActorAttributes.supervisionStrategy(Supervision.resumingDecider))
```
While trying to figure out while it always uses `Supervision.stoppingDecider` I noticed that [here](https://github.com/akka/akka/blob/v2.4.20/akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala#L190) the graph interpreter seems to do the `and` of the attributes in the wrong order. As the custom (`originalAttributes`) are _appended_ they would be ignored if there was an attribute of the same class in the defaults (`inheritedAttributes`).

**Comment by johanandren** [comment] 2017-09-19 06:00
I think this is a duplicate of #22523

**Comment by ktoso** [comment] 2017-11-13 12:44
Closing as duplicate, attributes are in need of a deep re-thinking and fixing. We'll solve it in the big ticket, and this one is linked to the big one.

**Closed by ktoso** 2017-11-13 12:44 UTC
