### ISSUE TITLE
FAILED: ClusterStressSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16785] opened 2015-02-06 11:21 UTC
https://jenkins.akka.io:8498/job/akka-multi-node/978/consoleFull

[JVM-13] - must join nodes one-by-one to large cluster *** FAILED *** (43 seconds, 717 milliseconds)
[JVM-13]   12 was not equal to 13 (MultiNodeClusterSpec.scala:291)
[JVM-13]   org.scalatest.exceptions.TestFailedException:
[JVM-13]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-13]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6141)
[JVM-13]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6175)
[JVM-13]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(MultiNodeClusterSpec.scala:291)
[JVM-13]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$2.apply(MultiNodeClusterSpec.scala:291)
[JVM-13]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$2.apply(MultiNodeClusterSpec.scala:291)
[JVM-13]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:269)
[JVM-13]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:280)
[JVM-13]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:738)
[JVM-13]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply$mcV$sp(MultiNodeClusterSpec.scala:291)
[JVM-13]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:288)
[JVM-13]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:288)

**Comment by drewhk** [comment] 2015-02-06 11:22
This happened this morning and therefore has very likely nothing to do with upgrades of the servers.

**Comment by patriknw** [comment] 2015-02-06 12:06
I took a look at the log. During the joining phase and one node (akka.tcp://StressSpec@a6.moxie:48124) is marked as unreachable, and removed by the auto-down. It can be explained by some very long gc pauses. Let's leave the ticket open for a while to make sure it's a flake and not a regression.

    [JVM-6] 32.728: [GC [PSYoungGen: 68224K->5035K(142080K)] 68232K->5051K(316864K), 1.8709530 secs] [Times: user=18.91 sys=0.50, real=1.87 secs] 
    
    [JVM-3] 21.474: [GC [PSYoungGen: 68192K->5563K(142080K)] 68200K->5579K(316864K), 1.7186390 secs] [Times: user=17.99 sys=0.58, real=1.72 secs]
    
    [JVM-8] 45.651: [GC [PSYoungGen: 68224K->4827K(142080K)] 68232K->4843K(316864K), 2.3942980 secs] [Times: user=22.09 sys=0.59, real=2.39 secs] 
    
    [JVM-2] 2.055: [GC [PSYoungGen: 65600K->2576K(76480K)] 65600K->2584K(251264K), 4.6852130 secs] [Times: user=47.25 sys=0.51, real=4.69 secs] 

[JVM-7] 41.006: [GC [PSYoungGen: 68224K->4315K(76480K)] 68232K->4331K(251264K), 4.8488080 secs] [Times: user=47.73 sys=0.73, real=4.85 secs]

**Comment by patriknw** [comment] 2015-02-06 12:42
I think it must be a regression, since several other tests fail in a similar fashion

**Comment by patriknw** [comment] 2015-02-06 14:35
I'm pretty sure this has something to do with upgrades of the build servers. The jvm shows some kind of warning when starting up:

    libnuma: Warning: /sys not mounted or invalid. Assuming one node: No such file or directory
    mbind: Invalid argument
    mbind: Invalid argument

I have verified that we have long gc pauses also on release-2.3 branch before merging the cluster changes.

**Closed** 2015-02-16 09:12 UTC
Labels: failed, t:cluster
