### ISSUE TITLE
Cancelled sinks are blocking other consumers of BroadcastHub

### ISSUE THREAD

**Issue by sumnulu** [akka/akka#23205] opened 2017-06-19 19:34 UTC
The following test case is reproducing the problem. After the cancelled sink subscribed, BroadcastHub does not pulling from the up stream. 
 
```scala
   "handle cancelled Sink with a buffer size of one" in assertAllStagesStopped {
      val (firstElem, source) = Source.maybe[Int].concat(Source(2 to 10)).toMat(BroadcastHub.sink(1))(Keep.both).run()

      val f1 = source.runWith(Sink.cancelled)
      val f2 = source.runWith(Sink.seq)

      // Ensure subscription of Sinks. This is racy but there is no event we can hook into here.
      Thread.sleep(100)
      firstElem.success(Some(1))
      f2.futureValue should ===(1 to 10)
    }
````

log output
```
--- Stream actors debug dump ---
Stream actors alive: List(Actor[akka://HubSpec/user/StreamSupervisor-0/flow-53-0-unnamed#-1679909879], Actor[akka://HubSpec/user/StreamSupervisor-0/flow-55-0-seqSink#-1807617136])
activeShells (actor: Actor[akka://HubSpec/user/StreamSupervisor-0/flow-55-0-seqSink#-1807617136]):
  GraphInterpreterShell(
    logics: [
      SeqStage attrs: [Name(seqSink), Dispatcher(akka.test.stream-dispatcher), InputBuffer(4,16), SupervisionStrategy(<function1>)],
      akka.stream.scaladsl.BroadcastHub$$anon$3@41354a9c attrs: [Dispatcher(akka.test.stream-dispatcher), InputBuffer(4,16), SupervisionStrategy(<function1>)]
    ],
    connections: [
      Connection(0, 8, Empty, akka.stream.impl.SeqStage$$anon$4@437dcde, akka.stream.scaladsl.BroadcastHub$$anon$3$$anon$5@26d74ff5)
    ]
  )

dot format graph for deadlock analysis:
================================================================
digraph waits {
  N0 [label="SeqStage"];
  N1 [label="akka.stream.scaladsl.BroadcastHub$$anon$3@41354a9c"];
  N0 -> N1 [label=shouldPush, color=red];
}
================================================================
// (1, 3, 3)() (running=2, shutdown=1,1)
newShells:

activeShells (actor: Actor[akka://HubSpec/user/StreamSupervisor-0/flow-53-0-unnamed#-1679909879]):
  GraphInterpreterShell(
    logics: [
      akka.stream.scaladsl.BroadcastHub@64bec035 attrs: [Dispatcher(akka.test.stream-dispatcher), InputBuffer(4,16), SupervisionStrategy(<function1>)],
      StatefulMapConcat attrs: [Name(statefulMapConcat), Name(iterableSource), Name(iterableSource), Dispatcher(akka.test.stream-dispatcher), InputBuffer(4,16), SupervisionStrategy(<function1>)],
      SingleSource attrs: [Name(singleSource), Name(iterableSource), Name(iterableSource), Dispatcher(akka.test.stream-dispatcher), InputBuffer(4,16), SupervisionStrategy(<function1>)],
      Concat(2) attrs: [Name(concat), Dispatcher(akka.test.stream-dispatcher), InputBuffer(4,16), SupervisionStrategy(<function1>)],
      Detacher attrs: [Name(detacher), Dispatcher(akka.test.stream-dispatcher), InputBuffer(4,16), SupervisionStrategy(<function1>)],
      Detacher attrs: [Name(detacher), Dispatcher(akka.test.stream-dispatcher), InputBuffer(4,16), SupervisionStrategy(<function1>)],
      BatchingActorInputBoundary(forPort=akka.stream.impl.fusing.GraphStages$Detacher$$anon$2@5a90e1af, fill=0/16, completed=true, canceled=false) attrs: []
    ],
    connections: [
      Connection(0, 1, Empty, akka.stream.scaladsl.BroadcastHub$BroadcastSinkLogic@6a7922d2, akka.stream.scaladsl.Concat$$anon$8@6e46ab45),
      Connection(1, 49, Empty, akka.stream.impl.fusing.StatefulMapConcat$$anon$28@2b4428e9, akka.stream.impl.fusing.GraphStages$SingleSource$$anon$7@39e9fadc),
      Connection(2, 49, Empty, akka.stream.scaladsl.Concat$$anon$8$$anon$19@1a252081, akka.stream.impl.fusing.GraphStages$Detacher$$anon$2@5a90e1af),
      Connection(3, 1, Empty, akka.stream.scaladsl.Concat$$anon$8$$anon$19@4162ac03, akka.stream.impl.fusing.GraphStages$Detacher$$anon$2@4b6bd7a6),
      Connection(4, 56, Empty, akka.stream.impl.fusing.GraphStages$Detacher$$anon$2@5a90e1af, BatchingActorInputBoundary(forPort=akka.stream.impl.fusing.GraphStages$Detacher$$anon$2@5a90e1af, fill=0/16, completed=true, canceled=false)),
      Connection(5, 1, 2, akka.stream.impl.fusing.GraphStages$Detacher$$anon$2@4b6bd7a6, akka.stream.impl.fusing.StatefulMapConcat$$anon$28@2b4428e9)
    ]
  )

dot format graph for deadlock analysis:
================================================================
digraph waits {
  N0 [label="akka.stream.scaladsl.BroadcastHub@64bec035"];
  N1 [label="StatefulMapConcat"];
  N2 [label="SingleSource"];
  N3 [label="Concat(2)"];
  N4 [label="Detacher"];
  N5 [label="Detacher"];
  N6 [label="BatchingActorInputBoundary(forPort=akka.stream.impl.fusing.GraphStages$Detacher$$anon$2@5a90e1af, fill=0/16, completed=true, canceled=false)"];
  N0 -> N3 [label=shouldPull, color=blue];
  N1 -> N2
  N3 -> N4
  N3 -> N5 [label=shouldPull, color=blue];
  N4 -> N6
  N5 -> N1 [label=shouldPull, color=blue];
}
================================================================
// (8, 14, 14)() (running=4, shutdown=67108865,1,0,2,0,2,0)
newShells:

[info] - must handle cancelled Sink with a buffer size of one *** FAILED *** (7 seconds, 259 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 50 times, sleeping 100 milliseconds between each query. (HubSpec.scala:288)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.stream.scaladsl.HubSpec$$anonfun$2$$anonfun$apply$mcV$sp$24$$anonfun$apply$22.apply(HubSpec.scala:288)
[info]   at akka.stream.scaladsl.HubSpec$$anonfun$2$$anonfun$apply$mcV$sp$24$$anonfun$apply$22.apply(HubSpec.scala:279)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
[info]   at akka.stream.scaladsl.HubSpec$$anonfun$2$$anonfun$apply$mcV$sp$24.apply(HubSpec.scala:279)
[info]   at akka.stream.scaladsl.HubSpec$$anonfun$2$$anonfun$apply$mcV$sp$24.apply(HubSpec.scala:279)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:26)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:59)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:59)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:59)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by sumnulu** [comment] 2017-07-06 15:31
Hi, 
I think this is some what important bug. **At high load** BroadcastHub will always fail, if the size of subscribed sinks that are not called pull exceeds the buffer size of Hub.

Or am I missing something?

**Comment by patriknw** [comment] 2017-07-07 15:19
Thanks for reporting. Sounds serious. I haven't verified. Marking as bug for investigation.

**Comment by johanandren** [comment] 2017-07-17 15:35
I can confirm that the bug is there. Haven't been able to fix but this test based on @sumnulu's reproducer consistently reproduces the bug whatever the buffer size is:

```
    "handle a directly cancelled Sink" in assertAllStagesStopped {

      val (sourceProbe, hub) = TestSource.probe[Int]
        .toMat(BroadcastHub.sink(1))(Keep.both) // tried with buffer size 1,2,4,16 - all fails
        .run()

      hub.runWith(Sink.cancelled)
      val sinkProbe = hub.runWith(TestSink.probe[Int])

      // racey here with the cancelled subscription but seems to fail consistently
      sinkProbe.ensureSubscription()

      sinkProbe.requestNext()

      sourceProbe.sendNext(1)
      sinkProbe.expectNext(1)
    }
```

**Comment by jrudolph** [comment] 2017-07-18 09:50
After the last (or only) subscriber has cancelled, the BroadcastHub will shutdown. So, imo the test is not supposed to work in any case. Could that explain the behavior at least partly?

**Comment by johanandren** [comment] 2017-07-18 11:12
Aaaah, race in that it connects, cancels before the stage knows there is another one. Yes, that sounds like it could explain.

**Comment by johanandren** [comment] 2017-07-18 14:00
Actually, nope, this still fails:

```
    "handle a directly cancelled Sink" in assertAllStagesStopped {
      val (sourceProbe, hub) = TestSource.probe[Int]
        .toMat(BroadcastHub.sink(4))(Keep.both)
        .run()

      val cancelling = hub.runWith(TestSink.probe[Int])
      val movingAlong = hub.runWith(TestSink.probe[Int])

      cancelling.ensureSubscription()
      movingAlong.ensureSubscription()

      cancelling.cancel()

      movingAlong.requestNext()
      sourceProbe.sendNext(1)
      movingAlong.expectNext(1)
    }
```

**Comment by patriknw** [comment] 2017-08-14 13:58
I looked at this, and that last test is not correct. It's failing on `requestNext()` because nothing has been sent. It works fine when defined as:
```scala
"handle a directly cancelled Sink" in {
      val (sourceProbe, hub) = TestSource.probe[Int]
        .toMat(BroadcastHub.sink(4))(Keep.both)
        .run()

      val cancelling = hub.runWith(TestSink.probe[Int])
      val movingAlong = hub.runWith(TestSink.probe[Int])

      cancelling.ensureSubscription()
      movingAlong.ensureSubscription()

      cancelling.cancel()

      movingAlong.request(10)
      sourceProbe.sendNext(1)
      movingAlong.expectNext(1)
      movingAlong.cancel()
    }
```

Note that the hub is not shutdown because the last consumer is removed. The `in` must also be closed.
```
          if (activeConsumers == 0) {
            if (isClosed(in)) completeStage()
```

And the original test case by @sumnulu fails because the sink that is added first is `cancelled`. It works if they are added in other order. I'm not sure why. The initialization of this is complicated.

**Comment by johanandren** [comment] 2017-10-03 10:37
Hmm, ok, so this one, which fails for all buffer sizes:

```
      val in = TestPublisher.probe[Int]()
      val hubSource = Source.fromPublisher(in).runWith(BroadcastHub.sink(8))

      val out = TestSubscriber.probe[Int]()

      hubSource.runWith(Sink.cancelled)
      hubSource.runWith(Sink.fromSubscriber(out))

      out.ensureSubscription()

      out.request(1)
      in.expectRequest()
      in.sendNext(1)
      out.expectNext(1)

      in.sendComplete()
      out.expectComplete() // fails here, never sees complete from upstream
```

**Comment by patriknw** [comment] 2017-10-23 12:12
That last test case works if `out.request(5)`, i.e. the complete signal is not propagated until there is demand, which is a valid behavior.

However, assertAllStagesStopped fails with `expected no StreamSupervisor children, but got [Actor[akka://HubSpec/user/StreamSupervisor-0/flow-66-0-unnamed#-452365641]]`

**Comment by patriknw** [comment] 2017-10-23 12:23
The reason is that when `RegistrationPending` is received the consumer is added, and `consumer.callback.invoke(Initialize(startFrom))`, but since the consumer is already dead it will not get that callback and the hub will keep the consumer at that start position. Here is a test that illustrates this:

```scala
"handle cancelled Sink" in assertAllStagesStopped {
      val in = TestPublisher.probe[Int]()
      val hubSource = Source.fromPublisher(in).runWith(BroadcastHub.sink(4))

      val out = TestSubscriber.probe[Int]()

      hubSource.runWith(Sink.cancelled)
      hubSource.runWith(Sink.fromSubscriber(out))

      out.ensureSubscription()

      out.request(10)
      in.expectRequest()
      in.sendNext(1)
      out.expectNext(1)
      in.sendNext(2)
      out.expectNext(2)
      in.sendNext(3)
      out.expectNext(3)
      in.sendNext(4)
      out.expectNext(4)
      in.sendNext(5)
      out.expectNext(5)

      in.sendComplete()
      out.expectComplete()
    }
```

```
timeout (3 seconds) during expectMsg while waiting for OnNext(5)
```

**Comment by patriknw** [comment] 2017-10-23 12:25
I think we should solve this with the new async callbacks in https://github.com/akka/akka/pull/23185

**Closed** 2017-11-17 09:55 UTC
Labels: 3 - in progress, bug, t:stream
