### ISSUE TITLE
Duplicate entities in cluster sharding with remember entities off

### ISSUE THREAD

**Issue by drexin** [akka/akka#22870] opened 2017-05-08 17:01 UTC
After upgrading our app to Akka 2.5.1 we have seen duplicate entities in cluster sharding. I don't know if it's related to https://github.com/akka/akka/issues/22289, since we don't have remember entities enabled. Unfortunately I couldn't find anything suspicious in the logs, but I will try to reproduce the error and see if I can find any useful information.

**Comment by patriknw** [comment] 2017-05-08 17:11
Thanks for reporting. Logs or reproducer would be great. If you are not using remember entities then the other issue should not cause trouble.

**Comment by jamesmulcahy** [comment] 2017-05-08 17:15
For context, we upgraded from 2.4.18 to 2.5.1, and things seemed fine at 2.4.18 (and various versions before that).

**Comment by patriknw** [comment] 2017-05-08 19:00
It's a big change. ddata mode is default in 2.5, but it should of course not be duplicates. I assume that this didn't happen furing a rolling upgrade from 2.4.18 to 2.5.1.

**Comment by drexin** [comment] 2017-05-08 19:04
@patriknw I was able to find some useful information in the logs. The actual events started earlier than I first thought and the logs had already rolled.

#### Host 2 (original running entity)

```
2017-05-05 04:48:04.139 - Shard gets moved to Host 3

[…]

2017-05-05 05:10:23.525 194422732 [XXX-akka.actor.default-dispatcher-86] () ERROR a.c.s.DDataShardCoordinator - The ShardCoordinator was unable to
get an initial state within 'waiting-for-state-timeout' (was retrying): 5000 millis
2017-05-05 05:10:24.295 194423502 [XXX-akka.actor.default-dispatcher-4] () WARN  a.c.s.ShardRegion - Trying to register to coordinator at [Some(Act
orSelection[Anchor(akka://XXX/), Path(/system/sharding/ServiceCoordinator/singleton/coordinator)])], but no acknowledgement. Total [145] buffered m
essages.
2017-05-05 05:10:26.295 194425502 [XXX-akka.actor.default-dispatcher-60] () WARN  a.c.s.ShardRegion - Trying to register to coordinator at [Some(Ac
torSelection[Anchor(akka://XXX/), Path(/system/sharding/ServiceCoordinator/singleton/coordinator)])], but no acknowledgement. Total [145] buffered
messages.

[…]

2017-05-05 05:10:41.260 194440467 [XXX-akka.actor.default-dispatcher-98] () INFO  ShutdownOrchestrator - Received request to shut down

[…]

2017-05-05 05:10:47.587 3284 [XXX-akka.actor.default-dispatcher-2] () WARN  XXX - ShardRegion actor ref not found for system/sharding/XXX
2017-05-05 05:10:52.581 8278 [XXX-akka.actor.default-dispatcher-4] () WARN  XXX - ShardRegion actor ref not found for system/sharding/XXX
2017-05-05 05:10:57.590 13287 [XXX-akka.actor.default-dispatcher-4] () WARN  XXX - ShardRegion actor ref not found for system/sharding/XXX
2017-05-05 05:11:00.213 15910 [XXX-akka.actor.default-dispatcher-84] () INFO  XXX - Actor[akka://XXX/user/XXX#-1628
758845]
2017-05-05 05:11:00.214 15911 [XXX-akka.actor.default-dispatcher-105] () INFO  XXX - Member akka.tcp://XXX@host3 is up
2017-05-05 05:11:00.214 15911 [XXX-akka.actor.default-dispatcher-105] () INFO  XXX - Member akka.tcp://XXX@host5 is up
2017-05-05 05:11:00.215 15912 [XXX-akka.actor.default-dispatcher-105] () INFO  XXX - Member akka.tcp://XXX@host1 is up
2017-05-05 05:11:00.216 15913 [XXX-akka.actor.default-dispatcher-105] () INFO  XXX - Member akka.tcp://XXX@host4 is up
2017-05-05 05:11:01.321 17018 [XXX-akka.actor.default-dispatcher-110] () INFO  XXX - Member akka.tcp://XXX@host2 is up
2017-05-05 05:11:02.590 18287 [XXX-akka.actor.default-dispatcher-61] () INFO  XXX - Region ref Actor[akka://XXX/system/sharding/XXX#195350029] set
```

#### Host 3 (failed over to first)

```
2017-05-05 04:48:15.365 - Node receives request to start entity

After that the entity keeps running on that node and is not requested to stop

2017-05-05 05:10:54.164 - Problems start because 2 nodes run the entity
```

#### Host4 (failed over to second)

```
2017-05-05 05:10:24.916 1106333 [XXX-akka.actor.default-dispatcher-112] () WARN  a.r.EndpointReader - Serializer not defined for message with serializer id [6] and manifest []. Transient association error (association remains live). Cannot find manifest class [akka.cluster.MetricsGossipEnvelope] for serializer with id [5].
2017-05-05 05:10:31.010 1112427 [XXX-akka.actor.default-dispatcher-108] () ERROR HttpModule - Request timed out
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://XXX/user/XXX#2036220648]] after [45000 ms]. Sender[
null] sent message of type "XXX.XXX$XXX”.
        at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:601)
        at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:140)
        at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:864)
        at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:109)
        at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:103)
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:862)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:328)
        at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:279)
        at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:283)
        at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:235)
        at java.lang.Thread.run(Thread.java:745)
2017-05-05 05:10:43.611 1125028 [XXX-akka.actor.default-dispatcher-112] () WARN  a.r.t.n.NettyTransport - Remote connection to host2 failed with java.io.IOException: Connection reset by peer
2017-05-05 05:10:43.612 1125029 [XXX-akka.actor.default-dispatcher-112] () WARN  a.r.ReliableDeliverySupervisor - Association with remote system [akka.tcp://XXX@host2] has failed, address is now gated for [5000] ms. Reason: [Disassociated]
2017-05-05 05:10:47.245 1128662 [XXX-akka.actor.default-dispatcher-3] () INFO  XXX - Member akka.tcp://XXX@host2 is unreachable
2017-05-05 05:10:47.245 1128662 [XXX-akka.actor.default-dispatcher-3] () INFO  XXX - Scheduling reachability check for node akka.tcp://XXX@host2
2017-05-05 05:10:47.568 1128985 [XXX-akka.actor.default-dispatcher-105] () WARN  a.c.ClusterCoreDaemon - Cluster Node [akka.tcp://XXX@host4] - Marking node(s) as UNREACHABLE [Member(address = akka.tcp://XXX@host2, status = Up)]. Node roles [XXX]
2017-05-05 05:10:50.571 1131988 [XXX-akka.actor.default-dispatcher-38] () INFO  XXX - Member akka.tcp://XXX@host2 has been removed, previousStatus was Down
2017-05-05 05:10:52.257 1133674 [XXX-akka.actor.default-dispatcher-4] () INFO  XXX - Got status request for akka.tcp://XXX@host2, is Unreachable
2017-05-05 05:10:52.264 1133681 [XXX-akka.actor.default-dispatcher-4] () INFO  XXX - Got status request for akka.tcp://XXX@host2, is Unreachable
2017-05-05 05:10:52.266 1133683 [XXX-akka.actor.default-dispatcher-4] () INFO  XXX - Member akka.tcp://XXX@host2 will be removed
2017-05-05 05:10:52.341 1133758 [XXX-akka.actor.default-dispatcher-4] () INFO  XXX - Got status request for akka.tcp://XXX@host2, is Unreachable
2017-05-05 05:10:52.345 1133762 [XXX-akka.actor.default-dispatcher-4] () INFO  XXX - Got status request for akka.tcp://XXX@host2, is Unreachable

2017-05-05 05:10:53.403 - Node receives request to start entity
```

**Comment by patriknw** [comment] 2017-05-09 08:22
@drexin Was this during a rolling upgrade from 2.4.18 to 2.5.1? Did you have a mix of nodes with those two versions in the same Cluster?

I suspect that you had that because in the log there is a mention of `akka.cluster.MetricsGossipEnvelope`, which was removed in 2.5 (deprecated in 2.4, replaced by `akka.cluster.metrics.MetricsGossipEnvelope` in module `akka-cluster-metrics`).

Note this section in the migration guide: http://doc.akka.io/docs/akka/2.5/project/migration-guide-2.4.x-2.5.x.html#mig25-sharding-store
There might also be other considerations for such rolling upgrade, see http://doc.akka.io/docs/akka/2.5/project/migration-guide-2.4.x-2.5.x.html#Rolling_Update

**Comment by drexin** [comment] 2017-05-09 16:33
@patriknw Yes, it probably was mid-roll. We've been using `akka.cluster.sharding.state-store-mode = ddata` for a long time already, so that's not the issue. We didn't change the `enable-additional-serialization-bindings` setting, so that's likely to cause issues. Thanks for the help! I will do some more testing and report back here.

**Comment by patriknw** [comment] 2017-05-10 06:30
ok, let us know if you find anything more, or a reproducer

**Comment by jamesmulcahy** [comment] 2017-05-21 23:45
We now believe that the issue we're observing isn't due to one shard running in two locations at the same time, it's that one of the shards leaves behind a running stream which gives upon initial inspection/debugging, led to that impression.  I think we can close this -- apologies for the noise.  cc/ @drexin

**Comment by patriknw** [comment] 2017-05-23 08:46
Thanks for the update, no worries

**Closed by patriknw** 2017-05-23 08:46 UTC
