### ISSUE TITLE
akka.actor.testkit.typed.timefactor unexpected behavior

### ISSUE THREAD

**Issue by martin-konkol** [akka/akka#30021] opened 2021-02-12 05:17 UTC
Hi everyone, first of all, I'm a big fan of Akka, so thanks for all the hard work!

I might have bumped into an unexpected behavior of the `akka.actor.testkit.typed.timefactor` in `akka-actor-testkit-typed`. I might be missing something or maybe misunderstanding something, so it would be great if someone could help me verify the following issue.

**Symptoms**

Setting the `akka.actor.testkit.typed.timefactor` in `application-test.conf` to a *value* results in timeouts being scaled by *value^2* .

**Steps to Reproduce**

Create a mini-project with the following 3 files:
- build.sbt
```sbt
val akka = "2.6.12"
libraryDependencies ++= Seq(
  "org.scalatest" %% "scalatest" % "3.2.2" % Test,
  "com.typesafe.akka" %% "akka-actor-testkit-typed" % akka % Test
)
```
- src/test/resources/application-test.conf
```hocon
akka.actor.testkit.typed.timefactor = 3.0
akka.actor.testkit.typed.single-expect-default = 2s
```
- src/test/scala/debugging/SampleSpec.scala
```scala
package debugging

import akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit
import org.scalatest.flatspec.AnyFlatSpecLike

class SampleSpec extends ScalaTestWithActorTestKit with AnyFlatSpecLike { 
  it should "use timefactor correctly" in {
    sealed trait Dummy
    val probe = testKit.createTestProbe[Dummy]()
    probe.expectMessageType[Dummy]
  }
}
```

Running this code either via `sbt test` or even through VSCode results in:
```
SampleSpec:
- should use timefactor correctly *** FAILED ***
  java.lang.AssertionError: Timeout (18 seconds) during expectMessageClass waiting for interface debugging.SampleSpec$Dummy$1
  at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:391)
  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageClass_internal(TestProbeImpl.scala:238)
  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageType(TestProbeImpl.scala:217)
  at debugging.SampleSpec.$anonfun$new$1(SampleSpec.scala:11)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1683)
  ...
Execution took 18s
1 tests, 1 failed
```

Changing the config values to:
```hocon
akka.actor.testkit.typed.timefactor = 4.0
akka.actor.testkit.typed.single-expect-default = 1s
```
results in:
```
SampleSpec:
- should use timefactor correctly *** FAILED ***
  java.lang.AssertionError: Timeout (16 seconds) during expectMessageClass waiting for interface debugging.SampleSpec$Dummy$1
  at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:391)
  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageClass_internal(TestProbeImpl.scala:238)
  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageType(TestProbeImpl.scala:217)
  at debugging.SampleSpec.$anonfun$new$1(SampleSpec.scala:11)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1683)
  ...
Execution took 16s
1 tests, 1 failed
```

Changing the config values again to:
```hocon
akka.actor.testkit.typed.timefactor = 3.0
akka.actor.testkit.typed.single-expect-default = 1s
```
results in:
```
SampleSpec:
- should use timefactor correctly *** FAILED ***
  java.lang.AssertionError: Timeout (9 seconds) during expectMessageClass waiting for interface debugging.SampleSpec$Dummy$1
  at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:391)
  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageClass_internal(TestProbeImpl.scala:238)
  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageType(TestProbeImpl.scala:217)
  at debugging.SampleSpec.$anonfun$new$1(SampleSpec.scala:11)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1683)
  ...
Execution took 9.05s
1 tests, 1 failed
```

**Comment by johanandren** [comment] 2021-02-12 07:42
Thanks for a clear report, that doesn't look right. 

If you'd be up for digging into what the cause is and do a PR that is welcome.

**Comment by martin-konkol** [comment] 2021-02-13 22:33
Hi @johanandren I think I managed to track this down.

In `akka.actor.testkit.typed.internal.TestProbeImpl`:
```scala
override def remainingOrDefault: FiniteDuration = remainingOr(settings.SingleExpectDefaultTimeout.dilated)
```

The `dilated` extension comes from a package-defined implicit in `akka.actor.testkit.typed`:
```scala
implicit class TestDuration(val duration: FiniteDuration) extends AnyVal {
  def dilated(implicit settings: TestKitSettings): FiniteDuration = settings.dilated(duration)
}
```

However, the `SingleExpectDefaultTimeout` and other timeout configs in settings are already being dilated at creation time.
You can see it in `akka.actor.testkit.typed.TestKitSettings`: 
```scala
final class TestKitSettings(val config: Config) {

  import akka.util.Helpers._

  val TestTimeFactor: Double = config
    .getDouble("timefactor")
    .requiring(tf => !tf.isInfinite && tf > 0, "timefactor must be positive finite double")

  /** Dilated with `TestTimeFactor`. */
  val SingleExpectDefaultTimeout: FiniteDuration = dilated(config.getMillisDuration("single-expect-default"))

  /** Dilated with `TestTimeFactor`. */
  val ExpectNoMessageDefaultTimeout: FiniteDuration = dilated(config.getMillisDuration("expect-no-message-default"))

  /** Dilated with `TestTimeFactor`. */
  val DefaultTimeout: Timeout = Timeout(dilated(config.getMillisDuration("default-timeout")))

  /** Dilated with `TestTimeFactor`. */
  val DefaultActorSystemShutdownTimeout: FiniteDuration = dilated(config.getMillisDuration("system-shutdown-default"))

  val ThrowOnShutdownTimeout: Boolean = config.getBoolean("throw-on-shutdown-timeout")

  /** Dilated with `TestTimeFactor`. */
  val FilterLeeway: FiniteDuration = dilated(config.getMillisDuration("filter-leeway"))

  /**
   * Scala API: Scale the `duration` with the configured `TestTimeFactor`
   */
  def dilated(duration: FiniteDuration): FiniteDuration =
    Duration.fromNanos((duration.toNanos * TestTimeFactor + 0.5).toLong)

  /**
   * Java API: Scale the `duration` with the configured `TestTimeFactor`
   */
  def dilated(duration: java.time.Duration): java.time.Duration =
    dilated(duration.asScala).asJava
}
```

It seems that's why the dilation *value* is applied as *value^2* for the resulting test timeouts.

Regarding the fix, that seems to be more of a design decision, whether the dilation should be applied at creation or on-the-fly and is for you to decide. Unfortunately, I'm so busy recently that I couldn't even promise any work on this based on how things look for me at the moment.

**Comment by martin-konkol** [comment] 2021-02-13 22:50
Also fixing this might affect tests of a lot of projects out there. I don't know how many are using the `akka-actor-testkit-typed` and the timefactor feature.

**Comment by johanandren** [comment] 2021-02-15 10:14
You are right about the double-dilation-cause, I think this should be fixed regardless if it makes some projects fail as in that case it is making them pass for an unexpected reason right now. Would be good to double check the other durations dilated in `TestProbeImpl` so that there isn't additional bugs just like this.

**Comment by johanandren** [comment] 2021-02-15 10:44
Quick enough for me to fix this so I did. Thanks for the report and investigation @martin-konkol

**Comment by martin-konkol** [comment] 2021-02-16 00:42
Perfect, I agree it needs to be fixed. I was thinking more about whether this warrants some kind of warning in the change log / release notes or not. But you probably have a process for that anyway. Thanks for the fix, looking forward to it.

**Closed** 2021-02-22 16:48 UTC
Labels: 3 - in progress, t:testing
