### ISSUE TITLE
Akka Streams Memory Leak (TextMessage.streamText / BinaryMessage.streamData)

### ISSUE THREAD

**Issue by cullender-skew** [akka/akka#29635] opened 2020-09-20 19:03 UTC
Hi,

We use akka http to consume websocket messages (at quite a high rate) and we have been noticing that our services hit OOM issues after running some time.

After digging around, it seems there is a memory leak within the akka stream where we use it to fold a streaming text message.

The code looks like as follows (written in kotlin)

```kotlin
        // we create our source (<OUT,MAT>)
        val queueSource = Source
                .queue<Message>(5000, OverflowStrategy.fail())
                .throttle(throttleElements, throttleDuration)
        // we create our sink (<IN,MAT>)
        val actorSink = Sink.actorRef<WsTextMessageResponse>(
                self,
                WsDisconnectedResponse("sink completed for ${message.wsUrl}")
        )
        // we create our mapping sink flow <IN, OUT, MAT>
        val flow = Http.get(context.system).webSocketClientFlow(request)
                .filter { it.isText }
                .mapAsync(3) { wsMessage ->
                    val textMessage = wsMessage as TextMessage
                    if (textMessage.isStrict) {
                        CompletableFuture.completedFuture(WsTextMessageResponse(textMessage.strictText))
                    } else {
                        wsMessage
                                .toStrict(5_000, materializer())
                                .thenApply { WsTextMessageResponse(it.text()) }
                    }
                }
        // we now wire up our stream
        val pair = queueSource
                .viaMat(flow, Keep.both())
                .toMat(actorSink, Keep.left())
                .run(materializer())
```

The stream 

```kotlin
                        wsMessage
                                .toStrict(5_000, materializer())
                                .thenApply { WsTextMessageResponse(it.text()) }
```

is created hundreds of times a second. 

When profiling the JVM, it is clear that the unbounded message queue instances grow continuously (which are created from the above stream) - the below screenshot is from visual vm after running for a while (with delta's enabled) and after doing multiple `Perform GC's`

![image](https://user-images.githubusercontent.com/50367911/93719774-a0c4f400-fb7c-11ea-85fc-aaff5ae7849b.png)

**Comment by jrudolph** [comment] 2020-09-21 09:49
Moved this over to akka/akka. Let's treat it as a duplicate of #29557 but feel free to continue the discussion over here if you think it fits here better (or you think it's an issue in its own).

**Closed by jrudolph** 2020-09-21 09:49 UTC
Labels: 0 - new, t:stream
