### ISSUE TITLE
cluster sharding Unknown entity Actor

### ISSUE THREAD

**Issue by Hatebeingslow** [akka/akka#28321] opened 2019-12-06 04:42 UTC
So when i do passivate, Shard doesn't know which entity acor he should stop
```
def passivateEntity(): Unit = {
    log.info("Sending stop message to parent: {}", context.parent.path.toStringWithoutAddress)
    context.parent ! Passivate(stopMessage = PoisonPill)
  }
```
Here are the logs:
```
[akka.tcp://CustomerSystem@10.244.1.149:2551/system/sharding/CustomerShard/41/50fa90e2-de5a-37c0-9c58-7fb7f1375077] k.d.m.c.e.Customer | Sending stop message to parrent: /system/sharding/CustomerShard/41
```
```
[akka.tcp://CustomerSystem@10.244.1.149:2551/system/sharding/CustomerShard/41] a.c.s.Shard | Unknown entity Actor[akka://CustomerSystem/user/$a#-903358967]. Not sending stopMessage back to entity.
```
as you see, my actor entity with id name `[akka.tcp://CustomerSystem@10.244.1.149:2551/system/sharding/CustomerShard/41/50fa90e2-de5a-37c0-9c58-7fb7f1375077]` is sending stop message to context parent, but Shard receives another id name `[akka://CustomerSystem/user/$a#-903358967]` Why it happens?

**Comment by patriknw** [comment] 2019-12-10 08:17
This was asked in https://discuss.lightbend.com/t/cluster-sharding-nnknown-entity-actor-when-passivating/5550
Closing issue, since I'm pretty sure it's not a bug in Akka.

**Closed by patriknw** 2019-12-10 08:17 UTC
