### ISSUE TITLE
Akka streams Source.fromIterator hangs when iterator throws on hasNext

### ISSUE THREAD

**Issue by anton-fomin** [akka/akka#21620] opened 2016-10-04 10:04 UTC
When it is first hasNext everything seems ok. Source.runForeach returns future that fails immediately. But if an error thrown on next steps it just hangs. In the following example future never completes.

```
val failOnHasNextIterator = new Iterator[Int]{
  var needToTrow = false

  override def hasNext: Boolean = {
    if (needToTrow) {
      throw new Exception
    }
    needToTrow = true
    true
  }

  override def next(): Int = 1
}

val source = Source.fromIterator(() => failOnHasNextIterator)
source.runForeach(println)
```

Version "com.typesafe.akka" %% "akka-stream" % "2.4.10"

**Comment by johanandren** [comment] 2016-10-04 14:33
This is not correct, however, the reason why it may seem so is that you do not in any way observe the state of the stream. To observe the outcome you will have to do something like this:

```
 Source.fromIterator { () =>
    new Iterator[Int] {
      override def hasNext: Boolean = throw new RuntimeException("It broke")
      override def next(): Int = ???
    }
  }.runForeach(println)
    .onComplete(println)
```

Or use the monitor stage.

**Comment by anton-fomin** [comment] 2016-10-04 15:47
> the reason why it may seem so is that you do not in any way observe the state of the stream

Actually I do in real code. And as I mentioned in issue description problem only happens when iterator throws on second hasNext or later. Anyway I noticed that there is version 2.4.11 already and it seems that this issue is fixed there.

**Comment by johanandren** [comment] 2016-10-04 16:01
Ah, sorry, I read the description too a bit fast. I can't see that anything changed with the codepath up to calling `onNext` for the last half year though, I'll reopen this for some investigations.

I thought it may be the event chasing bug that was fixed in 2.4.11 but I can reproduce with 2.4.8 which is before the bug was introduced.

**Comment by johanandren** [comment] 2016-10-04 16:02
(would be good to know how this bug happens and what fixed it)

**Comment by patriknw** [comment] 2016-10-31 15:25
@anton-fomin is this fixed, and in that case what fixed it?

**Comment by drewhk** [comment] 2016-10-31 15:29
Is supervision enabled on the stream where you observed it? Source.iterator is implemented in terms of statefulMapConcat which allows supervision, for example Resume or Restart. May that be an issue?

**Comment by anton-fomin** [comment] 2016-10-31 16:18
@patriknw Yes it seems so. I can't reproduce this in 2.4.11.

As @drewhk mentioned I tried different supervisions
```

  val failOnHasNextIterator = new Iterator[Int]{
      var needToTrow = false

      override def hasNext: Boolean = {
        if (needToTrow) {
          throw new Exception
        }
        needToTrow = true
        true
      }

      override def next(): Int = 1
    }
  val source = Source.fromIterator(() => failOnHasNextIterator)
      .withAttributes(ActorAttributes.supervisionStrategy(Supervision.restartingDecider))

    val future = source.runForeach(println)
    future.foreach(_ => println("Done"))
    future.failed.foreach(_ => println("Failed"))
```
And for restarting decider I've got
```
[ERROR] [10/31/2016 18:11:11.848] [default-akka.actor.default-dispatcher-2] [akka://default/user/StreamSupervisor-0/flow-0-0-unknown-operation] Error in stage [StatefulMapConcat]: requirement failed: Cannot pull port (StatefulMapConcat.in) twice
java.lang.IllegalArgumentException: requirement failed: Cannot pull port (StatefulMapConcat.in) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:355)
	at akka.stream.impl.fusing.StatefulMapConcat$$anon$25.pushPull(Ops.scala:1546)
	at akka.stream.impl.fusing.StatefulMapConcat$$anon$25.onPull(Ops.scala:1566)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:754)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:660)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:414)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
And for resuming I've got
```
[ERROR] [10/31/2016 18:12:48.670] [default-akka.actor.default-dispatcher-4] [akka://default/user/StreamSupervisor-0/flow-0-0-unknown-operation] Error in stage [StatefulMapConcat]: null
java.lang.Exception
	at Solution$$anon$1.hasNext(Main.scala:22)
	at akka.stream.impl.fusing.StatefulMapConcat$$anon$25.hasNext(Ops.scala:1538)
	at akka.stream.impl.fusing.StatefulMapConcat$$anon$25.pushPull(Ops.scala:1542)
	at akka.stream.impl.fusing.StatefulMapConcat$$anon$25.onPull(Ops.scala:1566)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:754)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:660)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:414)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

With stopping decider there is no difference. Stream just hangs.

**Comment by drewhk** [comment] 2016-11-04 10:19
Hm, not sure why this is fixed but if nothing else, we can add a few more test cases to make sure there is no regressions. I mark this as triaged, can be a good pick for cleanup days.

**Comment by ktoso** [comment] 2017-09-06 14:53
Closing as fixed in the days of yore

**Closed by ktoso** 2017-09-06 14:53 UTC
Labels: 1 - triaged, t:stream
