### ISSUE TITLE
akka-http file upload doesn't support chinese filename

### ISSUE THREAD

**Issue by huanwuji** [akka/akka#17847] opened 2015-06-26 10:19 UTC
route code like this：

```scala
    (path("upload") & parameter('test)) {
      test ⇒
        println(test)
        formFields('file.as[StrictForm.FileData]) {
          case StrictForm.FileData(name, HttpEntity.Strict(ct, data)) ⇒
            complete(s"type ${ct.mediaType} length ${data.length} filename ${name.get}")
        }
    } 
```
it doesn't support upload file name like `菊花.jpg`, which is a chinese file name

exception stack like this:
```
18:17:59.790 [default-akka.actor.default-dispatcher-3] ERROR akka.actor.ActorSystemImpl - Outgoing request stream error
java.lang.IllegalStateException: Substream publisher only supports one subscriber (which is allowed, see reactive-streams specification, rule 1.12)
	at akka.stream.impl.ReactiveStreamsCompliance$.rejectAdditionalSubscriber(ReactiveStreamsCompliance.scala:57) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MultiStreamOutputProcessor$SubstreamOutput.subscribe(StreamOfStreamProcessors.scala:104) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession.assignPort(StreamLayout.scala:693) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.ActorMaterializerImpl$$anon$3.materializeAtomic(ActorMaterializerImpl.scala:98) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:660) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:651) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at scala.collection.immutable.Set$Set3.foreach(Set.scala:145) ~[scala-library-2.11.6.jar:?]
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:651) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession.materializeComposite(StreamLayout.scala:676) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:666) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:651) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79) ~[scala-library-2.11.6.jar:?]
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:651) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:663) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:651) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at scala.collection.immutable.Set$Set3.foreach(Set.scala:145) ~[scala-library-2.11.6.jar:?]
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:651) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession.materializeComposite(StreamLayout.scala:676) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:666) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:651) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79) ~[scala-library-2.11.6.jar:?]
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:651) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession.materializeComposite(StreamLayout.scala:676) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:666) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:651) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:111) ~[scala-library-2.11.6.jar:?]
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:651) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.MaterializerSession.materialize(StreamLayout.scala:636) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:204) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:334) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.scaladsl.Source.runWith(Source.scala:110) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.ConcatAllImpl$$anonfun$1.apply$mcV$sp(ConcatAllImpl.scala:28) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.Pump$class.pump(Transfer.scala:199) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.ActorProcessorImpl.pump(ActorProcessor.scala:250) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.SimpleOutputs$$anonfun$downstreamRunning$1.applyOrElse(ActorProcessor.scala:237) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.6.jar:?]
	at akka.stream.impl.SubReceive.apply(Transfer.scala:16) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.stream.impl.SubReceive.apply(Transfer.scala:12) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.6.jar:?]
	at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.6.jar:?]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[scala-library-2.11.6.jar:?]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.11.jar:?]
	at akka.stream.impl.ActorProcessorImpl.aroundReceive(ActorProcessor.scala:250) ~[akka-stream-experimental_2.11-1.0-RC4.jar:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.11.jar:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.11.jar:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.11.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.11.jar:?]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:?]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:?]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:?]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:?]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:?]
```

**Comment by ktoso** [comment] 2015-06-30 14:54
Thanks for reporting!

cc @sirthias @jrudolph

**Comment by jrudolph** [comment] 2015-07-02 13:12
This may be related to or a duplicate of #16821 though the error here is interesting enough to warrant an extra ticket for now.

**Comment by jrudolph** [comment] 2015-07-02 13:27
I cannot reproduce the stack trace but using the above filename results for me in a 400 response:

```
The form field 'file' was malformed:
multipart/form-data part must contain `Content-Disposition` header with `name` parameter
```

which probably means that the `Content-Disposition` header wasn't parsed correctly.

**Comment by huanwuji** [comment] 2015-07-03 06:05
```scala
    (path("upload") & parameter('test)) {
      test ⇒
        println(test)
        formFields('file.as[StrictForm.FileData]) {
          case StrictForm.FileData(name, HttpEntity.Strict(ct, data)) ⇒
            complete(s"type ${ct.mediaType} length ${data.length} filename ${name.get}")
        }
    } ~
      extractRequest {
        request ⇒
          val response = Source.single(request).via(BackendConf.backendFlow).runWith(Sink.head)
          complete(response)
      }
```
I'm sorry, the full code like this, because `path("upload")` not match, so make it go to another path

**Comment by 2beaucoup** [comment] 2015-07-03 07:58
Is this related to https://github.com/sirthias/parboiled2/issues/147?

**Comment by jrudolph** [comment] 2015-07-03 08:45
I'd say, it's unlikely:

```
scala> "菊花".size
res4: Int = 2
```

**Comment by ktoso** [comment] 2015-11-30 14:22
Closing due to a) inactivity and also we fixed things which may have been related to this recently.

**Closed** 2015-11-30 14:22 UTC
Labels: bug, t:http
