### ISSUE TITLE
HTTP 1.0-RC2 appears to handle incoming connections sequentially

### ISSUE THREAD

**Issue by markhatton** [akka/akka#17508] opened 2015-05-18 15:25 UTC
Given the following simple server implementation:
```
object TestServer extends App with Directives {
  implicit val system = ActorSystem()
  implicit val flowMaterializer = ActorFlowMaterializer()

  val requestHandler: HttpRequest => HttpResponse = {
    _ => HttpResponse()
  }

  val serverSource = Http().bind("localhost", 8080)

  serverSource.to(Sink.foreach { connection =>
    connection handleWithSyncHandler requestHandler
  }).run()
}
```

Testing via ApacheBench reports the same # of requests / sec irrespective of the client concurrency (on my machine this is only 130 RPS).  The same server code running with HTTP v1.0-M5 on the other hand shows throughput increasing proportional to client concurrency.

It seems as though each incoming connection is being handled sequentially by the server.

**Comment by markhatton** [comment] 2015-05-18 17:32
I note that with keepalive enabled, the throughput is identical between 1.0-M5 and 1.0-RC2.  So it is as if the TCP handshake is now being run sequentially.

**Comment by jrudolph** [comment] 2015-05-19 06:09
@markhatton Thanks for the report.

This seems to be basically a duplicate of what was reported in #17395. The issue is two-fold as explained in the latest comments in the issue. We have a bottleneck in the connection establishment pipeline (#17512) and a performance regression in setting up streams (#17317) that in combination lead to what you observed.

I'm closing this as #17317 has already be fixed and a release containing the fix will be released soon.

**Closed by jrudolph** 2015-05-19 06:09 UTC
Labels: bug, t:http, t:http:core, t:http:server, t:stream
