### ISSUE TITLE
Akka Streams / HTTP memory leak

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16900] opened 2015-02-18 15:03 UTC
Reported by @benjamingeer in https://github.com/akka/akka/issues/16290#issuecomment-74877049:

> We recently switched back from Akka HTTP to Spray because we found that Akka HTTP leaks memory. I haven't had time to make a minimal test case for you, but it involved hammering our REST API using [Apache Bench](http://httpd.apache.org/docs/2.4/programs/ab.html) for 20 minutes with 50 concurrent connections, and watching the application's total heap allocation in [VisualVM](http://visualvm.java.net/). With Akka HTTP, the average allocation increased steadily, up to the JVM's maximum heap size:
![screen_shot_2015-02-09_at_12 18 02](https://cloud.githubusercontent.com/assets/558389/6249280/73e534f8-b786-11e4-87f7-a4f5bec5a50b.png)

> With Spray, the average allocation is roughly constant:
![screen_shot_2015-02-17_at_16 31 05](https://cloud.githubusercontent.com/assets/558389/6249314/9f695dde-b786-11e4-895c-08e4c04f9d96.png)

/cc @sirthias

**Comment by jrudolph** [comment] 2015-02-18 15:05
@benjamingeer as a quick check - if you get the chance - could you look at the output of `jmap -histo:live <pid>` to see which kind of instances take up the extra memory? You could do this repeatedly or at the end.

**Comment by benjamingeer** [comment] 2015-02-18 15:23
I will try to do that, but in the meantime, here's what I saw in VisualVM:

![heap-dump](https://cloud.githubusercontent.com/assets/558389/6249647/df9a89d0-b788-11e4-86e9-46bb9acf71b5.png)

I wondered why there are 150,000 instances of `ChildActorPath`, `ActorCell`, `Props`, etc. In this test, our code doesn't create more than about 100 actor instances. A lot of those `ChildActorPath` instances seem to  have names that start with `flow`:

![child-actor-path](https://cloud.githubusercontent.com/assets/558389/6249675/10c3fd3e-b789-11e4-9fbe-826e2b9c661b.png)

**Comment by drewhk** [comment] 2015-02-18 15:26
The reason is simple: all Stream processing stages are currently backed by exactly one actor. This will be reduced as we will make it configurable how you want to allocate parts of your processing pipeline to actors. This needs some work though, and the first step of that is the currently ongoing rewrite that completely unifies the internal representation. This is the first necessary ingredient to be able to fuse complex graphs and execute them in a single actor.

**Comment by bantonsson** [comment] 2015-02-18 21:27
@drewhk, that would only make it grow slower. There is something else that is fishy here, maybe the streams are not being terminated properly and the actors not stopped, or else you wouldn't have the ever growing trend, but maybe just a higher baseline.

**Comment by drewhk** [comment] 2015-02-19 07:02
Well, it depends on how long the above chart is compared to the benchmark. I mean if it is still accepting connections at the peak we see then it might be not a leak just a hell of a lot of actors. However if the benchmark is already stopped there then we very likely leak. Someone else reported running out of file descriptors, so something fishy is going on indeed.

**Comment by drewhk** [comment] 2015-02-19 07:03
@benjamingeer Which version did you use? M3 fixed some TCP termination problems that were present in M2.

**Comment by bantonsson** [comment] 2015-02-19 08:20
@drewhk If I read the description correctly, there is only ever 50 concurrent connections, but they get torn down and recreated, and the test has been running for more than 15 minutes.

Is that correct @benjamingeer ?

**Comment by drewhk** [comment] 2015-02-19 08:21
I have a feeling that this is somehow related to https://github.com/akka/akka/issues/16899

**Comment by bantonsson** [comment] 2015-02-19 08:23
Yes, that could very well be the case. Would be awesome to have a small reproducer though.

**Comment by drewhk** [comment] 2015-02-19 08:26
I don't think it is hard to do one. We need to create a stress test.

**Comment by benjamingeer** [comment] 2015-02-19 08:31
@drewhk We used M3. In the above chart, there are about 30 seconds at the end after the test client stops making connections, but the allocated memory isn't freed.

@bantonsson Yes, that's correct, there are never more than 50 concurrent connections. I just ran Apache Bench repeatedly for 20 minutes:

```
$ ab -n 50000 -c 50 http://localhost/...
```

Once the maximum heap size (1 GB in this test) is fully allocated, the garbage collector runs constantly trying to free memory for new allocations (I could see this by turning on the `verbosegc` JVM option), and this makes the application run extremely slowly.

I've got a lot on my plate right now, but I'll try to find a little time to make a small reproducer.

**Comment by drewhk** [comment] 2015-02-19 09:56
@benjamingeer thank you very much for reporting this. I suspect this might be a leak and/or TCP half-close and some weirdenss of how NIO handles that (the ticket I linked).

**Comment by drewhk** [comment] 2015-04-10 09:56
This should be repeated with M5. We fixed a couple of leaks.

**Comment by benjamingeer** [comment] 2015-04-10 10:11
I wish I could help more, but I've been unable to find time to do so. Since Spray is working for us, the consensus in our team is that we'll stick with Spray until Akka Streams matures. If you haven't done so already, I hope you can find time to write your own tests to check for memory leaks. Our application is pretty straightforward: it's a RESTful API server that receives HTTP requests, turns them into messages that are sent to pools of actors using the `ask` pattern, and turns the actors' reply messages into JSON (using spray-json) that's sent back to the client. All I did was hammer it with [Apache Bench](http://httpd.apache.org/docs/2.4/programs/ab.html) and watch the heap allocation using [VisualVM](http://visualvm.java.net/).Hope this helps.

**Comment by drewhk** [comment] 2015-04-10 10:20
Sorry if I was ambiguous, I meant my previous statement for us, Akka team. I.e. we should try to look at it again.

**Comment by patriknw** [comment] 2015-04-14 13:38
I have verified that this is fixed in latest release-2.3-dev.
This was the test program I used for profiling:

    package akka.http.server
    
    import scala.concurrent.duration._
    import akka.actor.ActorSystem
    import akka.stream.ActorFlowMaterializer
    import akka.http.model.HttpResponse
    import akka.http.Http
    import akka.http.model.Uri
    import akka.http.model.HttpRequest
    import akka.http.model.HttpEntity
    import akka.http.model.MediaTypes
    import akka.actor.Actor
    import akka.stream.scaladsl.Source
    import akka.stream.scaladsl.ImplicitFlowMaterializer
    import akka.stream.scaladsl.Sink
    import akka.actor.Props
    import scala.concurrent.forkjoin.ThreadLocalRandom
    import akka.actor.ActorLogging
    import akka.pattern.pipe
    import java.util.concurrent.CountDownLatch
    
    object LongRunningHttpServer {
    
      case object Tick
    
      class TestClient(latch: CountDownLatch) extends Actor with ImplicitFlowMaterializer with ActorLogging {
        import context.dispatcher
        val system = context.system
        val interval = 750.millis + ThreadLocalRandom.current.nextInt(500).millis
        system.scheduler.schedule(interval, interval, self, Tick)
        log.info("Started {} with interval {} ms", self.path.name, interval.toMillis)
        var requests = 0
        var responses = 0
    
        def receive = {
          case Tick ⇒
            requests += 1
            val connection = Http(system).outgoingConnection(host = "localhost", port = 8080)
            Source.single(HttpRequest(uri = "/ping")).via(connection).runWith(Sink.head).pipeTo(self)
    
          case response ⇒
            log.debug("{}", response)
            responses += 1
            if (responses == 10 || responses % 100 == 0)
              log.info("Req [{}] - Resp [{}]", requests, responses)
            if (responses == 600) {
              log.info("Stopped {} after {}", self.path.name, responses)
              latch.countDown()
              context.stop(self)
            }
    
        }
      }
    
      def startServer(): Unit = {
        implicit val system = ActorSystem("Server")
        implicit val materializer = ActorFlowMaterializer()
    
        val serverSource = Http(system).bind(interface = "localhost", port = 8080)
    
        import akka.http.model.HttpMethods._
        import akka.stream.scaladsl.Flow
    
        val requestHandler: HttpRequest ⇒ HttpResponse = {
          case HttpRequest(GET, Uri.Path("/"), _, _, _) ⇒
            HttpResponse(
              entity = HttpEntity(MediaTypes.`text/html`,
                "<html><body>Hello world!</body></html>"))
    
          case HttpRequest(GET, Uri.Path("/ping"), _, _, _)  ⇒ HttpResponse(entity = "PONG!")
          case HttpRequest(GET, Uri.Path("/crash"), _, _, _) ⇒ sys.error("BOOM!")
          case _: HttpRequest                                ⇒ HttpResponse(404, entity = "Unknown resource!")
        }
    
        serverSource.runForeach { connection ⇒
          system.log.debug("Accepted new connection from {}", connection.remoteAddress)
    
          connection handleWithSyncHandler requestHandler
          // this is equivalent to
          // connection handleWith { Flow[HttpRequest] map requestHandler }
        }
      }
    
      def startClients(): Unit = {
        val system = ActorSystem("Client")
        val latch = new CountDownLatch(100)
        for (n ← 1L to latch.getCount)
          system.actorOf(Props(classOf[TestClient], latch), s"client-$n")
        latch.await()
        system.log.info("All clients done")
      }
    
      def main(args: Array[String]): Unit = {
        startServer()
        startClients()
      }
    }

Same test program showed severe leaks of lingering actors for 1.0-M3.

There are some more related tickets, but I consider this one done.
Thanks for reporting @benjamingeer!

**Closed by patriknw** 2015-04-14 13:38 UTC
Labels: 3 - in progress, t:http, t:stream

**Comment by drewhk** [comment] 2015-04-14 13:49
Good!
