### ISSUE TITLE
Mixing ip addresses and dns entries doesn't start the cluster.

### ISSUE THREAD

**Issue by neowulf33** [akka/akka#21124] opened 2016-08-04 17:40 UTC
Version:
Akka Cluster Version: 2.4.7
Scala Version: 2.11.8

Setup:
1. `eth0` bound to internal_ip_address
1. DNS entries for internal ip address and external ip address 

Starting the cluster with the following options:

1. Works!
```
-Dakka.cluster.seed-nodes.1=akka.tcp://cluster@internal_ip:2572 -Dakka.remote.netty.tcp.hostname=""
```
2. Works!
```
-Dakka.cluster.seed-nodes.1=akka.tcp://cluster@internal_dns_entry:2572 -Dakka.remote.netty.tcp.hostname=internal_dns_entry
```
3. Works!
```
-Dakka.cluster.seed-nodes.1=akka.tcp://cluster@internal_ip:2572 -Dakka.remote.netty.tcp.hostname=internal_ip
```
4. Doesn't work!
```
-Dakka.cluster.seed-nodes.1=akka.tcp://cluster@internal_dns:2572 -Dakka.remote.netty.tcp.hostname=internal_ip
```
5. Doesn't work!
```
-Dakka.cluster.seed-nodes.1=akka.tcp://cluster@internal_ip:2572 -Dakka.remote.netty.tcp.hostname=internal_dns
```
6. Doesn't work!
```
-Dakka.cluster.seed-nodes.1=akka.tcp://cluster@internal_dns_entry:2572 -Dakka.remote.netty.tcp.hostname=""
```

**Comment by johanandren** [comment] 2016-08-08 10:50
The behavior is as intended. The documentation of the settings says "The hostname or ip clients should connect to." (which does not necessarily be the same as the server is bound to, there is also `akka.remote.netty.tcp.bind-hostname`) 

The string you specify as hostname becomes part of what identifies the cluster node, if an incoming message does not match the hostname it is dropped, you can see this in your logs:

```
[ERROR] [08/08/2016 12:44:35.059] [cluster-akka.remote.default-remote-dispatcher-5] [akka.tcp://cluster@localhost:2551/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Fcluster%40localhost%3A2551-1/endpointWriter] dropping message [class akka.actor.ActorSelectionMessage] for non-local recipient [Actor[akka.tcp://cluster@127.0.0.1:2551/]] arriving at [akka.tcp://cluster@127.0.0.1:2551] inbound addresses are [akka.tcp://cluster@localhost:2551]
```

As a side note, using empty string for hostname, leads to `InetAddress.getLocalHost.getHostAddress` being used, which essentially asks the OS about the hostname and then resolves that. It may or may not match your `internal_ip` and what `internal_dns_entry` resolves to (I'd stay clear of using that).

**Comment by patriknw** [comment] 2016-08-08 14:18
not an issue, closing

**Closed by patriknw** 2016-08-08 14:18 UTC
