### ISSUE TITLE
Streams established using SourceRef and SinkRef timeout

### ISSUE THREAD

**Issue by svozniuk** [akka/akka#24934] opened 2018-04-20 09:28 UTC
I have been trying to use Stream references for a week now (Akka 2.5.12)
However I'm experiencing that every stream established using SourceRef or SinkRef is unstable and times out in exactly `akka.stream.materializer.stream-ref.subscription-timeout` period of time. Note that it times out even after the data had been flowing through it (i.e. it was properly materialized and functioning)

I have been debugging this behavior and I think I've isolated the problem: During the startup of `SinkRefImpl` the timeout timer is attempted to be cancelled in `preStart` but it doesn't exist at that point of time. Afterwards, the last thing that `preStart` does is scheduling of a new timer that's never cancelled and leads to stream being stopped.

I have tried using both `SourceRef` and `SinkRef` and I'm getting the same instability of the stream, however the exceptions logged are different depending on the case 
* in case of `SinkRef` being shared - the real exception is silently swallowed and it looks like the stream just stopped 
* in case of `SourceRef` being shared you can clearly see that it's due to the timer ` akka.stream.StreamRefSubscriptionTimeoutException ... Remote side did not subscribe (materialize) handed out Sink reference`

I have created a small reproducer project here https://github.com/svozniuk/akka-streamref-issue

The bug can be observed both when running a Clustered version (see `Main.java` in the reproducer project) or a simple local `ActorSystem` (see `SourceRefTest.java` or `SinkRefTest.java`)

The main thing to observe in the logs - in 30 seconds the stream breaks, although it was successfully running and streaming data from source to sink

**Comment by ktoso** [comment] 2018-04-20 12:41
Thanks for reporting; thought we fixed it in https://github.com/akka/akka/issues/24626 though perhaps still not quite; I will look into it, thanks.

**Comment by svozniuk** [comment] 2018-04-20 13:04
I saw #24626 and it's related. But I think this time the problem is in the way `SinkRefImpl` is started. What I observed that the call to `cancelTimer(SubscriptionTimeoutTimerKey)` happened before the timer was actually started in `SinkRefImpl.scala:99`

**Comment by ktoso** [comment] 2018-04-20 13:08
since you looked so into it, would you mind submitting a pull request about
it? would really help a lot - now stuck in travel between airplanes etc :)

**Comment by svozniuk** [comment] 2018-04-21 07:44
I'm not an expert in Akka internals, but I will give it a try

**Comment by ktoso** [comment] 2018-04-23 01:39
Confirmed it's a bug, I'm looking into it a bit. Hope you don't mind @svozniuk ?

**Comment by ktoso** [comment] 2018-04-23 02:03
I have a fix for this, thanks a lot for reporting.

**Comment by svozniuk** [comment] 2018-04-23 05:14
I have a fix for this too :) Wanted to submit a PR in a couple of hours
However mine is a bit different from yours, since I didn't know the handshake was supposed to be bidirectional

**Comment by ktoso** [comment] 2018-04-23 05:16
Hmm, I wonder how we'd prefer it to be. If you have it ready can you point to your branch or PR for discussion?

**Comment by svozniuk** [comment] 2018-04-23 07:04
The PR is here https://github.com/akka/akka/pull/24948

**Comment by svozniuk** [comment] 2018-04-23 08:37
Just a small explanation for the change:
There are 2 ways that SinkRefStageImpl is created:
* either in StreamRefs.sourceRef
* or in preStart of it's counterpart (i.e. SinkRefImpl is created in preStart of SourceRefStageImpl)

I'll consider each side of the problem separately

When StreamRefs.sourceRef is called it will create a new instance of SinkRefStageImpl with uninitialized initialPartnerRef. 
In the preStart of SinkRefStageImpl there will be a new instance of SouceRefImpl created with the partner initialized to `self`. So now we have 2 actors running: 
1. The origin actor (SkinkRefStageImpl) that wasn't initialized with the initialPartnerRef and runs the timeout timer that is cancelled as soon as the first CumulativeDemand message is received (because it will call observeAndValidateSender of SinkRefStageImpl) 
2. The remote actor (SourceRefStageImpl) that was initialized with the initialPartnerRef to that of the origin. It will also have the timeout timer running. Now we have a choice: that will send the handshake as the response to first CumulativeDemand (your fix), or we just might not start the timer in the remote and already initialized counterpart (my fix)

Now the other way

When StreamRefs.sinkRef is called it will create a new instance of SourceRefStageImpl with uninialized initialParnerRef
In the preStart of SourceRefStageImpl here will be a new instance of SinkRefImpl created with the initialPartner initialized to `self`. So now we have 2 actors running: 
1. The origin actor (SourceRefStageImpl) that wasn't initialized with the initialPartnerRef and runs the timeout timer until it receives a handshake 
2. The remote actor (SinkRefStageImpl) that was initialized with the initialPartnerRef to that of the origin. It will also have the timeout timer running. But in your fix this timer will never be cancelled. (SInce it's only cancelled from observeAndValidateSender and it will be called in preStart before the timer is scheduled)

So it seems we will need both approaches merged
* yours to handle properly the handshake
* mine to handle the counterpart (sink)

**Comment by ktoso** [comment] 2018-04-24 17:13
Thanks for the reporting and collaboration on this!~

**Closed** 2018-04-24 17:13 UTC
Labels: bug, t:stream

**Comment by brunogbv** [comment] 2018-05-07 17:46
Hello guys, 

I'm using akka-streams 2.5.12 and I'm still getting this exact same error. I'm creating a source from kafka using akka-stream-kafka (0.20) and sending the created SourceRef to another actor via message. The stream is materialized and I can see stream elements being parsed on the log. What should I do? Is there another way to run a source in a remote actor?

**Comment by patriknw** [comment] 2018-05-07 19:09
This has not been released yet. It's targeted for upcoming 2.5.13.
There was one fix for 2.5.12 but that was not covering everything.

**Comment by ktoso** [comment] 2018-05-08 05:55
As workaround on 2.5.12 you can set the timeout to infinite, and apply one manually using the akka streams timeout operators

**Comment by brunogbv** [comment] 2018-05-11 18:34
Thank you very much for the reply @patriknw @ktoso.
How can I set the timeout to infinite? Setting it to 0 or <0?

Thanks in advance!!
