### ISSUE TITLE
HTTP client: If a client application does not read a response body, then future requests will stall

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#17403] opened 2015-05-06 17:45 UTC
(Closely related to #16898 -- this is basically the client-side mirror of that issue.)

I have some HTTP client code which makes repeated requests to the same host.
After upgrading this code to use the pooled-connection HTTP client in 1.0-RC1, I have found that some requests never complete, even though the remote host has replied.

I believe that the issue is that my client code does not read the full response body in all cases. For example, where it can determine that the response is an error from the status code or the Content-Type it does not read the full response body.

I assume that the HTTP client pool does not notice that the TCP connection "down" stream is stalled in this way, and puts it back in the pool for reuse. The next request to the same host is sent on the "up" stream of that connection, but the next response is never read, as the "down" stream is stalled.

The following test demonstrates the issue:

```
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.{HttpResponse, StatusCodes, HttpRequest}
import akka.stream.ActorFlowMaterializer
import org.specs2.mutable.Specification
import org.specs2.time.NoTimeConversions
import scala.concurrent.{Future, Await}
import scala.concurrent.duration._

class StalledConnectionSpec
  extends Specification
  with NoTimeConversions {

  implicit val system = ActorSystem()
  implicit val fm = ActorFlowMaterializer()

  "HTTP clients who do not read the response body" should {

    "not stall future requests to the same host" in {

      val request = HttpRequest(uri = "http://en.wikipedia.org/wiki/Main_Page")
      val httpClient: HttpRequest => Future[HttpResponse] = Http().singleRequest(_)

      // Make a request, don't read the body:
      val response1 = Await.result(httpClient(request), 10.seconds)
      response1.status mustEqual StatusCodes.OK

      // Make a second request to the same host:
      // The same TCP connection will be re-used by the pool, but it
      // is now blocked waiting for the body of `response1` to be read.
      // The request will time out waiting for that...
      val response2 = Await.result(httpClient(request), 10.seconds)
      response2.status mustEqual StatusCodes.OK
    }
  }
}
```

I think that the TCP connection should not be released to the pool for reuse until the full response has been read by the client code.

/cc @sirthias

**Comment by sirthias** [comment] 2015-05-07 07:20
Thanks for the report, Richard, your analysis is correct.
Currently the connection is "put back in the pool" as soon as the response has been dispatched, which doesn't mean that the response body has actually been consumed.

/cc @jrudolph

**Comment by rkuhn** [comment] 2015-05-28 08:27
For GET requests this behavior is arguably correct, is it not? Otherwise you’d just need to disable pipelining completely. What we should perhaps offer is an `ignorePayload` method on the `HttpResponse` that can be called to dispose of unwanted bytes, saving people the hassle of having to `.runWith(Sink.ignore)` themselves.

**Comment by sirthias** [comment] 2015-05-28 08:42
IMHO the request method doesn't come into play here.
This tickets addresses a problem in the "house-keeping" logic of the connection pool, which keeps count of the currently active requests on one connection.
Currently this counter is decreased too early (namely when the response instance has been *dispatched* rather than when the response entity has been *entirely consumed*). This miscounting causes subsequent requests to be dispatched to a connection that is still busy producing a (potentially long-running response), even when pipelining is disabled.

**Comment by rkuhn** [comment] 2015-05-28 08:45
Yes, true, and in this sense this is a duplicate of #17591. My proposal was to track this flaw over there and repurpose this ticket for adding awareness and convenience methods for the consequences of not consuming payloads.

**Closed** 2015-06-15 15:13 UTC
Labels: bug, t:http, t:http:client, t:http:core, t:http:next
