### ISSUE TITLE
Association fails when restarting two nodes at the same time in a cluster

### ISSUE THREAD

**Issue by lksoe** [akka/akka#25418] opened 2018-07-31 18:48 UTC
In our current setup, we have two nodes that are part of a cluster that are initially working as expected. Node1 is the initial seed node and Node2 is the other seed node. 

In rare occasions, when we restart Node1 and then subsequently restart Node2, we see that association in Node1 does not occur (not logged) even though Node2 reports an association. This causes Node2 to report that it cannot connect to seed Node1.

Logs from Node1:
```
Jul 31 17:09:50 host1 mySystem: [INFO] [07/31/2018 17:09:50.305] [main] [akka.remote.Remoting] Starting remoting
Jul 31 17:09:50 host1 mySystem: [INFO] [07/31/2018 17:09:50.486] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.ssl.tcp://mySystem@host1:9610]
Jul 31 17:09:50 host1 mySystem: [INFO] [07/31/2018 17:09:50.489] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.ssl.tcp://mySystem@host1:9610]
Jul 31 17:09:50 host1 mySystem: [INFO] [07/31/2018 17:09:50.520] [main] [akka.cluster.Cluster(akka://mySystem)] Cluster Node [akka.ssl.tcp://mySystem@host1:9610] - Starting up...
Jul 31 17:09:50 host1 mySystem: [INFO] [07/31/2018 17:09:50.572] [main] [akka.cluster.Cluster(akka://mySystem)] Cluster Node [akka.ssl.tcp://mySystem@host1:9610] - Registered cluster JMX MBean [akka:type=Cluster]
Jul 31 17:09:50 host1 mySystem: [INFO] [07/31/2018 17:09:50.572] [main] [akka.cluster.Cluster(akka://mySystem)] Cluster Node [akka.ssl.tcp://mySystem@host1:9610] - Started up successfully
Jul 31 17:09:50 host1 mySystem: [DEBUG] [07/31/2018 17:09:50.946] [mySystem-akka.remote.default-remote-dispatcher-6] [NettyTransport(akka://mySystem)] SSL random number generator set to: AES128CounterSecureRNG
Jul 31 17:09:53 host1 mySystem: [DEBUG] [07/31/2018 17:09:53.917] [New I/O worker #1] [NettyTransport(akka://mySystem)] Remote connection to [host2/host2ipaddress:9610] was disconnected because of [id: 0x6f3131e8, /host1ipaddress:41380 :> host2/host2ipaddress:9610] DISCONNECTED
Jul 31 17:09:53 host1 mySystem: [WARN] [07/31/2018 17:09:53.920] [New I/O worker #1] [NettyTransport(akka://mySystem)] Remote connection to [host2/host2ipaddress:9610] failed with javax.net.ssl.SSLException: Received close_notify during handshake
Jul 31 17:09:55 host1 mySystem: [DEBUG] [07/31/2018 17:09:55.616] [mySystem-akka.actor.default-dispatcher-18] [akka.ssl.tcp://mySystem@host1:9610/system/cluster/core/daemon/firstSeedNodeProcess-1] Couldn't join other seed nodes, will join myself. seed-nodes=[akka.ssl.tcp://mySystem@host1:9610, akka.ssl.tcp://mySystem@host2:9610]
Jul 31 17:09:55 host1 mySystem: [INFO] [07/31/2018 17:09:55.626] [mySystem-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://mySystem)] Cluster Node [akka.ssl.tcp://mySystem@host1:9610] - Node [akka.ssl.tcp://mySystem@host1:9610] is JOINING, roles [mySystem-websockets, dc-default]
Jul 31 17:09:55 host1 mySystem: [INFO] [07/31/2018 17:09:55.636] [mySystem-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://mySystem)] Cluster Node [akka.ssl.tcp://mySystem@host1:9610] - Leader is moving node [akka.ssl.tcp://mySystem@host1:9610] to [Up]
Jul 31 17:10:05 host1 mySystem: [INFO] [07/31/2018 17:10:05.709] [mySystem-akka.remote.default-remote-dispatcher-6] [akka.ssl.tcp://mySystem@host1:9610/system/transports/akkaprotocolmanager.ssl.tcp0/akkaProtocol-ssl.tcp%3A%2F%2FmySystem%40host2%3A9610-1] No response from remote for outbound association. Associate timed out after [15000 ms].
Jul 31 17:10:05 host1 mySystem: [DEBUG] [07/31/2018 17:10:05.712] [mySystem-akka.remote.default-remote-dispatcher-5] [akka.ssl.tcp://mySystem@host1:9610/system/endpointManager/reliableEndpointWriter-akka.ssl.tcp%3A%2F%2FmySystem%40host2%3A9610-0/endpointWriter] AssociationError [akka.ssl.tcp://mySystem@host1:9610] -> [akka.ssl.tcp://mySystem@host2:9610]: Error [Association failed with [akka.ssl.tcp://mySystem@host2:9610]] [
Jul 31 17:10:05 host1 mySystem: akka.remote.EndpointAssociationException: Association failed with [akka.ssl.tcp://mySystem@host2:9610]
Jul 31 17:10:05 host1 mySystem: Caused by: java.util.concurrent.TimeoutException: No response from remote for outbound association. Associate timed out after [15000 ms].
Jul 31 17:10:05 host1 mySystem: at akka.remote.transport.ProtocolStateActor$$anonfun$2.applyOrElse(AkkaProtocolTransport.scala:366)
Jul 31 17:10:05 host1 mySystem: at akka.remote.transport.ProtocolStateActor$$anonfun$2.applyOrElse(AkkaProtocolTransport.scala:340)
Jul 31 17:10:05 host1 mySystem: at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
Jul 31 17:10:05 host1 mySystem: at akka.actor.FSM$class.processEvent(FSM.scala:665)
Jul 31 17:10:05 host1 mySystem: at akka.remote.transport.ProtocolStateActor.processEvent(AkkaProtocolTransport.scala:285)
Jul 31 17:10:05 host1 mySystem: at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:659)
Jul 31 17:10:05 host1 mySystem: at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:631)
Jul 31 17:10:05 host1 mySystem: at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
Jul 31 17:10:05 host1 mySystem: at akka.remote.transport.ProtocolStateActor.aroundReceive(AkkaProtocolTransport.scala:285)
Jul 31 17:10:05 host1 mySystem: at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
Jul 31 17:10:05 host1 mySystem: at akka.actor.ActorCell.invoke(ActorCell.scala:559)
Jul 31 17:10:05 host1 mySystem: at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
Jul 31 17:10:05 host1 mySystem: at akka.dispatch.Mailbox.run(Mailbox.scala:224)
Jul 31 17:10:05 host1 mySystem: at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
Jul 31 17:10:05 host1 mySystem: at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
Jul 31 17:10:05 host1 mySystem: at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
Jul 31 17:10:05 host1 mySystem: at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Jul 31 17:10:05 host1 mySystem: at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Jul 31 17:10:05 host1 mySystem: ]
Jul 31 17:10:05 host1 mySystem: [WARN] [07/31/2018 17:10:05.715] [mySystem-akka.remote.default-remote-dispatcher-6] [akka.ssl.tcp://mySystem@host1:9610/system/endpointManager/reliableEndpointWriter-akka.ssl.tcp%3A%2F%2FmySystem%40host2%3A9610-0] Association with remote system [akka.ssl.tcp://mySystem@host2:9610] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.ssl.tcp://mySystem@host2:9610]] Caused by: [No response from remote for outbound association. Associate timed out after [15000 ms].]
Jul 31 17:10:05 host1 mySystem: [INFO] [07/31/2018 17:10:05.718] [mySystem-akka.actor.default-dispatcher-14] [akka://mySystem/deadLetters] Message [akka.cluster.InternalClusterAction$InitJoin] from Actor[akka://mySystem/system/cluster/core/daemon/firstSeedNodeProcess-1#1473082516] to Actor[akka://mySystem/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Jul 31 17:10:05 host1 mySystem: [INFO] [07/31/2018 17:10:05.718] [mySystem-akka.actor.default-dispatcher-14] [akka://mySystem/deadLetters] Message [akka.cluster.InternalClusterAction$InitJoin] from Actor[akka://mySystem/system/cluster/core/daemon/firstSeedNodeProcess-1#1473082516] to Actor[akka://mySystem/deadLetters] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Jul 31 17:10:05 host1 mySystem: [INFO] [07/31/2018 17:10:05.718] [mySystem-akka.actor.default-dispatcher-14] [akka://mySystem/deadLetters] Message [akka.cluster.InternalClusterAction$InitJoin] from Actor[akka://mySystem/system/cluster/core/daemon/firstSeedNodeProcess-1#1473082516] to Actor[akka://mySystem/deadLetters] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Jul 31 17:10:05 host1 mySystem: [INFO] [07/31/2018 17:10:05.718] [mySystem-akka.actor.default-dispatcher-14] [akka://mySystem/deadLetters] Message [akka.cluster.InternalClusterAction$InitJoin] from Actor[akka://mySystem/system/cluster/core/daemon/firstSeedNodeProcess-1#1473082516] to Actor[akka://mySystem/deadLetters] was not delivered. [4] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Jul 31 17:10:05 host1 mySystem: [INFO] [07/31/2018 17:10:05.718] [mySystem-akka.actor.default-dispatcher-14] [akka://mySystem/deadLetters] Message [akka.cluster.InternalClusterAction$InitJoin] from Actor[akka://mySystem/system/cluster/core/daemon/firstSeedNodeProcess-1#1473082516] to Actor[akka://mySystem/deadLetters] was not delivered. [5] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Jul 31 17:10:05 host1 mySystem: [DEBUG] [07/31/2018 17:10:05.719] [mySystem-akka.remote.default-remote-dispatcher-5] [akka.ssl.tcp://mySystem@host1:9610/system/endpointManager/reliableEndpointWriter-akka.ssl.tcp%3A%2F%2FmySystem%40host2%3A9610-0/endpointWriter] Disassociated [akka.ssl.tcp://mySystem@host1:9610] -> [akka.ssl.tcp://mySystem@host2:9610]
```

Logs from Node 2:
```
Jul 31 17:09:53 host2 mySystem: [INFO] [07/31/2018 17:09:53.990] [main] [akka.remote.Remoting] Starting remoting
Jul 31 17:09:54 host2 mySystem: [INFO] [07/31/2018 17:09:54.189] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.ssl.tcp://mySystem@host2:9610]
Jul 31 17:09:54 host2 mySystem: [INFO] [07/31/2018 17:09:54.191] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.ssl.tcp://mySystem@host2:9610]
Jul 31 17:09:54 host2 mySystem: [INFO] [07/31/2018 17:09:54.221] [main] [akka.cluster.Cluster(akka://mySystem)] Cluster Node [akka.ssl.tcp://mySystem@host2:9610] - Starting up...
Jul 31 17:09:54 host2 mySystem: [INFO] [07/31/2018 17:09:54.281] [main] [akka.cluster.Cluster(akka://mySystem)] Cluster Node [akka.ssl.tcp://mySystem@host2:9610] - Registered cluster JMX MBean [akka:type=Cluster]
Jul 31 17:09:54 host2 mySystem: [INFO] [07/31/2018 17:09:54.281] [main] [akka.cluster.Cluster(akka://mySystem)] Cluster Node [akka.ssl.tcp://mySystem@host2:9610] - Started up successfully
Jul 31 17:09:54 host2 mySystem: [DEBUG] [07/31/2018 17:09:54.686] [mySystem-akka.remote.default-remote-dispatcher-6] [NettyTransport(akka://mySystem)] SSL random number generator set to: AES128CounterSecureRNG
Jul 31 17:09:59 host2 mySystem: [DEBUG] [07/31/2018 17:09:59.845] [mySystem-akka.remote.default-remote-dispatcher-5] [akka.ssl.tcp://mySystem@host2:9610/system/endpointManager/reliableEndpointWriter-akka.ssl.tcp%3A%2F%2FmySystem%40host1%3A9610-0/endpointWriter] Associated [akka.ssl.tcp://mySystem@host2:9610] -> [akka.ssl.tcp://mySystem@host1:9610]
Jul 31 17:09:59 host2 mySystem: [DEBUG] [07/31/2018 17:09:59.857] [mySystem-akka.remote.default-remote-dispatcher-5] [akka.serialization.Serialization(akka://mySystem)] Using serializer [akka.cluster.protobuf.ClusterMessageSerializer] for message [akka.cluster.InternalClusterAction$InitJoin]
Jul 31 17:09:59 host2 mySystem: [DEBUG] [07/31/2018 17:09:59.886] [mySystem-akka.remote.default-remote-dispatcher-5] [akka.ssl.tcp://mySystem@host2:9610/system/endpointManager/reliableEndpointWriter-akka.ssl.tcp%3A%2F%2FmySystem%40host1%3A9610-0/endpointWriter] Drained buffer with maxWriteCount: 50, fullBackoffCount: 1, smallBackoffCount: 0, noBackoffCount: 0 , adaptiveBackoff: 1000
Jul 31 17:10:04 host2 mySystem: [WARN] [07/31/2018 17:10:04.405] [mySystem-akka.actor.default-dispatcher-2] [akka.ssl.tcp://mySystem@host2:9610/system/cluster/core/daemon/joinSeedNodeProcess-1] Couldn't join seed nodes after [2] attempts, will try again. seed-nodes=[akka.ssl.tcp://mySystem@host1:9610]
Jul 31 17:10:09 host2 mySystem: [WARN] [07/31/2018 17:10:09.423] [mySystem-akka.actor.default-dispatcher-2] [akka.ssl.tcp://mySystem@host2:9610/system/cluster/core/daemon/joinSeedNodeProcess-1] Couldn't join seed nodes after [3] attempts, will try again. seed-nodes=[akka.ssl.tcp://mySystem@host1:9610]
Jul 31 17:10:14 host2 mySystem: [WARN] [07/31/2018 17:10:14.443] [mySystem-akka.actor.default-dispatcher-19] [akka.ssl.tcp://mySystem@host2:9610/system/cluster/core/daemon/joinSeedNodeProcess-1] Couldn't join seed nodes after [4] attempts, will try again. seed-nodes=[akka.ssl.tcp://mySystem@host1:9610]
Jul 31 17:10:19 host2 mySystem: [WARN] [07/31/2018 17:10:19.463] [mySystem-akka.actor.default-dispatcher-2] [akka.ssl.tcp://mySystem@host2:9610/system/cluster/core/daemon/joinSeedNodeProcess-1] Couldn't join seed nodes after [5] attempts, will try again. seed-nodes=[akka.ssl.tcp://mySystem@host1:9610]
Jul 31 17:10:24 host2 mySystem: [WARN] [07/31/2018 17:10:24.483] [mySystem-akka.actor.default-dispatcher-18] [akka.ssl.tcp://mySystem@host2:9610/system/cluster/core/daemon/joinSeedNodeProcess-1] Couldn't join seed nodes after [6] attempts, will try again. seed-nodes=[akka.ssl.tcp://mySystem@host1:9610]
Jul 31 17:10:29 host2 mySystem: [WARN] [07/31/2018 17:10:29.503] [mySystem-akka.actor.default-dispatcher-2] [akka.ssl.tcp://mySystem@host2:9610/system/cluster/core/daemon/joinSeedNodeProcess-1] Couldn't join seed nodes after [7] attempts, will try again. seed-nodes=[akka.ssl.tcp://mySystem@host1:9610]
```

**Comment by jrudolph** [comment] 2019-06-25 16:17
Hi @lksoe, thanks for reporting this issue and sorry for never replying to it. These issues can be very hard to debug. Did it happen again since then? We would also recommend to try out Artery TCP as the remoting protocol instead as this has a simpler communication model that is less prone to these kinds of issues.

**Comment by Captain1653** [comment] 2023-08-28 18:13
This issue is quite old and has not been active for 4 years.

Should this issue be closed?

**Comment by johanandren** [comment] 2023-08-30 08:57
Closing as we didn't get any further information. Please re-open if some way of reproducing or more details available.

**Closed by johanandren** 2023-08-30 08:57 UTC
Labels: 0 - new
