### ISSUE TITLE
llegalArgumentException: Serializer identifier [32] of [akka.serialization.jackson.JacksonJsonSerializer] is not unique

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29351] opened 2020-07-03 15:45 UTC
In 2.6.6 we added the check of using same serializer id more than once.

Reported in https://discuss.lightbend.com/t/java-lang-illegalargumentexception-serializer-identifier-32-of-akka-serialization-jackson-jacksonjsonserializer-is-not-unique-it-is-also-used-by-akka-serialization-jackson-jacksonjsonserializer/6804/8

I couldn't reproduce.

Could be something with the config loading in Play if it ends up with two entries of JacksonJsonSerializer. Or if it's some leftover or config override from 2.6.5, where we started to change the cbor serializer binding.

**Comment by michaelahlers** [comment] 2020-07-08 22:30
I've encountered this with Play 2.8.2 and Akka 2.6.6.

**Comment by johanandren** [comment] 2020-07-09 08:15
@michaelahlers is it in dev mode of play (with the hot reloading of changes) you see this or production?

**Comment by sebastian-alfers** [comment] 2020-07-09 20:25
I faced this in local dev mode.

**Comment by WayneWang12** [comment] 2020-07-10 07:27
I've encountered the same problem.

**Comment by xuwei-k** [comment] 2020-07-13 12:50
I've also encountered the same problem.

**Comment by ignasi35** [comment] 2020-07-14 06:58
@xuwei-k @WayneWang12 are you also using a Play application with an overridden version of Akka? 

PS: As of this writing, the latest lay version is `2.8.2` but it ships with Akka `2.6.5` (which still doesn't include this check).

**Comment by xuwei-k** [comment] 2020-07-14 08:17
> are you also using a Play application with an overridden version of Akka?

precisely

**Comment by WayneWang12** [comment] 2020-07-15 02:26
> @xuwei-k @WayneWang12 are you also using a Play application with an overridden version of Akka?
> 
> PS: As of this writing, the latest lay version is `2.8.2` but it ships with Akka `2.6.5` (which still doesn't include this check).

yeah...I've solved it with @sebastian-alfers 's suggestion. It works

**Comment by jrudolph** [comment] 2020-08-12 11:45
This now also fails the nightly Telemetry build. Can we fix this on Akka's side for 2.6.9 or at least give a better error message about what the problem is (probably some incompatible classpath issue)?

**Comment by jrudolph** [comment] 2020-08-12 11:52
It seems the reason the wrong version of `akka-serialization-jackson` is not reported by `ManifestInfo.checkSameVersion` is that it is missing from `ActorSystemImpl.allModule`.

**Comment by jrudolph** [comment] 2020-08-12 12:03
> It seems the reason the wrong version of `akka-serialization-jackson` is not reported by `ManifestInfo.checkSameVersion` is that it is missing from `ActorSystemImpl.allModule`.

Fix for that in #29487

**Comment by raboof** [comment] 2020-08-13 07:28
> Fix for that in #29487

With that I think we can close the issue here, right?

**Comment by jrudolph** [comment] 2020-08-13 07:30
Yes, as I understand it, using an old version of akka-serialization-jackson with a new akka version will now fail with an incompatibility warning instead of this error.

**Closed by jrudolph** 2020-08-13 07:30 UTC
Labels: 1 - triaged, t:serialization
