### ISSUE TITLE
RandomizedSplitBrainResolverIntegrationSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29185] opened 2020-06-05 06:33 UTC
```
[info] [JVM-1] - must Scenario(lease-majority, 3) (on node 'node1', class akka.cluster.sbr.RandomizedSplitBrainResolverIntegrationSpecMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(DoubleRegister(/system/sharding/Entity-1/0/0-default,trying to register akka://RandomizedSplitBrainResolverIntegrationSpec-1@localhost:32875, but akka://RandomizedSplitBrainResolverIntegrationSpec-1@localhost:41379 was already registered for /system/sharding/Entity-1/0/0-default),Actor[akka://RandomizedSplitBrainResolverIntegrationSpec/user/shardingRegistry-1#-253734919]) after 0 millis
[info] [JVM-1]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:767)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:731)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:730)
[info] [JVM-1]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:969)
[info] [JVM-1]   at akka.cluster.sbr.RandomizedSplitBrainResolverIntegrationSpec$DisposableSys.$anonfun$verify$25(RandomizedBrainResolverIntegrationSpec.scala:351)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)
[info] [JVM-1]   at akka.cluster.sbr.RandomizedSplitBrainResolverIntegrationSpec$DisposableSys.$anonfun$verify$4(RandomizedBrainResolverIntegrationSpec.scala:348)
[info] [JVM-1]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [JVM-1]   at akka.testkit.TestKitBase.within(TestKit.scala:416)
[info] [JVM-1]   at akka.testkit.TestKitBase.within$(TestKit.scala:404)
[info] [JVM-1]   ...
[info] [JVM-1] [INFO] [06/05/2020 03:53:26.193] [RandomizedSplitBrainResolverInte
```

https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7723/consoleFull

**Comment by patriknw** [comment] 2020-06-24 09:33
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7778

**Comment by johanandren** [comment] 2020-06-25 09:01
https://jenkins.akka.io:8498/job/akka-multi-node-nightly-remember-entities/94/consoleText

**Comment by raboof** [comment] 2020-07-01 08:21
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/431/consoleFull

**Comment by raboof** [comment] 2020-07-01 09:58
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2398/consoleFull

**Comment by patriknw** [comment] 2020-07-01 11:31
The problem is what @johanandren identified in the logs:
```
[JVM-5] [INFO] [akkaMemberChanged][06/20/2020 06:34:16.271] [SplitBrainResolverIntegrationSpec-13-akka.actor.internal-dispatcher-31] [Cluster(akka://SplitBrainResolverIntegrationSpec-13)] Cluster Node [akka://SplitBrainResolverIntegrationSpec-13@localhost:NODE-5] dc [dcB] - Leader is moving node [akka://SplitBrainResolverIntegrationSpec-13@localhost:NODE-5] to [Up]
[JVM-5] [INFO] [akkaMemberChanged][06/20/2020 06:34:16.271] [SplitBrainResolverIntegrationSpec-13-akka.actor.internal-dispatcher-31] [Cluster(akka://SplitBrainResolverIntegrationSpec-13)] Cluster Node [akka://SplitBrainResolverIntegrationSpec-13@localhost:NODE-5] dc [dcB] - Leader is moving node [akka://SplitBrainResolverIntegrationSpec-13@localhost:NODE-4] to [Up]


// 5 is saying it is Up:ing itself, and then marking 4 as up, even though already is up since 06:34:15.284
// do we have a split brain from some bug with joining and multi-dc here?
```

NODE-4 joins via NODE-1 and moves itself to Up in dcB.

NODE-5 joins via NODE-1 and moves itself to Up in dcB. NODE-5 has lower address than NODE-4 and is therefore new leader. It hasn't seen NODE-1 as Up yet so it assigns the upNumber=1 to NODE-5, but that is what NODE-4 also did to itself. Two singletons.

We must find a more safe cross-dc joining mechanism.

In this case both joined via NODE-1 but it could be even worse if they concurrently joined via different nodes.

**Comment by patriknw** [comment] 2020-07-01 11:34
sorry, commented on wrong ticket, moving to https://github.com/akka/akka/issues/29280

**Comment by johanandren** [comment] 2020-07-08 11:26
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/439/consoleText

**Comment by jrudolph** [comment] 2020-07-14 08:23
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7856/console

**Comment by jrudolph** [comment] 2020-07-14 08:42
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2411/

**Comment by ignasi35** [comment] 2020-07-20 08:46
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2416/console

**Comment by raboof** [comment] 2020-07-22 08:06
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7864/consoleFull

**Comment by raboof** [comment] 2020-07-24 14:41
https://jenkins.akka.io:8498/job/akka-nightly-2.13/601/consoleFull

**Comment by patriknw** [comment] 2020-08-06 11:29
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7907/

**Comment by patriknw** [comment] 2020-08-17 08:47
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7939

**Closed** 2020-08-18 10:20 UTC
Labels: failed
