### ISSUE TITLE
Flow#keepAlive cause error when onTimer triggered

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31711] opened 2022-10-31 08:12 UTC
Hi team, I just encounter this problem.

usage:
```java
        if (keepAliveEnabled) {
            final int keepAliveInSeconds = bizConfig.getKeepAliveInSeconds();
            groupedSource = groupedSource
                .keepAlive(
                    Duration.ofSeconds(Math.max(keepAliveInSeconds, 1)),
                    (Creator<List<MergeClass>>) () -> keepAliveMessageProvider.getKeepAliveMergeClass(namespace, topic));
        }
```

Error when offering `akka.stream.BoundedSourceQueue#offer`:
![lQLPJxbUSNrGjWLNA3vNBz6wf0O9ctWCF9gDXN-VmgAFAA_1854_891](https://user-images.githubusercontent.com/501740/198961472-940e27a7-3dd5-458e-9327-51d4164aa3ea.png)

![image](https://user-images.githubusercontent.com/501740/198964123-c7655b59-06dd-4e30-946e-a622809b4779.png)

![lQLPJxbUSSVIAf3NAk3NB0ywhRB847yuSeEDXOAPOoA2AA_1868_589](https://user-images.githubusercontent.com/501740/198961506-be3ae334-c364-4ee4-9bbe-f0c7f648b669.png)

My keep alive time is `30s`.

I'm still try to find the root cause, thanks.

**Comment by johanandren** [comment] 2022-10-31 08:55
Duplicate of https://github.com/akka/akka/issues/30333

Please report any details you can share there (os, hardware, exact jdk version)

**Closed by johanandren** 2022-10-31 08:55 UTC
