### ISSUE TITLE
avoid excuting scheduled tasks when ActorSystem is terminated

### ISSUE THREAD

**Issue by almothafar** [akka/akka#21286] opened 2016-08-25 09:57 UTC
I think its really a critical point to fix, It's mentioned in the documentation as Warning

> All scheduled task will be executed when the ActorSystem is terminated, i.e. the task may execute before its timeout.

Could be this a feature request if its need to be as a configuration? 
or a question for how to avoid this ? 

Here is a question that posted for my story: http://stackoverflow.com/questions/37771194/playframework-akka-how-to-avoid-excuting-scheduled-tasks-executed-when-shutdo

**Comment by patriknw** [comment] 2016-08-25 18:42
Yes, this is annoying and should be fixed. 

A workaround is that you use `system.registerOnTermination` and in that callback cancel your scheduled task. Your callback will be run before the scheduler is shutdown, which is what makes the scheduled task to run.

This is a duplicate of https://github.com/akka/akka/issues/16495, so I'm closing it.

**Closed by patriknw** 2016-08-25 18:42 UTC
