### ISSUE TITLE
akka 2.4.9 regression when handling requests with absoluteURIs in HTTP/1.1 requests

### ISSUE THREAD

**Issue by jamesmulcahy** [akka/akka#21270] opened 2016-08-23 22:54 UTC
One of our users sends our akka-http service requests which used absoluteURIs.  This seemed to work just fine in akka 2.4.8, but as of 2.4.9, akka is failing to process the request, throwing an exception internally, and terminating the client connection.

The requests look like:

```
PUT http://127.0.0.1:8081/api/v2/services/REDACTED HTTP/1.1\r\n
```

RFC2616 says that "all HTTP1/1 servers MUST accept the absoluteURI form in requests", so it seems like this should be supported.  Even if it isn't supported, I'd expect a more graceful failure handling (i.e. 4xx client response).

The exception trace is
```
2016-08-23 15:48:09.019 40198 [Redacted-akka.actor.default-dispatcher-3] () ERROR a.a.ActorSystemImpl - Outgoing response stream error
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at akka.http.impl.model.parser.IpAddressParsing$class.ip$minusnumber(IpAddressParsing.scala:21)
	at akka.http.impl.model.parser.UriParser.ip$minusnumber(UriParser.scala:21)
	at akka.http.impl.model.parser.IpAddressParsing$class.ip$minusv4$minusaddress(IpAddressParsing.scala:13)
	at akka.http.impl.model.parser.UriParser.ip$minusv4$minusaddress(UriParser.scala:21)
	at akka.http.impl.model.parser.UriParser.ipv4Host(UriParser.scala:150)
	at akka.http.impl.model.parser.UriParser.host(UriParser.scala:135)
	at akka.http.impl.model.parser.UriParser.hostAndPort(UriParser.scala:131)
	at akka.http.impl.model.parser.UriParser.authority(UriParser.scala:125)
	at akka.http.impl.model.parser.UriParser.hier$minuspart(UriParser.scala:102)
	at akka.http.impl.model.parser.UriParser.absolute$minusURI(UriParser.scala:111)
	at akka.http.impl.model.parser.UriParser.request$minustarget(UriParser.scala:233)
	at akka.http.impl.model.parser.UriParser$$anonfun$7.apply(UriParser.scala:237)
	at akka.http.impl.model.parser.UriParser$$anonfun$7.apply(UriParser.scala:237)
	at akka.parboiled2.Parser.runRule$1(Parser.scala:143)
	at akka.parboiled2.Parser.phase0_initialRun$1(Parser.scala:151)
	at akka.parboiled2.Parser.__run(Parser.scala:204)
	at akka.http.impl.model.parser.UriParser.parseHttpRequestTarget(UriParser.scala:237)
	at akka.http.scaladsl.model.Uri$.parseHttpRequestTarget(Uri.scala:266)
	at akka.http.impl.engine.parsing.HttpRequest$anon$1.parseRequestTarget(HttpRequestParser.scala:139)
	at akka.http.impl.engine.parsing.HttpRequestParser$$anon$1.parseMessage(HttpRequestParser.scala:72)
	at akka.http.impl.engine.parsing.HttpMessageParser$class.startNewMessage(HttpMessageParser.scala:100)
	at akka.http.impl.engine.parsing.HttpRequestParser$$anon$1.startNewMessage(HttpRequestParser.scala:42)
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$3.apply(HttpMessageParser.scala:34)
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$3.apply(HttpMessageParser.scala:34)
	at akka.http.impl.engine.parsing.HttpMessageParser$class.run$1(HttpMessageParser.scala:64)
	at akka.http.impl.engine.parsing.HttpMessageParser$class.parseBytes(HttpMessageParser.scala:78)
	at akka.http.impl.engine.parsing.HttpRequestParser$$anon$1.parseBytes(HttpRequestParser.scala:42)
	at akka.http.impl.engine.parsing.HttpMessageParser$class.parseSessionBytes(HttpMessageParser.scala:60)
	at akka.http.impl.engine.parsing.HttpRequestParser$$anon$1.parseSessionBytes(HttpRequestParser.scala:42)
	at akka.http.impl.engine.parsing.HttpRequestParser$$anon$1.onPush(HttpRequestParser.scala:53)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:755)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:657)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:470)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:422)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:602)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:617)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:528)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

This appears to be trivially reproducible against any akka-http 2.4.9 server, so I've not included a test  case, but I'm happy to put one together if needs be.

**Comment by johanandren** [comment] 2016-08-24 10:55
Duplicate of #21243, already fixed!

**Closed** 2016-08-24 10:55 UTC
