### ISSUE TITLE
failed: ClusterClientSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#18440] opened 2015-09-10 06:26 UTC
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3637/consoleFull

Could be the same as #17735

**Comment by patriknw** [comment] 2015-09-16 13:17
this might be a duplicate of https://github.com/akka/akka/issues/18155

I'm running it in a repeat job with debug logging to be able to understand what is wrong

**Comment by ktoso** [comment] 2015-09-17 13:15
One more:

```
[Association failed with [akka.trttl.gremlin.tcp://ClusterClientSpec@a5.moxie:33345]] Caused by: [Connection refused: a5.moxie/10.0.1.235:33345]
[JVM-1] [WARN] [09/14/2015 00:20:14.425] [ClusterClientSpec-akka.actor.default-dispatcher-4] [akka://ClusterClientSpec/deadLetters] received dead letter from Actor[akka://ClusterClientSpec/user/client3#1249827410]: GetContacts
[JVM-1] - must re-establish connection to receptionist after partition *** FAILED ***
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.cluster.client.ClusterClientSpec$Reply
[JVM-1]   at scala.Predef$.assert(Predef.scala:165)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:435)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:417)
[JVM-1]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:735)
[JVM-1]   at akka.cluster.client.ClusterClientSpec$$anonfun$1$$anonfun$apply$mcV$sp$22$$anonfun$apply$mcV$sp$23$$anonfun$apply$mcV$sp$24$$anonfun$apply$mcV$sp$25.apply$mcV$sp(ClusterClientSpec.scala:249)
[JVM-1]   at akka.cluster.client.ClusterClientSpec$$anonfun$1$$anonfun$apply$mcV$sp$22$$anonfun$apply$mcV$sp$23$$anonfun$apply$mcV$sp$24$$anonfun$apply$mcV$sp$25.apply(ClusterClientSpec.scala:247)
[JVM-1]   at akka.cluster.client.ClusterClientSpec$$anonfun$1$$anonfun$apply$mcV$sp$22$$anonfun$apply$mcV$sp$23$$anonfun$apply$mcV$sp$24$$anonfun$apply$mcV$sp$25.apply(ClusterClientSpec.scala:247)
[JVM-1]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:266)
[JVM-1]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:277)
[JVM-1]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:735)
[JVM-1]   ...
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2893/consoleFull

**Comment by patriknw** [comment] 2015-09-17 14:35
yes, I'm debugging this

**Comment by patriknw** [comment] 2015-09-18 08:46
It was the same as #17735, I did not fix it correctly.

**Closed** 2015-09-18 15:09 UTC
Labels: failed, t:cluster-tools
