### ISSUE TITLE
FAILED akka.cluster.Stress

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21143] opened 2016-08-09 06:38 UTC
https://jenkins.akka.io:8498/job/akka-nightly/3582/consoleFull

```
[JVM-3] - must use many actors with high throughput *** FAILED *** (10 seconds, 139 milliseconds)
[JVM-3]   64 did not equal 0 (StressSpec.scala:1047)
[JVM-3]   org.scalatest.exceptions.TestFailedException:
[JVM-3]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-3]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply$mcV$sp(StressSpec.scala:1047)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1034)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1034)
[JVM-3]   at akka.cluster.StressSpec.reportResult(StressSpec.scala:948)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18.apply$mcV$sp(StressSpec.scala:1034)
...
```

**Comment by patriknw** [comment] 2016-08-09 07:58
Duplicate of https://github.com/akka/akka/issues/20223

**Closed by patriknw** 2016-08-09 07:58 UTC
Labels: failed
