### ISSUE TITLE
Failure: HubSpec

### ISSUE THREAD

**Issue by seglo** [akka/akka#30207] opened 2021-04-29 15:21 UTC
```
[0m[[0m[0minfo[0m] [0m[0m[31m- must immediately cancel new producers while draining *** FAILED *** (2 seconds, 60 milliseconds)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  List(11, 12, 13, 14, 15, 16, 17, 18, 19, 20) did not equal Range$Inclusive(1, 2, 3, 4, 5, 6, 7, 8, 9, 10) (HubSpec.scala:211)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  org.scalatest.exceptions.TestFailedException:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.stream.scaladsl.HubSpec.$anonfun$new$31(HubSpec.scala:211)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.stream.scaladsl.HubSpec.$anonfun$new$30(HubSpec.scala:202)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:33)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at scala.collection.immutable.List.foreach(List.scala:333)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at scala.collection.immutable.List.foreach(List.scala:333)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:54)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Suite.run(Suite.scala:1112)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Suite.run$(Suite.scala:1094)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.AkkaSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AkkaSpec.scala:54)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runImpl(Engine.scala:535)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:54)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.AkkaSpec.run(AkkaSpec.scala:54)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at java.util.concurrent.FutureTask.run(FutureTask.java:266)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at java.lang.Thread.run(Thread.java:748)[0m[0m
```

https://jenkins.akka.io:8498/job/akka-nightly-2.13/883/consoleText

**Comment by johanandren** [comment] 2021-05-03 06:55
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8717/testReport/junit/akka.stream.scaladsl/HubSpec/MergeHub_must_immediately_cancel_new_producers_while_draining/

**Comment by johanandren** [comment] 2021-05-03 06:57
@nivox if you'd have time to look at if this could be an actual bug (or if it is just a race condition in the test) in the new draining for mergehub you added that'd be great.

**Comment by nivox** [comment] 2021-05-03 07:23
@johanandren I had a quick look and it is pretty clear that the issue is just a poorly written test.

In my mind I wanted to create 2 different producers, start the draining and verify that new producers could not be attached at that point.

However I then verified that already existing producers where completely consumed by the MergeHub by doing 2 separate reads expecting to get the results in the order in which I added the producers, but this is obviously not guaranteed.

I'll try and prepare a pull request this afternoon which fixes the test.

By the way, looking at the test I now fear that there is another possible issue.
Given that in the end we decided to have the `drainAndComplete` method not give back any feedback (i.e. a Future indicating whether the draining has started), it seems to me that the third producer could get attached before the MergeHub had a chance to handle the `AsyncCallback` telling it to start the draining.

Given that we do not have any feedback mechanism, the only way that I can think of to lower this possibility is to add a delay between the `drainAndComplete` call and the materialization of the third producer. 
Do you have any suggestions on how to handle this better?

**Comment by johanandren** [comment] 2021-05-03 08:07
If it is tested with probes instead of sinks and sources, I think you could consistently observe draining starting for one upstream and then "stall" the draining with a second upstream that observes a pull/demand but does not emit anything (if I remember it right that it does wait for an outstanding push before canceling an upstream)

**Comment by octonato** [comment] 2021-05-03 09:44
@nivox, do you plan to work on this? I will assign it to you, but feel free to remove yourself if that's not the case.

**Comment by nivox** [comment] 2021-05-03 09:48
Yes, I plan to prepare a PR sometime today... 
it's my mess so it seems only reasonable I go back and fix it :sweat_smile:

**Closed** 2021-05-14 14:15 UTC
Labels: failed, t:stream
