### ISSUE TITLE
StreamRef doesn't complete stream in v2.5.20

### ISSUE THREAD

**Issue by aschen77** [akka/akka#26348] opened 2019-02-07 16:56 UTC
I'm using a remote SinkRef to stream data between two nodes. When the stream is completed upstream, I see the log message on the SinkRef originator `The remote stream has completed, completing as well...`. However, the stream never ends up completing. I'm connecting the SinkRef to a Sink.seq and the future never returns. This issue happens intermittently so it may be a race condition. When using v2.5.19 I don't observe this behavior so it seems to be a regression in v2.5.20.

**Comment by patriknw** [comment] 2019-02-07 17:00
Thanks for reporting. It's a duplicate of https://github.com/akka/akka/issues/26326 and a fix is in progress. This might be serious enough that you have to revert to 2.5.19 until we have released 2.5.21. Sorry for the inconvenience.

**Closed by patriknw** 2019-02-07 17:00 UTC
