### ISSUE TITLE
Failed: StressSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23370] opened 2017-07-17 07:23 UTC
On the multi-dc repeat job:

https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14097/

```
[JVM-3] - must use routers with normal throughput (on node 'node-3', class akka.cluster.StressMultiJvmNode11) *** FAILED *** (30 seconds, 54 milliseconds)
[JVM-3]   8 did not equal 0 (StressSpec.scala:1029)
[JVM-3]   org.scalatest.exceptions.TestFailedException:
[JVM-3]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-3]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply$mcV$sp(StressSpec.scala:1029)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1016)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1016)
```

**Comment by johanandren** [comment] 2017-07-18 20:21
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14151/

**Comment by johanandren** [comment] 2017-07-20 06:40
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14176/

**Comment by patriknw** [comment] 2017-08-15 14:25
This is failing on other branches also, and I don't think it's related to multi-dc.

One interesting thing in the log is the "trying to remove non-child" before the deadLetters. Noticed also in some of the other failing logs, but not in successful runs. Might be something with remote deployment?

**Comment by jrudolph** [comment] 2017-08-21 08:22
Probably a duplicate of https://github.com/akka/akka/issues/20223 and #21810.

**Comment by johanandren** [comment] 2017-10-30 09:07
Ups. And #23511 as well

**Comment by chbatey** [comment] 2017-11-14 12:00
Closing and keeping #23511 open

**Closed by chbatey** 2017-11-14 12:00 UTC
Labels: 1 - triaged, failed, t:cluster
