### ISSUE TITLE
Asynchronous stage error handling

### ISSUE THREAD

**Issue by mtarzi** [akka/akka#24574] opened 2018-02-20 12:49 UTC
When using a Sink.foldAsync or Sink.mapAsync, if the next streamed element fails then the stream fails whithout waiting for the current element async processing to finish.
The version used to test are: 
- scala version: 1.12.4
- akka stream version: 2.5.9

Find below an example code to replicate the issue:
gist link : [https://gist.github.com/mtarzi/96774990dadabaac60a43a8137101691](https://gist.github.com/mtarzi/96774990dadabaac60a43a8137101691)

**Comment by ktoso** [comment] 2018-02-20 13:17
That's because that's the semantics set by reactive streams. Errors "overtake" values.
Changing that behaviour in Akka could be thought about, but not made lightly -- what if the error caused the thing completing the futures to stop, and all the other futures will now never complete (hanging zombie stream happens) and other questions arise then.

If you just want to drop such element you can:

```
   * If the function `f` throws an exception or if the `CompletionStage` is completed
   * with failure and the supervision decision is [[akka.stream.Supervision#stop]]
   * the stream will be completed with failure.
   *
   * If the function `f` throws an exception or if the `CompletionStage` is completed
   * with failure and the supervision decision is [[akka.stream.Supervision#resume]] or
   * [[akka.stream.Supervision#restart]] the element is dropped and the stream continues.
```

**Comment by Menelgil** [comment] 2018-02-20 13:56
Hi, coworker here to try to further explain our issue.

The issue here is that it's not the processing of an element that fails and cause the stream to collapse. That would be perfectly reasonable.

The issue is that while the Nth element is being asynchronously processed in foldAsync, the element N+1 is pulled from the source but that element causes an error and the source fails.
We would expect the error to make the stream complete with failure but only after the Nth element processing has been completed.
Here the stream completes while the Nth element processing is still running.

**Comment by johanandren** [comment] 2018-02-20 15:10
In general you can expect stream failures to propagate as fast as possible, regardless if stages are doing asynchronous work on on the side. If you want to have the downstream complete what it does etc. you can use `recoverWithRetries` and provide `Source.empty` as recovered stream.

**Comment by johanandren** [comment] 2018-06-12 12:47
Closing this since it should be solvable with `recover` and friends, and hasn't seen more discussion since February.

**Closed by johanandren** 2018-06-12 12:47 UTC
