### ISSUE TITLE
akka.discovery.ServiceDiscovery$DiscoveryTimeoutException: Dns resolve did not respond within 5.000 s

### ISSUE THREAD

**Issue by shanmukha511** [akka/akka#28948] opened 2020-04-20 09:42 UTC
Hi Team,

Getting below error 
"akka.discovery.ServiceDiscovery$DiscoveryTimeoutException: Dns resolve did not respond within 5.000 s"
Has anyone encountered the above error?
How to fix it?

**Comment by johanandren** [comment] 2020-04-20 18:16
Could be infrastructure related (dns not responding), I think we've seen some Linux bug giving DNS timeouts when doing both IPv4 and IPv6 lookups concurrently as well. One think to try could be the async-dns provider: https://doc.akka.io/docs/akka/current/io-dns.html#dns-extension

**Comment by shanmukha511** [comment] 2020-04-21 05:21
yes we are using async dns still we are getting the error.Can you pls let me know wt is the bug?
Do we have any issue on that?

**Comment by johanandren** [comment] 2020-04-21 07:03
We don't have an issue since it was outside of Akka and I don't remember quite what circumstances the Linux issue was, some specific glibc version perhaps. I think there was also some cases where some specific forwarding DNS server did not respond (can't remember the details of either, could have been dnsmasq on OpenShift with very long srv records).

**Comment by johanandren** [comment] 2020-04-21 07:12
Investigate it further I the async-dns impl should be generous with details in the debug logs so enable those and see if that gives you any clue.

**Comment by raboof** [comment] 2020-04-21 10:33
In the duplicate ticket at https://github.com/akka/akka-management/issues/660 it was shared that this was on Alpine linux. Indeed I seem to remember having seen issues with Alpine/musl, the JDK and DNS - though it would be good to record the specifics of which versions/combinations are problematic. I'm not sure if async-dns should also be affected by that?

Could be related to https://github.com/gliderlabs/docker-alpine/issues/476 ?

**Comment by shanmukha511** [comment] 2020-04-21 17:59
sure will have a look

**Comment by johanandren** [comment] 2020-05-25 11:06
Did you figure out some further information showing that this was in fact a bug in Akka @shanmukha511 or can we close this ticket?

**Comment by smrobinson** [comment] 2020-05-29 00:12
I work as a developer in the same organization where @shanmukha511 is part of the operations team. We thought we had eliminated this issue by updating our Docker image to use AdoptOpenJDK11-Alpine rather than a JDK8. We had not seen this error in over a month after updating our services that use Akka Discovery but it happened again yesterday.

This is the full stacktrace:
```
akka.discovery.ServiceDiscovery$DiscoveryTimeoutException: Dns resolve did not respond within 5.000 s
	at akka.discovery.dns.DnsServiceDiscovery$$anonfun$convertToTimeout$1.applyOrElse(DnsServiceDiscovery.scala:152)
	at akka.discovery.dns.DnsServiceDiscovery$$anonfun$convertToTimeout$1.applyOrElse(DnsServiceDiscovery.scala:149)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
For reference, this is a excerpt from the Akka HTTP service's build info:
```
"allDependencies" : [
    "org.scala-lang:scala-compiler:2.12.10:scala-tool->default,optional(default)",
    "org.scala-lang:scala-library:2.12.10:scala-tool->default,optional(default)",
    "org.scala-lang:scala-library:2.12.10",
    "com.typesafe.akka:akka-actor:2.6.4",
    "com.typesafe.akka:akka-testkit:2.6.4:test",
    "com.typesafe.akka:akka-multi-node-testkit:2.6.4:test",
    "com.lightbend.akka.discovery:akka-discovery-kubernetes-api:1.0.3",
    "com.typesafe.akka:akka-http:10.1.12",
    "com.typesafe.akka:akka-http-spray-json:10.1.12",
    "com.typesafe.akka:akka-http-testkit:10.1.12:test",
    "com.typesafe.akka:akka-discovery:2.6.1",
    "com.typesafe.akka:akka-stream:2.6.4",
    "com.typesafe.akka:akka-stream-kafka:2.0.3",
    "commons-codec:commons-codec:1.11",
    "com.arangodb:arangodb-java-driver:4.3.4",
    "com.arangodb:velocypack-module-scala:1.0.2",
    "com.arangodb:velocypack-module-jdk8:1.0.2",
    "org.typelevel:cats-core:1.4.0",
    "org.typelevel:cats-kernel:1.4.0",
    "org.typelevel:cats-macros:1.4.0",
    "org.apache.kafka:kafka-clients:2.4.1",
    "com.lightbend.lagom:lagom-scaladsl-api:1.6.0",
    "com.lightbend.lagom:lagom-scaladsl-akka-discovery-service-locator:1.6.0",
    "com.lightbend.lagom:lagom-scaladsl-kafka-client:1.6.0",
    "com.typesafe.akka:akka-slf4j:2.6.4",
    "ch.qos.logback:logback-classic:1.2.3",
    "com.typesafe.scala-logging:scala-logging:3.9.2",
    "com.softwaremill.macwire:macros:2.3.3:provided",
    "com.softwaremill.macwire:macrosakka:2.3.3:provided",
    "com.softwaremill.macwire:util:2.3.3",
    "com.typesafe.play:play-json:2.8.1",
    "org.scalatest:scalatest:3.1.1:test",
    "com.spingo:op-rabbit-core:2.1.0",
    "com.spingo:op-rabbit-play-json:2.1.0",
    "com.spingo:op-rabbit-json4s:2.1.0",
    "com.spingo:op-rabbit-akka-stream:2.1.0"
]
```

**Comment by shanmukha511** [comment] 2020-06-08 14:39
Hi @johanandren 

The above is complete stacktrace which posted by @smrobinson.We are part of same org.

Still we are receiving the DNS timeout error now and then and we suspect the error may not because of alpine as we are running other pods with alpine as base images.

if we say the issue is because of alpine base image we should observe these error on other pods as well.

And second we cant say even its kubernetes dns issue as we don't see any error logs from DNS pods as well.

And one more thing that the DNS timeout error we see only on Akka related pods.

have team encountered any error before?

Is it any issue/bug from akka perspective?

**Comment by raboof** [comment] 2020-06-10 11:54
> Is it any issue/bug from akka perspective?

Right now we have too little information to consider this an actionable bug in Akka.

> if we say the issue is because of alpine base image we should observe these error on other pods as well.

It could still be a bug/incompatibility in Alpine, the JVM, or some other part of the stack that just isn't triggered in those other pods.

It would be great if we could track down this problem, but right now it's too early to conclude this is a problem in Akka. Even if this was a bug in Akka, this issue doesn't yet provide sufficient information to track it down and fix it.

Exactly what base image are you using? How are you building your docker image? Are you using sbt-native-packager? Which version? which packaging options?

**Comment by shanmukha511** [comment] 2020-06-12 05:45
Hi @raboof 

we are using openjdk which is installed on top of alpine.
 
**Are you using sbt-native-packager** -> Yes, it is built with the 'docker' packager in sbt native packager which is built-in to sbt.
**Which version** -> sbt 1.3.8
**How are you building your docker image** -> "sbt docker:publishLocal"
**Options**:
packageName in Docker := "<service name>",
dockerUpdateLatest := true,
dockerCommands ++= Seq(
  Cmd("USER", "root"),
),
dockerBaseImage := "***"

**Comment by raboof** [comment] 2020-06-12 12:33
> Can you provide an example project that shows the problem, so we can reproduce it?

I'm afraid we can't really help diagnose the issue without a small project with which we can reproduce the issue, sorry... I'll close this for now, but feel free to reopen when you can share a reproducer project.

**Closed by raboof** 2020-06-12 12:33 UTC
Labels: 0 - new
