### ISSUE TITLE
akka-protobuf-v3 isn't fully shaded

### ISSUE THREAD

**Issue by philipwhiuk** [akka/akka#31826] opened 2023-02-01 12:27 UTC
If you depend on akka and also use protobuf in your application (thus pulling in protobuf-java), then try to build an uber JAR de-duplication will fail

The reason for this is that, while the Protobuf code is shaded the proto-files themselves aren't shaded.

```
[error] /root/.ivy2/cache/com.typesafe.akka/akka-protobuf-v3_2.12/jars/akka-protobuf-v3_2.12-2.6.20.jar:google/protobuf/any.proto
[error] /root/.ivy2/cache/com.google.protobuf/protobuf-java/bundles/protobuf-java-3.20.0.jar:google/protobuf/any.proto
[error] deduplicate: different file contents found in the following:
[error] /root/.ivy2/cache/com.typesafe.akka/akka-protobuf-v3_2.12/jars/akka-protobuf-v3_2.12-2.6.20.jar:google/protobuf/descriptor.proto
[error] /root/.ivy2/cache/com.google.protobuf/protobuf-java/bundles/protobuf-java-3.20.0.jar:google/protobuf/descriptor.proto
[error] deduplicate: different file contents found in the following:
[error] /root/.ivy2/cache/com.typesafe.akka/akka-protobuf-v3_2.12/jars/akka-protobuf-v3_2.12-2.6.20.jar:google/protobuf/empty.proto
[error] /root/.ivy2/cache/com.google.protobuf/protobuf-java/bundles/protobuf-java-3.20.0.jar:google/protobuf/empty.proto
[error] deduplicate: different file contents found in the following:
[error] /root/.ivy2/cache/com.typesafe.akka/akka-protobuf-v3_2.12/jars/akka-protobuf-v3_2.12-2.6.20.jar:google/protobuf/struct.proto
[error] /root/.ivy2/cache/com.google.protobuf/protobuf-java/bundles/protobuf-java-3.20.0.jar:google/protobuf/struct.proto
```

(This is reproducible on 2.8.0-M4)

As a work-around assuming you don't actually have a runtime dependency on the proto files themselves you can probably safely do something like:
```
assemblyMergeStrategy in assembly ~= (old => {
  case x if x.endsWith(".proto") =>  MergeStrategy.discard  
  case x => old(x)
}
```

**Comment by patriknw** [comment] 2023-02-01 13:04
Thanks for reporting. It's a duplicate of https://github.com/akka/akka/issues/29456
Those are not used in runtime so the workaround you suggested should work fine.

**Closed by patriknw** 2023-02-01 13:04 UTC
