### ISSUE TITLE
ClusterRouterPoolActor adds Routee when full cluster shutdown is initiated

### ISSUE THREAD

**Issue by stmaute** [akka/akka#30329] opened 2021-06-15 14:04 UTC
After sending "Prepare-for-full-shutdown" to the Akka cluster via Akka Management endpoint we encountered 
that the ClusterRouterPoolActor is starting new routees. One new routee when receiving a MemberReadyForShutdown message and another one when MemberDowned message is received.
This is an unexpected behavior because the actual running routee is going to be stopped right after the full cluster shutdown was initiated and no other routees should be started at all.

Can you verify that my observations are correct and this is a bug?

**Comment by johanandren** [comment] 2021-06-21 11:34
Yep, looks like a bug, in `ClusterRouterConfig` there is a `case m: MemberEvent if isAvailable(m.member)` that is but should not trigger for the new:ish `MemberReadyForShutdown` event, I would not expect it for `MemberDowned` though because the `isAvailable` check verifies that the member in the message is up.

Would you be up for PR:ing a fix?

**Comment by stmaute** [comment] 2021-06-22 08:50
@johanandren Thanks for the reply.

Can you fix this and let me know when bug is resolved?

**Comment by johanandren** [comment] 2021-06-22 11:14
If you are a Lightbend customer, please run this through the support portal and we can prioritize it accordingly, if not, it will be fixed when there's time, like in any OSS project, or if you want a swift fix in that case please submit a PR with a fix.

**Comment by johanandren** [comment] 2021-07-02 09:09
Actually I missed out on the fact that the `isAvailable` does in fact check member status to be `Up` or `WeaklyUp` which means that nodes `ReadyForShutdown` and `PreparingForShutdown` will not end up calling `addMember` but rather `removeMember` in `ClusterRouterActor.clusterReceive`, I don't have a theory how this could work in any other way than the expected.

**Comment by johanandren** [comment] 2022-02-22 10:07
No theory about how it could happen and no reproducer, so leaving this for now.

**Comment by patriknw** [comment] 2022-03-10 13:28
I agree with Johan. This should be covered by the `isAvailable` method. Closing, unless you have any more evidence @stmaute

**Closed by patriknw** 2022-03-10 13:28 UTC
Labels: 1 - triaged, t:cluster, bug
