### ISSUE TITLE
calling "leave" before restarting node caused other nodes to shutdown actor system

### ISSUE THREAD

**Issue by elyrank** [akka/akka#18379] opened 2015-09-01 11:00 UTC
in order to avoid having an unreachable node on upgrade , we decided to do leave before stopping the node, and then restarting it.

when we did that (leave for the self address and not wait for the node to be removed) and then stopped the node,
we saw that other nodes of the cluster were shutting down.
we did not see any logs as to what triggered this shutdown.

**Comment by ktoso** [comment] 2015-09-01 11:01
Can you describe your setup a bit more? There's not much information about configuration here - are you using a downing strategy that may have caused this?

**Comment by elyrank** [comment] 2015-09-01 11:07
we are using akka 2.3.11
auto-down-unreachable-after = off
we are using zookeeper for the seed nodes
using akka cluster & sharding & persistence

seed-node-timeout = 20s
    failure-detector{
      threshold = 12.0
      acceptable-heartbeat-pause = 20s
      min-std-deviation = 1s
    }

anything else I can provide?

**Comment by hepin1989** [comment] 2015-09-01 11:25
@elyrank Ha,we just did that too,call the leave before we restart node.And I think there should need a webui for that op.For the other nodes shutdown,we have not noticed that,may be there are other settings which affected that or there is any other error?How about change to loglevel to debug and see is there any logging?Like you tail -f the logging on one of the nodes which before shutted down,and then redo it again, I think you may see some log.

**Comment by lutzh** [comment] 2015-09-01 14:58
@elyrank This may or may not be completely unrelated to your issue, but I'm wondering. You say
> we are using zookeeper for the seed nodes

Would you care to elaborate a bit on that? How do you use ZK, do you use an Akka Extension? Have you tested without ZK and seen the same phenomenon?

Thanks!

**Comment by elyrank** [comment] 2015-09-02 05:17
we have the following configuration:
implemented it as an Akka Extension
cluster {
    zookeeper{
              url  = "zoo1:2181,zoo2:2181,zoo3:2181"
              path = "/akka/cluster"
           }

it is mostly used to make sure there will not be a split brain
when starting up the whole cluster zookeeper will determine who will be the leader and the rest will join to that node.

when restarting just one node in the cluster - the zookeeper will tell that node to which node to join.

we decided to use zookeeper after having a lot of split brain issues
since it will only affect on which node to join - I doubt it is related to this issue, but then again - I have no idea what is the cause...

**Comment by patriknw** [comment] 2015-09-02 06:28
@elyrank shutdown of other nodes sounds very strange. I would be very interested in taking a look at the logs. Can you reproduce the issue?

**Comment by hepin1989** [comment] 2015-09-02 07:51
@lutzh we have SeedNodesProvider too,yeah,that prevent the split a bit.
@elyrank Just like @patriknw haven't encounter this too,very interesting.

**Comment by elyrank** [comment] 2015-09-02 08:13
we managed to reproduce it a few times in our QA env, but it is not entirely clear how this happens.
however - there was nothing in the log , just saw that shutdown started

**Comment by elyrank** [comment] 2015-09-02 11:00
another scenario for this problem:
1, stop 2 nodes
2. wait for both to be unreachable
3. down (in JMX) only one of them
4. start them both

result - the node that was up is terminated
we have implemented a cluster listener that shows the following log:

2015-09-02 13:38:10,676 WARN  Cluster Member detected as unreachable: Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Up) ClusterState: Leader: Some(akka.tcp://ActorSystem@node053.tlv.lpnet.com:2553), Members: [Member(address = akka.tcp://ActorSystem@node053.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node054.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Up)], SeenBy: [akka.tcp://ActorSystem@node053.testDomain.com:2555, akka.tcp://ActorSystem@node055.testDomain.com:2555, akka.tcp://ActorSystem@node054.tlv.lpnet.com:2553], Unreachable: Set(Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Up))  
2015-09-02 13:38:18,674 WARN  Cluster Member detected as unreachable: Member(address = akka.tcp://ActorSystem@node054.testDomain.com:2555, status = Up) ClusterState: Leader: Some(akka.tcp://ActorSystem@node053.tlv.lpnet.com:2553), Members: [Member(address = akka.tcp://ActorSystem@node053.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node054.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Up)], SeenBy: [akka.tcp://ActorSystem@node053.tlv.lpnet.com:2553], Unreachable: Set(Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node054.testDomain.com:2555, status = Up))  
2015-09-02 13:39:47,434 WARN  Cluster Member is Removed: Member(address = akka.tcp://ActorSystem@node053.testDomain.com:2555, status = Removed) ClusterState: Leader: Some(akka.tcp://ActorSystem@node053.tlv.lpnet.com:2553), Members: [Member(address = akka.tcp://ActorSystem@node053.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node054.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Up)], SeenBy: [akka.tcp://ActorSystem@node053.tlv.lpnet.com:2553], Unreachable: Set(Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node054.testDomain.com:2555, status = Up))  
2015-09-02 13:39:47,435 WARN  Cluster Member is Removed: Member(address = akka.tcp://ActorSystem@node054.testDomain.com:2555, status = Removed) ClusterState: Leader: Some(akka.tcp://ActorSystem@node053.tlv.lpnet.com:2553), Members: [Member(address = akka.tcp://ActorSystem@node053.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node054.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Up)], SeenBy: [akka.tcp://ActorSystem@node053.tlv.lpnet.com:2553], Unreachable: Set(Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node054.testDomain.com:2555, status = Up))  
2015-09-02 13:39:47,439 WARN  Cluster Member is Removed: Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Removed) ClusterState: Leader: Some(akka.tcp://ActorSystem@node053.tlv.lpnet.com:2553), Members: [Member(address = akka.tcp://ActorSystem@node053.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node054.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Up)], SeenBy: [akka.tcp://ActorSystem@node053.tlv.lpnet.com:2553], Unreachable: Set(Member(address = akka.tcp://ActorSystem@node055.testDomain.com:2555, status = Up), Member(address = akka.tcp://ActorSystem@node054.testDomain.com:2555, status = Up))  
2015-09-02 13:39:47,439 WARN  ClusterListener: unhandled message Terminate()

**Comment by patriknw** [comment] 2015-09-03 06:34
I have difficulties understanding how that would be possible. I cannot reproduce it with the [SimpleClusterApp](https://github.com/akka/akka/blob/v2.3.12/akka-samples/akka-sample-cluster-scala/src/main/scala/sample/cluster/simple/SimpleClusterApp.scala). Can you provide a small sample application that I can run to reproduce the issue?

**Comment by elyrank** [comment] 2015-09-04 08:18
currently I'm trying to see if it is related to zookeeper, we have tried to run with static seed nodes and currently it did not reproduce. I will continue to investigate it on Sunday.
but even if it does only reproduce with zookeeper I don't understand why it happens.
I only have a theory - when trying to connect, the zookeeper has a leader of a node that is currently in the cluster state of down, and when trying to join that node it sends member removed to all the nodes- which causes the actor system to shutdown

**Comment by elyrank** [comment] 2015-09-06 07:58
we couldn't reproduce the issue without zookeeper. so we are switching to work with static seed nodes, though we still don't exactly understand what happened when working with zookeeper for dynamic seed nodes list

**Comment by danny-lesnik** [comment] 2015-09-06 10:11
Unfortunately, I'm able to reproduce it with static seeds as well, sending leave command on leader and then restarting it, crashes another cluster node.

**Comment by elyrank** [comment] 2015-09-06 11:59
yes - it is actually still reproduced. 
some progress on this issue:

for some reason we don't see the akka log, but had some listener on error log that printed this:
Error(java.lang.AssertionError: assertion failed,LocalActorRefProvider(akka://ActorSystem),class akka.event.DummyClassForStringSources,guardian failed, shutting down system) 

I will try to find out why is the original log not printed and then see what is the source of this assertionError

my guess is that it is related to the fact that sharded actors were removed from the master node and while trying to load them on another node the assertion was called.

**Comment by danny-lesnik** [comment] 2015-09-07 11:20
When it happens we catch the following exception. 

java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:165) ~[scala-library-2.10.4.jar:na]
        at akka.remote.EndpointManager.akka$remote$EndpointManager$$createEndpoint(Remoting.scala:759) ~[akka-remote_2.10-2.3.9.jar:na]
        at akka.remote.EndpointManager.createAndRegisterEndpoint(Remoting.scala:665) ~[akka-remote_2.10-2.3.9.jar:na]
        at akka.remote.EndpointManager.handleInboundAssociation(Remoting.scala:644) ~[akka-remote_2.10-2.3.9.jar:na]
        at akka.remote.EndpointManager$$anonfun$handleStashedInbound$1.apply(Remoting.scala:424) ~[akka-remote_2.10-2.3.9.jar:na]
        at akka.remote.EndpointManager$$anonfun$handleStashedInbound$1.apply(Remoting.scala:424) ~[akka-remote_2.10-2.3.9.jar:na]
        at scala.collection.Iterator$class.foreach(Iterator.scala:727) ~[scala-library-2.10.4.jar:na]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) ~[scala-library-2.10.4.jar:na]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.10.4.jar:na]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[scala-library-2.10.4.jar:na]
        at akka.remote.EndpointManager.handleStashedInbound(Remoting.scala:424) ~[akka-remote_2.10-2.3.9.jar:na]
        at akka.remote.EndpointManager$$anonfun$1.applyOrElse(Remoting.scala:596) ~[akka-remote_2.10-2.3.9.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.10-2.3.11.jar:na]
        at akka.remote.EndpointManager.aroundReceive(Remoting.scala:394) ~[akka-remote_2.10-2.3.9.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.11.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.10-2.3.11.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.10-2.3.11.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.10-2.3.11.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.10-2.3.11.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.4.jar:na]

**Comment by patriknw** [comment] 2015-09-07 12:13
@danny-lesnik That problem was fixed in a later version, please try with Akka 2.3.13

@elyrank you are speaking about another assert, right? It would be great if you can track down where that happens. No stack trace?

**Comment by elyrank** [comment] 2015-09-07 14:00
@patriknw :   @danny-lesnik  and I work together so it is the same issue

**Comment by patriknw** [comment] 2015-09-07 14:18
ah, I missed that. Then update. That assert has been fixed.

**Comment by patriknw** [comment] 2015-09-07 14:20
Here is that issue by the way: https://github.com/akka/akka/issues/17213

**Comment by patriknw** [comment] 2015-09-09 07:11
@elyrank please let me know when you have verified, so we can close this issue

**Comment by drewhk** [comment] 2015-09-09 09:36
Weird, in your stack traces there is a mixture of 2.3.11 and 2.3.9 artifacts. That is no good. Please ensure that all of the Akka components of the same version, and the latest, 2.3.13. The issue @patriknw mentioned was fixed in 2.3.10 (your remoting version is 2.3.9 according to stacktrace).

**Comment by elyrank** [comment] 2015-09-09 09:45
we saw that, we also had Kamon-remote that was dependent on 2.3.9, we fixed that now. we are running tests to make sure it is not reproduced again.

**Comment by elyrank** [comment] 2015-09-17 09:02
using 2.3.13 - we can no longer reproduce this issue. it can be closed
thanks!

**Comment by patriknw** [comment] 2015-09-17 09:47
ok, thanks

**Closed** 2015-09-17 09:47 UTC
Labels: t:cluster
