### ISSUE TITLE
Docs or logic bug in Source.queue behavior

### ISSUE THREAD

**Issue by prettynatty** [akka/akka#21852] opened 2016-11-17 11:29 UTC
`Source.queue` doc says that if bufferSize is 0 the overflowStrategy does not matter.
At the same time `SourceQueue.offer` doc says:

> fails when stream is completed or you cannot call offer in this moment because of implementation rules
>   * (like for backpressure mode and full buffer you need to wait for last offer call Future completion)

Indeed, `offer` throws `IllegalStateException("You have to wait for previous offer to be resolved to send another request")` when called on `Source.queue` with zero buffer and `OverflowStrategy.backpressure`.

**Comment by patriknw** [comment] 2016-11-21 10:36
Sounds like inconsistencies in the documentation. Would you like to submit a pull request that is fixing this, @prettynatty ?

**Comment by hhimanshu** [comment] 2017-01-20 04:01
The pull request seem merged, why the issue is still open?

**Comment by johanandren** [comment] 2017-01-20 07:52
I think we just missed to close the ticket, thanks for noticing.

**Closed** 2017-01-20 07:52 UTC
Labels: 1 - triaged, community, t:stream
