### ISSUE TITLE
FAILED: akka.contrib.pattern.ClusterClient

### ISSUE THREAD

**Issue by 2m** [akka/akka#19320] opened 2015-12-31 08:34 UTC
https://jenkins.akka.io:8498/job/akka-release-2.3/226/consoleFull
https://jenkins.akka.io:8498/job/akka-release-2.3/227/consoleFull

```
[JVM-1] - must re-establish connection to receptionist after server restart *** FAILED ***
[JVM-1]   java.lang.AssertionError: assertion failed: expected bonjour4-ack, found bonjour3-ack
[JVM-1]   at scala.Predef$.assert(Predef.scala:179)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:339)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:324)
[JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[JVM-1]   at akka.contrib.pattern.ClusterClientSpec$$anonfun$1$$anonfun$apply$mcV$sp$26$$anonfun$apply$mcV$sp$27$$anonfun$apply$mcV$sp$28.apply$mcV$sp(ClusterClientSpec.scala:261)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
[JVM-1]   at akka.contrib.pattern.ClusterClientSpec$$anonfun$1$$anonfun$apply$mcV$sp$26$$anonfun$apply$mcV$sp$27.apply$mcV$sp(ClusterClientSpec.scala:253)
[JVM-1]   at akka.contrib.pattern.ClusterClientSpec$$anonfun$1$$anonfun$apply$mcV$sp$26$$anonfun$apply$mcV$sp$27.apply(ClusterClientSpec.scala:252)
[JVM-1]   at akka.contrib.pattern.ClusterClientSpec$$anonfun$1$$anonfun$apply$mcV$sp$26$$anonfun$apply$mcV$sp$27.apply(ClusterClientSpec.scala:252)
[JVM-1]   at akka.testkit.TestKitBase$class.within(TestKit.scala:296)
```

**Comment by patriknw** [comment] 2016-04-05 14:23
This is fixed. Duplicate of https://github.com/akka/akka/issues/18741

**Closed by patriknw** 2016-04-05 14:23 UTC
Labels: 1 - triaged, failed, t:cluster-tools
