### ISSUE TITLE
NPE with ClusterClient

### ISSUE THREAD

**Issue by polymorphic** [akka/akka#22290] opened 2017-02-10 21:28 UTC
I am observing lots of NPEs upon connecting the ClusterClient to an existing cluster. Here's the stack trace corresponding to the first NPE while attempting to connect the client to a 1-node cluster running at 127.0.0.1:2551:

[DEBUG] [02/10/2017 13:20:38.616] [d-agent-akka.remote.default-remote-dispatcher-22] [akka.serialization.Serialization(akka://d-agent)] Using serializer [akka.serialization.JavaSerializer] for message [akka.actor.Identify]
[INFO] [02/10/2017 13:20:38.720] [d-agent-akka.actor.default-dispatcher-21] [akka.tcp://d-agent@127.0.0.1:59507/user/$a] received cluster event ContactPointAdded(akka.tcp://d-system@127.0.0.1:2551/system/receptionist)
Disconnected from the target VM, address: '127.0.0.1:59504', transport: 'socket'
[ERROR] [02/10/2017 13:20:40.620] [d-agent-akka.actor.default-dispatcher-2] [akka://d-agent/user/$a/clusterClient] null
java.lang.NullPointerException
	at akka.cluster.client.ClusterClient$$anonfun$establishing$1.applyOrElse(ClusterClient.scala:382)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497)
	at akka.cluster.client.ClusterClient.aroundReceive(ClusterClient.scala:323)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I verified in the debugger and as odd as it may sound the receptionist is indeed null here:

      case ActorIdentity(_, Some(receptionist)) ⇒
        log.info("Connected to [{}]", receptionist.path)

I ran into this problem in an environment where the seed node (127.0.0.1:2551) was compiled with Scala 2.12.1 whilst the code using ClusterClient with 2.11.8. While it repros consistently with this configuration I haven't been able to repro it when the code running on both ends is compiled with 2.11.8. In all experiments I used Akka 2.4.17.

**Comment by jamesmulcahy** [comment] 2017-02-10 21:32
Perhaps related to #22004 ?

**Comment by polymorphic** [comment] 2017-02-10 22:13
Compiling both nodes with Scala 2.12.1 doesn't produce the error so this smells like a version interop problem.

**Comment by patriknw** [comment] 2017-02-10 22:21
yes, smells like a java serialization issue. I suspect `scala.Some`. You could try with 

```
enable-additional-serialization-bindings = on
```

but then that must be enabled on both sides.

**Comment by patriknw** [comment] 2017-02-10 22:22
the full property is

    akka.actor.enable-additional-serialization-bindings = on

**Comment by johanandren** [comment] 2017-02-13 09:52
Do we give any guarantees around wire compatibility between 2.12 and 2.11 though?

**Comment by ktoso** [comment] 2017-02-13 09:54
If java serialisation is used absolutely no. So `akka.actor.enable-additional-serialization-bindings = on` is recommended here anyway, or even better `akka.actor.enable-additional-serialization-bindings = on`

See http://akka.io/news/2017/02/10/akka-2.4.17-released.html

**Comment by patriknw** [comment] 2017-02-13 10:45
Let's investigate if it's because serialization of `scala.Some` broke (again) and then decide what to do about it.

**Comment by patriknw** [comment] 2017-02-13 12:29
Closing this as a duplicate of https://github.com/akka/akka/issues/22004
@polymorphic Thanks for reporting, please watch the other issue for progress.

**Closed by patriknw** 2017-02-13 12:29 UTC
