### ISSUE TITLE
FAILED: CompressionIntegrationSpec wrap around

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21965] opened 2016-12-07 14:53 UTC
https://jenkins.akka.io:8498/job/akka-release-2.4/2/testReport/akka.remote.artery.compress/CompressionIntegrationSpec/wrap_around/

```
dodaj opis
Error Message

104 did not equal 103
Stacktrace

      org.scalatest.exceptions.TestFailedException: 104 did not equal 103
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$23$$anonfun$apply$4.apply(CompressionIntegrationSpec.scala:302)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$23$$anonfun$apply$4.apply(CompressionIntegrationSpec.scala:292)
      at akka.testkit.TestKitBase$class.within(TestKit.scala:345)
      at akka.testkit.TestKit.within(TestKit.scala:814)
      at akka.testkit.TestKitBase$class.within(TestKit.scala:359)
      at akka.testkit.TestKit.within(TestKit.scala:814)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$23.apply(CompressionIntegrationSpec.scala:292)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$23.apply(CompressionIntegrationSpec.scala:285)
      at scala.collection.immutable.Range.foreach(Range.scala:160)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply$mcV$sp(CompressionIntegrationSpec.scala:285)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply(CompressionIntegrationSpec.scala:262)
      at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply(CompressionIntegrationSpec.scala:262)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at akka.remote.artery.ArteryMultiNodeSpec.withFixture(ArteryMultiNodeSpec.scala:79)
      at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
      at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
```

**Comment by drewhk** [comment] 2016-12-07 14:57
Argh. This is similar to the one I assumed to be fixed (the race).

**Comment by patriknw** [comment] 2016-12-07 15:25
we should probably look at all those when we move the compression to the decoder

**Comment by johanandren** [comment] 2016-12-14 08:11
https://jenkins.akka.io:8498/job/akka-release-2.4/13/consoleFull

**Comment by ktoso** [comment] 2016-12-16 11:47
Relates to the ownership ticket: https://github.com/akka/akka/issues/21475

**Comment by jrudolph** [comment] 2017-01-02 11:24
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/580

and

https://jenkins.akka.io:8498/job/akka-release-2.4/33

**Comment by jrudolph** [comment] 2017-01-02 11:24
https://jenkins.akka.io:8498/job/akka-release-2.4/39/

**Comment by drewhk** [comment] 2017-01-10 11:44
https://jenkins.akka.io:8498/job/akka-release-2.4/51/consoleFull

**Comment by patriknw** [comment] 2017-01-10 14:02
This can probably be closed together with https://github.com/akka/akka/pull/22047
At least it doesn't make sense to debug the old implementation.

**Comment by johanandren** [comment] 2017-01-30 22:37
https://jenkins.akka.io:8498/job/akka-multi-node/1927/console

**Comment by drewhk** [comment] 2017-02-13 14:24
https://jenkins.akka.io:8498/job/akka-release-2.4/89/consoleFull
https://jenkins.akka.io:8498/job/akka-release-2.4/90/consoleFull
https://jenkins.akka.io:8498/job/akka-release-2.4/91/consoleFull

**Comment by drewhk** [comment] 2017-02-14 13:56
I think the issue is only with the test, fix is in progress now.

**Closed** 2017-02-21 08:26 UTC
Labels: 3 - in progress, failed, t:remoting:artery, t:remoting:artery:compression
