### ISSUE TITLE
HTTP client not robust

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16795] opened 2015-02-09 08:24 UTC
client deadlocks after a few requests, see https://groups.google.com/d/msg/akka-user/Gp0TezTei94/x5py6rcY1RIJ

**Comment by sirthias** [comment] 2015-04-16 15:18
@luksow @CptnKirk I just tried to reproduce the issue based on the latest code and have so far failed.
Have you tried things again with 1.0-M4 release?

**Comment by luksow** [comment] 2015-04-16 16:37
@sirthias I've run extensive tests with both my demo & bigger app (M5) and it looks like this issue is fixed. Thanks!

**Comment by CptnKirk** [comment] 2015-04-16 17:13
I also see this as fixed in M4/5. Thanks!

-Jim

-- Sent from my mobile device

**Comment by rkuhn** [comment] 2015-04-16 18:25
Thanks for checking and reporting!

**Comment by sirthias** [comment] 2015-04-17 07:06
I'll still issue a PR against this ticket, since we've apparently been missing a test.

**Comment by rkuhn** [comment] 2015-04-17 07:23
Ah, I missed that aspect, reopening it then.

**Closed** 2015-04-21 08:28 UTC
Labels: 1 - triaged, t:http, t:http:client, t:http:core, t:http:next
