### ISSUE TITLE
Akka HTTP client resolves numeric address to hostnames when sending requests

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#17059] opened 2015-03-23 09:29 UTC
If I send an HTTP request with a numeric hostname like:

```
  def sendRequest(request: HttpRequest): Future[HttpResponse] = {
    val connection =
      Http().outgoingConnection(request.uri.authority.host.address(), request.uri.effectivePort)

    val request2 = request.withUri(request.uri.toRelative)

    Source.single(request2) via connection runWith Sink.head()
  }

  sendRequest(HttpRequest(uri = "http://127.0.0.1/"))
```

Then Akka HTTP resolves the address to a hostname before rending the request over the wire:

```
GET / HTTP/1.1

Host: www.smoothgesturesapp.com:80

User-Agent: akka-http/2.3.9
```

("smoothgesturesapp" is an address I have in my "hosts" file set to 127.0.0.1)

I think this is a bug, and the client should use the provided numeric address in this case, i.e.

```Host: 127.0.0.1:80```

**Comment by sirthias** [comment] 2015-03-23 11:14
Closing as duplicate of https://github.com/akka/akka/issues/16808.

/cc @jrudolph

**Closed by sirthias** 2015-03-23 11:14 UTC

**Comment by RichardBradley** [comment] 2015-03-23 11:45
Thanks.

In case it helps anyone else, I am currently working around this with code like:

```
  def sendRequest(request: HttpRequest): Future[HttpResponse] = {
    val connection =
      http.outgoingConnection(request.uri.authority.host.address(), request.uri.effectivePort)

    val source = Source.single(
      fixUri(
        fixHost(request)))

    source via connection runWith Sink.head()
  }

  // See https://github.com/akka/akka/issues/17057
  private def fixUri(request: HttpRequest): HttpRequest =
    request.withUri(request.uri.toRelative)

  // See https://github.com/akka/akka/issues/17059
  private def fixHost(request: HttpRequest): HttpRequest =
    request.header[Host] match {
      case Some(_) => request
      case None =>
        request.addHeader(
          Host(
            request.uri.authority.host.address(),
            request.uri.effectivePort))
    }
```
