### ISSUE TITLE
Throttle does not work when added to several flows.

### ISSUE THREAD

**Issue by jvieten** [akka/akka#19958] opened 2016-03-07 15:42 UTC
If I add a Flow.throttle to independent streams only the last works correctly.

The attached sample shows that most of the time only the last "Invoke Pipe 2" gets written to System.out
[ThrottleTest.txt](https://github.com/akka/akka/files/161563/ThrottleTest.txt)

Could be a duplicate of #19862 
(Maybe @drewhk can help)

**Comment by drewhk** [comment] 2016-03-07 15:51
It might be very well a duplicate. I cannot look at this right now though, but I triage it for now.

**Comment by drewhk** [comment] 2016-03-14 13:35
I will take a look at this, although I don't see anything that would prevent reusability.

**Comment by drewhk** [comment] 2016-03-31 12:25
Throttle is reusable, we cannot reproduce non-reusablilty. I close this for now. Please rerun your tests after the 2.4.3 release (scheduled tomorrow) because there were multiple issues fixed with throttle.

**Closed** 2016-05-09 18:17 UTC
Labels: obsolete – reopen if necessary, t:stream
