### ISSUE TITLE
SelectionHandler unhandled ChannelReadable message

### ISSUE THREAD

**Issue by mgutmanis** [akka/akka#29330] opened 2020-06-30 17:44 UTC
Once Akka version was upgraded from 2.5.30 to 2.6.4 following messages are constantly being logged.

`INFO a.a.LocalActorRef Message [akka.io.SelectionHandler$ChannelReadable$] to Actor[akka://app/system/IO-TCP/selectors/$b/209816#765382547] was unhandled. [9] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.`

Messages appears to have no effect on functionality, but logs are flooded with messages.

**Comment by johanandren** [comment] 2020-07-01 07:06
Thanks for letting us know, we have not seen this before. A reproducer or any more details how you are using akka io would be helpful. Is it through Akka HTTP or some other lib or do you do TCP connections directly from your own code?

**Comment by mgutmanis** [comment] 2020-07-02 12:10
I was not able to reproduce the issue or correlate with any other events in application that could indicate to an issue.
There is no direct TCP connections created. We are using Akka Http version 10.1.12, server and client part.

**Comment by jrudolph** [comment] 2021-01-13 09:43
There are not many states left in TcpConnection that don't handle `ChannelReadable`. AFACS, it's:

 * `waitingForRegistration`: No interests should be set, so that seems unlikely
 * `peerSentEOF`: Not sure how we would end up getting a `ChannelReadable` here. On the previous `ChannelReadable` we should have observed the end of stream and moved into `peerSentEOF`. Why would we get another `ChannelReadable`?
   * One (somewhat unlikely?) explanation could be that the user of the TCP connection (likely the TcpStages in akka-stream) send an early `ResumeReading`. In that case messages could end up being handled like this:
     * Channel becomes readable and selection handler disables read interest 
     * At the same time a new `ResumeReading` message is generated by the user (bug if true)
     * Previous `ChannelReadable` and `ResumeReading` race
     * `ResumeReading` is handled first in state `connected` and reenables interest
     * `ChannelReadable` moves state to `peerSentEOF`
     * Channel is instantly readable again because the stream is half-closed

**Comment by alewando** [comment] 2021-07-08 20:03
For what it's worth, we just starting using `akka-http` (via `alpakka`, as a client to AWS SQS) in our production environment and come across these occasionally. Like the OP, they don't seem to cause any problems directly, but there is lots of fault-tolerance throughout the whole system so maybe it's being handled elsewhere. We aren't getting "flooded" with them, however, (just one or two per day) but that may just be due to lower usage.

```
akka.actor.LocalActorRef - Message [akka.io.SelectionHandler$ChannelReadable$] to Actor[akka://sqs/system/IO-TCP/selectors/$a/26392#70108981] was unhandled. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'
```

**Comment by jypma** [comment] 2021-12-15 11:04
Just wanted to chime in that we're also getting these (very occasionally) under high load (using `akka-http` 10.1.11). There was one line in the log above that _may_ correlate to the unhandled message (then again, it also may be unrelated)
```
['2021-12-15 09:45:54,108 DEBUG a.s.i.i.TcpConnectionStage$TcpStreamLogic - [TcpConnectionStage$TcpStreamLogic(akka://main)] Closing connection from XXXXXX:443 because downstream cancelled stream without failure']
['2021-12-15 09:45:54,110 INFO  c.i.p.h.HttpClientLive - [] PUT https://YYYYYYYYYYY]
["2021-12-15 09:45:54,131 INFO  a.a.LocalActorRef - [akka://main/system/IO-TCP/selectors/$a/13] Message [akka.io.SelectionHandler$ChannelReadable$] to Actor[akka://main/system/IO-TCP/selectors/$a/13#240115499] was unhandled. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'."]
```

**Comment by nparekh127** [comment] 2022-02-25 08:48
any solution for this? I'm also facing the same exception.

**Comment by Captain1653** [comment] 2023-09-07 17:24
The PR was merged, but the issue is still open.

Should this issue be closed?

**Comment by patriknw** [comment] 2023-09-08 06:31
not fully clear if the PR solved everything

> It is not completely clear that this state is the culprit but since we do
not have any better idea, let's try this.

but let's close

**Closed by patriknw** 2023-09-08 06:31 UTC
Labels: 0 - new
