### ISSUE TITLE
`Connection: close` breaks streaming responses

### ISSUE THREAD

**Issue by zhxiaogg** [akka/akka#20236] opened 2016-04-05 12:24 UTC
Hi, below is the complete unit test I used, and it will success if I replace the request protocol from `HTTP 1.0` to `HTTP 1.1`.  See also https://groups.google.com/forum/#!topic/akka-user/wa5UIB95SWA with detail log.

```scala
// setup mock server
val json =
  """
    |{"result":true}
  """.stripMargin

val source = Source(ByteString(json) :: Nil)
val mockRoutes = path("test" / "proxy_chunked.do") {
  get {
    complete {
      HttpResponse(StatusCodes.OK, entity = HttpEntity(ContentTypes.`application/json`, source))
    }
  }
} ~ complete {
  HttpResponse(StatusCodes.NotFound)
}

val (_, host, port) = AkkaHttpTestUtils.temporaryServerHostnameAndPort()
val bindingFuture = Http().bindAndHandle(mockRoutes, host, port)

val request = HttpRequest(
  HttpMethods.GET,
  uri = s"http://${host}:${port}/test/proxy_chunked.do",
  protocol = HttpProtocols.`HTTP/1.0`
)

val futureByteString = Http().singleRequest(request).map { resp =>
  println("response returned")
  resp.entity.dataBytes
} flatMap { source =>
  source.runFold(ByteString.empty)((r, bs) => r ++ bs)
}
val byteString = Await.result(futureByteString, 10 seconds)
byteString.utf8String shouldEqual (json)
```

**Comment by viktorklang** [comment] 2016-04-05 12:34
Http 1.0 doesn't support transfer-encoding chunked?
http://www8.org/w8-papers/5c-protocols/key/key.html

**Comment by 2beaucoup** [comment] 2016-04-05 12:54
@viktorklang Looks like this isn't chunked but `CloseDelimited` i.e. the end of the entity is signaled by closing of the connection which seems to terminate the selector before the stream is materialized.
```
HttpResponse(200 OK,List(Server: akka-http/2.4-SNAPSHOT, Date: Tue, 05 Apr 2016 12:39:17 GMT, Connection: close),HttpEntity.CloseDelimited(application/json,Source(SourceShape(StreamUtils$$anon$2.out), CompositeModule [1451cc3d]
  Name: unnamed
  Modules:
    (unnamed) CompositeModule [44de6922]
      Name: unnamed
      Modules:
        (SubSource%28EntitySource%29) GraphStage(EntitySource) [6c8461f5]
        (unnamed) [15ce6519] copy of GraphStage(Collect) [0f6463b9]
        (limitable) [38c48c0e] copy of CompositeModule [7780c92a]
          Name: limitable
          Modules:
            (unnamed) GraphStage(unknown-operation) [11809c6e]
          Downstreams: 
          Upstreams: 
          MatValue: Ignore
      Downstreams: 
        SubSource.out -> Collect.in
        Collect.out -> unknown-operation.in
      Upstreams: 
        Collect.in -> SubSource.out
        unknown-operation.in -> Collect.out
      MatValue: Atomic(SubSource%28EntitySource%29[6c8461f5])
    (unnamed) [3dd54c4c] copy of GraphStage(akka.http.impl.util.StreamUtils$$anon$2@5055479a) [216d1304]
  Downstreams: 
    SubSource.out -> Collect.in
    Collect.out -> unknown-operation.in
    unknown-operation.out -> StreamUtils$$anon$2.in
  Upstreams: 
    Collect.in -> SubSource.out
    unknown-operation.in -> Collect.out
    StreamUtils$$anon$2.in -> unknown-operation.out
  MatValue: Atomic(akka.stream.impl.StreamLayout$CompositeModule[44de6922]))),HttpProtocol(HTTP/1.1))
```

**Comment by viktorklang** [comment] 2016-04-05 13:21
@2beaucoup I should've know better than to trust the title of the Issue… :)

If it is as you say, then I guess the problem is that the short-circuit is too eager and needs to wait for completion before tearing down the connection.

**Comment by zhxiaogg** [comment] 2016-04-05 13:29
@viktorklang I really shouldn't use the word chunked just because the streaming response entity. Sorry for that.

So, the reason why server returns a CloseDelimited response is because I send a HTTP 1.0 request, right? I can by pass this problem if I send all request with HTTP 1.1 protocol, can you confirm this?

**Comment by viktorklang** [comment] 2016-04-05 13:30
@zhxiaogg No worries, I was only joking :)

**Comment by 2beaucoup** [comment] 2016-04-05 13:41
@viktorklang please see my update above. The response is indeed chunked as a result of using the `Entity` constructor with `Source[ByteString]`. The response is HTTP/1.1 so chunking should be fine.

The problem is the connection closing and the failure also happens with HTTP 1.1 if an `Connection: close` is added to the response.

**Comment by viktorklang** [comment] 2016-04-06 14:58
@2beaucoup I'm surprised that there is no test which verifies this behavior.

**Comment by 2beaucoup** [comment] 2016-04-07 06:47
@viktorklang Me too! ;) I added one [here](https://github.com/2beaucoup/akka/commit/3f9841c2fa40a8d5d8e5a110f46c88df07515d93).

**Comment by 2beaucoup** [comment] 2016-04-07 07:53
Problem seems to be [this line](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala#L186) where the stage gets completed before the substream is completed.

/cc @sirthias

**Comment by sirthias** [comment] 2016-04-07 08:42
If the client signals only HTTP/1.0 capabilities the server is actually not allowed to respond with an HTTP/1.1 response.

> So, the reason why server returns a CloseDelimited response is because I send a HTTP 1.0 request, right?

Yes.

> I can by pass this problem if I send all request with HTTP 1.1 protocol, can you confirm this?

Yes.

**Comment by 2beaucoup** [comment] 2016-04-07 09:11
> If the client signals only HTTP/1.0 capabilities the server is actually not allowed to respond with an HTTP/1.1 response.

https://tools.ietf.org/html/rfc2145#section-2.3 suggests otherwise:

> An HTTP server SHOULD send a response version equal to the highest version for which the server is at least conditionally compliant, and whose major version is less than or equal to the one received in the request.

Question is: Should the server reply with `Transfer-Encoding: chunked` if the request was HTTP/1.0?

**Comment by viktorklang** [comment] 2016-04-07 09:17
@2beaucoup How could it? chunked belongs to the 1.1 spec, and a client communicating using 1.0 shouldn't be expected to understand a newer protocol specification.

**Comment by sirthias** [comment] 2016-04-07 09:18
Yes, true. My statement from before was misleading.
If the server receives an `HTTP/1.0` request it should signal its own capabilities but not present the client with a response that it must assume the client to not be able to properly interpret.
So the right approach would be to send a response with protocol marker `HTTP/1.1` but NOT use `Transfer-Encoding: chunked` (but rather close-after-response-end).

**Comment by 2beaucoup** [comment] 2016-04-07 09:18
>> I can by pass this problem if I send all request with HTTP 1.1 protocol, can you confirm this?

> Yes.

See the test case linked above. It doesn't work for HTTP 1.1 as well, when sent with `Connection: close` as the `PrepareResponse` stage seems to get completed before the chunk substream.

**Comment by sirthias** [comment] 2016-04-07 09:21
@2beaucoup Yes, there my be a problem in the current implementation. I was thinking about the what the right behavior should be.
It really is quite easy to misinterpret the protocol marker of an HTTP response. It does not qualify the response it is part of but rather the *capabilities of the server*. I forget about this myself all the same.

**Comment by 2beaucoup** [comment] 2016-04-07 09:23
> So the right approach would be to send a response with protocol marker HTTP/1.1 but NOT use Transfer-Encoding: chunked (but rather close-after-response-end).

Makes sense. I opened a new ticket.

**Comment by 2beaucoup** [comment] 2016-04-07 09:45
Sorry for leading the discussion in the wrong direction.

The issue here is solely that the response entity substream can't be consumed if `Conection: close` is set. (See my two comments from [above](https://github.com/akka/akka/issues/20236#issuecomment-206718858).)

**Comment by sirthias** [comment] 2016-04-07 10:15
@2beaucoup No prob at all. Thanks for digging through this!

**Comment by 2beaucoup** [comment] 2016-04-07 10:27
No prob @sirthias.

FTR: The problematic change seems to be https://github.com/akka/akka/commit/e3ee285574d17f5b401632760e6cbb3712c76669#diff-9d641a9b26bb92cd487f4e6c81832424R186.

**Closed** 2016-04-07 17:15 UTC
Labels: 3 - in progress, bug
