### ISSUE TITLE
UnexpectedDisconnectException using akka-http client against python flask server

### ISSUE THREAD

**Issue by yakticus** [akka/akka#21292] opened 2016-08-25 18:06 UTC
All the details including reproducing the error are here:
https://github.com/yakticus/akka-UnexpectedDisconnectException

**Comment by 2beaucoup** [comment] 2016-08-25 20:54
Duplicate of #20570?

**Comment by ktoso** [comment] 2016-08-26 03:26
Yeah it could be, not closing for now, let's use the reproducer to attempt a fix early next week

**Comment by drewhk** [comment] 2016-08-26 07:30
Yes, it looks like a duplicate to me. I opt for closing this one in favor of the other, otherwise it will become a mess to track things.

**Comment by ktoso** [comment] 2016-08-26 11:05
Okey, I'll post the reproducer by @yakticus  in the other ticket.

**Closed** 2016-08-26 11:05 UTC
Labels: 1 - triaged, 2 - pick next, bug, t:http, t:stream
