### ISSUE TITLE
FAILED: RemoteReDeploymentMediumSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18161] opened 2015-08-10 09:36 UTC
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/59/consoleFull

Split out from https://github.com/akka/akka/issues/18071

**Comment by patriknw** [comment] 2015-08-10 13:10
the problem:

    [JVM-2]   java.lang.RuntimeException: failure while attaching new conductor
    [JVM-2]   at akka.remote.testkit.MultiNodeSpec.attachConductor(MultiNodeSpec.scala:387)
    [JVM-2]   Cause: java.lang.RuntimeException: unexpected transition: Transition(Actor[akka://RemoteReDeploymentMultiJvmSpec/user/TestConductorClient#109524684],Connecting,Failed)
    [JVM-2]   at akka.remote.testconductor.Player$$anonfun$6$$anon$1$$anonfun$receive$1.applyOrElse(Player.scala:65)

due to ConnectionFailure

I have seen that a few times in various tests now. Very strange.

**Comment by drewhk** [comment] 2015-08-10 13:25
yep, I have seen various conductor hiccups before. We haven't touched that code for ages, so there is something else going on here.

**Comment by patriknw** [comment] 2015-09-09 11:32
Duplicate of #17317

**Closed** 2015-09-09 11:32 UTC
Labels: failed, t:remoting
