### ISSUE TITLE
Seednode crashes when a node within Tomcat 8.5 connects to it

### ISSUE THREAD

**Issue by nikiiv** [akka/akka#23874] opened 2017-10-30 16:32 UTC
Akka 2.5.6

application.conf
`
akka {
  actor {
    provider = "akka.cluster.ClusterActorRefProvider"
    serializers {
      java = "akka.serialization.JavaSerializer"
      proto = "akka.remote.serialization.ProtobufSerializer"
    }
  }

  remote {
    transport = "akka.remote.netty.NettyRemoteTransport"
    log-remote-lifecycle-events = off
    netty.tcp {
      hostname = "niki"
      port = 0
    }
  }

  cluster {
    seed-nodes = [
      "akka.tcp://SofiaDevelopment@niki:4007",
      "akka.tcp://SofiaDevelopment@niki:4008"
    ]
    auto-down-unreachable-after = 120s
  }

  extensions = ["akka.cluster.pubsub.DistributedPubSub"]

}
akka.cluster.metrics.enabled=off
akka.cluster.min-nr-of-members=1
akka.cluster.http.management.hostname = "niki"
akka.cluster.http.management.port = 19999

akka.cluster.pub-sub {
  name = geoDistributedPubSubMediator
  role = ""
  routing-logic = round-robin
  gossip-interval = 1s
  removed-time-to-live = 120s
  max-delta-elements = 3000

  use-dispatcher = ""
}
`

web.xml with listener that boots Akka in Tomcat 8.5.23
`
<?xml version="1.0" encoding="UTF-8"?>
<web-app id="WebApp_9" version="2.4"
	xmlns="http://java.sun.com/xml/ns/j2ee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd">
	<display-name>GeoWealth Platform</display-name>
 	<listener>
	    <listener-class>atomatron.worker.BaseListener</listener-class>
  	</listener>
	<welcome-file-list>
		<welcome-file>index.do</welcome-file>
		<welcome-file>index.htm</welcome-file>
	</welcome-file-list>
</web-app>
`
atomatron.worker.BaseListener code

`
package atomatron.worker;

import akka.actor.ActorSystem;
import akka.cluster.Cluster;
import com.geowealth.messaging.AkkaBooter;
import com.typesafe.config.Config;
import com.typesafe.config.ConfigFactory;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import java.io.File;

public class BaseListener  implements ServletContextListener {
	
	private static final Log log = LogFactory.getLog(BaseListener.class);
	AkkaBooter akka;

	
	@Override
	public void contextDestroyed(ServletContextEvent arg0) {
		
	}
	
	public void contextInitialized(ServletContextEvent arg0) {
		File file = new File("/Users/niki/ideaProjects/gwm-akka/application.conf");
		Config conf = ConfigFactory.parseFile(file);
		ActorSystem actorSystem = ActorSystem.create("SofiaDevelopment", conf);
		Cluster cluster = Cluster.get(actorSystem);
		log.info("Akka ActorSystem created");
	}
	

}`

I start one seed node that does nothing special just by passing the port 4007. 
if I connect to it with a Java app, all works fine, however if I connect from a Tomcat the seed node crashes with the Exception bellow..
Same code executed as a Java app connects to the cluster just fine..

`[ERROR] [10/30/2017 18:24:41.704] [SofiaDevelopment-akka.actor.default-dispatcher-2] [akka://SofiaDevelopment/system/cluster/core/daemon/heartbeatSender] DataCenter undefined, should not be possible
java.lang.IllegalStateException: DataCenter undefined, should not be possible
	at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
	at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
	at scala.Option.getOrElse(Option.scala:121)
	at akka.cluster.Member.dataCenter$lzycompute(Member.scala:28)
	at akka.cluster.Member.dataCenter(Member.scala:27)
	at akka.cluster.ClusterHeartbeatSender$$anonfun$3.apply(ClusterHeartbeat.scala:79)
	at akka.cluster.ClusterHeartbeatSender$$anonfun$3.apply(ClusterHeartbeat.scala:79)
	at akka.cluster.ClusterHeartbeatSender.addMember(ClusterHeartbeat.scala:139)
	at akka.cluster.ClusterHeartbeatSender$$anonfun$active$1.applyOrElse(ClusterHeartbeat.scala:124)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.cluster.ClusterHeartbeatSender.aroundReceive(ClusterHeartbeat.scala:69)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [10/30/2017 18:24:41.704] [SofiaDevelopment-akka.actor.default-dispatcher-4] [akka.tcp://SofiaDevelopment@niki:4007/system/cluster/core] Cluster node [akka.tcp://SofiaDevelopment@niki:4007] crashed, [DataCenter undefined, should not be possible] - shutting down...
java.lang.IllegalStateException: DataCenter undefined, should not be possible
	at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
	at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
	at scala.Option.getOrElse(Option.scala:121)
	at akka.cluster.Member.dataCenter$lzycompute(Member.scala:28)
	at akka.cluster.Member.dataCenter(Member.scala:27)
	at akka.cluster.MembershipState$$anonfun$dcReachabilityNoOutsideNodes$1.applyOrElse(MembershipState.scala:100)
	at akka.cluster.MembershipState$$anonfun$dcReachabilityNoOutsideNodes$1.applyOrElse(MembershipState.scala:100)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:141)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:140)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)
	at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)
	at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:154)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:271)
	at scala.collection.immutable.TreeSet.collect(TreeSet.scala:53)
	at akka.cluster.MembershipState.dcReachabilityNoOutsideNodes$lzycompute(MembershipState.scala:100)
	at akka.cluster.MembershipState.dcReachabilityNoOutsideNodes(MembershipState.scala:99)
	at akka.cluster.ClusterEvent$.diffUnreachable(ClusterEvent.scala:374)
	at akka.cluster.ClusterDomainEventPublisher.publishDiff(ClusterEvent.scala:603)
	at akka.cluster.ClusterDomainEventPublisher.publishChanges(ClusterEvent.scala:595)
	at akka.cluster.ClusterDomainEventPublisher$$anonfun$receive$1.applyOrElse(ClusterEvent.scala:536)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.cluster.ClusterDomainEventPublisher.aroundReceive(ClusterEvent.scala:511)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [10/30/2017 18:24:41.705] [SofiaDevelopment-akka.actor.default-dispatcher-4] [akka://SofiaDevelopment/system/cluster/core/publisher] DataCenter undefined, should not be possible
java.lang.IllegalStateException: DataCenter undefined, should not be possible
	at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
	at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
	at scala.Option.getOrElse(Option.scala:121)
	at akka.cluster.Member.dataCenter$lzycompute(Member.scala:28)
	at akka.cluster.Member.dataCenter(Member.scala:27)
	at akka.cluster.MembershipState$$anonfun$dcReachabilityNoOutsideNodes$1.applyOrElse(MembershipState.scala:100)
	at akka.cluster.MembershipState$$anonfun$dcReachabilityNoOutsideNodes$1.applyOrElse(MembershipState.scala:100)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:141)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:140)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)
	at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)
	at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:154)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:271)
	at scala.collection.immutable.TreeSet.collect(TreeSet.scala:53)
	at akka.cluster.MembershipState.dcReachabilityNoOutsideNodes$lzycompute(MembershipState.scala:100)
	at akka.cluster.MembershipState.dcReachabilityNoOutsideNodes(MembershipState.scala:99)
	at akka.cluster.ClusterEvent$.diffUnreachable(ClusterEvent.scala:374)
	at akka.cluster.ClusterDomainEventPublisher.publishDiff(ClusterEvent.scala:603)
	at akka.cluster.ClusterDomainEventPublisher.publishChanges(ClusterEvent.scala:595)
	at akka.cluster.ClusterDomainEventPublisher$$anonfun$receive$1.applyOrElse(ClusterEvent.scala:536)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.cluster.ClusterDomainEventPublisher.aroundReceive(ClusterEvent.scala:511)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[INFO] [10/30/2017 18:24:41.707] [SofiaDevelopment-akka.actor.default-dispatcher-19] [akka://SofiaDevelopment/user/actorListener] Member is Removed: Member(address = akka.tcp://SofiaDevelopment@niki:4007, status = Removed)
[ERROR] [10/30/2017 18:24:41.707] [SofiaDevelopment-akka.actor.default-dispatcher-23] [akka://SofiaDevelopment/user/actorListener] DataCenter undefined, should not be possible
java.lang.IllegalStateException: DataCenter undefined, should not be possible
	at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
	at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
	at scala.Option.getOrElse(Option.scala:121)
	at akka.cluster.Member.dataCenter$lzycompute(Member.scala:28)
	at akka.cluster.Member.dataCenter(Member.scala:27)
	at akka.cluster.Member.toString(Member.scala:39)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at akka.event.LoggingAdapter$class.format(Logging.scala:1299)
	at akka.event.BusLogging.format(Logging.scala:1678)
	at akka.event.LoggingAdapter$class.format1(Logging.scala:1282)
	at akka.event.LoggingAdapter$class.info(Logging.scala:1188)
	at akka.event.BusLogging.info(Logging.scala:1678)
	at com.geowealth.agent.AkkaClusterListener.lambda$2(AkkaClusterListener.java:65)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:132)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [10/30/2017 18:24:41.712] [SofiaDevelopment-akka.actor.default-dispatcher-2] [akka://SofiaDevelopment/system/cluster/core/publisher] DataCenter undefined, should not be possible
java.lang.IllegalStateException: DataCenter undefined, should not be possible
	at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
	at akka.cluster.Member$$anonfun$dataCenter$2.apply(Member.scala:28)
	at scala.Option.getOrElse(Option.scala:121)
	at akka.cluster.Member.dataCenter$lzycompute(Member.scala:28)
	at akka.cluster.Member.dataCenter(Member.scala:27)
	at akka.cluster.MembershipState$$anonfun$dcReachabilityNoOutsideNodes$1.applyOrElse(MembershipState.scala:100)
	at akka.cluster.MembershipState$$anonfun$dcReachabilityNoOutsideNodes$1.applyOrElse(MembershipState.scala:100)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:141)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:140)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)
	at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)
	at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:154)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:271)
	at scala.collection.immutable.TreeSet.collect(TreeSet.scala:53)
	at akka.cluster.MembershipState.dcReachabilityNoOutsideNodes$lzycompute(MembershipState.scala:100)
	at akka.cluster.MembershipState.dcReachabilityNoOutsideNodes(MembershipState.scala:99)
	at akka.cluster.ClusterEvent$.diffUnreachable(ClusterEvent.scala:373)
	at akka.cluster.ClusterDomainEventPublisher.publishDiff(ClusterEvent.scala:603)
	at akka.cluster.ClusterDomainEventPublisher.publishChanges(ClusterEvent.scala:595)
	at akka.cluster.ClusterDomainEventPublisher.postStop(ClusterEvent.scala:532)
	at akka.actor.Actor$class.aroundPostStop(Actor.scala:536)
	at akka.cluster.ClusterDomainEventPublisher.aroundPostStop(ClusterEvent.scala:511)
	at akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)
	at akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)
	at akka.actor.ActorCell.terminate(ActorCell.scala:370)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:468)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[INFO] [10/30/2017 18:24:41.713] [SofiaDevelopment-akka.actor.default-dispatcher-2] [akka://SofiaDevelopment/system/cluster/core/publisher] Message [akka.cluster.InternalClusterAction$Subscribe] without sender to Actor[akka://SofiaDevelopment/system/cluster/core/publisher#-120155830] was not delivered. [6] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [10/30/2017 18:24:41.714] [SofiaDevelopment-akka.actor.default-dispatcher-32] [akka.cluster.Cluster(akka://SofiaDevelopment)] Cluster Node [akka.tcp://SofiaDevelopment@niki:4007] - Shutting down...
[INFO] [10/30/2017 18:24:41.715] [SofiaDevelopment-akka.actor.default-dispatcher-32] [akka.cluster.Cluster(akka://SofiaDevelopment)] Cluster Node [akka.tcp://SofiaDevelopment@niki:4007] - Successfully shut down
[INFO] [10/30/2017 18:24:41.718] [SofiaDevelopment-akka.actor.default-dispatcher-23] [akka://SofiaDevelopment/user/actorListener] CLUSTER NAME IS SofiaDevelopment
[INFO] [10/30/2017 18:24:41.718] [SofiaDevelopment-akka.actor.default-dispatcher-23] [akka://SofiaDevelopment/system/cluster/core/daemon] Message [akka.cluster.InternalClusterAction$Subscribe] without sender to Actor[akka://SofiaDevelopment/system/cluster/core/daemon#-1203195857] was not delivered. [7] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [10/30/2017 18:24:41.727] [SofiaDevelopment-akka.remote.default-remote-dispatcher-15] [akka.tcp://SofiaDevelopment@niki:4007/system/remoting-terminator] Shutting down remote daemon.
[INFO] [10/30/2017 18:24:41.728] [SofiaDevelopment-akka.remote.default-remote-dispatcher-15] [akka.tcp://SofiaDevelopment@niki:4007/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [10/30/2017 18:24:41.777] [SofiaDevelopment-akka.remote.default-remote-dispatcher-38] [akka.tcp://SofiaDevelopment@niki:4007/system/remoting-terminator] Remoting shut down.
`

**Comment by raboof** [comment] 2017-10-30 16:42
Thanks for your question! Generally we try to use github issues just for bugs and features, and use the [mailinglist](https://groups.google.com/forum/#!forum/akka-user) and [gitter](gitter.im/akka/akka) for questions.

That said, could it be your seed node is running Akka 2.5.6 but the code in Tomcat that joins it is running an older version of Akka? Strictly speaking that isn't supported, though this particular error sounds like #23822 which should no longer be a problem in Akka 2.5.7. For the time being updating all nodes to the same version of Akka, or if that is not possible then downgrading the seed node to Akka 2.5.4, might be sufficient. Does that help?

**Comment by nikiiv** [comment] 2017-10-30 16:44
No.. Both are using the same version from the same pom.xml

**Comment by raboof** [comment] 2017-10-30 16:56
Interesting! Which version of Akka is that? Could you share your pom.xml? Is it possible to reproduce the problem using publically accessible code? Perhaps you could create a reproducer based on your own project or based on https://github.com/akka/akka-samples/tree/2.5/akka-sample-cluster-java ?

**Comment by nikiiv** [comment] 2017-10-30 17:23
2.5.4 seems to work OK.. Will try the next two versions as well//

**Comment by raboof** [comment] 2017-10-31 08:56
In fact there is no 2.5.5 and you saw the problem with 2.5.6, right? Still curious what exactly is going on...

**Comment by nikiiv** [comment] 2017-10-31 09:11
Weirdly today I cannot reproduce it with neither 2.5.6 or 2.5.4
My pom file is 
`
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>GW</groupId>
	<artifactId>Akka1</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>Akka1</name>
	<properties>
		<akka.version>2.5.6</akka.version>
		<scala.version>2.11.8</scala.version>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-actor_2.11</artifactId>
			<version>${akka.version}</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-cluster_2.11</artifactId>
			<version>${akka.version}</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-cluster-tools_2.11</artifactId>
			<version>${akka.version}</version>
		</dependency>

		<dependency>
			<groupId>com.lightbend.akka</groupId>
			<artifactId>akka-management-cluster-http_2.11</artifactId>
			<version>0.5</version>
		</dependency>


		<dependency>
			<groupId>org.scala-lang</groupId>
			<artifactId>scala-library</artifactId>
			<version>${scala.version}</version>
		</dependency>
		<dependency>
			<groupId>org.scala-lang</groupId>
			<artifactId>scala-compiler</artifactId>
			<version>${scala.version}</version>
		</dependency>
		<dependency>
			<groupId>org.scala-lang</groupId>
			<artifactId>scala-reflect</artifactId>
			<version>${scala.version}</version>
		</dependency>
		
		
		<dependency>
		  <groupId>junit</groupId>
		  <artifactId>junit</artifactId>
		  <version>4.12</version>
		</dependency>
		
		<dependency>
		    <groupId>org.fusesource</groupId>
		    <artifactId>sigar</artifactId>
		    <version>1.6.4</version>
		</dependency>
		
		<dependency>
		    <groupId>log4j</groupId>
		    <artifactId>log4j</artifactId>
	    	<version>1.2.17</version>
		</dependency>
		<dependency>
		    <groupId>javax.mail</groupId>
		    <artifactId>mail</artifactId>
		    <version>1.4</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.3</version>
		</dependency>
	</dependencies>
</project>
`

The tomcat webapp is just the web.xml and the Listener 
I upgraded to 2.5.6 weeks ago when akka-management-cluster-http_2.11 didn't work well with 2.5.4

**Comment by ktoso** [comment] 2017-10-31 09:12
2.5.5 sadly was "dead on arrival" and never announced; 2.5.6 should just work, so stick to that version :)

**Comment by ktoso** [comment] 2017-10-31 09:13
Seems like no problem after all, can we close this ticket?

**Comment by raboof** [comment] 2017-10-31 09:23
@nikiiv do I understand correctly that you did have the problem with 2.5.6 originally, but cannot reproduce it anymore now? If so, weird, but I guess let's close this issue ;).

**Comment by nikiiv** [comment] 2017-10-31 10:02
Yes, lets close it..

**Closed** 2017-10-31 10:04 UTC
