### ISSUE TITLE
Public API for safely publishing AsyncCallbacks/ActorRefs from GraphStage

### ISSUE THREAD

**Issue by eiennohito** [akka/akka#21741] opened 2016-10-27 18:30 UTC
History notes: the issue was named akka-stream GraphStage getAsyncCallback: events can be handled in different order.

I have a situation when events are sometimes handled in a different order than they were `invoke`d in 2.4.11. I don't think that's a correct behavior.

**Comment by eiennohito** [comment] 2016-10-28 03:18
Update: My bad. I was storing AsyncCallback in a Future and there was a race on Future.map depending on ordering. Hence the question: how to safely publish AsyncCallback to outside of a GraphStage.

There is a CallbackWrapper, but it is a private api and `private[akka]`.

**Comment by drewhk** [comment] 2016-10-31 10:55
@eiennohito yes, your request is basically a duplicate of #20503 as it is about the same pain point (exposing the AsyncCallback safely). I close this ticket for now, please check progress on that other one.

**Closed** 2016-10-31 10:55 UTC
