### ISSUE TITLE
Note in 2.4.2 docs outdated

### ISSUE THREAD

**Issue by matthewadams** [akka/akka#19942] opened 2016-03-02 20:58 UTC
The note at http://doc.akka.io/docs/akka/2.4.2/scala/stream/stream-io.html#Streaming_File_IO is outdated, since the doc is for Akka 2.4.2.  Here's the note text:

> Note
> Since the current version of Akka (2.3.x) needs to support JDK6, the currently provided File IO implementations are not able to utilise Asynchronous File IO operations, as these were introduced in JDK7 (and newer). Once Akka is free to require JDK8 (from 2.4.x) these implementations will be updated to make use of the new NIO APIs (i.e. AsynchronousFileChannel).

**Comment by ktoso** [comment] 2016-03-03 09:40
Thanks for reporting!

Duplicate of https://github.com/akka/akka/issues/19904 and resolved by https://github.com/akka/akka/pull/19907 :-)

**Comment by ktoso** [comment] 2016-03-09 16:23
This should have been closed after my comment

**Closed** 2016-03-09 16:23 UTC
Labels: t:docs
