### ISSUE TITLE
Discuss context propagation of FlowWithContext.statefulMapConcat

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#26341] opened 2019-02-06 15:34 UTC
Statefulness means that you want to carry over at least some bit of information about previous elements to one of the following elements. The currently implemented automatic context tracking however just ignores that fact. As @johanandren noted in https://github.com/akka/akka/pull/26312#issuecomment-459382336, for some usages the association seems somewhat wrong. In other cases, it might be just ok.

We could either remove that one from the XWithContext APIs or document our way out of it.

/cc @RayRoestenburg

**Comment by johanandren** [comment] 2019-02-07 12:10
Duplicate of #26330

**Closed by johanandren** 2019-02-07 12:10 UTC
Labels: 1 - triaged, discuss, t:docs, t:stream
