### ISSUE TITLE
Module.subModules is sometimes null during creation

### ISSUE THREAD

**Issue by jypma** [akka/akka#21369] opened 2016-09-05 12:45 UTC
I've not been able to reliably reproduce, but the following two NPE's have occurred when building/materializing a fairy complex graph from within an actor:

```
java.lang.NullPointerException
    at scala.collection.immutable.HashSet$HashTrieSet.iterator(HashSet.scala:965)
    at scala.collection.immutable.HashSet$HashTrieSet.iterator(HashSet.scala:517)
    at akka.stream.impl.fusing.Fusing$.akka$stream$impl$fusing$Fusing$$descend(Fusing.scala:366)
    at akka.stream.impl.fusing.Fusing$.doAggressive(Fusing.scala:44)
    at akka.stream.impl.fusing.Fusing$.aggressive(Fusing.scala:34)
    at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:144)
    at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:138)
    at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:351)
    at akka.stream.scaladsl.Source.runWith(Source.scala:81)
    at akka.stream.javadsl.Source.runWith(Source.scala:521)
    at com.tradeshift.reaktive.replication.DataCenterForwarder.lambda$2(DataCenterForwarder.java:117)
    at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
    at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
    at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
    at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:484)

```

and

```
java.lang.NullPointerException
    at scala.collection.immutable.HashSet.union(HashSet.scala:89)
    at scala.collection.immutable.HashSet.union(HashSet.scala:35)
    at akka.stream.impl.StreamLayout$Module$class.compose(StreamLayout.scala:282)
    at akka.stream.impl.StreamLayout$CompositeModule.compose(StreamLayout.scala:416)
    at akka.stream.impl.StreamLayout$Module$class.fuse(StreamLayout.scala:194)
    at akka.stream.impl.StreamLayout$CompositeModule.fuse(StreamLayout.scala:416)
    at akka.stream.scaladsl.Flow.toMat(Flow.scala:109)
    at akka.stream.scaladsl.Flow.to(Flow.scala:80)
    at akka.stream.javadsl.Flow.to(Flow.scala:149)
    at com.tradeshift.reaktive.replication.DataCenterForwarder.filteredDataCenterSink(DataCenterForwarder.java:188)
    at com.tradeshift.reaktive.replication.DataCenterForwarder.lambda$2(DataCenterForwarder.java:114)
    at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
    at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
    at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
    at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
```

Code that triggers the error is [here](https://github.com/Tradeshift/ts-reaktive/blob/949dc785c2e3ab34d75c152139de602d10f1ce08/ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/DataCenterForwarder.java).

**Comment by jrudolph** [comment] 2016-09-05 12:47
Does the example project has tests that one could run to try to trigger the conditions?

**Comment by jypma** [comment] 2016-09-05 12:49
Yes, `DataCenterForwarderSpec`. However, it only did it once for each of the stack traces for me, and I can't get it to fail any more... yes, with the exact same code...

**Comment by jrudolph** [comment] 2016-09-05 13:26
Thanks, this spec fails for me with

```
15:04:39,060 ERROR [c.t.r.r.DataCenterForwarder] akka://SharedActorSystemSpec/user/$a - A future created from this actor has failed
java.lang.IllegalStateException: Remote datacenter closed connection
	at com.tradeshift.reaktive.replication.DataCenterForwarder.filteredDataCenterSink(DataCenterForwarder.java:188)
	at com.tradeshift.reaktive.replication.DataCenterForwarder.lambda$new$1(DataCenterForwarder.java:114)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:47)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Is there something else needed to run the test?

**Comment by jypma** [comment] 2016-09-05 13:44
@jrudolph thanks a lot for looking in to it. The logged error is normal during tear-down of the test, so you can ignore the message. However, the version of the test in master actually has other concurrency problems that we're fixing right now, so you may have hit those. I suppose your console didn't log an akka NPE earlier?

If you really want to, you can run the one in https://github.com/Tradeshift/ts-reaktive/tree/marshal-streams instead (test should run fine there, although still with the above message); alternatively, feel free to park this ticket until the test itself runs :-).

**Comment by jrudolph** [comment] 2016-09-05 13:57
Ah, I see. I didn't actually want to work on it right now but just make sure that the reproducer works.

**Comment by jypma** [comment] 2016-09-05 14:46
Master branch on that repo should run now. That is, the test is now always green when I run it. So, it's not exactly a reproducer :-) but the closest thing we've got.

**Comment by drewhk** [comment] 2016-09-12 12:27
I am not sure how concurrency problems could be an issue here as the data structures involved here are immutable...

**Comment by drewhk** [comment] 2016-09-12 12:27
It looks like though some of the Module classes is not properly initialized and the field is not seen as non-null.

**Comment by drewhk** [comment] 2016-11-07 14:21
I close this as I have no clue how this can even happen. Please reopen if you have a reproducer.

**Closed by drewhk** 2016-11-07 14:21 UTC
Labels: 1 - triaged, bug, t:stream
