### ISSUE TITLE
Rename package `akka.typed` to `akka.typed.actor` as other things are also typed

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23675] opened 2017-09-21 06:23 UTC
Since we're going all in and all modules are getting typed API, we should rename `akka.typed.Actor` etc to `akka.typed.actor.Actor`, as repetetive as it sounds it is true that that "typed" is "typed actors", and "typed" will eventually be all of Akka, so this rename should be done before it's too late.

**Comment by patriknw** [comment] 2017-09-21 06:33
This is a duplicate of https://github.com/akka/akka/issues/23632

**Closed by patriknw** 2017-09-21 06:33 UTC
Labels: 1 - triaged, t:typed

**Comment by ktoso** [comment] 2017-09-21 06:36
Ah, missed that one, thanks
