### ISSUE TITLE
Improve package structure to put scala and java types on same level

### ISSUE THREAD

**Issue by sirthias** [akka/akka#17279] opened 2015-04-23 12:30 UTC
In the `akka-http-core` and `akka-http` modules the chosen solution for limiting code duplication is the "scala-side-extends-java-side" approach.

Thereby the current package structure doesn't put scala and java on the same level. For example, right now we have:

Scala | Java
----- | ----
akka.http.model.HttpEntity | akka.http.model.japi.HttpEntity
akka.http.model.headers.HttpChallenge | akka.http.model.japi.headers.HttpChallenge
akka.http.Http | akka.http.japi.Http

The proposal is to introduce two super packages `akka.http.scala` and `akka.http.java` under which we create identical sub-packages for all public types that have representations in both languages. So the above example would become:

Scala | Java
----- | ----
akka.http.scala.model.HttpEntity | akka.http.java.model.HttpEntity
akka.http.scala.model.headers.HttpChallenge | akka.http.java.model.headers.HttpChallenge
akka.http.scala.Http | akka.http.java.Http

Internal (implementation) types would only exist in their own side (mostly scala).

/cc @jrudolph

**Comment by rkuhn** [comment] 2015-04-23 16:42
Unfortunately the most directly understandable names—`scala` and `java`—are at the same time “forbidden”: having a package of that name will generate conflicts and surprising behavior, e.g. when users `import akka.http._`. This is why we went with `scaladsl` and `javadsl` in streams.

**Comment by jrudolph** [comment] 2015-04-23 17:19
Ah,yes, that's so easy to forget about.

**Comment by sirthias** [comment] 2015-04-23 19:08
@rkuhn Yes, of course. For stream the names `javadsl`/`scaladsl` make sense, but here things are not primarily DSLs. Maybe `javapi` and `scalapi` instead? :)

**Comment by rkuhn** [comment] 2015-04-23 19:10
We need names. Like Alice and Bob. Joe & Sam?

**Comment by sirthias** [comment] 2015-04-23 20:24
`jay` and `ess`?
`javapackagenamefactoryproviderimpl` and `scalaccompiling`?
`pinky` and `thebrain`?

I guess my favorites would be `japi` and `sapi`.

**Comment by rkuhn** [comment] 2015-04-23 20:54
At least at this late hour it seems to me that you interpret “DSL” more narrowly than necessary: the whole Akka HTTP library provides a language for talking HTTP, therefore I don’t see a good reason to deviate from the convention we use (or are going to use) in all other parts of Streams & HTTP.

Hence: `scaladsl` / `javadsl`

**Comment by sirthias** [comment] 2015-04-23 21:44
Ok, `scaladsl` / `javadsl` it shall be.

**Comment by hepin1989** [comment] 2015-04-24 02:38
in https://groups.google.com/forum/#!topic/play-framework-dev/OFCqXBgsYdI @jroper propose to choose
```
So here's a few requirements that we want to meet to solve the above:

1. A typical Play app will have either the Java API or the Scala API on the classpath, but not both.
2. Though, it will be possible to have both if you want to mix them.
3. The Scala and Java APIs should have their own namespace, with a logical naming strategy.
4. It should be straight forward to intercept Scala actions with Java filters and vice versa.
5. The APIs should not wrap each other (this would violate requirement 1 anyway), but may potentially wrap a lower level API.

So, here's our planned solution.  This is not set in stone, in fact I keep on changing my mind about some details every day:

The Scala API will be in the package play.sapi, while the Java API will be in the package play.japi.  This may be a little controversial, but we've ruled out a few other options that have been suggested:
* They can't use the same package name, as this would prevent mixing Scala and Java modules together.
* They can't use "scala" or "java", as this would cause problems, especially for Scala code, with relative imports.

sapi and japi are both concise names with a straight forward logical reason behind them, they are consistent with each other, and we also have a precedent of the Akka project using japi.
```

**Comment by jroper** [comment] 2015-04-24 02:58
If `sapi` and `japi` were chosen, this would be great for Play, since it will be possible for Play users to drop down to the lower level akka-http API, and this would make a consistent experience between the Play APIs and the Akka APIs.  I personally don't like including `dsl` in the name - it could be argued that every library api is a dsl, so should every package name ever created contain dsl in it?

DSL already has a conventional understand in the Scala ecosystem, you say dsl, people think operator rather than named methods and implicit conversions.  Of course, there's no hard line between a dsl and an api, but typically the interface has a syntax that's optimised for expressiveness rather than discoverability, to understand it you first need to learn it.

I think it's better to keep the name dsl for what people conventionally think of as a dsl rather than broaden it to include any api, that's likely to cause confusion in my opinion.

**Comment by rkuhn** [comment] 2015-04-24 05:40
Well, the problem is that the `japi` precedent is one of the very few sins that we committed and are very, very sorry about. We finally want to get rid of this term ;-) The concern that we have with this term has been voiced in the linked thread as well: `japi` sounds like many things (makes me always wonder which language that word is from), but `javaapi` is unmistakable. On a stylistic note we then decided that `javadsl` reads more nicely.

Another consideration is that we are releasing 1.0-RC1 today, so we will not change our existing `akka.stream` packages in any case, and to me it is non-obvious why one part of the API should be in `javadsl` while the other is in `japi`, because clearly most of it is a DSL in the classical sense. The boundary of what we consider Domain Specific is not clearly enough established to be able to expect users to intuitively know that starting an HTTP server is outside of this domain (as you claim—but I’m not certain if that is true).

**Comment by jrudolph** [comment] 2015-04-24 07:45
@rkuhn so, is that the final decision? 

What are we going to do with the internal implementation stuff? Should we put that in `akka.http.impl.util`, `akka.http.impl.server.engine`, etc.?

**Comment by sirthias** [comment] 2015-04-24 07:50
> What are we going to do with the internal implementation stuff? Should we put that in akka.http.impl.util, akka.http.impl.server.engine, etc.?

I'd vote for simply keeping it underneath the language package it is implemented in.
This way the internal implementation can be package private.
So, the `akka.http.scaladsl` package would have more sub-packages than `akka.http.javadsl`, because it also contains the internal impl, which would not be problem IMHO.

**Comment by sirthias** [comment] 2015-04-24 07:54
By the way: I'd like to get to this ticket ASAP (today) after these remaining PRs have been merged:

- #17266
- #17282
- #17283
- #17287

**Comment by jrudolph** [comment] 2015-04-24 07:58
Are we using package private classes that are not scoped `akka` or `http`? The advantage of putting stuff in `akka.http.impl` would be that API and implementation would be completely separated so that you could `import akka.http.scaladsl._` without getting internal stuff into scope which seems nice.

**Comment by rkuhn** [comment] 2015-04-24 08:23
@jrudolph good point, we also use `akka.stream.impl` for that purpose.

@sirthias two are closed, two cannot currently be merged

**Comment by sirthias** [comment] 2015-04-24 08:24
We still have a few `private[util]` and `private[server]` bits here and there.
But I guess you are right, the full separation of the internal into a dedicated package does have advantages probably justifying relaxation of everything to `private[http]`.

So we introduce `akka.http.impl` in addition to `akka.http.javadsl` and `akka.http.scaladsl`?
Or should it be `akka.http.internal`?

**Comment by rkuhn** [comment] 2015-04-24 08:29
We used `impl` now, so unless you have a strong opinion I’d vote for that.

**Comment by 2m** [comment] 2015-04-24 08:33
Please do this after https://github.com/akka/akka/pull/17238 is merged, because that PR touches some http-core files.

**Comment by sirthias** [comment] 2015-04-24 08:40
@2m Ok. If you are on it and #17238 will be merged soon I'll wait. (Johannes is currently rebasing his two remaining PRs so they can be merged first too.)

**Comment by jrudolph** [comment] 2015-04-24 08:49
`engine.server.ServerSettings` then needs to be moved to a place belonging to the API.

**Comment by sirthias** [comment] 2015-04-24 08:57
Just discussed things here once more with @jrudolph.
We'll move everything in the 11 modules that start with `akka-http-` into these new parent packages:

- `akka.http.impl`
- `akka.http.javadsl`
- `akka.http.scaladsl`

Additionally we'd like to rename some modules as well in order to more properly reflect the language structure:

Current | Becomes
--------|--------
`akka-http-core` | same
`akka-http` | `akka-http-scala`
`akka-http-java` | same
`akka-http-tests` | `akka-http-tests-scala`
`akka-http-java-tests` | `akka-http-tests-java`
`akka-http-java8-tests` | `akka-http-tests-java8`
`akka-http-marshallers` | `akka-http-marshallers-scala`
`akka-http-java-marshallers` | `akka-http-marshallers-java`
`akka-http-testkit` | `akka-http-testkit-scala`
`akka-http-java-testkit` | `akka-http-testkit-java`
`akka-http-parent` | same

**Comment by sirthias** [comment] 2015-04-24 08:58
I suppose the `-experimental` suffix is to be kept on all `akka-http-*` modules?

**Comment by rkuhn** [comment] 2015-04-24 09:12
Yes, looking good, and of course it stays experimental for a while.

**Comment by sirthias** [comment] 2015-04-24 09:19
Ok, great.
The benefit of renaming the `akka-http` module to `akka-http-scala` is also that we don't have overloading of term `akka-http` anymore.
From now on `akka-http` will refer to the whole thing (all `akka-http-*` modules) rather than also to one specific module.

**Comment by 2m** [comment] 2015-04-24 09:30
Stream TestKit (#17238) has been merged.

**Comment by sirthias** [comment] 2015-04-24 09:36
Ok, great. Only https://github.com/akka/akka/pull/17287 to go then.

**Comment by sirthias** [comment] 2015-04-24 09:45
Ok, all prior PRs merged. Starting the big shuffle now...

**Comment by patriknw** [comment] 2015-04-24 10:01
awesome

**Comment by sirthias** [comment] 2015-04-24 14:35
High-level scala side also done now. I had to temporarily deactivate one (not crucial) test due some yet unknown issue.

**Comment by jrudolph** [comment] 2015-04-24 15:58
The docs tests are still failing...

**Comment by sirthias** [comment] 2015-04-24 16:00
Yes, just realized.
I'll push a fix in a few minutes.

**Comment by sirthias** [comment] 2015-04-24 16:03
Ok, done. At least this was easy... :)

**Closed** 2015-04-28 10:37 UTC
Labels: t:http, t:http:client, t:http:core, t:http:java, t:http:next, t:http:server
