### ISSUE TITLE
document different Dispatcher use-cases

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16062] opened 2014-10-09 10:45 UTC
Currently we only list their properties, but a little more information as to when to use them (and when definitely not) would be helpful.

Example: PinnedDispatcher only useful for extremely timing-sensitive actors or those which use libraries that depend on running always on the same thread.

**Comment by 2m** [comment] 2015-10-08 12:43
Duplicate of #15773

**Closed by 2m** 2015-10-08 12:43 UTC
Labels: 1 - triaged, t:docs
