### ISSUE TITLE
Failed: ReliableDeliveryShardingSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30567] opened 2021-08-24 10:55 UTC
JDK 8, Scala 2.13 Nightly https://github.com/akka/akka/runs/3404384369

```
2021-08-23T22:29:31.4093056Z <-- [[34makka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec: ReliableDelivery with sharding must illustrate sharding usage with several producers[0m] End of log messages of test that [Failed(org.scalatest.exceptions.TestFailedException: Set("p1-2-entity-1", "p2-2-entity-1", "p1-2-entity-2", "p2-2-entity-2") did not equal HashSet("p1-2-entity-2", "p1-2-entity-1", "p2-2-entity-2", "p1-2-entity-0", "p2-2-entity-0", "p2-2-entity-1"))]
2021-08-23T22:29:31.4097116Z [0m[[0m[0minfo[0m] [0m[0m[31m- must illustrate sharding usage with several producers *** FAILED *** (4 seconds, 736 milliseconds)[0m[0m
2021-08-23T22:29:31.4099511Z [0m[[0m[0minfo[0m] [0m[0m[31m  Set("p1-2-entity-1", "p2-2-entity-1", "p1-2-entity-2", "p2-2-entity-2") did not equal HashSet("p1-2-entity-2", "p1-2-entity-1", "p2-2-entity-2", "p1-2-entity-0", "p2-2-entity-0", "p2-2-entity-1") (ReliableDeliveryShardingSpec.scala:161)[0m[0m
2021-08-23T22:29:31.4101908Z [0m[[0m[0minfo[0m] [0m[0m[31m  org.scalatest.exceptions.TestFailedException:[0m[0m
2021-08-23T22:29:31.4103952Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)[0m[0m
2021-08-23T22:29:31.4106121Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)[0m[0m
2021-08-23T22:29:31.4109326Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.$anonfun$new$6(ReliableDeliveryShardingSpec.scala:161)[0m[0m
2021-08-23T22:29:31.4111955Z [0m[[0m[0minfo[0m] [0m[0m[31m  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)[0m[0m
2021-08-23T22:29:31.4113444Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)[0m[0m
2021-08-23T22:29:31.4114745Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)[0m[0m
2021-08-23T22:29:31.4115979Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m[0m
2021-08-23T22:29:31.4117195Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m[0m
2021-08-23T22:29:31.4118572Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m[0m
2021-08-23T22:29:31.4120346Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)[0m[0m
2021-08-23T22:29:31.4122636Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:70)[0m[0m
2021-08-23T22:29:31.4125346Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:68)[0m[0m
2021-08-23T22:29:31.4128828Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.withFixture(ReliableDeliveryShardingSpec.scala:91)[0m[0m
2021-08-23T22:29:31.4132582Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)[0m[0m
2021-08-23T22:29:31.4134924Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)[0m[0m
2021-08-23T22:29:31.4136710Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)[0m[0m
2021-08-23T22:29:31.4138621Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)[0m[0m
2021-08-23T22:29:31.4140761Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)[0m[0m
2021-08-23T22:29:31.4144399Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.runTest(ReliableDeliveryShardingSpec.scala:91)[0m[0m
2021-08-23T22:29:31.4147655Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)[0m[0m
2021-08-23T22:29:31.4149555Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)[0m[0m
2021-08-23T22:29:31.4151229Z [0m[[0m[0minfo[0m] [0m[0m[31m  at scala.collection.immutable.List.foreach(List.scala:333)[0m[0m
2021-08-23T22:29:31.4153132Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)[0m[0m
2021-08-23T22:29:31.4154911Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)[0m[0m
2021-08-23T22:29:31.4156582Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)[0m[0m
2021-08-23T22:29:31.4158131Z [0m[[0m[0minfo[0m] [0m[0m[31m  at scala.collection.immutable.List.foreach(List.scala:333)[0m[0m
2021-08-23T22:29:31.4159836Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)[0m[0m
2021-08-23T22:29:31.4162004Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)[0m[0m
2021-08-23T22:29:31.4163716Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)[0m[0m
2021-08-23T22:29:31.4165659Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)[0m[0m
2021-08-23T22:29:31.4167875Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)[0m[0m
2021-08-23T22:29:31.4171087Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.runTests(ReliableDeliveryShardingSpec.scala:91)[0m[0m
```

**Comment by patriknw** [comment] 2021-09-06 06:00
https://github.com/akka/akka/runs/3519925916?check_suite_focus=true#step:5:34766

**Comment by patriknw** [comment] 2021-11-08 10:37
https://github.com/akka/akka/runs/4133358768?check_suite_focus=true#step:5:34295

**Comment by pvlugter** [comment] 2021-11-11 02:16
https://github.com/akka/akka/runs/4172433619?check_suite_focus=true#step:5:34251

**Comment by johanandren** [comment] 2021-11-18 11:19
https://github.com/akka/akka/runs/4245370219?check_suite_focus=true#step:5:34256

**Comment by patriknw** [comment] 2021-11-26 07:18
Marking this as bug since it could be a real issue, but will tag as GHExcludeTest

**Comment by patriknw** [comment] 2021-11-26 07:30
https://github.com/akka/akka/runs/4329062782?check_suite_focus=true#step:5:34311

**Comment by patriknw** [comment] 2021-11-26 07:31
https://github.com/akka/akka/runs/4306162313?check_suite_focus=true#step:5:34585

**Comment by raboof** [comment] 2022-02-22 10:20
> Different test failure, but on same Spec.
> 
> https://github.com/akka/akka/runs/3853922579?check_suite_focus=true#step:5:35076
> 
> ```
> [info] - must deliver unconfirmed if ShardingConsumerController is terminated *** FAILED *** (1 second, 620 milliseconds)
> ```

"must deliver unconfirmed if ShardingConsumerController is terminated" is tracked separately in #30664 .

Let's close this issue for now until we actually see it again in the "illustrate sharding usage with several producers" form, might be separate.

**Closed by raboof** 2022-02-22 10:20 UTC
Labels: failed, bug, t:cluster-sharding

**Comment by jrudolph** [comment] 2022-05-10 12:42
https://github.com/akka/akka/runs/6361613831?check_suite_focus=true#step:5:36208

```
[05-10 01:07:38.490] [info] - must illustrate sharding usage with several producers *** FAILED *** (4 seconds, 599 milliseconds)
[05-10 01:07:38.490] [info]   Set("p1-2-entity-1", "p2-2-entity-1", "p1-2-entity-2", "p2-2-entity-2") did not equal HashSet("p1-2-entity-2", "p1-2-entity-1", "p2-2-entity-2", "p1-2-entity-0", "p2-2-entity-0", "p2-2-entity-1") (ReliableDeliveryShardingSpec.scala:161)
[05-10 01:07:38.490] [info]   org.scalatest.exceptions.TestFailedException:
[05-10 01:07:38.490] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[05-10 01:07:38.490] [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[05-10 01:07:38.490] [info]   at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.$anonfun$new$6(ReliableDeliveryShardingSpec.scala:161)
```

**Comment by jrudolph** [comment] 2022-05-10 12:44
https://github.com/akka/akka/runs/6361613831?check_suite_focus=true#step:5:36208
