### ISSUE TITLE
Document that ActorRefBackpressureSinkStage sends onCompleteMessage sooner than last message is acked

### ISSUE THREAD

**Issue by tunkl** [akka/akka#21015] opened 2016-07-22 09:52 UTC
If actor is used as sink using ActorRefBackpressureSinkStage. There is a bug in order of messages send to actor. The onCompleteMessage is send to actor during the processing of message from stream. This happens without the acknowledged last message. See this source code to better understand:

```
object BugReport extends App with Logging

  import BugActor._

  implicit val system = ActorSystem("BugReport")
  implicit val blockingExecutionContext = system.dispatchers.lookup("blocking-dispatcher")
  implicit val materializer = ActorMaterializer(ActorMaterializerSettings(system), "bugReport-mat")

  val source = Source.single(1)

  val bugActor = Sink.actorRefWithAck(
    system.actorOf(BugActor.props(blockingExecutionContext).withDispatcher("blocking-dispatcher")),
    InitMessage,
    AckMessage,
    CompleteMessage
  )

  val runnableGraph = source.to(bugActor)
  runnableGraph.run()
}

object BugActor {

  def props(executionContext: ExecutionContext): Props = Props(new BugActor(executionContext))

  case object InitMessage
  case object AckMessage
  case object CompleteMessage
}

class BugActor(executionContext: ExecutionContext) extends Actor {
  import BugActor._

  override def receive: Receive = {
    case InitMessage => sender() ! AckMessage
    case CompleteMessage => {
      java.lang.System.out.println("Received complete message")
      context.stop(self)
    }
    case number: Int => {
      java.lang.System.out.println(s"Received number ${number}, starting to process...")
      val mySender = sender()
      Future {
        Thread.sleep(1000)
        java.lang.System.out.println(s"Number ${number}, processed...")
        mySender ! AckMessage
      }(executionContext)
    }
  }
}


```

Output of this code is:

```
Received number 1, starting to process...
Received complete message
Number 1, processed...
```

I would expect that onCompleteMessage would be send after the ack of last message.

**Comment by drewhk** [comment] 2016-07-22 11:08
No, this is not a bug. onCompleteMessage indicates that no more messages will arrive, which is exactly what happens here. I agree though that it is confusing, so this should be probably documented better.

**Comment by tunkl** [comment] 2016-07-22 11:22
But if it would behave like that. It would be easy to handle some closing jobs. This way you have to add some conditions to track this. And it is strange that this one message is not following rules that next message after ack.

**Comment by drewhk** [comment] 2016-07-22 11:39
Changing it would be a non-compatible change, so we can't really do that :( We could only do that if the current behavior would be considered broken, which is not, albeit I agree that the semantics you described would be maybe nicer.

**Comment by tunkl** [comment] 2016-07-22 11:51
But is it really not compatible? Maybe in matter of documentation, but I cannot imagine the bug this could raise. But I understand. Thanks

**Comment by drewhk** [comment] 2016-07-22 11:54
> But is it really not compatible? Maybe in matter of documentation, but I cannot imagine the bug this could raise.

It might not cause any bugs, but I rather be conservative with such changes.

**Comment by yufei-cai** [comment] 2018-01-08 16:10
I ran into this issue and would definitely appreciate a warning in the documentation of `Sink.actorRefWithAck` that the on-complete message might be sent without waiting for the last acknowledgement. Initially I thought `Sink.actorRefWithAck` did not work with remote actor references, but it was only because the delay of remote messaging caused the on-compete message to land on a behavior where it is not handled.

One reason to change the current `Sink.actorRefWithAck` is that it prevents the stream consumer (i. e., the actor whose reference is given to `Sink.actorRefWithAck` to implement a simple "acknowledge every stream element" logic. The simple stream consumer generates 1 dead letter per stream, namely the acknowledgement to the final stream element. It clogs up the dead letter logger so that real dead letters are not logged.

**Comment by nvollmar** [comment] 2021-11-25 12:49
Ran into the same issue. Now unfortunately the using actor needs to track wether the last message is still in processing.
Would be much nicer to use if the closing message would only be sent after the last message has been acked.

**Comment by johanandren** [comment] 2021-11-25 13:17
I agree, ack then complete sounds good (and I can't see that it would be breaking in any way). Please PR such a fix if you want.

**Closed** 2021-11-29 08:01 UTC
Labels: 1 - triaged, t:docs, t:stream
