### ISSUE TITLE
StageActor sees `Terminated` events with `sender == null`

### ISSUE THREAD

**Issue by sirthias** [akka/akka#24074] opened 2017-11-29 13:38 UTC
Consider the following, rather simple `GraphStage`:

```scala
class BackpressuredSourceActorStage[T](producer: ActorRef)
  extends GraphStage[SourceShape[T]] {
  
  private val out: Outlet[T]         = Outlet("Some.out")
  override val shape: SourceShape[T] = SourceShape(out)

  override def createLogic(inheritedAttributes: Attributes) =
    new GraphStageLogic(shape) with OutHandler {
      private[this] var stageActor: StageActor = _
  
      override def preStart(): Unit = {
        stageActor = getStageActor {
          case (sender, Terminated(`producer`)) =>
             require(sender ne null) // FAILS!!  
            
          case (sender, msg) =>
              ...
        }
        stageActor.watch(producer)
      }
  
      override def onPull(): Unit = ()
  
      setHandler(out, this)
    }
}
```

When the `stageActor` is watching another `Actor` and this watched `Actor` dies the `Terminated` event is delivered to the `stageActor` with a `null` sender, which appears to be a bug.

I'd expect the sender to be the same as for regular Actors, i.e. either the watched `ActorRef` or the dead letter mailbox (I don't remember which one is used in this case), but definitely not `null`.

/cc @drewhk

**Comment by johanandren** [comment] 2017-11-30 10:19
I think it's a bug, but it is so unlikely that anyone has problems with that I marked it as nice-to-have rather than `bug`

**Comment by drewhk** [comment] 2017-11-30 10:24
Um, well, null as sender is not nice in any case :)

**Comment by gosubpl** [comment] 2017-12-01 22:25
If you change https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorRef.scala#L723 to
`this.!(Terminated(actorRef)(existenceConfirmed = true, addressTerminated = false))(actorRef)`
the issue is fixed.

The change fails `FunctionRefSpec`, because now sender is not `null`, which was asserted in some tests. The fix is trivial, though.

**I would love to submit a PR, but before I do that, can please someone kindly confirm that this is not because there are reasons for the sender of `FunctionRef` death watch messages to be `null`?**

If this is an omission, then I need to say that the syntax of `!` invites it :)
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorRef.scala#L181

**Comment by gosubpl** [comment] 2017-12-01 22:35
In any case, there are some more places where `(sender)` is omitted, which results in it being defaulted to `null`.

**Closed** 2017-12-04 08:25 UTC
Labels: 1 - triaged, bug, nice-to-have (low-prio), t:stream
