### ISSUE TITLE
FlowFlatMapPrefixSpec: downstream failure is propagated via the materialized flow

### ISSUE THREAD

**Issue by raboof** [akka/akka#30469] opened 2021-08-04 11:24 UTC
https://github.com/akka/akka/pull/30451/checks?check_run_id=3240231313

```
downstream failure is propagated via the materialized flow *** FAILED *** (2 seconds, 13 milliseconds)
[info]   Some(Success(NotUsed)) was not empty (FlowFlatMapPrefixSpec.scala:426)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:402)
[info]   at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6783)
[info]   at org.scalatest.matchers.should.Matchers.should(Matchers.scala:6835)
[info]   at org.scalatest.matchers.should.Matchers.should$(Matchers.scala:1808)
[info]   at akka.testkit.AkkaSpec.should(AkkaSpec.scala:54)
[info]   at akka.stream.scaladsl.FlowFlatMapPrefixSpec.f$proxy20$1$$anonfun$1(FlowFlatMapPrefixSpec.scala:426)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.FlowFlatMapPrefixSpec.f$proxy20$2(FlowFlatMapPrefixSpec.scala:447)
[info]   at akka.stream.scaladsl.FlowFlatMapPrefixSpec.$init$$$anonfun$23$$anonfun$20$$anonfun$20(FlowFlatMapPrefixSpec.scala:447)
```

Seems like a legitimate failure: I don't see how the final `seq` could complete successfully when that stream should fail when processing `3` - much less already on line 426.

**Comment by ignasi35** [comment] 2021-08-05 15:58
Cloud be related to GHActions VS Jenkins  as I've seen it again in https://github.com/akka/akka/pull/30449/checks?check_run_id=3252611503#step:6:19223

**Comment by ignasi35** [comment] 2021-08-05 15:59
Hmm, same file, different test.

**Comment by raboof** [comment] 2021-08-05 16:00
> Cloud be related to GHActions VS Jenkins

Yes, this problem indeed shows up on GHA while it went unnoticed on Jenkins

**Comment by ignasi35** [comment] 2021-08-05 16:02
Possible duplicate of https://github.com/akka/akka/issues/28620#issuecomment-847098343

**Comment by raboof** [comment] 2021-08-06 07:49
When reading this stacktrace, be really careful about the line number: I previously thought the failure was on the line `suffixF.value should be(empty)`, which would be hard to explain, but looking closer I now think the failure was on the line `notUsedF.value should be(empty)` - which is an invalid assumption: `notUsedF.value` is resolved immediately when the substream is materialized, not when the substream completes, so it is entirely possible that it is non-empty already before expecting the subscription.

**Comment by ignasi35** [comment] 2021-08-06 18:07
Again in https://github.com/akka/akka/pull/30449/checks?check_run_id=3264635582#step:5:2456 (this time it's the same exact test).

**Comment by patriknw** [comment] 2021-08-12 06:36
```
[WARN] [08/11/2021 20:43:58.920] [FlowFlatMapPrefixSpec-akka.actor.default-dispatcher-7] [akka://FlowFlatMapPrefixSpec/user/StreamSupervisor*] received dead letter from Actor[akka://FlowFlatMapPrefixSpec/system/testProbe-2326#-1564739603]: GetChildren
16235
[INFO] [akkaDeadLetter][08/11/2021 20:43:58.920] [FlowFlatMapPrefixSpec-akka.actor.default-dispatcher-6] [akka://FlowFlatMapPrefixSpec/user/StreamSupervisor*] Message [akka.stream.impl.StreamSupervisor$GetChildren$] from Actor[akka://FlowFlatMapPrefixSpec/system/testProbe-2326#-1564739603] to Actor[akka://FlowFlatMapPrefixSpec/user/StreamSupervisor*] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://FlowFlatMapPrefixSpec/user/StreamSupervisor*] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
16236
--- Stream actors debug dump ---
16237
Stream is completed. No debug information is available
16238
[info] - must downstream failure is propagated via the materialized flow *** FAILED *** (2 seconds, 33 milliseconds)
16239
[info]   Some(Success(NotUsed)) was not empty (FlowFlatMapPrefixSpec.scala:426)
16240
[info]   org.scalatest.exceptions.TestFailedException:
16241
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
16242
[info]   at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6783)
16243
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6834)
16244
[info]   at akka.stream.scaladsl.FlowFlatMapPrefixSpec.$anonfun$new$85(FlowFlatMapPrefixSpec.scala:426)
16245
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
16246
[info]   at akka.stream.scaladsl.FlowFlatMapPrefixSpec.$anonfun$new$84(FlowFlatMapPrefixSpec.scala:407)
```

**Comment by patriknw** [comment] 2021-08-12 07:06
https://github.com/akka/akka/runs/3308519328?check_suite_focus=true#step:5:13379

**Comment by patriknw** [comment] 2021-08-13 08:39
https://github.com/akka/akka/runs/3319258651?check_suite_focus=true#step:5:13496

**Comment by patriknw** [comment] 2021-08-13 08:52
https://github.com/akka/akka/runs/3315690054?check_suite_focus=true#step:5:15657

**Closed** 2021-08-13 09:23 UTC
Labels: 2 - pick next, failed
