### ISSUE TITLE
JDK9: UdpIntegrationSpec - uses sun.io APIs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23403] opened 2017-07-24 08:30 UTC
```
Caused by: java.lang.IllegalAccessError: class akka.io.InetAddressDnsResolver (in unnamed module @0x5459139a) cannot access class sun.net.InetAddressCachePolicy (in module java.base) because module java.base does not export sun.net to unnamed module @0x5459139a
	at akka.io.InetAddressDnsResolver.getTtl(InetAddressDnsResolver.scala:20)
	at akka.io.InetAddressDnsResolver.<init>(InetAddressDnsResolver.scala:30)
	... 16 more
```

```
[info] - must be able to send several packet back and forth with binding *** FAILED *** (13 milliseconds)
[info]   java.lang.reflect.InaccessibleObjectException: Unable to make public void sun.nio.ch.DatagramSocketAdaptor.bind(java.net.SocketAddress) throws java.net.SocketException accessible: module java.base does not "exports sun.nio.ch" to unnamed module @6712c430
[info]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
[info]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
[info]   at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
[info]   at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
[info]   at scala.reflect.package$.ensureAccessible(package.scala:53)
[info]   at scala.runtime.ScalaRunTime$.ensureAccessible(ScalaRunTime.scala:140)
[info]   at akka.testkit.SocketUtil$.reflMethod$Method1(SocketUtil.scala:37)
[info]   at akka.testkit.SocketUtil$.$anonfun$temporaryServerAddresses$1(SocketUtil.scala:37)
[info]   at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:90)
[info]   at akka.testkit.SocketUtil$.temporaryServerAddresses(SocketUtil.scala:32)
[info]   at akka.io.UdpIntegrationSpec.$anonfun$new$4(UdpIntegrationSpec.scala:67)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
```

**Comment by jrudolph** [comment] 2017-07-24 08:52
I created another issue for the DNS thing here: https://github.com/akka/akka/issues/23404.

**Comment by jrudolph** [comment] 2017-07-24 08:57
I think we might see this one as a duplicate to 23400 because both are caused by Scala's structural types using reflection on the runtime types:

```scala
  private type GeneralSocket = {
    def bind(sa: SocketAddress): Unit
    def close(): Unit
    def getLocalPort(): Int
  }

      val serverSocket: GeneralSocket =
        if (udp) DatagramChannel.open().socket()
        else ServerSocketChannel.open().socket()

      serverSocket.bind(new InetSocketAddress(hostname, 0))
```

I wonder if that's something that could be fixed in the scala compiler?

**Comment by retronym** [comment] 2017-07-25 01:52
What build of Java 9 are you testing with? In the most recent builds, they turned some (all?) inaccessible reflection errors into warnings by default. A command line flag can escalate them to a hard error.

That said, to clean things up, it is very unfortunate that structural types fail to reflectively bind to that method when it could the public/exported method in the superclass instead. Java reflection doesn't make it that easy to navigate an overriden method (see https://stackoverflow.com/a/15302411/160378 for DIY implementation), so it isn't a straightforward thing for us to implement.

**Comment by retronym** [comment] 2017-07-25 01:59
`InaccessibleObjectException` is a newly declared exception from `setAccessible`, we might need to catch that in:

```scala
  def ensureAccessible[T <: jAccessibleObject](m: T): T = {
    if (!m.isAccessible) {
      try m setAccessible true
      catch { case _: SecurityException => } // does nothing
    }
    m
  }
```

**Comment by retronym** [comment] 2017-07-25 03:39
JDK9 has actually deprecated `isAccessible` and encourages use of the new method `canAccess`. That would return true as the method we're calling is public, and we wouldn't actually call `setAccessible`.

**Comment by johanandren** [comment] 2017-09-25 10:47
@ktoso was this the one you had a fix for?

**Comment by ktoso** [comment] 2017-09-25 11:11
No, I did CachePolicy for now, which is https://github.com/akka/akka/issues/23404 Please review

**Closed** 2017-09-26 06:44 UTC
Labels: 2 - pick next, 3 - in progress, failed, t:jdk9
