### ISSUE TITLE
NullPointerException with Flow join

### ISSUE THREAD

**Issue by JackyChan** [akka/akka#30138] opened 2021-03-20 17:41 UTC
It seems  that a bug with Flow.join operation. Try to run following code.

```
val f1 = Flow[Int].fold(0)(_+_)
val f2 = Flow[Int].fold(0)(_+_)
f1.join(f2).toString
```

Would output:

```
java.lang.NullPointerException
  akka.stream.Attributes$SourceLocation.locationName$lzycompute(Attributes.scala:319)
  akka.stream.Attributes$SourceLocation.locationName(Attributes.scala:311)
  akka.stream.Attributes$SourceLocation.toString(Attributes.scala:322)
  java.lang.String.valueOf(String.java:2994)
  java.lang.StringBuilder.append(StringBuilder.java:131)
  scala.collection.IterableOnceOps.addString(IterableOnce.scala:1191)
  scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1186)
  scala.collection.AbstractIterable.addString(Iterable.scala:920)
  scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1136)
  scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1134)
  scala.collection.AbstractIterable.mkString(Iterable.scala:920)
  scala.collection.Iterable.toString(Iterable.scala:76)
  scala.collection.Iterable.toString$(Iterable.scala:76)
  scala.collection.Seq.toString(Seq.scala:49)
  scala.collection.Seq.toString$(Seq.scala:49)
  scala.collection.AbstractSeq.toString(Seq.scala:1154)
  java.lang.String.valueOf(String.java:2994)
  java.lang.StringBuilder.append(StringBuilder.java:131)
  scala.collection.IterableOnceOps.addString(IterableOnce.scala:1191)
  scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1186)
  scala.collection.AbstractIterator.addString(Iterator.scala:1279)
  scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1136)
  scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1134)
  scala.collection.AbstractIterator.mkString(Iterator.scala:1279)
  scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:159)
  akka.stream.Attributes.toString(Attributes.scala:36)
  java.lang.String.valueOf(String.java:2994)
  java.lang.StringBuilder.append(StringBuilder.java:131)
  scala.collection.IterableOnceOps.addString(IterableOnce.scala:1191)
  scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1186)
  scala.collection.AbstractIterator.addString(Iterator.scala:1279)
  scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1136)
  scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1134)
  scala.collection.AbstractIterator.mkString(Iterator.scala:1279)
  scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:159)
  akka.stream.impl.PushAttributes.toString(TraversalBuilder.scala:178)
  java.lang.String.valueOf(String.java:2994)
  java.lang.StringBuilder.append(StringBuilder.java:131)
  scala.collection.IterableOnceOps.addString(IterableOnce.scala:1191)
  scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1186)
  scala.collection.AbstractIterator.addString(Iterator.scala:1279)
  scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1136)
  scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1134)
  scala.collection.AbstractIterator.mkString(Iterator.scala:1279)
  scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:159)
  akka.stream.impl.Concat.toString(TraversalBuilder.scala:93)
  java.lang.String.valueOf(String.java:2994)
  java.lang.StringBuilder.append(StringBuilder.java:131)
  scala.collection.IterableOnceOps.addString(IterableOnce.scala:1191)
  scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1186)
  scala.collection.AbstractIterator.addString(Iterator.scala:1279)
  scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1136)
  scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1134)
  scala.collection.AbstractIterator.mkString(Iterator.scala:1279)
  scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:159)
  akka.stream.impl.Concat.toString(TraversalBuilder.scala:93)
  java.lang.String.valueOf(String.java:2994)
  java.lang.StringBuilder.append(StringBuilder.java:131)
  scala.collection.IterableOnceOps.addString(IterableOnce.scala:1194)
  scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1186)
  scala.collection.AbstractIterator.addString(Iterator.scala:1279)
  scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1136)
  scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1134)
  scala.collection.AbstractIterator.mkString(Iterator.scala:1279)
  scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:159)
  akka.stream.impl.Concat.toString(TraversalBuilder.scala:93)
  java.lang.String.valueOf(String.java:2994)
  java.lang.StringBuilder.append(StringBuilder.java:131)
  scala.collection.IterableOnceOps.addString(IterableOnce.scala:1194)
  scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1186)
  scala.collection.AbstractIterator.addString(Iterator.scala:1279)
  scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1136)
  scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1134)
  scala.collection.AbstractIterator.mkString(Iterator.scala:1279)
  scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:159)
  akka.stream.impl.LinearTraversalBuilder.toString(TraversalBuilder.scala:735)
  java.lang.String.valueOf(String.java:2994)
  java.lang.StringBuilder.append(StringBuilder.java:131)
  scala.collection.IterableOnceOps.addString(IterableOnce.scala:1191)
  scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1186)
  scala.collection.AbstractIterator.addString(Iterator.scala:1279)
  scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1136)
  scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1134)
  scala.collection.AbstractIterator.mkString(Iterator.scala:1279)
  scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:159)
  akka.stream.scaladsl.RunnableGraph.toString(Flow.scala:727)
  ammonite.$sess.cmd64$.<clinit>(cmd64.sc:1)
```

**Comment by johanandren** [comment] 2021-03-22 08:10
Hi, I tried this on JDK 11 (11.0.8+10) and JDK 8 (1.8.0_272) which are the bounds of what we support, and it works fine. Do you have some additional details about your environment that could be the cause?

I still think it should be fixed, and just ignore providing the source location if not possible, but it would be good to be able to verify that a fix actually does something.

**Comment by JackyChan** [comment] 2021-03-22 09:19
> Hi, I tried this on JDK 11 (11.0.8+10) and JDK 8 (1.8.0_272) which are the bounds of what we support, and it works fine. Do you have some additional details about your environment that could be the cause?
> 
> I still think it should be fixed, and just ignore providing the source location if not possible, but it would be good to be able to verify that a fix actually does something.

My environment is MacOS 11.2.3, Scala 2.13.5, GraalVM 21, JDK 1.8.0_282, Akka Stream 2.6.13

<img width="474" alt="Screen Shot 2021-03-22 at 5 18 16 PM" src="https://user-images.githubusercontent.com/260615/111967131-a226a780-8b32-11eb-89c8-1881f469ce2d.png">


<img width="839" alt="Screen Shot 2021-03-22 at 5 16 14 PM" src="https://user-images.githubusercontent.com/260615/111966925-70154580-8b32-11eb-856f-4e82f36038df.png">

**Comment by johanandren** [comment] 2021-03-22 09:43
Interesting, that could mean that the source line extraction logic is broken in latest JDK 8 patch release but not before that (note I tried on _272 while you are on _282) so perhaps something more to do there than just making it not fail.

**Comment by JackyChan** [comment] 2021-03-23 01:14
Yeah, it seems relate to the JDK. It running fine with GraalVM 21 Java 11.0.10.

<img width="969" alt="Screen Shot 2021-03-23 at 9 13 52 AM" src="https://user-images.githubusercontent.com/260615/112077776-2111f380-8bb8-11eb-85ce-b2020e81b8d2.png">

**Closed** 2021-04-09 12:02 UTC
Labels: 3 - in progress, t:stream
