### ISSUE TITLE
Publisher and Subscriber cleanup

### ISSUE THREAD

**Issue by MichaelZinsmaier** [akka/akka#20780] opened 2016-06-14 11:35 UTC
Dear Akka Team,

I stumbled across the "subscription-timeout" in the Akka streams documentation. It does not seem to apply if I use the underlying reactive streams interface to bridge between implementations (atm. it seems to apply only to sub streams?). 

The question is should this guard against "explicit" publisher leaks as well or is it more some kind of internal API.

example:

```
val src = getSource()
val sink = Sink.asPublisher[ByteString](fanout = false)

src.runWith(sink)
// never subscribing to the publisher, expecting cancel after subscription timeout
```
[Full Example](https://github.com/akka/akka/files/313778/Example.txt)

**Justification** essentially I'm leaking a publisher and if this publisher is never subscribed to there will be a backpressured idle Akka stream that would never be released.

**Background**
The reason that I'm interested in this is that we are interconnecting two Akka WebSockets in our server implementation.  
`WS1 <-> server flows <-> WS2`
To achieve that we rely on asPublisher and asSubscriber to be able to upgrade both WebSockets independently [concept](https://groups.google.com/forum/#!searchin/akka-user/zinsmaier/akka-user/uye5ZiO0KjI/ONDvB9v4EAAJ) now if something goes wrong we need some reliable cleanup and doing that based on the fact that we never subscribed to both sides would be a nice way to achive that.

Best Michael

**Comment by patriknw** [comment] 2016-08-08 14:33
@drewhk any thoughts here?

**Comment by patriknw** [comment] 2016-08-08 14:50
Perhaps issue https://github.com/akka/akka/issues/19980 is related?

**Comment by drewhk** [comment] 2016-08-08 15:14
It seems like `ActorGraphInterpreter` does not have a timer to check whether it is fully connected. Probably not super hard to add.

OTOH, @MichaelZinsmaier, what you want can be achieved by simply adding a proper timer stage, like an `initialTimeout` http://doc.akka.io/api/akka/2.4/index.html#akka.stream.scaladsl.FlowOps@initialTimeout(timeout:scala.concurrent.duration.FiniteDuration):FlowOps.this.Repr[Out]

Or alternatively a `backpressureTimeout` http://doc.akka.io/api/akka/2.4/index.html#akka.stream.scaladsl.FlowOps@backpressureTimeout(timeout:scala.concurrent.duration.FiniteDuration):FlowOps.this.Repr[Out]

**Comment by drewhk** [comment] 2016-08-08 15:15
And yeah, this is a duplicate of #19980

**Closed** 2016-08-08 15:16 UTC
Labels: t:stream
