### ISSUE TITLE
Automated schema evolution regression for Akka serialization

### ISSUE THREAD

**Issue by jroper** [akka/akka#29810] opened 2020-11-11 23:11 UTC
Just capturing an idea that I was discussing with @hseeberger in case anyone wants to look into it further.

We could create some semi-automated framework for testing and generated tests for the evolution of schemas. Note that when I talk about schema evolutions here, I'm not necessarily talking about the Jackson schema evolution support that Akka has, though schemas that use that could certainly be tested using this framework. This could just as easily work for protobuf, or Jackson support even when not using the schema support, for testing that backwards compatible changes are, indeed, backwards compatible.

The idea would be that you would have a folder that contained a bunch of versioned binary representations of messages:

```
my-message.0
my-message.1
my-message.2
```

Then you would define a test that might look like this:

```scala
validateSchemas("my-message",
  0 -> MyMessage(a = "propA", b = None, c = None),
  1 -> MyMessage(a = "propA", b = Some("propB"), c = None),
  2 -> MyMessage(a = "propA", b = Some("propB"), c = Some("propC")),
)
```

In the above example, we have a class, `MyMessage`, that started off with a single field. Then, a new field was added, and a new field was added after that. The idea would be that once the a binary representation of a message has been created and put into the folder, it would always be left there, and never changed - the framework of course can't enforce this, that's up to the developers. But it means that we always have the original message 0 around, and we will always be able to verify that it can be deserialized to something that makes sense.

In addition to verifying that the deserialization of all the old messages results in the given messages, it would include the following assertions:

* For each binary message file, there is a deserialized representation to test against in code, and vice versa.
* For the last message in the code, it will also be round tripped. If it doesn't match the binary representation in the file, then this indicates that a new schema evolution has occurred that hasn't had a test added for it. This causes the test to fail. To assist the user in creating the test, the framework will also output a new file, `my-message.new`, that the developer can rename once they have created the new assertion in code, if they want to use that binary representation, or delete if they want to create a different one.
* If there are any binary message files that are missing, the framework will fail, but to assist the developer, will also write one, with a name like `my-message.3.new`, which the developer can rename to `my-message.3` if they want to use that, or delete if they need to fix another way. This is how the developer might create a new evolution to test, by defining evolution 3 in the code, letting the framework write out the binary representation, and then renaming to capture that for good.

**Comment by johanandren** [comment] 2020-11-12 08:02
Duplicate of #24623 ?
I did a spike of something like this in #24631 but newer completed it the work.

**Comment by johanandren** [comment] 2020-11-13 12:42
I should add that I think it would be a quite nice feature of the testkit.

**Comment by patriknw** [comment] 2020-11-16 10:06
Thanks for input. Closing this ticket and we can have it as additional input in https://github.com/akka/akka/issues/24623

**Closed by patriknw** 2020-11-16 10:06 UTC
Labels: t:serialization
