### ISSUE TITLE
Akka actor takes a long time to resolve Future when using a transactional database API

### ISSUE THREAD

**Issue by natemurthy** [akka/akka#20021] opened 2016-03-12 20:03 UTC
I have an actor that processes `ask` requests from a Play controller. The actor replies to the controller after it retrieves a record from a graph database I am using (OrientDB). The database driver has both a transactional and non-transaction API. Here's what my actor looks like when I use the transactional API:

```scala
class EventManager extends Actor {
  def receive = {
    case GetEvent(id) => getEventFromDb(id)
  }

  def getEventFromDb(id): Unit = {
    val origin = sender
    val factory = new OrientGraphFactory(dbUrl,user,paswd).setupPool(1,10)
    var graph: OrientGraph = null
    try { 
      graph = factory.getTx()
      val result = graph.getVertices("event_id",id) // id is unique so guaranteed to be 1 result
      origin ! result
    } finally {
      graph.shutdown()
      factory.close()
    }
  }
}
```

And now here's how long it takes to process the `ask` from my controller with this implementation:

```
2016-03-12 11:09:16,646 INFO  EventManager - +++++ entering actor ++++++
2016-03-12 11:09:17,601 INFO  orientechnologies - OrientDB auto-config DISKCACHE=9,035MB (heap=926MB os=12,010MB disk=24,689MB)
2016-03-12 11:09:26,749 ERROR application -  Ask timed out on EventManager [10000 ms]. Sender sent message of type "GetEvent"
2016-03-12 11:09:37,940 INFO  EventManager - event found
```

It took over **21 seconds** just to retrieve this single event record vertex from my graph database! And my database just has this one record stored in it! The `ask` I request of the actor times out after 10 seconds but eventually retrieves the record I wanted. Now if I use the non-transactional graph API (i.e. use `factory.getNoTx()`), my logs show me the retrieval time is much faster:

```
2016-03-12 11:43:20,489 INFO  EventManager - +++++ entering actor ++++++
2016-03-12 11:43:21,310 INFO  orientechnologies - OrientDB auto-config DISKCACHE=9,036MB (heap=926MB os=12,010MB disk=24,688MB)
2016-03-12 11:43:23,665 INFO  EventManager - event found
```

This query takes just **3 seconds**. Granted there may be something OrientDB is doing poorly when running on top of Akka, but just from an actor perspective what could possibly be going wrong? I'm using the default dispatcher - http://doc.akka.io/docs/akka/2.4/scala/dispatchers.html#Default_dispatcher. Maybe I need to do something fancier to configure my thread / fork-join pools?

I've posted a related question on the OrientDB issue tracker on their github page: https://github.com/orientechnologies/orientdb/issues/5822

**Comment by johanandren** [comment] 2016-03-14 18:58
If you call the same method directly from your controller I'd expect you to get the same time. The general idea of a connection pool is to share a set of connections to avoid expensive connects for each command you want to send to the database so you probably want to keep that alive and share it across requests. This can be done using actors but I'd recommend you to look at the existing database connectivity for Play and how they tie the connection pool to the life cycle of the play app.

I'm closing this, I'm pretty sure you will have the same overhead if you just call your database method directly without involving actors. Feel free to reopen if you have some reproducer showing that this has got anything to do with Akka.

**Closed by johanandren** 2016-03-14 18:58 UTC

**Comment by ktoso** [comment] 2016-03-14 22:18
Hi there, I agree with @johanandren that it's not really an "issue" for Akka, however allow me to explain what you're seeing.

Since OrientDB operations are blocking (everything in `getEventFromDb`), and you execute that inside Actors you effectively end up doing a lot of blocking work on the default dispatcher, which is a "bad idea" ™, please refer to my SO answer that explains in detail how blocking on the default dispatcher is so bad for performance of Actor systems: http://stackoverflow.com/questions/34641861/akka-http-blocking-in-a-future-blocks-the-server/34645097#34645097

Also, please read the [blocking needs careful management](http://doc.akka.io/docs/akka/current/general/actor-systems.html#Blocking_Needs_Careful_Management) section in the Akka docs which also explain this.

In essence, you'll want to spawn the work in a `Future {}` and have that future use a dedicated dispatcher – like I explain in that SO answer.

Happy hakking.
