### ISSUE TITLE
FAILED: VirtualProcessorSingleTest

### ISSUE THREAD

**Issue by 2m** [akka/akka#19646] opened 2016-01-29 13:13 UTC
```
[info] - required_spec309_requestZeroMustSignalIllegalArgumentException *** FAILED ***
[info]   java.lang.AssertionError: Expected onError(java.lang.IllegalArgumentException) within 800 ms
```

(Jan 29, 2016 1:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3006/consoleFull
(Jan 25, 2016 11:19:00 PM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3410/consoleFull
(Jan 25, 2016 3:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/2995/consoleFull
(Jan 24, 2016 1:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/2991/consoleFull

**Comment by patriknw** [comment] 2016-02-05 12:42
Marking this as duplicate of #19385. Must be something in the infra/common stuff since it is failing for several of the stages.

**Closed** 2016-02-05 12:42 UTC
Labels: 1 - triaged, failed
