### ISSUE TITLE
FAILED: Akka Typed ActorContextSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21936] opened 2016-12-02 11:58 UTC
```
 set large receive timeout *** FAILED *** (2 seconds, 854 milliseconds)
[info]   akka.typed.StepWise$$anon$2: timeout of 3 seconds expired while waiting for a message
[info]   at akka.typed.ActorContextSpec$Tests$MessageStep.stimulate(ActorContextSpec.scala:238)
[info]   at akka.typed.ActorContextSpec$Tests$$anonfun$31$u0020must$u0020set$u0020large$u0020receive$u0020timeout$1.apply(ActorContextSpec.scala:498)
[info]   at akka.typed.ActorContextSpec$Tests$$anonfun$31$u0020must$u0020set$u0020large$u0020receive$u0020timeout$1.apply(ActorContextSpec.scala:493)
[info]   at akka.typed.ActorContextSpec$Tests$$anonfun$setup$1.apply(ActorContextSpec.scala:200)
[info]   at akka.typed.ActorContextSpec$Tests$$anonfun$setup$1.apply(ActorContextSpec.scala:192)
[info]   at akka.typed.StepWise$$anonfun$apply$1.applyOrElse(StepWise.scala:111)
[info]   at akka.typed.StepWise$$anonfun$apply$1.applyOrElse(StepWise.scala:110)
[info]   at akka.typed.ScalaDSL$Full.management(ScalaDSL.scala:161)
[info]   at akka.typed.adapter.ActorAdapter.preStart(ActorAdapter.scala:54)
[info]   at akka.actor.Actor$class.aroundPreStart(Actor.scala:489)
[info]   at akka.typed.adapter.ActorAdapter.aroundPreStart(ActorAdapter.scala:9)
[info]   at akka.actor.ActorCell.create(ActorCell.scala:590)
[info]   at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
[info]   at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
[info]   at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
[info]   at akka.dispatch.Mailbox.run(Mailbox.scala:223)
[info]   at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info]   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
```

**Comment by patriknw** [comment] 2016-12-05 09:47
Duplicate of #21653

**Closed by patriknw** 2016-12-05 09:47 UTC
Labels: bug, t:typed
