### ISSUE TITLE
List of 'Remembered Entries'

### ISSUE THREAD

**Issue by jsuchenia** [akka/akka#18714] opened 2015-10-12 15:33 UTC
As ClusterSharding is now able to remember entries and keep them after restart, is there a possibilit to retrieve a collection of all remembered entries (actor ids, entity ids)?

Currently we have a separate singleton actor that is keeping such list, where sharding is keeping the same list.

**Comment by patriknw** [comment] 2015-10-21 16:03
there is a pull request right now for retrieving the entity ids: https://github.com/akka/akka/pull/18543
Is that enough?

**Comment by jsuchenia** [comment] 2015-10-21 16:33
Yes, that's solving our basic issue (however the best could be to get details of all regions in one shot)

**Comment by patriknw** [comment] 2015-10-22 13:04
Retrieving all in one shot would potentially meaning sending a lot of data over the wire and that is not something we would like to encourage without users thinking about the consequences. E.g. it might be better to perform the work (or aggregate something) on the nodes where the regions are located.

I'm closing this as an duplicate of https://github.com/akka/akka/issues/17695 now.

**Closed by patriknw** 2015-10-22 13:04 UTC
Labels: t:cluster-tools
