### ISSUE TITLE
FAILED: sample.distributeddata.ReplicatedMetricsSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22081] opened 2017-01-02 11:12 UTC
https://jenkins.akka.io:8498/job/akka-nightly-2.12/68:

```
[JVM-2] - must cleanup removed node *** FAILED ***
[JVM-2]   akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://ReplicatedMetricsSpec/user/TestConductorClient#-466191927]] after [10000 ms]. Sender[null] sent message of type "akka.remote.testconductor.ToServer".
[JVM-2]   at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
[JVM-2]   at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
[JVM-2]   at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
[JVM-2]   at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
[JVM-2]   at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
[JVM-2]   at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:329)
[JVM-2]   at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:280)
[JVM-2]   at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:284)
[JVM-2]   at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236)
[JVM-2]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by patriknw** [comment] 2017-01-03 14:34
This is a duplicate of https://github.com/akka/akka/issues/21870

**Closed by patriknw** 2017-01-03 14:34 UTC
Labels: 1 - triaged, failed
