### ISSUE TITLE
Cannot shutdown actor system when using the affinity pool executor

### ISSUE THREAD

**Issue by yanns** [akka/akka#24040] opened 2017-11-22 07:55 UTC
When I use the affinity pool executor:
```
akka {
  actor {
    default-dispatcher {
      executor: "affinity-pool-executor"
    }
  }
}
```

the call to shutdown the actor system `Await.result(system.terminate(), 20.seconds)`
throws an exception:
```
[error] 	at scala.concurrent.Future.$anonfun$andThen$1(Future.scala:533)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error] 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
[error] 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
[error] 	at akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.executeNext$1(AffinityPool.scala:265)
[error] 	at akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.runLoop$1(AffinityPool.scala:283)
[error] 	at akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.run(AffinityPool.scala:294)
[error] 	at java.base/java.lang.Thread.run(Thread.java:844)
```

I tried with higher timeouts, with the same result.

**Comment by johanandren** [comment] 2017-11-22 08:14
I tried to repeat but couldn't see any problem, so there is something more to this than just terminating with the affinity executor:

```
object Terminate extends App {
  val system = ActorSystem("name", ConfigFactory.parseString(
    """akka.actor.default-dispatcher.executor: "affinity-pool-executor""""))
  Await.result(system.terminate(), 20.seconds)
}
```

Can you tell us any more details about the circumstances?

**Comment by yanns** [comment] 2017-11-22 08:20
First: thank you for your quick reactivity! ❤️ 

I'm using akka-stream on top of that.
Maybe this can explain this behavior?
```
materializer.shutdown()
Await.result(system.terminate(), 20.seconds)
```

**Comment by johanandren** [comment] 2017-11-22 08:24
Still not repeating on my machine with materializer, or materializer + running stream.

**Comment by yanns** [comment] 2017-11-22 08:26
I'll try to reproduce it with a minimal app.

**Comment by yanns** [comment] 2017-11-23 09:03
I cannot reproduce it with a small application.
I can still reproduce it with an internal application, closed source.

Maybe an important information:
when I reproduce it, I also see the following errors:
```
[info] [ERROR] [11/23/2017 10:02:15.152] [indexing-job-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(indexing-job)] Outgoing request stream error (akka.stream.AbruptTerminationException: Processor actor [Actor[akka://indexing-job/user/StreamSupervisor-1/flow-1-0-mergePreferred#-793974341]] terminated abruptly)
[info] [ERROR] [11/23/2017 10:02:15.152] [indexing-job-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(indexing-job)] Outgoing request stream error (akka.stream.AbruptTerminationException: Processor actor [Actor[akka://indexing-job/user/StreamSupervisor-1/flow-5-0-mergePreferred#1141427748]] terminated abruptly)
[info] [ERROR] [11/23/2017 10:02:15.153] [indexing-job-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(indexing-job)] Outgoing request stream error (akka.stream.AbruptTerminationException: Processor actor [Actor[akka://indexing-job/user/StreamSupervisor-1/flow-5-0-mergePreferred#1141427748]] terminated abruptly)
```

**Comment by yanns** [comment] 2017-11-23 09:06
In this internal application, we do use akka http client, and we close it first:
```
Await.result(Http().shutdownAllConnectionPools(), 20.seconds)
materializer.shutdown()
Await.result(system.terminate(), 20.seconds)
```

**Comment by johanandren** [comment] 2017-11-23 12:50
The abrupt termination is when an ActorMaterializer is shut down while streams materialized with it are still running, so that sounds fairly reasonable to see.

Try catching a thread dump when the system termination is hanging and see if there is something that got stuck?

**Comment by jrudolph** [comment] 2019-06-25 15:13
Closing this for lack of enough information to reproduce. Thanks for opening this issue, @yanns, please request reopening this issue if you are still affected (but since this ticket is so old, you may also consider opening a new issue).

**Closed by jrudolph** 2019-06-25 15:13 UTC
Labels: 0 - new
