### ISSUE TITLE
Need More Deployment Options

### ISSUE THREAD

**Issue by reynoldsm88** [akka/akka#18971] opened 2015-11-19 16:42 UTC
Since 2.4.0 deprecates the Microkernel, there are only two deployment options outlined in the documentation now. One is to use the SBT Native plugin and the other is to use a commercial Typesafe offering.

Can you please cover more options such as packaging with Maven as an uber jar?

**Comment by TimothyKlim** [comment] 2015-11-19 19:36
@reynoldsm88 you can use http://www.scala-sbt.org/sbt-native-packager/gettingstarted.html instead of depricated microkernel.

**Comment by ktoso** [comment] 2015-11-20 09:59
Hi @reynoldsm88,
those two are what we recommend.

I worked with Markus Eisele recently about how to package up an Akka (HTTP) app using Maven plugins as a docker container. So you might want to have a look here: http://blog.eisele.net/2015/10/akka-http-in-the-cloud-maven-docker-for-java-developers.html?utm_source=dlvr.it&utm_medium=twitter

It would be awesome if you could lend us a hand and PullRequest such description for Maven users, as we're not the most up to date on that part of the stack. I'm happy to help out if you get stuck somewhere - the above post should help (and http://doc.akka.io/docs/akka/snapshot/additional/faq.html#Why_are_replies_not_received_from_a_remote_actor_ is you're behind NAT or inside docker).

// refs: http://doc.akka.io/docs/akka/snapshot/intro/deployment-scenarios.html

Hope this helps!

**Comment by reynoldsm88** [comment] 2015-12-23 23:58
Hey sorry, haven't had much time to look at this issue since this Akka project isn't my top priority. I'd be happy to look into the things you mentioned and see if I can improve the documentation for packaging via Maven.

Thanks,
Michael Reynolds

**Comment by ktoso** [comment] 2018-04-24 00:48
Note that we refined things, and the commercial deployment tool does not exist anymore.
Tools to deploy remain:
- sbt native packager, as usual
- the OSS yet maintained by lightbend k8s orchestration https://developer.lightbend.com/docs/lightbend-orchestration-kubernetes/latest/features.html
- note also that https://developer.lightbend.com/docs/akka-management/current/bootstrap.html exists now as well, for joining clusters in cloud envs more easil

**Comment by Captain1653** [comment] 2021-08-24 18:23
The issue is really old. Some links are broken in the comments. Is it still needed?

**Comment by johanandren** [comment] 2021-08-24 18:41
I think we can close this, plenty done on Akka management/k8 support etc.

**Closed by johanandren** 2021-08-24 18:41 UTC
Labels: 1 - triaged, help wanted, t:docs
