### ISSUE TITLE
Add high-level client-side API / response handling DSL

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16845] opened 2015-02-10 16:37 UTC
Migrated from spray/spray#144.

/cc @sirthias

**Comment by rkuhn** [comment] 2015-02-12 13:07
Does this include simple things like unmarshaling a JSON response? I think a nice response routing DSL is not urgently needed, but we must document how to deal with the responses that clients get back.

**Comment by ktoso** [comment] 2015-10-20 08:38
Duplicate of https://github.com/akka/akka/issues/15909

**Closed by ktoso** 2015-10-20 08:38 UTC
Labels: 1 - triaged, t:http, t:http:client
