### ISSUE TITLE
RejectedExecutionException with akka 2.3.9

### ISSUE THREAD

**Issue by zzzhy** [akka/akka#23114] opened 2017-06-07 10:49 UTC
I use akka to post requests to a livy server, one of my job comes out error like the followings .
the stacktrace :
``` bash
job run failed,
exception:Map(message -> Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3b98040 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@191d6b4d[Terminated,pool size = 0,active threads = 0,queued tasks = 0,completed tasks = 8],
 errorClass -> java.util.concurrent.RejectedExecutionException,
 stack -> WrappedArray(java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047),
 java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823),
 java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326),
 java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533),
 java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632),
 java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678),
 com.cloudera.livy.client.http.JobHandleImpl.start(JobHandleImpl.java:160),
 com.cloudera.livy.client.http.HttpClient.sendJob(HttpClient.java:177),
 com.cloudera.livy.client.http.HttpClient.submit(HttpClient.java:104),
 io.wetoo.repl.LivyRunner.runJob(LivyRunner.scala:18),
 io.wetoo.Runner.submit(Runner.scala:8),
 io.wetoo.actor.RunnerActor$$anonfun$wrappedReceive$1$$anonfun$1.apply(RunnerActor.scala:25),
 scala.util.Try$.apply(Try.scala:192),
 io.wetoo.actor.RunnerActor$$anonfun$wrappedReceive$1.applyOrElse(RunnerActor.scala:24),
 scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36),
 io.wetoo.actor.base.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33),
 scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36),
 io.wetoo.actor.base.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25),
 io.wetoo.actor.base.Slf4jLogging$class.io$wetoo$actor$base$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34),
 io.wetoo.actor.base.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24),
 scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36),
 io.wetoo.actor.base.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:16),
 akka.actor.Actor$class.aroundReceive(Actor.scala:465),
 io.wetoo.actor.base.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8),
 akka.actor.ActorCell.receiveMessage(ActorCell.scala:516),
 akka.actor.ActorCell.invoke(ActorCell.scala:487),
 akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254),
 akka.dispatch.Mailbox.run(Mailbox.scala:221),
 akka.dispatch.Mailbox.exec(Mailbox.scala:231),
 scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260),
 scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253),
 scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346),
 scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979),
 scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107))),
```
the pom file is : 
``` java
<dependency>
            <groupId>com.typesafe.slick</groupId>
            <artifactId>slick_2.11</artifactId>
            <version>3.2.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.typesafe.slick</groupId>
            <artifactId>slick-codegen_2.11</artifactId>
            <version>3.2.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.39</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>1.6.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.scalatest</groupId>
            <artifactId>scalatest_2.11</artifactId>
        </dependency>
        <dependency>
            <groupId>com.huaban</groupId>
            <artifactId>jieba-analysis</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>net.logstash.log4j</groupId>
            <artifactId>jsonevent-layout</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.0.29.Final</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>asm</groupId>
            <artifactId>asm</artifactId>
            <version>3.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.xbean</groupId>
            <artifactId>xbean-asm5-shaded</artifactId>
            <version>4.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.wetoo</groupId>
            <artifactId>wetoo-runner</artifactId>
            <version>${service.runner.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-all</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>asm</groupId>
                    <artifactId>asm</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.xbean</groupId>
                    <artifactId>xbean-asm5-shaded</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-core</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>io.spray</groupId>
            <artifactId>spray-json_${scala.binary.version}</artifactId>
            <version>${spray.version}</version>
        </dependency>
        <dependency>
            <groupId>io.spray</groupId>
            <artifactId>spray-can_${scala.binary.version}</artifactId>
            <version>${spray.version}</version>
        </dependency>
        <dependency>
            <groupId>io.spray</groupId>
            <artifactId>spray-caching_${scala.binary.version}</artifactId>
            <version>${spray.version}</version>
        </dependency>
        <dependency>
            <groupId>io.spray</groupId>
            <artifactId>spray-routing_${scala.binary.version}</artifactId>
            <version>${spray.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.scala-lang.modules</groupId>
                    <artifactId>scala-xml_2.11</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-actor_${scala.binary.version}</artifactId>
            <version>2.3.9</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.0.7</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-slf4j_${scala.binary.version}</artifactId>
            <version>2.3.9</version>
        </dependency>
```
any ideas for this ? 
ps: spray-version: 1.3.3

**Comment by gchudnov** [comment] 2017-06-07 12:33
Guess your thread pool executor has been shut down?
```
[Terminated,pool size = 0,active threads = 0,queued tasks = 0,completed tasks = 8]
```

**Comment by ktoso** [comment] 2017-06-07 12:49
Yeah, such rejections can indeed show up when you try to do things after the pools (so the ActorSystem) terminates.

Please note that Akka 2.3 is ancient, and you should upgrade ASAP to 2.4.x or 2.5.x even.
All of those *are binary and (mostly AFAIR) source compatible*, so upgrading should not pose an issue.
The same can be said about Spray, which also has been end of lifed almost a year ago (with 2 year ahead notice).

Proposing to close this issue, as explanation above seems to be it, and no reproducer was provided.

**Closed** 2017-06-07 12:49 UTC

**Comment by ktoso** [comment] 2017-06-07 12:50
The follow up in other words: 

- either don't issue tasks after shutdown
- if you knowingly shutdown the system (or use revolver etc), ignore these messages since that is normal
- maybe you accidentally shutdown and are not aware?

**Comment by zzzhy** [comment] 2017-06-08 02:00
thanks all, I found my problem where it is. It's my spray routing-define code bug.
