### ISSUE TITLE
Incorrect quarantine event - Remote system has been silent for too long. (more than 48.0 hours)

### ISSUE THREAD

**Issue by vijaydaniel** [akka/akka#26418] opened 2019-02-20 07:48 UTC
Hi,

I'm using akka version 2.5.19 in a 3 node cluster.
Though the cluster seems to be fine and no error are seen in the application logs, two of the node is been quarantine with the below error message. 

**2019-02-17** 00:50:37,598 | ERROR | ult-dispatcher-3 | Remoting                         | 207 - com.typesafe.akka.slf4j - 2.5.19 | Association to [akka.tcp://opendaylight-cluster-data@192.168.28.3:2550] with UID [-86188694] irrecoverably failed. Quarantining address.
java.util.concurrent.TimeoutException: Remote system has been silent for too long. (more than 48.0 hours)
	at akka.remote.ReliableDeliverySupervisor$$anonfun$idle$1.applyOrElse(Endpoint.scala:386)[223:com.typesafe.akka.remote:2.5.19]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)[206:com.typesafe.akka.actor:2.5.19]
	at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:207)[223:com.typesafe.akka.remote:2.5.19]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)[206:com.typesafe.akka.actor:2.5.19]
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)[206:com.typesafe.akka.actor:2.5.19]

As the message says, the process ran for 48 hours and got quarantined. 
This is happening continuously for every 2 days in 2 nodes - even when these nodes are restarted. Please note that the 3rd node is not restarted at all and may have the previous UUID reference. Pasting the previous quarantine messages as well.

**2019-02-15** 00:50:32,517 | ERROR | lt-dispatcher-82 | Remoting                         | 207 - com.typesafe.akka.slf4j - 2.5.19 | Association to [akka.tcp://opendaylight-cluster-data@192.168.28.3:2550] with UID [526552531] irrecoverably failed. Quarantining address.
java.util.concurrent.TimeoutException: Remote system has been silent for too long. (more than 48.0 hours)
	at akka.remote.ReliableDeliverySupervisor$$anonfun$idle$1.applyOrElse(Endpoint.scala:386)[223:com.typesafe.akka.remote:2.5.19]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)[206:com.typesafe.akka.actor:2.5.19]
	at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:207)[223:com.typesafe.akka.remote:2.5.19]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)[206:com.typesafe.akka.actor:2.5.19]
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)[206:com.typesafe.akka.actor:2.5.19]

**2019-02-13** 00:50:27,440 | ERROR | lt-dispatcher-96 | Remoting                         | 207 - com.typesafe.akka.slf4j - 2.5.19 | Association to [akka.tcp://opendaylight-cluster-data@192.168.28.3:2550] with UID [526552531] irrecoverably failed. Quarantining address.
java.util.concurrent.TimeoutException: Remote system has been silent for too long. (more than 48.0 hours)
	at akka.remote.ReliableDeliverySupervisor$$anonfun$idle$1.applyOrElse(Endpoint.scala:386)[223:com.typesafe.akka.remote:2.5.19]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)[206:com.typesafe.akka.actor:2.5.19]
	at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:207)[223:com.typesafe.akka.remote:2.5.19]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)[206:com.typesafe.akka.actor:2.5.19]
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)[206:com.typesafe.akka.actor:2.5.19]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)[206:com.typesafe.akka.actor:2.5.19]

As a quick workaround, I thought of increasing the value 'quarantine-after-silence' to higher value say 60 days. What are the other parameter should I tune to support / increase the quarantine-after-silence ?

With Regards,
Vijay Daniel

**Comment by patriknw** [comment] 2019-02-22 11:31
Is this a duplicate of https://github.com/akka/akka/issues/26426 ?

**Comment by rovarga** [comment] 2019-04-09 09:33
Yes, it is.

**Closed** 2019-04-16 17:12 UTC

**Comment by tnevrekar** [comment] 2019-12-09 08:25
folks we are seeing the same issue in one of our deployments. Is there a known workaround for this issue? @vijaydaniel did increasing the quarantine-after-silence back to 5d help prevent this failure?

**Comment by vijaydaniel** [comment] 2019-12-10 15:48
Hi,

yes, increasing this to many days postponed the problem to happen.
Indeed we tried some big number like 800d, but it was rejected saying it is
too huge to configure.
If I recall correctly, we ended up configuring it to somewhere 250days.

With Regards
Vijay
