### ISSUE TITLE
Sink.collection potential regression on Scala 2.12.8

### ISSUE THREAD

**Issue by longshorej** [akka/akka#26305] opened 2019-01-29 23:57 UTC
Hi! With Akka 2.5.20, I'm seeing an issue with `Sink.collection`. See the REPL session below:

```
[info] Starting scala interpreter...
Welcome to Scala 2.12.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_202).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

import akka.actor._
import akka.stream._
import akka.stream.scaladsl._

implicit val sys: ActorSystem = ActorSystem()
implicit val mat: Materializer = ActorMaterializer()

val source = Source.single(1234)

val f = source.runWith(Sink.collection)

// Exiting paste mode, now interpreting.

<console>:20: error: could not find implicit value for parameter cbf: akka.util.ccompat.Factory[T,That with scala.collection.immutable.Iterable[_]]
       val f = source.runWith(Sink.collection)

```

I've tried helping it along, to no avail:

```
val f: Future[Vector[Int]] = source.runWith(Sink.collection)


// Exiting paste mode, now interpreting.

<console>:21: error: could not find implicit value for parameter cbf: akka.util.ccompat.Factory[T,That with scala.collection.immutable.Iterable[_]]
       val f: Future[Vector[Int]] = source.runWith(Sink.collection)

val f: Future[Vector[Int]] = source.runWith(Sink.collection[Int, Vector[Int]])


// Exiting paste mode, now interpreting.

<pastie>:21: error: could not find implicit value for parameter cbf: akka.util.ccompat.Factory[Int,Vector[Int] with scala.collection.immutable.Iterable[_]]
val f: Future[Vector[Int]] = source.runWith(Sink.collection[Int, Vector[Int]])
```

However, with Akka 2.5.19, it compiles without any hints:

```
import akka.actor._
import akka.stream._
import akka.stream.scaladsl._

implicit val sys: ActorSystem = ActorSystem()
implicit val mat: Materializer = ActorMaterializer()

val source = Source.single(1234)

val f = source.runWith(Sink.collection)

// Exiting paste mode, now interpreting.

import akka.actor._
import akka.stream._
import akka.stream.scaladsl._
sys: akka.actor.ActorSystem = akka://default
mat: akka.stream.Materializer = PhasedFusingActorMaterializer(akka://default,ActorMaterializerSettings(4,16,,<function1>,StreamSubscriptionTimeoutSettings(CancelTermination,5000 milliseconds),false,1000,1000,false,true,IoSettings(16384)),akka.dispatch.Dispatchers@54659d94,Actor[akka://default/system/StreamSupervisor-0#246650023],false,akka.stream.impl.SeqActorNameImpl@4cdd66a3)
source: akka.stream.scaladsl.Source[Int,akka.NotUsed] = Source(SourceShape(single.out(883743633)))
f: scala.concurrent.Future[scala.collection.immutable.IndexedSeq[Int]] = Future(<not completed>)

```

Any ideas? Am I missing some imports, or perhaps this is a bug introduced in the 2.13 compatibility?

**Comment by raboof** [comment] 2019-01-30 10:09
This indeed seems like a bug introduced in the 2.13 compatibility. It looks like we've been a bit too eager in making `akka.util.ccompat` things `private[akka]`, without realizing they're leaking through in the public API for `Sink.collection`. I don't see any other places that are affected.

I guess for the time being you could fall back to something like `source.runFold(List.empty[Int])((a, e) => a :+ e)`, while we see if we can find a good API for `Sink.collection` that works for all supported Scala versions.

**Comment by patriknw** [comment] 2019-01-30 11:12
Thanks for reporting

**Comment by krotton** [comment] 2019-02-12 00:57
I can confirm the same issue at 2.12.6.

**Comment by huntc** [comment] 2019-02-15 20:09
Any update on this issue given that 2.5.21 is now released? Is the resolution to use `Sink.seq`?

**Comment by patriknw** [comment] 2019-02-15 20:22
We haven’t got around looking into this issue yet.

**Comment by huntc** [comment] 2019-02-15 20:36
Thanks. Is seems as though the workaround is to use `Sink.seq`. Perhaps others will found this info useful.

**Comment by patriknw** [comment] 2019-02-18 10:21
Seems fine in master. I guess it was fixed by https://github.com/akka/akka/pull/26350
Removed an import in https://github.com/akka/akka/pull/26401 to avoid future regression.

**Closed** 2019-03-04 14:03 UTC
Labels: bug, t:scala-2.13, t:stream
