### ISSUE TITLE
[PersistentFSM] stay andThen not executing

### ISSUE THREAD

**Issue by mvdstam** [akka/akka#23329] opened 2017-07-10 14:06 UTC
Hey all,

Please regard the following example in a PersistentFSM actor:

```scala
when(Starting) {
  case Event(myEvent(), _) =>
    stay andThen { _ =>
      doSomething() // Never gets called
    }
}
```

The `doSomething()` never gets called. However, the following works:

```scala
when(Starting) {
  case Event(evt @ myEvent(), _) =>
    stay applying evt andThen { _ =>
      doSomething() // Gets called just fine
    }
}
```

Looking at the code of `PersistentFSM.scala`:

```scala
/**
 * Register a handler to be triggered after the state has been persisted successfully
 */
def andThen(handler: D ⇒ Unit): State[S, D, E] = {
  copy(afterTransitionDo = handler)
}
```

I _kinda_ understand why an `andThen` wouldn't fire since there is not a transition. However, this does not explain why `andThen` _does_ run after running `applying()`, since there still isn't any transition happening from one state to the other.

I'm using Akka 2.5.3 and scala 2.11. Any thoughts on this?

CC @jordymoos

**Comment by johanandren** [comment] 2017-07-13 17:45
There's something off here, because `andThen` takes  a `D => Unit` but in your samples you are not passing a function to it so it should not even compile. Was that just a copy-pasta error?

**Comment by mvdstam** [comment] 2017-07-13 17:50
@johanandren Yes, you're right, I merely forgot to add it in the samples. :)

**Comment by sovaalexandr** [comment] 2017-11-06 23:11
Also had this gotcha. Spent a couple of hours to debug. Reproduces if [eventsToPersist.isEmpty](https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala#L140). It's definitely a bug it may be 

- a documentation bug - then this behavior description should be added and there **should be no way to add _andThen_ at code** if neither transition (which is essentially applying) nor applying() happen
- a code bug - then andThen should be called nevertheless there were any events or not.

@leonidb git says it's your code. Which behavior have you planned on this? I can fix it, I just need to know which way.

**Comment by sovaalexandr** [comment] 2017-11-06 23:33
It would be much easier to fix a "code bug" since it just requires to move [          nextState.afterTransitionDo(stateData)](https://github.com/akka/akka/blob/d7330c3c72618af031cabae417cac4bb32f60af2/akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala#L156) outside of if block.
Ad a "documentation bug" fix is slightly harder. It requires to decompose [State[S, D, E]](https://github.com/akka/akka/blob/d7330c3c72618af031cabae417cac4bb32f60af2/akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala#L331) to two classes - "state with events applied" and "state without events applied" (naming is still a point to think of). And andThen method should be available only at class "state with events applied". And, of course, documentation should be fixed.
Who thinks which solution fits best?

**Comment by leonidb** [comment] 2017-11-07 23:40
@sovaalexandr The motivation for `andThen` was to provide a way to execute "side effects" after the state is saved successfully. I've probably overlooked the case when state doesn't need to be saved.  
Current behavior indeed seems confusing, since it's possible to use the callback when staying in the same state.  
In my opinion it probably would be better to execute `andThen` in all cases.  
It's pretty clear to the user if the state is changed or not (`stay` vs `goto` or `applying`) , so if the user doesn't want to execute the callback when state doesn't change, he can still do it explicitly.

@johanandren @patriknw what do you think?

**Comment by leonidb** [comment] 2017-11-07 23:45
@sovaalexandr the fix you proposed wouldn't work, if you move `nextState.afterTransitionDo(stateData)` out of `applyStateOnLastHandler()` it will be executed before the events are persisted.
Adding it after [super.applyState(nextState)](https://github.com/akka/akka/blob/d7330c3c72618af031cabae417cac4bb32f60af2/akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala#L142) would fix it.

**Comment by sovaalexandr** [comment] 2017-11-08 02:46
@leonidb Yes, actually meant that. But curious tried just moving outside of if block - it fixed this case and broke test for "persist snapshot"

**Comment by synox** [comment] 2018-02-12 15:07
Has this been shipped with akka 2.5.9?

**Comment by johanandren** [comment] 2018-02-12 15:12
The PR was merged but then reverted, see discussion in the PR itself.

**Comment by raboof** [comment] 2019-06-25 15:11
We're phasing out PersistentFSM in favor of Persistence Typed, so I think we should close this issue focus on that instead.

**Closed by raboof** 2019-06-25 15:11 UTC
Labels: 0 - new, t:persistence
