### ISSUE TITLE
Cluster Node throws 'Not initialized yet' exception and becomes unreachable

### ISSUE THREAD

**Issue by akapsalis** [akka/akka#27732] opened 2019-09-17 11:23 UTC
Hi,

For over three years now we use Akka Cluster in our application. At first we were using Netty-TPC-based Akka remote classic but the last year we started to migrate our clients to use Akka Artery Aeron/UDP at Akka version 2.5.21 (scala 2.12). The migration of the client with the highest load was completed two months ago and at some point we started observing a strange behaviour in the production environment.
The following exception occurs in the logs and at that point the problematic node marks all of the nodes that are in its failure detector as unreachable, ignores their gossip status because of unreachability and at some point forms its own isolated cluster. Likewise, other nodes' failure detectors mark it too as unreachable.

```
2019-09-14 01:05:38,047 WARN  akka.cluster.Cluster(akka://product_name) - Cluster Node [akka://product_name@web8:6500] - Scheduled sending of heartbeat was delayed. Previous heartbeat was sent [5007] ms ago, expected interval is [2000] ms. This may cause failure detection to mark members as unreachable. The reason can be thread starvation, e.g. by running blocking tasks on the default dispatcher, CPU overload, or GC.
2019-09-14 01:05:38,283 ERROR akka://product_name/system/StreamSupervisor-1/remoteControl-0-0-ignoreSink - Error in stage [akka.remote.artery.InboundHandshake@54780767]: outboundControlIngress not initialized yet
java.lang.IllegalStateException: outboundControlIngress not initialized yet
    at akka.remote.artery.Association.outboundControlIngress(Association.scala:227)
    at akka.remote.artery.Association.sendControl(Association.scala:312)
    at akka.remote.artery.ArteryTransport.sendControl(ArteryTransport.scala:699)
    at akka.remote.artery.InboundHandshake$$anon$2.$anonfun$onHandshakeReq$1(Handshake.scala:250)
    at akka.remote.artery.InboundHandshake$$anon$2.akka$remote$artery$InboundHandshake$$anon$$after(Handshake.scala:272)
    at akka.remote.artery.InboundHandshake$$anon$2.akka$remote$artery$InboundHandshake$$anon$$onHandshakeReq(Handshake.scala:249)
    at akka.remote.artery.InboundHandshake$$anon$2$$anon$3.onPush(Handshake.scala:220)
    at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:515)
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:407)
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:474)
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:730)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:745)
    at akka.actor.Actor.aroundReceive(Actor.scala:517)
    at akka.actor.Actor.aroundReceive$(Actor.scala:515)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
    at akka.actor.ActorCell.invoke(ActorCell.scala:561)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
    at akka.dispatch.Mailbox.run(Mailbox.scala:225)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2019-09-14 01:05:41,193 ERROR akka.remote.artery.aeron.ArteryAeronUdpTransport(akka://product_name) - Inbound control stream failed. Restarting it. outboundControlIngress not initialized yet
java.lang.IllegalStateException: outboundControlIngress not initialized yet
    at akka.remote.artery.Association.outboundControlIngress(Association.scala:227)
    at akka.remote.artery.Association.sendControl(Association.scala:312)
    at akka.remote.artery.ArteryTransport.sendControl(ArteryTransport.scala:699)
    at akka.remote.artery.InboundHandshake$$anon$2.$anonfun$onHandshakeReq$1(Handshake.scala:250)
    at akka.remote.artery.InboundHandshake$$anon$2.akka$remote$artery$InboundHandshake$$anon$$after(Handshake.scala:272)
    at akka.remote.artery.InboundHandshake$$anon$2.akka$remote$artery$InboundHandshake$$anon$$onHandshakeReq(Handshake.scala:249)
    at akka.remote.artery.InboundHandshake$$anon$2$$anon$3.onPush(Handshake.scala:220)
    at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:515)
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:407)
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:474)
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:730)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:745)
    at akka.actor.Actor.aroundReceive(Actor.scala:517)
    at akka.actor.Actor.aroundReceive$(Actor.scala:515)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
    at akka.actor.ActorCell.invoke(ActorCell.scala:561)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
    at akka.dispatch.Mailbox.run(Mailbox.scala:225)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2019-09-14 01:06:04,733 WARN  akka.cluster.Cluster(akka://product_name) - Cluster Node [akka://product_name@web8:6500] - Marking node(s) as UNREACHABLE [Member(address = akka://product_name@prod2:28000, status = Up), Member(address = akka://product_name@web1:6500, status = Up), Member(address = akka://product_name@web2:6500, status = Up)]. Node roles [web, static, dc-default]
2019-09-14 01:06:05,697 WARN  akka.cluster.Cluster(akka://product_name) - Cluster Node [akka://product_name@web8:6500] - Marking node(s) as UNREACHABLE [Member(address = akka://product_name@web12:6500, status = Up)]. Node roles [web, static, dc-default]
2019-09-14 01:06:09,842 INFO  akka.cluster.Cluster(akka://product_name) - Cluster Node [akka://product_name@web8:6500] - Ignoring received gossip from unreachable [UniqueAddress(akka://product_name@web2:6500,9106794823932235696)] 
2019-09-14 01:06:09,987 WARN  akka.cluster.Cluster(akka://product_name) - Cluster Node [akka://product_name@web8:6500] - Marking node(s) as UNREACHABLE [Member(address = akka://product_name@prod3:26000, status = Up)]. Node roles [web, static, dc-default]
2019-09-14 01:06:10,541 INFO  akka.cluster.Cluster(akka://product_name) - Cluster Node [akka://product_name@web8:6500] - Ignoring received gossip from unreachable [UniqueAddress(akka://product_name@web2:6500,9106794823932235696)] 
2019-09-14 01:06:16,626 INFO  akka.cluster.Cluster(akka://product_name) - Cluster Node [akka://product_name@web8:6500] - Ignoring received gossip status from unreachable [UniqueAddress(akka://product_name@web2:6500,9106794823932235696)]
... similar "Ignoring received gossip (status) from unreachable"  log messages follows for other nodes
```
Looking at the error it seems that it tries to respond in a HandshakeReq but the outbound control stream's ingress for the particular association does not exist. However the error message doesn't provide details about which association that is. 
The cluster, which is formed by 15-16 static (permanent) nodes but also has short-lived dynamic nodes (that bind to ephemeral ports), never recovers from this until the problematic node is restarted. Please note that we are not using any automatic downing strategy but in case of a dynamic instance's leaving cluster times out, we force a Down before exiting.
   
Some observations about the issue are:
- the error has never been observed during or closely after the startup of a member instance but instead happens after the instance is running for quite some time (normally restarts happen on a weekly basis).
- it occurs only in our product with the highest load and only in the production environment. Very similarly-configured Akka cluster products for other clients with ~10 nodes and a bit less traffic run for over a year now and they have never experienced a similar issue.
- the operating environment is noisy, with GC pauses sometimes exceeding 20 secs but in general we have been unable to correlate the errors with either machine load of any kind or GC / stop the world activity.
- it occurs quite often, once every day or so.
- even though the problematic node has marked as unreachable business-level actors deployed on it can communicate fine with others (both ways) via akka cluster remote protocol (i.e. actorSelection that ignores cluster reachability state), so the error does not seem to affect the data streams (only the control?).

We can provide you with detailed logs if this can help solve the issue but all the logs right now are in info level (but if needed we will switch to debug).

Thanks

**Comment by patriknw** [comment] 2019-09-17 12:19
@akapsalis Thanks for reporting. This is definitely something we want to investigate and fix. I'd like to look at logs.

In the meantime could you also try with latest version 2.5.25, so that we are not hunting something that has already been fixed. I don't think we have fixed anything related but 2.5.21 is quite old.

**Comment by akapsalis** [comment] 2019-09-17 13:54
These are [the logs](https://github.com/akka/akka/files/3621579/logs.zip) for two days (only the static nodes). During these two days, the error occurred two times in two different nodes:
- at 2019-09-13 12:52:36,794 for prod3 and the node was manually restarted at 2019-09-13 23:14:58,990
- at 2019-09-14 01:05:38,283 for web8 , also the error occurred again at 2019-09-14 01:48:36,885 (within a 30 min gap). The node was manually restarted at 2019-09-14 02:42:57,081.

We are in the process of migrating to Akka version 2.5.25, but this may take some time.

**Comment by akapsalis** [comment] 2019-09-17 18:49
After enabling the debug log level in production, some cluster nodes were logging messages like these:

```
InboundQuarantineCheck(akka://actor_system_name) - Dropping message [ActorSelectionMessage(akka.cluster.ClusterHeartbeatSender$Heartbeat)] from [akka://actor_system_name@web8:64638#1512060173390585968] because the system is quarantined
akka.remote.artery.Association(akka://actor_system_name) - Send control message [akka.remote.artery.OutboundHandshake$HandshakeRsp] to quarantined [akka://actor_system_name@web8:64638]
```
It seems there were some 'ghost' dynamic instances which were still running in the background for a long period of time but they were not part of the cluster anymore because they had been quarantined by other nodes. Maybe some of these instances were sending handshake requests back to some cluster nodes even after "akka.remote.artery.advanced.remove-quarantined-association-after" duration had passed (set to the default value 1h). Might this be the root cause for this issue?

**Comment by patriknw** [comment] 2019-09-23 13:19
Thanks, I'll try to dig into it and see if I can find an explanation.

**Comment by nvrs** [comment] 2019-09-23 13:53
@patriknw, also worth mentioning that since we tracked and killed all the rogue instances (there were 3 of them, all quarantined but still sending handshake requests and heartbeats), the issue has not occurred.

**Comment by patriknw** [comment] 2019-10-01 08:21
@akapsalis @nvrs I'm pretty sure I have found the race condition that may cause this. Fixed in https://github.com/akka/akka/pull/27834
Should be very rare in normal operations but probably triggered more frequently by the jvm issues (in logs also seen as the delayed heartbeats).

**Comment by nvrs** [comment] 2019-10-01 08:47
@patriknw thanks!

Yes it is very rare, we have been running many clusters on many environments for more than a year and this manifested only in one. These particular VMs are operating with a huge heap which is something we can't do anything about for the time being.

**Comment by nvrs** [comment] 2019-10-07 08:06
@patriknw 

After forking 2.5.25, cherry picking #27834 and deploying on the environment that we can reproduce the issue (not within a deterministic timeframe but with a high probability of it happening in an ~10 hour window), we are unable to reproduce it anymore.

**Comment by patriknw** [comment] 2019-10-07 08:21
thanks for testing

**Closed** 2019-10-09 13:53 UTC
Labels: 3 - in progress, bug, t:remoting:artery
