### ISSUE TITLE
Remove the need for Scheduler to run all callbacks on shutdown

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16495] opened 2014-12-09 14:12 UTC
This should be mentioned in the API docs of the individual methods. We might also think about adding the ability to opt out of this behavior.

**Comment by jroper** [comment] 2015-08-03 07:00
Just another datapoint for confusion of scheduled tasks being executed before shutdown:

https://github.com/playframework/playframework/issues/4905

I've noticed this problem myself before too. I can understand that for schedule once tasks, it would often, or maybe usually be useful that they be executed at shutdown, but recurring tasks don't make sense to me - in my particular use case, I had a recurring task that was polling Play contributor data out of GitHub every 24 hours. Running this task again on shutdown doesn't make sense, and especially in the context of Play, where every change to the code base results in an Akka shutdown.

**Comment by rkuhn** [comment] 2015-08-03 07:14
Yes, indeed, that is not usually what is intended. We’ll have to rethink that part—possibly by drawing the line between the ActorSystem’s Scheduler (that is only intended to be used for timeouts) and a to-be-written component that can send messages at particular calendar times. We might even need to rename things to make the difference clear.

**Comment by patriknw** [comment] 2016-05-24 12:25
this is now a duplicate of https://github.com/akka/akka/issues/20256 keeping this one

**Comment by patriknw** [comment] 2016-08-25 18:43
Another workaround: Use `system.registerOnTermination` and in that callback cancel your scheduled task. Your callback will be run before the scheduler is shutdown, which is what makes the scheduled task to run.

**Closed** 2019-08-29 07:16 UTC
Labels: 3 - in progress, t:core
