### ISSUE TITLE
FAILED: ReplicatedMetricsSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#18418] opened 2015-09-08 11:32 UTC
https://jenkins.akka.io:8498/job/akka-nightly/2587/consoleFull

**Comment by drewhk** [comment] 2015-09-09 08:49
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2872/consoleFull

**Comment by patriknw** [comment] 2015-09-09 08:51
This is a duplicate of #18157

**Closed** 2015-09-09 08:51 UTC
Labels: 1 - triaged, failed, t:cluster-tools
