### ISSUE TITLE
FAILED: akka.actor.LightArrayRevolverSchedulerSpec.A Scheduler must not be affected by long running task

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#24503] opened 2018-02-05 12:17 UTC
https://jenkins.akka.io:8498/job/akka-nightly/5203/testReport/junit/akka.actor/LightArrayRevolverSchedulerSpec/A_Scheduler_must_not_be_affected_by_long_running_task/

```
Error Message

org.scalatest.exceptions.TestFailedException: 3.2126168224299065 did not equal 4.4 plus or minus 0.5

Stacktrace

sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: 3.2126168224299065 did not equal 4.4 plus or minus 0.5
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6824)
	at akka.actor.SchedulerSpec$$anonfun$1$$anonfun$apply$mcV$sp$29.apply(SchedulerSpec.scala:268)
	at akka.actor.SchedulerSpec$$anonfun$1$$anonfun$apply$mcV$sp$29.apply(SchedulerSpec.scala:258)
```

**Comment by johanandren** [comment] 2018-02-13 14:25
Duplicate of #18160

**Closed** 2018-02-13 14:26 UTC
Labels: 1 - triaged, failed, t:core
