### ISSUE TITLE
Tcp.Connect message not responded to with CommandFailed or Connected

### ISSUE THREAD

**Issue by RatanRSur** [akka/akka#25700] opened 2018-09-28 16:03 UTC
https://github.com/RatanRSur/raicoin/tree/c731b5d2c9f337a13e0e64b93d142b1cefe9793f

At this point in my project, I'm trying to make two peers discover each other through the initial node in the peer to peer network.

Steps to reproduce:

`sbt test`

Observe that my `BlockchainActor` will print out `Unexpected Message` when an unhandled message, such as `CommandFailed`, is received and another debug print if `Connected` is received.

In the output for the failing test, the following line:

`C connecting to localhost/127.0.0.1:42044`

is not followed by any other types of debug prints.

**Comment by raboof** [comment] 2018-09-28 16:16
I'm afraid I can't reproduce this, from https://pastebin.com/4nxdNZwy it seems `C` successfully connects and sends something to `A`. This might fit better at https://discuss.akka.io

**Comment by RatanRSur** [comment] 2018-09-28 18:50
Oh, I should have specified, it's the C B connection that is the problem. B and C connect to A fine

**Comment by RatanRSur** [comment] 2018-09-28 18:57
But your output does look different from mine. Will take a deeper look

**Comment by raboof** [comment] 2018-10-03 12:02
OK! I'll close this for now, but feel free to bring it up at https://discuss.akka.io if there is anything unclear, or open a new issue when it really appears to be a library bug.

**Closed by raboof** 2018-10-03 12:02 UTC
