### ISSUE TITLE
Akka Typed watchWith failures

### ISSUE THREAD

**Issue by huntc** [akka/akka#25803] opened 2018-10-17 04:44 UTC
When using `watchWith` in Akka Typed, I'm unable to discern between what has caused the termination e.g. whether the actor stopped itself or threw an exception. All that I know is that the watched actor has terminated.

I had assumed (for some reason) that `watchWith` might still cause `Terminated` to be sent to the observing actor in the case of a failure. This doesn't appear to be the case though.

Should I revert to just using `watch` in cases where I need to discern the cause of termination, or might it be useful to register an additional message with `watchWith` to fire when there is abnormal termination... or even just have `watchWith` send `Terminated` in such an instance?

As a slight aside, I find it annoying that Akka logs the abnormal termination as an error... Is there a means to avoid logging in such a circumstance?

**Comment by patriknw** [comment] 2018-10-17 11:51
The primary purpose of `watchWith` is to translate the termination signal into the message protocol of the watching actors (without using signals).

> Should I revert to just using watch in cases where I need to discern the cause of termination, or might it be useful to register an additional message with watchWith to fire when there is abnormal termination... or even just have watchWith send Terminated in such an instance?

I think it would be easiest if you use `watch` for that case. Other alternatives seems to make the API rather much more complicated.

> As a slight aside, I find it annoying that Akka logs the abnormal termination as an error... Is there a means to avoid logging in such a circumstance?

That logging can be disabled via the supervision strategy.
```
Behaviors.supervise(targetBehavior)
  .onFailure[Throwable](SupervisorStrategy.stop.withLoggingEnabled(false))
```

**Comment by huntc** [comment] 2018-10-17 19:12
Thanks!

On using `watch` instead, the downside for me is that the normal handling of an actor terminating is out of band to my general receive handling. It makes the code harder to follow. 

Thanks for the logging advice. FUI this may result in a bit of boilerplate though given that I’m dealing with an FSM and multiple behaviours.

**Comment by patriknw** [comment] 2018-10-18 06:33
> In summary, even when using watch, I'm unable to discern between a child actor stopping gracefully vs stopping given a failure.

> I've now changed my code to use only watch but I still don't see the failure field being set when I know that the child actor has stopped because of failure. Any ideas? Here's the relevant line where I'm not seeing a failure field value

That information should be included via the `failure: Option[Throwable]` in the `Terminated`.
We have a test for that in https://github.com/akka/akka/blob/master/akka-actor-typed-tests/src/test/scala/akka/actor/typed/WatchSpec.scala#L108 so it's strange that you don't see it in your code.

**Comment by huntc** [comment] 2018-10-18 07:59
Thanks for the pointer to the test. I'm not quite sure what to test next... I shall of course look further, but if you have any further inspiration then it would be welcome. Thanks.

**Comment by huntc** [comment] 2018-10-18 09:44
@patriknw I've just modified the test that you pointed out to switch to another behaviour and then throw the exception (which is what my code is doing). I think that this could be our problem as the test will fail i.e. in your test:

```scala
        def nextBehaviour: Behavior[Any] = Behaviors.receive[Any]((ctx, msg) ⇒
          throw ex
        )
        val child = ctx.spawn(Behaviors.receive[Any]((ctx, msg) ⇒
          nextBehaviour
        ), "child")
```

...causes the test to fail.

**Comment by huntc** [comment] 2018-10-18 09:58
@patriknw The problem appears to be to do with when declaring a supervisor strategy. If I change your test to:

```scala
        val child = ctx.spawn(Behaviors.supervise(Behaviors.receive[Any]((ctx, msg) ⇒
          throw ex
        )).onFailure(SupervisorStrategy.stop), "child")
```

...then it fails. Accordingly, if I remove the supervisor declaration from my code then it works. :-)

**Comment by patriknw** [comment] 2018-10-18 10:10
That's a good finding. It's a bug.

**Comment by huntc** [comment] 2018-10-18 10:14
Good to know - I'll let it log the errors for now - at least I don't get horrid stack traces!

I tried to figure out how the code worked re. supervision so I could raise a PR, but I guess it may just be beyond me. :-)

**Comment by patriknw** [comment] 2018-11-05 10:35
When I thought some more about it afterwards I'm skeptical to this exception passing via watch because sending exceptions in remote messages is difficult (serialization problems). Just having them for watch of local child actors doesn't align well with location transparency principles.

**Comment by huntc** [comment] 2018-11-05 12:14
I don’t know what else other than an exception to convey abnormal termination to an observer. 

Also, to revisit, my main requirement is to discern between an actor terminating normally and abnormally given some exceptional, but recoverable, circumstance.

**Comment by chbatey** [comment] 2018-11-27 14:43
As it stands the Typed supervision mechanism stops the exception reaching the `ActorAdapter`. The exception is only filled in if the adapter's supervision gets the exception. 

I think for now let's remove the exception from Terminated as it is broken by typed supervision and it only was designed to work for direct children.

**Comment by huntc** [comment] 2018-11-27 18:36
I need to discern between a direct child terminating abnormally vs not. How would you propose that I do that if you remove the exception from Terminated?

Please note also that the Alpakka MQTT streaming connector relies on the ability to make this distinction.

**Comment by hepin1989** [comment] 2018-11-27 19:06
Termination should be a seald trait then。

**Comment by chbatey** [comment] 2018-11-29 10:56
@huntc looking at the Alpakka MQTT connector and the use case of bubbling up exceptions I agree we should keep it. We'll make it clean with a specific `ChildTerminated` rather than an option in the normal `Terminated` message. Typed won't support remote deployment so children are always local.

**Comment by huntc** [comment] 2018-11-29 10:58
That sounds great! Thanks for the consideration.

**Comment by patriknw** [comment] 2018-12-07 07:42
@huntc This was fixed in https://github.com/akka/akka/pull/25992 by introducing a new `ChildTerminated` signal. Created Alpakka issue https://github.com/akka/alpakka/issues/1359

**Closed by patriknw** 2018-12-07 07:42 UTC
Labels: bug, t:typed

**Comment by huntc** [comment] 2019-01-27 07:30
I'd like to re-visit this issue if I may. 

My understanding is that the new `ChildFailed` signal will be generated when using `watch`. However, when using `watchWith` there is still no ability to discern between normal and abnormal child termination. Given,_"The primary purpose of watchWith is to translate the termination signal into the message protocol of the watching actors (without using signals)."_, `watchWith` appears to be falling short on this goal.

I've got a couple of places where I didn't change the use of `watchWith` in the MQTT streaming connector where, on further consideration, I do actually need to deal with failure. I will migrate these to using `watch`, but as feedback, I'm not finding `watchWith` useful in general.

**Comment by huntc** [comment] 2019-01-28 22:11
Done: https://github.com/akka/akka/issues/26296. Thanks.
