### ISSUE TITLE
Upgrade to Scala 2.13.0-RC1

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26691] opened 2019-04-05 08:38 UTC

**Comment by johanandren** [comment] 2019-04-05 08:44
Depends on ghik/silencer#25

**Comment by johanandren** [comment] 2019-04-05 12:36
I think we also need a scala-java8-compat release (or did I hear somewhere that is now deprecated?)

**Comment by raboof** [comment] 2019-04-05 12:39
Apparently it is now rolled into 2.13, yes: https://github.com/scala/scala/pull/7458

**Comment by SethTisue** [comment] 2019-04-08 10:56
silencer is out, genjavadoc is out https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md

**Comment by johanandren** [comment] 2019-04-08 11:58
We'll have to spend some time on figure out how we deal with scala-java8-compat namespace changes while we continue to release for 2.11 and 2.12 (unless I misunderstood something there)

**Comment by SethTisue** [comment] 2019-04-08 12:14
@lrytz was contemplating perhaps shipping a scala-java8-compat for 2.13 that would just contain forwarders rather than code, perhaps this could be a testbed for that?

**Comment by SethTisue** [comment] 2019-04-08 12:46
the changes Lukas used in the 2.13 community build are here: https://github.com/lrytz/akka/commit/b67ad773cf02e28b6e4f06d80c884a8b41f064e7

**Comment by johanandren** [comment] 2019-04-08 12:57
Yeah, or we introduce such forwarders in our code base, so there's no need for a separate artifact just because we need it?

**Comment by SethTisue** [comment] 2019-04-08 13:05
right, you're not sunk without it, but it might be useful to other projects as well to publish the forwarders

**Comment by lrytz** [comment] 2019-04-12 07:13
java8-compat: https://github.com/scala/scala-java8-compat/pull/139

**Comment by johanandren** [comment] 2019-04-15 09:08
Ran the test suite with a snapshot of that java8-compat PR and it looks good!

**Comment by SethTisue** [comment] 2019-04-18 20:57
@johanandren do you have a WIP branch somewhere that I can use in the 2.13 community build?

**Comment by johanandren** [comment] 2019-04-23 06:47
Here: https://github.com/johanandren/akka/tree/wip-scala-2.13.0-RC1-johanandren
It depends on having a `0.9.1-SNAPSHOT` of java8-compat available though.

**Comment by SethTisue** [comment] 2019-04-24 17:23
@johanandren I'm not able to get your branch to compile, either locally, or in the community build, either. is it really still that WIPpy?

**Comment by johanandren** [comment] 2019-04-25 11:37
Yeah, I messed something up here @SethTisue , that branch cannot be trusted, sorry! We'll look into it.

**Comment by adriaanm** [comment] 2019-04-25 13:12
FYI, here's a quick way to see the compile errors. Looks like my *FactoryDefaults PR (https://github.com/scala/scala/pull/7929) broke a few things (missing empty override mostly).

https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1992/console

**Comment by adriaanm** [comment] 2019-04-25 13:24
```patch
--- i/akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala
+++ w/akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala
@@ -672,6 +672,7 @@ sealed abstract class ByteString
 
   override protected def fromSpecific(coll: IterableOnce[Byte]): ByteString = ByteString(coll)
   override protected def newSpecificBuilder: mutable.Builder[Byte, ByteString] = ByteString.newBuilder
+  override def empty: ByteString = ByteString.empty
 
```

**Comment by adriaanm** [comment] 2019-04-25 13:24
then we get:
```
/Users/adriaan/git/akka/akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala:679: error: method writeReplace overrides nothing
  protected[this] override def writeReplace(): AnyRef = this
                               ^
```

**Comment by adriaanm** [comment] 2019-04-25 13:29
(pushed a minimal fix to https://github.com/scalacommunitybuild/akka/tree/community-build-2.13)

**Comment by raboof** [comment] 2019-05-02 13:56
Akka 2.5.22 was released for 2.13.0-RC1 from the `2.5.22-scala-2.13.0-RC1` branch.

PR's for `release-2.5` and `master` are at #26821 and #26817, but given RC2 seems around the corner perhaps we should wait until RC2, update those branches, and then review/merge those.

**Comment by SethTisue** [comment] 2019-05-02 16:27
(I'm not too close to the details here, but speaking generally:)

honestly time is now so short, any unnecessary waiting worries me a bit. unless there's some real roadblock, I would suggest proceeding with RC1, landing it as a baseline, and then treat RC2 separately

**Comment by patriknw** [comment] 2019-05-03 06:35
It's not that we are waiting. We have published for 2.13.0-RC1 to maven central and that can be used by downstream projects.

Not merging this to master/release-2.5 branches just yet is just a precaution to not introduce regressions for the stable 2.12 and 2.11 releases, since it's using the same code base. Some of the changes for 2.13.0-RC1 are workarounds for issues that will (probably) be fixed in RC2.

**Comment by SethTisue** [comment] 2019-05-03 14:08
okay, understood :+1:

**Comment by Sciss** [comment] 2019-05-19 17:24
Whats the status of 2.13.0-RC2?

**Comment by adriaanm** [comment] 2019-05-19 17:24
It’s on maven central. Full announcement coming tomorrow

**Comment by raboof** [comment] 2019-05-20 07:27
Superseded by #26964

**Closed by raboof** 2019-05-20 07:27 UTC
Labels: 3 - in progress, t:scala-2.13
