### ISSUE TITLE
ideleTimeout in Http?

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#18694] opened 2015-10-09 16:45 UTC
What's the purpose of `ServerSettings.timeouts.idleTimeout` in `HttpExt.bind`? It's ignored downstream in `StreamTcpManager.receive`!

**Comment by drewhk** [comment] 2015-10-09 17:15
Yes, we know. The proper timeout support just have been added in the last weeks and it will be hooked up with Http in the next release.

**Comment by hseeberger** [comment] 2015-10-09 17:17
Somehow I knew that this is no surprise for you ;-)

**Comment by drewhk** [comment] 2015-10-09 17:19
We needed missing infrastructure to do it properly, so yes, we knew and people complained righly :)

**Comment by hseeberger** [comment] 2015-10-09 17:22
Missing infrastructure? How can this have happened? AFAIK the Akka team has 1000s of members, so you should be able to fix any issues in advance ... ;-)

**Comment by patriknw** [comment] 2015-10-09 17:28
Lol, PRs are welcome ;-)

**Comment by hseeberger** [comment] 2015-10-09 17:31
Ah, no, wait a moment, ... PRs are too much work, you know, ..., but complaining is easy, bla bla ;-)

**Comment by ktoso** [comment] 2015-10-09 20:12
This is a duplicate of both https://github.com/akka/akka/issues/17732 and https://github.com/akka/akka/issues/16597
Yes, we'll work on it, infra is here now.

**Closed by ktoso** 2015-10-09 20:12 UTC
