### ISSUE TITLE
Using StreamConverters.asOutputStream truncates output on 2.5.23

### ISSUE THREAD

**Issue by oxbowlakes** [akka/akka#28280] opened 2019-11-29 15:21 UTC
I seem to be hitting the same issue as #25983. This was fixed by a modification to OutputStreamSourceStage made by @raboof on Dec 18 2018 (https://github.com/akka/akka/commit/8e0d3e4c96ef64c77f8258284040fbe5e6b19f09) and was marked fixed for 2.5.21. 

However, I can see that issue 26136 was fixed by a commit (https://github.com/akka/akka/commit/b0b0865e4ccefa4bd90224b5f4576357a73b27cc#diff-3fc5b08f30cf4755b842061163961132) on Feb 7 which completely changes the class' implementation (and could conceivably have reintroduced the bug).

We are seeing (extremely occasional) truncation of output stream responses (i.e. issue #25983) with akka-http 10.1.8 / akka-stream 2.5.23. This is a real issue as the (now useless) response is being (legitimately) cached by an intermediate proxy layer, so this is not observed as a transient issue by our users. Here's the code where I write to an `OutputStream`:

      def pipe(f: OutputStream => Unit): Source[ByteString, Any] = {
        implicit val ec = blockingIoPool
        import gsa.shared.scala._

        StreamConverters.asOutputStream(15.seconds).mapMaterializedValue { os =>
          val metered = new CountingOutputStream(new BufferedOutputStream(os, 2 << 13))
          Future {
            val (_, d) = timed(scala.concurrent.blocking(f(metered)))
            finest(f"Piped response to query $q to $os in ${d.fractionalMillis}%,1fms")
            IOResult(metered.getCount, Success(Done))
          }.andThen {
            case _ =>
              try metered.flush() finally metered.close()
          }
        }
      }

I have checked and all `f`s we send to this function `flush` their input anyway. Our logs do not indicate any issues with writing the response stream

Do you have any suggestions as to how I may furnish you with any useful information to help you narrow it down?

**Comment by patriknw** [comment] 2019-12-10 08:38
Thanks for reporting.

@raboof do you have any thoughts on this?

**Comment by raboof** [comment] 2019-12-10 10:26
Looking at the new implementation I don't see a way how it could successfully complete without the outputstream completing, so I wouldn't expect problems in that area.

What could happen is the `close` call somehow arriving earlier than the last data: while I'm pretty sure that would be caused by improper use of the outputstream, I don't think we produce a clear error message in that case. @oxbowlakes could you review the `f` code that uses the `OutputStream` to see if something like that could happen? Perhaps add a `os.close()` that is triggered from the same thread the produces the data, if that is possible?

The most useful way to narrow this down further is if we could come up with some kind of (stress) test that reliably reproduces the problem in isolation... but I know that's easier said than done.

**Comment by oxbowlakes** [comment] 2019-12-11 17:15
I have double checked and there are no calls to `close` within `f`. Are you suggesting that I make the change to this?

        StreamConverters.asOutputStream(15.seconds).mapMaterializedValue { os =>
          Future {
            val (count, d) = timed(scala.concurrent.blocking{
              Using.resource(new CountingOutputStream(new BufferedOutputStream(os, 2 << 13))) { metered =>
                f(metered)
                metered.flush()
                metered.getCount
              }
            })
            finest(f"Piped response of $count%,d bytes to query $q to $os in ${d.fractionalMillis}%,1fms")
            IOResult(count, Success(Done))
          }
        }

**Comment by raboof** [comment] 2020-01-03 13:18
I was thinking of parallelism problems inside of `f`.

Perhaps you could make the `CountingOutputStream` a bit more strict with something like:

```
public final class CountingOutputStream extends FilterOutputStream {
  private volatile boolean closed = false;
  private long count;

  /**
   * Wraps another output stream, counting the number of bytes written.
   *
   * @param out the output stream to be wrapped
   */
  public CountingOutputStream(OutputStream out) {
    super(checkNotNull(out));
  }

  /** Returns the number of bytes written. */
  public long getCount() {
    return count;
  }

  @Override
  public void write(byte[] b, int off, int len) throws IOException {
    if (closed) { throw new IllegalStateException("got write after close"); };
    out.write(b, off, len);
    count += len;
  }

  @Override
  public void write(int b) throws IOException {
    if (closed) { throw new IllegalStateException("got write after close"); };
    out.write(b);
    count++;
  }

  // Overriding close() because FilterOutputStream's close() method pre-JDK8 has bad behavior:
  // it silently ignores any exception thrown by flush(). Instead, just close the delegate stream.
  // It should flush itself if necessary.
  @Override
  public void close() throws IOException {
    closed = true;
    out.close();
  }
}
```

Perhaps it might be helpful to add the `metered.getCount` to the log message to see if all bytes made it there?

**Comment by oxbowlakes** [comment] 2020-01-07 14:21
I can promise that there is literally zero parallelism within `f` in my code. Each `f` sequentially writes bytes to the `OutputStream` (representing a ZIP file) in the calling thread.

**Comment by raboof** [comment] 2020-01-07 14:31
Interesting, I cannot explain that from just looking at the code. The modified `CountingOutputStream` and logging `metered.getCount` might still be useful to further narrow down the source of the truncation, though a reliable reproducer would be valuable with or without it.

**Comment by raboof** [comment] 2020-09-01 15:16
I've put the reproducer in a test (https://github.com/akka/akka/compare/v2.5.23...raboof:reproduce-28280) but haven't been able to trigger the issue yet (also trying some variations).

I think we should close this for now since we don't have anything to go on, but if we can find a way to reproduce the issue we should definitely reopen.

**Closed by raboof** 2020-09-01 15:16 UTC
Labels: 1 - triaged, bug, t:stream
