### ISSUE TITLE
Akka Streams: Potential onComplete deadlock 

### ISSUE THREAD

**Issue by janlisse** [akka/akka#17507] opened 2015-05-18 14:44 UTC
Hello Akka-Team,

as proposed by Endre on the Akka mailing-list i'm creating this issue. 
I'm currently building a scraper system on top of Akka Streams. I have written a Flow that is able to follow paginated sites and scrape them in a loop.
For this i use a feedback loop with Merge/Unzip. As Endre stated the stream does not deadlock on elements/backpressure but it deadlocks on the completion signal. 
When all URL's are processed the stream never completes. OnComplete never gets invoked.
Is this the expected behaviour?
You can find a sample project with a Spec that demonstrates the problem [here](https://github.com/janlisse/akka-stream-oncomplete-deadlock)

**Comment by drewhk** [comment] 2015-05-18 15:52
This is the expected behavior, but this is not the desired behavior :) It is a tricky to workaround this.

**Comment by jrudolph** [comment] 2015-05-19 06:11
Original mailing-list topic: https://groups.google.com/forum/#!topic/akka-user/_ENOeHyeEF0

**Comment by jrudolph** [comment] 2015-05-19 06:21
In a naive scraping approach you would keep a queue of work items containing the pages you still need to scrape. The termination condition would then be that 1) no work is outstanding and 2) the queue is empty.

Using the stream setup you seem to distribute the work queue into the buffers of the participating stream elements and thus you cannot observe the above conditions at any single point. So if there's a solution, it would probably be to make that information locally accessible somehow by having some kind of "conductor" at some point which has enough information to terminate processing.

**Comment by drewhk** [comment] 2015-05-19 07:56
Another option would be to add a "poision pill" element that is sent as the last element in the original stream, and once it is observed at the feedback point it should close the stream. We don't have a built-in takeUntil stage right now but it is not hard to construct one.

**Comment by janlisse** [comment] 2015-05-19 08:25
How do i close the stream manually when the poison pill element is received?

**Comment by drewhk** [comment] 2015-05-19 08:44
You only need to close the feedback loop, since the other port of the merge has been closed. You can do this by adding a custom stage as the last stage of the feedback-arc (before the preferred port) that just finishes the stream when it sees the poison-pill.

**Comment by jrudolph** [comment] 2015-05-19 09:24
@drewhk in the simplest case the original stream may only contain one element (the "anchor" to start scraping). If the poison pill would be the next element the stream would be instantly closed.

**Comment by drewhk** [comment] 2015-05-19 09:29
ah, ok, it is adding recursively elements. Btw, if the depth limit of the recursion is static, then the best approach would be to unroll the loop. Iteration is hard to express with the current stages we have, I had some ideas around one year ago but was not implemented.

**Comment by drewhk** [comment] 2015-05-19 09:36
well, to be more precise, (nested) iteration is easy to express (doesn't need cycles in the graph), unbounded depth iteration is the hard one.

**Comment by drewhk** [comment] 2015-11-27 12:05
This is not a bug per se, closing.

**Closed by drewhk** 2015-11-27 12:05 UTC
Labels: 1 - triaged
