### ISSUE TITLE
Modularize release script

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17432] opened 2015-05-08 14:55 UTC
Instead of one master script containing every step:
- the substeps should be separate scripts, callable manually if needed, including the "revert all" step
- the master script should execute the substeps as it did before, but on failure should ask if you really want to revert. If not, the one responsible for the release can still continue manually, executing the rest of the steps, or reverting, as he sees fit.

**Comment by Captain1653** [comment] 2021-06-22 20:08
The issue is old. Is it still needed? I can try to do it, if you explain me.
1) Which master script do you mean?   I have found some [commit](https://github.com/akka/akka/commit/ceb888b9a7764e070ed637d5c7cd536c59052065). I can see the master script and Release.scala , but the commit is really old.  I can't find these files.
2) I have found some info in RELEASING.MD: 

> Release script instructions
Make sure you have completed the setup in project/scripts/release

Are these instructions actual ? I can't find any files or folders "release" in project/scripts.

3) Can I test some new script? I don't have Lightbend Whitesource credentials. The RELEASING.MD tells

> Make sure you have the Lightbend Whitesource credentials configured in your ~/.sbt/1.0/private-credentials.sbt

Kind regards

**Comment by patriknw** [comment] 2021-06-22 20:32
Thanks for offering your help. This is indeed old and the build has improved, including releases from CI. I'll close this.

**Closed** 2021-06-22 20:32 UTC
Labels: 1 - triaged, nice-to-have (low-prio), t:build
