### ISSUE TITLE
Remove actor context from calls in typed persistence

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25649] opened 2018-09-20 08:39 UTC
Having the ActorContext as a parameter to the command handler makes the methods unnecessarily long/complicated, we discussed this and decided  to remove it. If you need to use it you can wrap the persistent behavior with a `setup ( ctx => )` to close over the context.

**Comment by patriknw** [comment] 2018-09-20 08:51
@johanandren This is a duplicate of existing ticket 
https://github.com/akka/akka/issues/25620

**Closed by patriknw** 2018-09-20 08:51 UTC
Labels: 3 - in progress, t:typed
