### ISSUE TITLE
The commit of make ForkJoinPool asyncMode configurable has not real effect!

### ISSUE THREAD

**Issue by MQ-EL** [akka/akka#17488] opened 2015-05-14 13:22 UTC
In akka 2.3.11 version, it make ForkJoinPool asyncMode configurable, see #17429. But I don't think it works as expected!

In FJP, the asyncMode is used to control forked tasks, ***NOT*** external pushed tasks(look at the implemtation of FJP). The misuse of #17429 would mislead the user of akka, because the order of handling msgs in actor is not controlled by task-peeking-mode in conf file.
```shell
  # Setting to "FIFO" to use queue like peeking mode which "poll" or "LIFO" to use stack
  # like peeking mode which "pop".
     task-peeking-mode = "FIFO"
```

Look at my test code as follows, the output is the same:

```scala
import scala.concurrent.forkjoin.ForkJoinPool
//import java.util.concurrent.ForkJoinPool

object OrderTester extends App {  

  externalPush(true)
  Thread.sleep(2000)
  externalPush(false)
  Thread.sleep(2000)
  
    //mimic the way of akka using FJP
  def externalPush(mode: Boolean) ={
    val fjp = new ForkJoinPool(1, ForkJoinPool.defaultForkJoinWorkerThreadFactory, null, mode)
    (1 to 100).foreach{ i =>
      fjp.execute(new Runnable {
        override def run(): Unit = print(s"$i ")
      })
    }
    println
  }
}
```

The #17274 is a desired feature that i wanted. But due to the way of akka using FJP(always using execute method), the asyncMode is Hard to show it's power!

**Comment by drewhk** [comment] 2015-05-14 13:26
Ok, this had probably an effect before we reverted the code that used fork() because of the starvation bug. Currently it might not have any effect if you are right.

**Comment by MQ-EL** [comment] 2015-05-14 14:07
You can test my code. The reverted happened before this commit IMG. could you tell me the result of talk between of @viktorklang with Doug? thank you very much :)

**Comment by hepin1989** [comment] 2015-05-14 14:24
I think it would be a better way for us to hunting down all the issue with a better coming up mechanism other than like this,change ,revert ,change.

There must be a master ring to rule them all. 
we need more control and more flexibility.

netty's event loop will worth to take a look at,if we want to take this way ,other than rely on the forkjoin pool.

**Comment by viktorklang** [comment] 2015-05-14 14:26
Hi @MQ-EL, we (Doug & I) strongly suspect the situation for the starvation to be the priorization of the worker-local queue vs the striped external submission queues. Also, there is no true FIFO or LIFO in a system with work-stealing, multiple workers and multiple queues.

In the end I think the proper solution is to purpose-build a thread pool for Akka. This is highly non-trivial though. I have another chat with him about it next week.

**Comment by drewhk** [comment] 2015-05-14 14:32
I have also some prototype :)

**Comment by hepin1989** [comment] 2015-05-14 14:37
So we need a master ring,vote for this,and will the master ring,we could master them all.
http://img4.wikia.nocookie.net/__cb20131122154023/lotr/images/8/84/1357942144.jpg

**Comment by MQ-EL** [comment] 2015-05-14 14:38
Thanks @viktorklang , Waitting for the good news :)

**Comment by hepin1989** [comment] 2015-05-14 14:39
the discussion in netty
https://github.com/netty/netty/issues/2250

**Comment by hepin1989** [comment] 2015-05-14 14:51
one more thing the test on the current thread may be not right.
if i am not mess up something,in netty,they are using code like this.
```
            if (eventLoop.inEventLoop()) {
//do something
            } else {
                    eventLoop.execute(()->//do something);
                }
```

**Comment by viktorklang** [comment] 2015-05-14 14:53
@hepin1989 I'm not sure how that Netty Issue is related. Would you mind elaborating?

**Comment by hepin1989** [comment] 2015-05-14 15:38
@viktorklang one proposal then said is to have a task queue per Channel,which turn it like the akka module,but later them think that maybe not a good idea.in fact the Channel like Actor.

I have an idea,how about we tracking the send target and just following the graph?
like if A -> B -> C,we may loop A and then trying to loop B,and then trying to loop C.I think this more like we follow the message stream pipeline.

**Comment by viktorklang** [comment] 2015-05-14 15:42
@hepin1989 As you say, Actors are just like that (a Runnable with a message queue).

IT's an interesting idea to track the graph, but how would you handle fan-out/self-sends/remote-sends/etc? Also, what happens with respect to other queued Runnables? (Futures etc)

**Comment by hepin1989** [comment] 2015-05-14 16:02
for the fan out,like broadcast,(I haven't look very into stream),I think I could call ```fork``` will give more eventloop ,and I start to following that down,and if that target actor have a dedicated dispatcher,we just submit and stop following.

for self send,that just loop to self ,then it's a while like .

for remote send cause the task was just submit to the remote writer ,so I think we may need do something special .

this may like ```Depth First Search```,I just come with that idea and have't think hard about that.but If I try to write a executorpool for akka,I may want to try that way.

**Comment by hepin1989** [comment] 2015-05-14 20:02
how about we introduce a new marker trait like ```Forking```for Actor,then,all the task which caused by that actor will allowed to fork then.

**Comment by hepin1989** [comment] 2015-05-15 09:05
@MQ-EL why you closed this?

**Comment by MQ-EL** [comment] 2015-05-15 11:54
Have nothing else to discuss, did you

**Comment by MQ-EL** [comment] 2015-05-28 02:48
Hi @viktorklang, did you have chat with Doug?

**Comment by viktorklang** [comment] 2015-05-28 07:48
Hi @MQ-EL,

thanks for reminding me. I am currently waiting for him to send me a tweaked version of FJP that won't have the starvation bug.

The topic of an alternate implementation of a pool for Akka is currently on my private backlog.

**Comment by MQ-EL** [comment] 2015-05-28 07:58
It may be wait a long time to implement a new version of FJP.

```shell
  # Setting to "FIFO" to use queue like peeking mode which "poll" or "LIFO" to use stack
  # like peeking mode which "pop".
     task-peeking-mode = "FIFO"
```
Could you tell me does it have a real effect?

**Comment by viktorklang** [comment] 2015-05-28 08:00
AFAIK this wouldn't change anything as there is a difference between
worker-local-task-queues and the striped external submission queues.

On Thu, May 28, 2015 at 9:58 AM, qian miao <notifications@github.com> wrote:

> It may be wait a long time to implement a new version of FJP.
>
>   # Setting to "FIFO" to use queue like peeking mode which "poll" or "LIFO" to use stack
>   # like peeking mode which "pop".
>      task-peeking-mode = "FIFO"
>
> Could you tell me does it have a real effect?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akka/akka/issues/17488#issuecomment-106222137>.
>



-- 
Cheers,
√

**Comment by MQ-EL** [comment] 2015-05-28 08:12
TYVM

**Closed** 2015-05-28 08:42 UTC
Labels: 1 - triaged, t:core
