### ISSUE TITLE
Durable store LMDB corruption

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28923] opened 2020-04-15 09:19 UTC
Seen in the wild but not repeatable as far as we know.

Repeats for a while and then ends up with a segfault crashing the JVM

```
org.lmdbjava.LmdbNativeException$PageCorruptedException: located page was wrong type (-30796) 
    at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:73) 
    at org.lmdbjava.Dbi.put(Dbi.java:432) 
    at akka.cluster.ddata.LmdbDurableStore.dbPut(DurableStore.scala:277) 
    at akka.cluster.ddata.LmdbDurableStore.writeBehind(DurableStore.scala:294) 
    at akka.cluster.ddata.LmdbDurableStore$$anonfun$active$1.applyOrElse(DurableStore.scala:265) 
    at akka.actor.Actor.aroundReceive(Actor.scala:534) 
    at akka.actor.Actor.aroundReceive$(Actor.scala:532) 
    at akka.cluster.ddata.LmdbDurableStore.aroundReceive(DurableStore.scala:113) 
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573) 
    at akka.actor.ActorCell.invoke$$original(ActorCell.scala:543) 
    at akka.actor.ActorCell.invoke(ActorCell.scala:61) 
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269) 
    at akka.dispatch.Mailbox.run$$original(Mailbox.scala:230) 
    at akka.dispatch.Mailbox.run(Mailbox.scala:32) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
    at java.lang.Thread.run(Thread.java:748) 
```

**Comment by patriknw** [comment] 2020-10-05 09:50
We need some way (or hint) of how to reproduce this. Closing since we will not be able to make progress with current information.

**Closed by patriknw** 2020-10-05 09:50 UTC
Labels: 0 - new, bug, obsolete – reopen if necessary, t:cluster-ddata
