### ISSUE TITLE
case class validation rejection is not handled by ValidationRejection

### ISSUE THREAD

**Issue by 1mdc** [akka/akka#20658] opened 2016-05-30 01:32 UTC
I use akka http 2.4.6 to make a small micro web service. I made a custom rejection handles:

```
.handle {
      case MalformedRequestContentRejection(msg, _) ⇒
        completeWithCors((BadRequest, "The request content was malformed: " + msg))
    }
```
...
```
.handle { case ValidationRejection(msg, _) ⇒ completeWithCors((BadRequest, msg)) }
```

my my case class
```
case class LoginMessage(username: String,
                        password: String) {
  require(3 <= username.length && username.length <= 255, "username must be between 3 and 255")
  require(6 <= password.length && password.length <= 255, "password must be between 6 and 255")
}
```
failed require goes into `MalformedRequestContentRejection`

**Comment by ktoso** [comment] 2016-05-30 13:59
Thanks for reporting!

"Works as designed" would be one way to answer here actually.
The default exception handler does not handle `IllegalArgumentException` in any special way, thus no rejection is created, you could have to write an ExceptionHandler, not a Rejection handler to handle this case.

I think `require` in case classes is a popular pattern enough that we can support it, i.e. add a handler to the default `ExceptionHandler` for `IllegalArgumentException`. Opinions @2beaucoup @jrudolph @sirthias ?

This is a good ticket to get started looking at RejectionHandling infra etc.
Fixing should be relatively simple, and starts out by adding:

```scala
      case ex: IllegalArgumentException ⇒ ctx ⇒ { // special handling require() throws (often used in object construction validation)
        //   ...   
        ctx.reject(...)
      }
```

FYI @krzemin @note @kwyczesany @pjazdzewski1990

**Comment by 2beaucoup** [comment] 2016-05-30 14:06
This "should work". (#15792)

@1mdc How do you unmarshal your case class?

**Comment by 1mdc** [comment] 2016-05-30 14:19
@ktoso Thanks for the response. 

http://doc.akka.io/docs/akka/2.4.6/scala/http/routing-dsl/case-class-extraction.html
`If you write your validations like this Akka HTTP's case class extraction logic will properly pick up all error messages and generate a ValidationRejection if something goes wrong`
In my understanding, should it be handled by ValidationRejection?
This is my extraction:
```scala
entity(as[LoginMessage]) { loginMessage =>
...
}
```

@2beaucoup I use json4s

**Comment by 2beaucoup** [comment] 2016-05-30 14:56
The docs you cited are about parameter extraction. For a `ValidationRejection` thrown by `entity` your unmarshaller needs to correctly buuble up `InvalidArgumentException`s.

> @2beaucoup I use json4s

How? Via https://github.com/hseeberger/akka-http-json?

**Comment by 1mdc** [comment] 2016-05-30 15:41
@2beaucoup Yes. Something like this:
```scala
import de.heikoseeberger.akkahttpjson4s.Json4sSupport
import org.json4s.{Formats, jackson}

trait MySerialization extends Json4sSupport  {
  implicit val formats: Formats = org.json4s.DefaultFormats
}
```

**Comment by 2beaucoup** [comment] 2016-05-30 21:54
I see. The problem is that json4s nests these exceptions two levels deep in `MappingException` / `InvocationTargetException`. So either json4s or akka-http-json is changed to unwrap them or you wrap the unmarshaller and do the extraction yourself.

**Comment by 2beaucoup** [comment] 2016-05-31 14:33
I submitted a fix in akka-http-json.

**Comment by ktoso** [comment] 2016-05-31 15:53
Awesome, I think that'd be the right place to solve it in any case.
I think we can close this ticket then since the unwrap reflection exceptions PR https://github.com/hseeberger/akka-http-json/issues/68 was merged.

Thanks a lot @2beaucoup !

**Closed** 2016-05-31 15:53 UTC
Labels: 1 - triaged, easy-to-contribute, t:http:server:dsl
