### ISSUE TITLE
Stashing in typed actors

### ISSUE THREAD

**Issue by dbolotin** [akka/akka#23161] opened 2017-06-14 13:14 UTC
Are there any plans to implement unified way to create typed behaviours which will `stash` unhandled messages until not-`same` behaviour is returned by underlying behaviour; in which case it forwards buffered messages to returned behaviour. This looks like a super common pattern.

**Comment by patriknw** [comment] 2017-06-15 11:25
Stash is useful in classic untyped actors because it's a convenient way of restoring the original `sender` when unstashing. In Typed there is no sender so the main advantage disappears. Instead it's better to use an internal buffer, that you also have full control of.

Closing this as a duplicate of https://github.com/akka/akka/issues/22275

**Closed by patriknw** 2017-06-15 11:25 UTC
