### ISSUE TITLE
InputStreamPublisher should immediately emit data only when there's available demand

### ISSUE THREAD

**Issue by fsat** [akka/akka#19256] opened 2015-12-22 05:06 UTC
I have encountered the following exception when using `StreamConverters.fromInputStream`:

```
2015-12-22T04:51:10Z 6135c7857c85 ERROR ActorSystemImpl ActorSystem(conductr) - Outgoing response stream error
java.lang.IllegalStateException: onNext is not allowed when the stream has not requested elements, totalDemand was 0
	at akka.stream.actor.ActorPublisher$class.onNext(ActorPublisher.scala:182) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.jar:na]
	at akka.stream.impl.io.InputStreamPublisher.onNext(InputStreamPublisher.scala:30) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.jar:na]
	at akka.stream.impl.io.InputStreamPublisher.readAndEmit(InputStreamPublisher.scala:67) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.jar:na]
	at akka.stream.impl.io.InputStreamPublisher.readAndSignal(InputStreamPublisher.scala:49) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.jar:na]
	at akka.stream.impl.io.InputStreamPublisher$$anonfun$receive$1.applyOrElse(InputStreamPublisher.scala:43) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[com.typesafe.akka.akka-actor_2.11-2.3-bin-rp-15v09p03i03.jar:na]
	at akka.stream.impl.io.InputStreamPublisher.akka$stream$actor$ActorPublisher$$super$aroundReceive(InputStreamPublisher.scala:30) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.jar:na]
	at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:309) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.jar:na]
	at akka.stream.impl.io.InputStreamPublisher.aroundReceive(InputStreamPublisher.scala:30) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:520) ~[com.typesafe.akka.akka-actor_2.11-2.3-bin-rp-15v09p03i03.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:489) ~[com.typesafe.akka.akka-actor_2.11-2.3-bin-rp-15v09p03i03.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) ~[com.typesafe.akka.akka-actor_2.11-2.3-bin-rp-15v09p03i03.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) ~[com.typesafe.akka.akka-actor_2.11-2.3-bin-rp-15v09p03i03.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66-internal]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66-internal]
```

I believe `InputStreamPublisher` need to read & emit when there's a demand.

**Comment by sirthias** [comment] 2015-12-22 10:41
I get this error as well with http and streams 2.0.
It ends up killing persistent connections very quickly, even if there is currently request or response traffic active, thus making HTTP in 2.0 not really usable!

**Comment by drewhk** [comment] 2015-12-22 12:44
@sirthias where in HTTP do you use InputStreamPublisher? Or what do you mean?

**Comment by drewhk** [comment] 2015-12-22 12:45
@sirthias in fact, there is no ActorPublisher used AFAIK in the HTTP server. Do you have a reproducer?

**Comment by drewhk** [comment] 2015-12-22 12:53
I see, this happens on serving static resources. Dang. How did this pass tests?

**Comment by sirthias** [comment] 2015-12-22 12:55
I don't know, we must have a test hole somewhere...

**Comment by drewhk** [comment] 2015-12-22 12:58
I cannot work on it right now. Probably something easy to fix though. I think we might want to release a quick patch for this. I might try it tomorrow.

**Comment by sirthias** [comment] 2015-12-22 13:00
Ok. Yeah, I think this shouldn't be hard to dig up and fix.
It'll be interesting to see why this wasn't caught so far. Maybe we need a test serving some larger static input. I'll submit a a PR with a reproducer later today.

**Comment by ktoso** [comment] 2015-12-22 13:01
I just arrived at my other flat. Will work on this soon.

**Comment by ktoso** [comment] 2015-12-22 13:32
Thanks @sirthias for PR with reproducer, in the meantime I'll start looking into this right away.
We'll need to release a minor to fix this it seems :~

**Comment by sirthias** [comment] 2015-12-22 13:45
I tried creating a reproducer but am getting too frustated by akka dispatcher magic.
I'll have to let this go and turn to a few other things I need to get done today. Sorry, guys!

**Comment by jrudolph** [comment] 2015-12-22 14:11
The problem is that `Continue` messages are scheduled regardless of whether there is still one in flight. So, either the fix is to check the demand in `readAndSignal` or, while handling `Request`, call `readAndSignal` only when there was no previous demand.

**Comment by jrudolph** [comment] 2015-12-22 14:18
And, indeed it is more likely to happen with more data because every `Request` that comes in with a `Continue` outstanding will create another chain of `Continue`s.

Here's a log from InputStreamPublisher (I parameterized Continue with the total demand at the time it was dispatched):

```
681039489 Got request(16) demand now 16
681039489 Sending out Continue(15)
681039489 after servicing request(16) demand now 15
681039489 Got continue(15) with 15
681039489 Sending out Continue(14)
681039489 After continue(15) with 14
681039489 Got continue(14) with 14
681039489 Sending out Continue(13)
681039489 After continue(14) with 13
681039489 Got continue(13) with 13
681039489 Sending out Continue(12)
681039489 After continue(13) with 12
681039489 Got continue(12) with 12
681039489 Sending out Continue(11)
681039489 After continue(12) with 11
681039489 Got continue(11) with 11
681039489 Sending out Continue(10)
681039489 After continue(11) with 10
681039489 Got continue(10) with 10
681039489 Sending out Continue(9)
681039489 After continue(10) with 9
681039489 Got continue(9) with 9
681039489 Sending out Continue(8)
681039489 After continue(9) with 8
681039489 Got continue(8) with 8
681039489 Sending out Continue(7)
681039489 After continue(8) with 7
681039489 Got continue(7) with 7
681039489 Sending out Continue(6)
681039489 After continue(7) with 6
681039489 Got continue(6) with 6
681039489 Sending out Continue(5)
681039489 After continue(6) with 5
681039489 Got continue(5) with 5
681039489 Sending out Continue(4)
681039489 After continue(5) with 4
681039489 Got continue(4) with 4
681039489 Sending out Continue(3)
681039489 After continue(4) with 3
681039489 Got continue(3) with 3
681039489 Sending out Continue(2)
681039489 After continue(3) with 2
681039489 Got continue(2) with 2
681039489 Sending out Continue(1)
681039489 After continue(2) with 1
681039489 Got request(8) demand now 9
681039489 Sending out Continue(8) <-- here a new chain of Continues is started
681039489 after servicing request(8) demand now 8 
681039489 Got continue(1) with 8 <-- this is from the old chain
681039489 Sending out Continue(7)
681039489 After continue(1) with 7
681039489 Got continue(8) with 7 <-- this is from the new chain but the demand doesn't equal the expected one
681039489 Sending out Continue(6)
681039489 After continue(8) with 6
681039489 Got continue(7) with 6
681039489 Sending out Continue(5)
681039489 After continue(7) with 5
681039489 Got continue(6) with 5
681039489 Sending out Continue(4)
681039489 After continue(6) with 4
681039489 Got continue(5) with 4
681039489 Sending out Continue(3)
681039489 After continue(5) with 3
681039489 Got continue(4) with 3
681039489 Sending out Continue(2)
681039489 After continue(4) with 2
681039489 Got continue(3) with 2
681039489 Sending out Continue(1)
681039489 After continue(3) with 1
681039489 Got continue(2) with 1
681039489 After continue(2) with 0
681039489 Got continue(1) with 0
681039489 After continue(1) with 0
[ERROR] [12/22/2015 13:03:31.620] [ServerTest-akka.actor.default-dispatcher-33] [ActorSystem(ServerTest)] Outgoing response stream error
java.lang.IllegalStateException: onNext is not allowed when the stream has not requested elements, totalDemand was 0
```

**Comment by jrudolph** [comment] 2015-12-22 14:21
Btw. I tripped on this while migrating the akka-http-websocket-chat which needs to serve the scala.js compiled javascript code. This code was fortunately big enough to trigger the bug very reliably after only a few tries... :)

**Comment by ktoso** [comment] 2015-12-22 14:23
Technically we should never attempt signaling onNext without checking totalDemand, too east to do something wrong (like here). And in addition we can avoid sending too many self messages, but that's a secondary thing. I'm in there as well now, are you planning to continue looking at this and send a PR or should I continue?

Seems we have the same plan and it's rather clear what is wrong, so trying to not duplicate efforts.

**Comment by jrudolph** [comment] 2015-12-22 14:32
I probably wouldn't get to fix it any time soon. When I tripped on it I just wanted to figure out what's going on (the code seemed so simple that I was surprised not to be able to spot it just from looking at it).

**Comment by ktoso** [comment] 2015-12-22 14:34
Yep, so I'll PR it today. Thanks for noticing guys.
I'll figure out when we ship a fix for this, may need to ping @rkuhn, hope he won't mind

**Closed** 2015-12-22 22:26 UTC
Labels: 3 - in progress, bug
