### ISSUE TITLE
[akka-http] Timeouts doesn't work

### ISSUE THREAD

**Issue by Darnok99** [akka/akka#17732] opened 2015-06-15 22:10 UTC
settings:
```
akka.http.client.connecting-timeout
akka.http.client.idle-timeout
akka.http.host-connection-pool.idle-timeout
```
Doesn't take any effect.

code (I'm using specs2):

```
   "should timeout after specified time" >> { implicit ee: EE =>
        val url = HttpRequest(uri = Uri("http://127.0.0.1:8080/"))
        val orig = ConnectionPoolSettings(system).copy(idleTimeout = 1.second)
        val clientSettings = orig.connectionSettings.copy(idleTimeout = 1.second)
        val settings = orig.copy(connectionSettings = clientSettings)
        val resultCode: Future[Int] = Http().singleRequest(url, settings = settings)(materializer).map(
            resp => {
              resp.status.intValue()
           }
        )
        resultCode must beEqualTo(200).await(retries = 0, timeout = 1 minute)
    }
```

server listening on http://127.0.0.1:8080/ is just waiting 90 seconds and responding with some string.
result of running that test is:

[error]    Timeout after 60 seconds (retries = 0, timeout = 1 minute) (HttpDownloadTest.scala:73)

It's quite big issue to me because when we connect this one with "max-open-connections" setting, app keeps throwing "Exceeded configured max-open-requests value of" errors.

**Comment by jrudolph** [comment] 2015-06-16 07:07
@sirthias what's the state on timeouts? Are timeouts unsupported and we still wait for a pluggable timeout implementation from akka-stream? If that's not going to be fixed soon we should document it somewhere or comment the settings for now.

**Comment by jrudolph** [comment] 2015-06-16 07:09
It seems #16597 should provide timeouts on the TCP level but it isn't yet implemented.

**Comment by drewhk** [comment] 2015-06-16 07:14
Yep, I don't think this will be implemented in 1.0

**Comment by Darnok99** [comment] 2015-06-16 07:34
Well, this one is causing mentioned "Exceeded configured max-open-requests value of [1024]" error (i've elaborated this one more here: https://groups.google.com/forum/#!topic/akka-user/ueiDGTMw3c0) any ideas how to walk around it? Right now i have to restart app every day do have it working which doesn/t seem to be any solution:)

**Comment by rkuhn** [comment] 2015-06-16 08:46
@drewhk At first I misunderstood the issue, we should look into it but bugs still have priority.

**Comment by sirthias** [comment] 2015-06-16 10:05
Yes, so far there is no timeout support whatsoever on the HTTP layer since we decided to rely on a general and reusable timeout flow element for 1-to-1 streams.
#16597 looks like the one.

**Comment by Darnok99** [comment] 2015-06-16 22:01
Thanks guys! Looking forward to see it working:)

2015-06-16 20:05 GMT+10:00 Mathias <notifications@github.com>:

**Comment by atamborrino** [comment] 2015-07-27 09:04
Any ideas of workaround until it is implemented to avoid the ""Exceeded configured max-open-requests value of [1024]" error" which is very annoying in production?

**Comment by Darnok99** [comment] 2015-07-27 09:08
@atamborrino 
I ended up with spray. It wasn't so bad to migrate there though.

**Comment by ktoso** [comment] 2015-10-20 12:36
This is now unblocked, thanks to https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/io/Timeouts.scala
Related: Timeouts will be moved out of `stream.io` (in case the above link breaks)

**Comment by rkuhn** [comment] 2015-10-20 12:45
The “broken link” is why I always link to the SHA1 instead of the branch name: https://github.com/akka/akka/blob/90bd5d681082a569b9ad82adb6df9efad9352b32/akka-stream/src/main/scala/akka/stream/io/Timeouts.scala

**Comment by ktoso** [comment] 2015-10-20 12:54
true dat :wink:

**Comment by ktoso** [comment] 2015-11-04 09:04
To close this ticket I'll want to implement tests for all styles of clients.

**Comment by ktoso** [comment] 2015-11-04 14:45
Reference to idleTimeout PR: https://github.com/akka/akka/pull/18770
Adding more client-side tests now.

**Comment by ktoso** [comment] 2015-11-04 17:36
I can confirm this to have been solved by the https://github.com/akka/akka/pull/18770 PR, and added some more tests in PR: https://github.com/akka/akka/pull/18854

**Comment by ktoso** [comment] 2015-11-16 09:32
Got a bug, would not detect "long writing of response" properly, working on it today.

**Comment by ktoso** [comment] 2015-11-30 14:22
This is fixed in M2

**Closed by ktoso** 2015-11-30 14:22 UTC
Labels: 3 - in progress, t:http, t:http:core
