### ISSUE TITLE
Can't remove/down inaccessible node from cluster

### ISSUE THREAD

**Issue by maqdev** [akka/akka#18474] opened 2015-09-15 10:26 UTC
I have cluster of 12 nodes (akka 2.3.11). Sometimes we need to down and remove nodes and sometimes this isn't graceful (because graceful shutdown is very hard #18344). However those nodes, that become inaccessible sometimes can't be removed even manually using JMX. Here is what I have in logs:

1. node is already inaccessible
`2015-09-15T12:35:05+03:00 Association with remote system [akka.tcp://eu-inn@cpb12-lc.local.com:10005] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://eu-inn@cpb12-lc.local.com:10005]] Caused by: [Connection refused: cpb12-lc.local.com/10.64.76.13:10005]`

2. I downed it manually through JMX (thourgh leader node) and got a confirmation in a log file
`2015-09-15T12:35:19+03:00 Cluster Node [akka.tcp://eu-inn@a001-lc.local.com:10000] - Marking node [akka.tcp://eu-inn@cpb12-lc.local.com:10005] as [Down]`

3. leader node trying to connect to that node after downing:
`2015-09-15T12:35:39+03:00 Association with remote system [akka.tcp://eu-inn@cpb12-lc.local.com:10005] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://eu-inn@cpb12-lc.local.com:10005]] Caused by: [Connection refused: cpb12-lc.local.com/10.64.76.13:10005]`

This leads to the situation that I can't joint that node after restart. Because I can't down existing node.
I'm not sure if this issue is the same as #17479

**Comment by patriknw** [comment] 2015-09-16 10:33
@maqdev so you say that the downed node is not removed from the cluster membership.
Do you see log entry starting with "Leader can currently not perform its duties"?
https://github.com/akka/akka/blob/release-2.3/akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala#L775

Do you have other unreachable nodes at this point, which have not been downed?

**Comment by maqdev** [comment] 2015-09-22 16:33
Hi @patriknw!

1. There were 4 nodes unreachable at the moment and I downed all of them, some of them a couple of times. 
2. At some point, after downing them I get the log entry with "Leader can currently not perform its duties". 
3. After some time I get the log entry "Leader can perform its duties again" but still continue getting messages that the nodes that I've downed are unreachable.

The situation was repeating each time I tried to down all nodes that were unreachable.

Here is full log with 4 nodes: https://gist.github.com/maqdev/233173364fb41a71ad58

**Comment by patriknw** [comment] 2015-09-23 15:15
you have truncated the lines in the log, e.g. "Leader can currently not perform its duties, reachability status: [], member status: [akka.tcp://eu-inn@a001-lc.local.com:10000 Up seen=true, akka.tcp://eu-inn@a002-lc.local.com:10000 Up s..."

I would be interested in the ...

It would be very helpful if you can package up a runnable example to reproduce the problem.

**Comment by maqdev** [comment] 2015-09-23 17:34
here is the full message, i've formatted it to be more readable:
```
Cluster Node [akka.tcp://eu-inn@a001-lc.local.com:10000] - Leader can currently not perform its duties, reachability status: [], member status: [
  akka.tcp://eu-inn@a001-lc.local.com:10000 Up seen=true, 
  akka.tcp://eu-inn@a002-lc.local.com:10000 Up seen=false, 
  akka.tcp://eu-inn@bss1-lc.local.com:10002 Up seen=false, 
  akka.tcp://eu-inn@bss2-lc.local.com:10002 Up seen=true, 
  akka.tcp://eu-inn@cpb10-lc.local.com:10004 Down seen=false, 
  akka.tcp://eu-inn@cpb10-lc.local.com:10005 Up seen=false, 
  akka.tcp://eu-inn@cpb11-lc.local.com:10004 Down seen=false, 
  akka.tcp://eu-inn@cpb11-lc.local.com:10005 Up seen=false, 
  akka.tcp://eu-inn@cpb12-lc.local.com:10004 Down seen=false, 
  akka.tcp://eu-inn@cpb12-lc.local.com:10005 Down seen=false, 
  akka.tcp://eu-inn@cpb5-lc.local.com:10004 Up seen=false, 
  akka.tcp://eu-inn@cpb5-lc.local.com:10005 Up seen=false, 
  akka.tcp://eu-inn@cpb7-lc.local.com:10004 Up seen=false, 
  akka.tcp://eu-inn@cpb7-lc.local.com:10005 Up seen=false, 
  akka.tcp://eu-inn@cpb8-lc.local.com:10004 Up seen=false, 
  akka.tcp://eu-inn@cpb8-lc.local.com:10005 Up seen=false,
  akka.tcp://eu-inn@cpb9-lc.local.com:10004 Up seen=true,
  akka.tcp://eu-inn@cpb9-lc.local.com:10005 Up seen=false, 
  akka.tcp://eu-inn@mks1-lc.local.com:10001 Up seen=false, 
  akka.tcp://eu-inn@mks2-lc.local.com:10001 Up seen=false
]
```

If the problem will repeate we will try to package it. Currently it's happening on production and this is complicated...

**Comment by patriknw** [comment] 2015-09-23 19:01
Thanks, the nodes marked as `Up seen=false` are interesting.
The leader will remove the downed nodes when all seen=true (excluding the Down nodes). seen=true means that those nodes have seen the current membership state, which is disseminated to all nodes in the cluster via a gossip protocol. We call that convergence.

The big question is why those nodes have not seen the current membership state? Could we not send gossip messages to them? If that was the case they would be marked as unreachable, and that is at least not indicated by that log.

One idea is that your cluster was unstable for a longer time, and nodes were marked unreachable/reachable back and forth and the cluster never reached convergence.

Did you see any log entries about "Marking node(s) as UNREACHABLE" and "Marking node(s) as REACHABLE" during the problematic period. It doesn't have to be on the leader node.

**Comment by maqdev** [comment] 2015-10-17 01:03
Hi! Sorry for a late answer. Sadly there is no logs for other nodes. But we have this (or similar situation again). The situation is complicated with other, not related to this issue things, but I'll try to extract what could matter.

One node `cpb10:10004` for some reason have marked other node `cpb11:10005` unreachable. 
```
2015-10-15T17:26:23+03:00
Cluster Node [akka.tcp://eu-inn@cpb10:10004] - Marking node(s) as UNREACHABLE [
  Member(address = akka.tcp://eu-inn@cpb11:10005, status = Up)
]
```
At that moment there is no any simptom that `cpb11:10005` was offline, it was fully working. Also there is no any such message from other nodes.

We see that this was processed on the leader node (string below is our log of MemberEvent):

```
2015-10-15T17:26:23+03:00
UnreachableMember(Member(address = akka.tcp://eu-inn@cpb11:10005, status = Up)) / uid#892777844
```

Some time later there is a message from leader that:

```
2015-10-15T17:26:38+03:00
Cluster Node [akka.tcp://eu-inn@a001:10000] - Leader can currently not perform its duties, reachability status: [
  akka.tcp://eu-inn@cpb10:10004 -> akka.tcp://eu-inn@cpb11:10005: Unreachable [Unreachable] (1)
], member status: [
  akka.tcp://eu-inn@a001:10000 Up seen=true, 
  akka.tcp://eu-inn@a002:10000 Up seen=true, 
  akka.tcp://eu-inn@bss1:10002 Up seen=true, 
  akka.tcp://eu-inn@bss2:10002 Up seen=true, 
  akka.tcp://eu-inn@cpb10:10004 Up seen=true, 
  akka.tcp://eu-inn@cpb10:10005 Up seen=true, 
  akka.tcp://eu-inn@cpb11:10004 Up seen=true, 
  akka.tcp://eu-inn@cpb11:10005 Up seen=false, 
  akka.tcp://eu-inn@cpb12:10004 Up seen=true, 
  akka.tcp://eu-inn@cpb12:10005 Up seen=true, 
  akka.tcp://eu-inn@cpb9:10004 Down seen=false, 
  akka.tcp://eu-inn@cpb9:10005 Up seen=true,
  akka.tcp://eu-inn@mks1:10001 Up seen=true, 
  akka.tcp://eu-inn@mks2:10001 Up seen=true
]
```

After this there is a repeating log messages on node `akka.tcp://eu-inn@cpb10:10004`, each 5 seconds:

```
2015-10-15T17:29:50+03:00
Cluster Node [akka.tcp://eu-inn@cpb10:10004] - Ignoring received gossip status from unreachable [
  UniqueAddress(akka.tcp://eu-inn@cpb11:10005,892777844)
] 
```

It seems that this node `cpb11:10005` is actually online is marked as `seen=false`. And there is no evidence that any other node is trying to reconnect to this node. (I will investigate on this statemenet more, have to lookup through all logs).

**Comment by patriknw** [comment] 2015-10-20 09:06
There is an unreachability observation `cpb10:10004 -> cpb11:10005` which is the reason for `Ignoring received gossip status from unreachable`. Then the question is why `cpb11:10005` is not marked as reachable again. If you would run with DEBUG loglevel we could see log messages such as:

    "Heartbeat to"
    "Heartbeat response from"

From that we could see if `cpb10:10004` is still trying to send heartbeats to `cpb11:10005`.

**Closed** 2016-03-09 14:40 UTC
Labels: obsolete – reopen if necessary, t:cluster-tools
