### ISSUE TITLE
`akka.dispatch.Mailboxes` is a package-private class

### ISSUE THREAD

**Issue by aoboturov** [akka/akka#22075] opened 2016-12-30 14:52 UTC
On Akka-2.4, apparently, it is not possible to extend the `akka.dispatch.DispatcherPrerequisites` trait because the `akka.dispatch.Mailboxes` is a package-private class. Was this done intentionally?

**Comment by aoboturov** [comment] 2016-12-30 14:54
One could, of course, use ` override def mailboxes = prerequisites.mailboxes` without a type, but still...

**Comment by patriknw** [comment] 2017-01-03 15:57
I agree that it should be

```scala
private[akka] def mailboxes: Mailboxes
```

Why would you need to extend `DispatcherPrerequisites`, @aoboturov ?

**Comment by aoboturov** [comment] 2017-01-03 16:11
As far as I can see, that's the only option to provide a custom
ThreadFactory via a Dispatcher Configurator.

**Comment by ktoso** [comment] 2017-06-13 10:03
What should we do with this one @patriknw ?
The issue is that `Mailboxes` is not reachable for classes outside the akka package, is extending this type something we want to allow?

**Comment by aoboturov** [comment] 2017-06-13 19:21
@ktoso - see https://github.com/akka/akka/issues/22075#issuecomment-269780204

**Comment by patriknw** [comment] 2017-06-15 11:40
Do I understand it correctly that the request is to be able to plugin a custom ThreadFactory (by having the implementation class in config)? What is the use case for that?

**Comment by ktoso** [comment] 2017-06-15 12:40
The reason I commented @aoboturov is because doing what is advice in the comment would not resolve the problem (rather, the class would have to be made public). I also would like to first understand the use case more in depth before we open up things more :-)

**Comment by aoboturov** [comment] 2017-06-15 12:46
@ktoso technically I don't need the `private[akka] def mailboxes: Mailboxes` anymore. The reason I have asked about it in the first place was the compilation problem for which there's an easy workaround... So you could close this ticket... The important part is that we're about to override the ThreadFactory.

**Comment by patriknw** [comment] 2017-06-15 12:56
ok, closing then

**Closed by patriknw** 2017-06-15 12:56 UTC
