### ISSUE TITLE
akka-persistence: support multiple configurations

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16635] opened 2015-01-11 17:03 UTC
after a bit of prototyping with akka-persistence we discovered that different types of persistent actors need either different settings for the same plugin, or different plugins altogether.

there is a "promise" of this feature in [Persistence.scala](https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/Persistence.scala#L89)

can we have it in 2.4?

**Comment by ktoso** [comment] 2015-01-11 17:07
Here's the ticket for it: https://github.com/akka/akka/issues/15587
It's very likely to be included as persistence gets stable, as the need for it has been voiced already and we'll also need it for the journal migration tool: https://github.com/akka/akka/issues/16332

Sounds like we can close this ticket as duplicate of #15587?

**Comment by hepin** [comment] 2015-01-11 17:11
need something like https://github.com/akka/akka/issues/16541 done before.
and then the persistent actor need to provide the plugin id or clazz to select the provider

**Comment by Andrei-Pozolotin** [comment] 2015-01-11 17:58
lets just do it now for 2.4

please suggest how do you see a) actor -> plugin mapper and b) multi config name space?
using ```persistenceId``` to resolve to plugin/config profile seems convoluted. 
how if we add to ```PersistentActor``` explicit configuration name:
```
/**
* Persistent actor configuration name. 
* Must be located in the following 'reference.conf' section:
* akka {
*    persistence {
*       configuration {
*          name { // User-provided custom configuration name.
*              journal { ... }
*              snapshot-store { ... }
*          }
*       }
*    }
* }
*/
def configuration: String = "" // Empty default for legacy config name space.
```

**Comment by patriknw** [comment] 2015-01-12 08:29
Please discuss this in the existing ticket, #15587

**Closed** 2015-01-12 08:29 UTC
Labels: 0 - new, t:persistence
