### ISSUE TITLE
Allow configuring resetDeadline for the stream restart count 

### ISSUE THREAD

**Issue by r-glyde** [akka/akka#29291] opened 2020-06-23 14:02 UTC
Currently the stream restart with backoff logic (for source, flow and sink) uses the `minBackoff` parameter to set a [`resetDeadline`](https://github.com/akka/akka/blob/ce07d5f15a94920a3ad75465a931326cf14fe065/akka-stream/src/main/scala/akka/stream/scaladsl/RestartFlow.scala#L228). I think this is to prevent restarts happening far apart from counting towards the same failure count?

I think it would be nice to have the option of configuring this deadline time as the `minBackoff` might not always make sense. We have times where the stream will not necessarily fail instantly but we would still like to restart it quickly (with a small `minBackoff`) and not leave it hanging for a long period of time (unless it is failing a lot and it is the larger backoff times that cause it to wait before restarting).

Happy to have a go at this if the above makes sense. Haven't looked through all the related code too much but was thinking of just introducing an overloaded method with the additional deadline parameter and the existing methods would just call that passing the `minBackoff` (which I think would keep binary compatibility?).

**Comment by patriknw** [comment] 2020-09-11 09:17
Very related, or duplicate of https://github.com/akka/akka/issues/29550

**Comment by r-glyde** [comment] 2020-09-12 12:17
Created #29591 with changes I made when I originally opened this issue (also now renaming the new parameter to `maxRestartsWithin` as suggested in #29550). Personally, I prefer the approach of defining a separate duration to bound the `maxRestarts` rather than defining multiple maxRestarts (total and bounded).

Don't mind if you want to close this in favour of #29550 or vice versa to keep discussion in one place?

**Comment by laszlovandenhoek** [comment] 2020-09-14 22:37
@r-glyde I agree that Patrik's suggestion is an improvement. I don't mind closing my issue (#29550) because it seems you already got more work in, including tests. What do you think about encapsulating the restart parameters in a separate object as I suggested? My intuition is that simply adding more "flat" parameters would cause an explosion in the number of methods in the Java API, but I haven't written it all out yet.

**Comment by r-glyde** [comment] 2020-09-14 23:35
Thanks @laszlovandenhoek - sorry should have pushed what I had a while ago but kept getting distracted by other things and never got round to finalising some bits to get it ready for a PR 🙂 

Yeah, I agree that all these overloaded methods are getting kind of unwieldy. Initially I was thinking of doing something similar  to how alpakka handles these sorts of settings e.g. [`ElasticsearchWriteSettings`](https://github.com/akka/alpakka/blob/a2762d2ee027bce87ddc5bf1caeab08bbc69b8e5/elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchWriteSettings.scala#L61). I don't think the additional method overloads are too bad right now but any future changes could probably make it worse so might be good to switch out for some separate settings class now that might be more manageable.

I think I should be able to have a go at this tomorrow so will update the PR and can see what direction if preferred.

**Comment by laszlovandenhoek** [comment] 2020-09-15 13:44
We've all been there :)

I'll keep tabs on your issues, I hope I can be of assistance.

**Comment by ennru** [comment] 2020-10-05 07:13
Fixed with https://github.com/akka/akka/pull/29591

**Closed by ennru** 2020-10-05 07:13 UTC
Labels: 1 - triaged, help wanted, t:stream
