### ISSUE TITLE
FAILED: RemoteReDeploymentSlowMultiJvmNode1

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20057] opened 2016-03-16 17:09 UTC
https://jenkins.akka.io:8498/job/akka-multi-node/1403/consoleFull

```
[JVM-2] - must terminate the child when its parent system is replaced by a new one *** FAILED *** (25 seconds, 602 milliseconds)
[JVM-2]   java.lang.AssertionError: assertion failed: timeout (15 seconds) during expectMsg while waiting for HelloParent
[JVM-2]   at scala.Predef$.assert(Predef.scala:165)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:349)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:335)
[JVM-2]   at akka.testkit.TestKit.expectMsg(TestKit.scala:734)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$7.apply$mcV$sp(RemoteReDeploymentSpec.scala:142)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:335)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(RemoteReDeploymentSpec.scala:138)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RemoteReDeploymentSpec.scala:100)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RemoteReDeploymentSpec.scala:100)
[JVM-2]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[JVM-2]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-2]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-2]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-2]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-2]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[JVM-2]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec.withFixture(RemoteReDeploymentSpec.scala:88)
[JVM-2]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[JVM-2]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[JVM-2]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[JVM-2]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[JVM-2]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec.runTest(RemoteReDeploymentSpec.scala:88)
[JVM-2]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[JVM-2]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[JVM-2]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
```

**Comment by patriknw** [comment] 2016-05-03 08:34
Duplicate of https://github.com/akka/akka/issues/20180

**Closed by patriknw** 2016-05-03 08:34 UTC
Labels: 1 - triaged, failed
