### ISSUE TITLE
simple ping pong performance degradation with scala 2.12.0

### ISSUE THREAD

**Issue by chenfengyuan** [akka/akka#21910] opened 2016-11-30 04:06 UTC
repo is [https://github.com/chenfengyuan/akka-ping-pong](https://github.com/chenfengyuan/akka-ping-pong)

Environment:

> hardware: 2015 macbook air
> cpu: 1.6 GHz Intel Core i5
> memory: 4G
> java version:
>> java version "1.8.0_102"
>> Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
>> Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

scala 2.11.8:
```
$ sbt assembly && java -jar target/scala-2.11/minimal-akka-scala-seed-assembly-1.0.jar
... 20000000 messages, 14366ms, 1392175.9710427397 msg/s
```

scala 2.12.0:
```
$ sed -ie 's/2.11.8/2.12.0/' build.sbt      # change scala version in build.sbt
$ sbt assembly && java -jar target/scala-2.12/minimal-akka-scala-seed-assembly-1.0.jar
...20000000 messages, 54785ms, 365063.4297709227 msg/s
```

result:
akka(2.4.14) with scala 2.11.8: 1392k messages per second
akka(2.4.14) with scala 2.12.0: 365k messages per second

Do I do something wrong? Or do i miss something import to update to scala 2.12? Thanks

**Comment by johanandren** [comment] 2016-11-30 08:30
I can verify a 10-40% throughput degradation with a simple ping-pong scenario.

**Comment by ktoso** [comment] 2016-11-30 11:06
Since we could reproduce I marked as triaged. @johanandren "Party Cannon" Anandren is working on it ;)

**Comment by johanandren** [comment] 2016-11-30 16:19
Profiling cpu and memory using yourkit did not show much, except `Dispatcher.dispatch` seeming to take more time, cpu load being lower. Snapshots of that data can be found over at the parallel Scala ticket: https://issues.scala-lang.org/browse/SI-10083

Theories tried:
* Object layout is different and causing false sharing or such: Analysis of the following classes did not show any differences: concrete actor, Actor, ActorCell, Dispatcher, MessageDispatcher, Mailbox
* Things aren't inlined like they used to: Tried to compare 2.11 and 2.12 runs using JitWatch, and there are differences but hard to find anything that obviously would cause the difference
* From Jason Zaugg - nesting became too deep for inlining, try with `-Xmixin-force-forwarders:true` - built a 2.12 artifact with that flag, no change
* aroundReceive is expensive - made actors with overridden aroundReceive not allocating a lambda, no change

Sample code project based on the reported one, but using nanoTime for relative time measurements: https://github.com/johanandren/akka-ping-pong (currently on a 1 thread threadpool dispatcher)

**Comment by johanandren** [comment] 2016-12-02 08:26
Got a hint about the lambda in aroundReceive not being cacheable, is in PR #21921 
Sadly did not help in this case.

**Comment by johanandren** [comment] 2016-12-05 10:24
Some progress from the Scala team, it seems to be that Scala 2.12 switched to the JDK ForkJoinPool while 2.11 still runs on a custom Scala-specific copy of it. Switching to the Java FJP on 2.11 yields the same performance degradation.

**Comment by ktoso** [comment] 2016-12-05 11:13
via @retronym:

> JDK8u40 and higher disable some spin waiting of worker threads before they block. The benchmark was a two-actor ping pong, so there are lots of other threads idle. The benchmark seems to heavily profit from avoiding the thread context switch by having idle cores "primed" with spin waiting workers.
> 
> https://bugs.openjdk.java.net/browse/JDK-8080623

We should try the scala pool with disabled spinning to see if that's the culprit.

**Comment by johanandren** [comment] 2016-12-05 13:07
Some more thorough numbers with varying load, on my 4core i7 mbp:

```
2.12.0
1  actor pairs exchanging a total of  20000000 messages,   763 940 msgs/s
2  actor pairs exchanging a total of  40000000 messages,   484 483 msgs/s
4  actor pairs exchanging a total of  80000000 messages, 3 311 294 msgs/s
8  actor pairs exchanging a total of 160000000 messages, 4 537 814 msgs/s
10 actor pairs exchanging a total of 200000000 messages, 4 641 624 msgs/s


2.11.8
1  actor pairs exchanging a total of  20000000 messages, 1 094 588 msgs/s
2  actor pairs exchanging a total of  40000000 messages, 2 395 987 msgs/s
4  actor pairs exchanging a total of  80000000 messages, 2 903 151 msgs/s
8  actor pairs exchanging a total of 160000000 messages, 4 260 798 msgs/s
10 actor pairs exchanging a total of 200000000 messages, 4 795 660 msgs/s
```

**Comment by jrudolph** [comment] 2017-02-23 09:06
@patriknw I cannot seem to find the ticket where better solutions for the `SPINS` constant were discussed. I found this thread where better configuration options are hinted at:

http://mail.openjdk.java.net/pipermail/core-libs-dev/2015-May/033570.html

> The interim fix is to turn off spinning. This has the effect of making questionable cases worse (e.g. parallel streams with an inappropriate small number elements).
>
> It will be back ported to 8u60 and it is planned that a better solution will be introduced in 9 (and time permitting it may be possible to backport that).

**Comment by patriknw** [comment] 2017-02-23 12:23
It was an internal Akka team email. I confirmed by embedding the JDK ForkJoinPool into Akka and compared `SPINS=0` and `SPINS=2048`. The CPU usage looked like this

`SPINS = 0`
![spins0](https://cloud.githubusercontent.com/assets/336161/23258971/0ec86d68-f9cb-11e6-952b-92a2b3852d5d.png)

`SPINS = 2048`
![spins2048](https://cloud.githubusercontent.com/assets/336161/23258974/12744eb4-f9cb-11e6-8e3c-484b06c1feb0.png)

```
JDK FJP with SPINS 0

[info] Benchmark                                                 (threads)  (tpt)   Mode  Cnt        Score         Error  Units
[info] ForkJoinActorBenchmark.pingPong                                   1      5  thrpt    5   698777.934 ±  317998.103  ops/s
[info] ForkJoinActorBenchmark.pingPongLessActorsThanCores                1      5  thrpt    5  2002343.459 ±  671949.374  ops/s
[info] ForkJoinActorBenchmark.pingPongMoreActorsThanCores                1      5  thrpt    5  7448264.278 ±  192248.600  ops/s
[info] ForkJoinActorBenchmark.pingPongSameNumberOfActorsAsCores          1      5  thrpt    5  5416995.471 ± 2455255.761  ops/s

JDK FJP with SPINS 2048

[info] Benchmark                                                 (threads)  (tpt)   Mode  Cnt        Score        Error  Units
[info] ForkJoinActorBenchmark.pingPong                                   1      5  thrpt    5  2370586.128 ±  48288.255  ops/s
[info] ForkJoinActorBenchmark.pingPongLessActorsThanCores                1      5  thrpt    5  3308543.227 ± 479569.999  ops/s
[info] ForkJoinActorBenchmark.pingPongMoreActorsThanCores                1      5  thrpt    5  7446020.046 ± 189666.629  ops/s
[info] ForkJoinActorBenchmark.pingPongSameNumberOfActorsAsCores          1      5  thrpt    5  9111954.676 ± 681838.504  ops/s
```

**Comment by patriknw** [comment] 2017-03-16 21:27
Fixed in https://github.com/akka/akka/pull/22560

**Closed by patriknw** 2017-03-16 21:27 UTC
Labels: 1 - triaged
