### ISSUE TITLE
Memory leak when running a stream defined with recursion

### ISSUE THREAD

**Issue by notxcain** [akka/akka#22352] opened 2017-02-21 10:26 UTC
Here is a simple reproducer that hits OOM because of growing `List[Attributes.Name]`
```scala
def rec: Source[Unit, Cancellable] =
  Source
    .tick(100.millis, 0.millis, ())
    .take(1)
    .flatMapConcat(_ => rec)
rec.runWith(Sink.ignore)
```

**Comment by jrudolph** [comment] 2017-02-21 12:47
Not sure if that's actually a bug. You create an ever increasing stream graph:

At first it's just these elements:

     Source
    .tick(100.millis, 0.millis, ())
    .take(1)
    .flatMapConcat(_ => rec)

after one tick, at least the flatMapConcat still needs to be alive (it has received complete from upstream but still needs to wait for elements from the inner source), so the graph basically looks like this:

    .flatMapConcat(_ => Source
    .tick(100.millis, 0.millis, ())
    .take(1)
    .flatMapConcat(_ => rec))

after another step it looks like that:

    .flatMapConcat(_ => 
    .flatMapConcat(_ =>  Source
    .tick(100.millis, 0.millis, ())
    .take(1)
    .flatMapConcat(_ => rec)))

So, the graph will grow an ever increasing number of graph elements.

(In fact, it's even worse as you probably observed: also the `tick` and `take` graph stages are still alive as stages fused together are also cleaned up together.)

The recommendation at least for long-running graphs is to use a bounded number of subgraphs.

I'd tend to close this as invalid.

**Comment by notxcain** [comment] 2017-02-21 12:50
@jrudolph I see, does this graph has the same unboundness problem?
```scala
def rec: Source[Unit, Cancellable] =
  Source
    .tick(100.millis, 0.millis, ())
    .take(1)
    .concat(Source.lazily(() => rec))
```

**Comment by jrudolph** [comment] 2017-02-21 12:50
Yes, I think so. The `Concat` stage is similar to `flatMapConcat` in that regard.

**Comment by notxcain** [comment] 2017-02-21 12:52
So how do I implement this semantics? Given that `rec` may have parameters that depends on previous stream?

**Comment by jrudolph** [comment] 2017-02-21 12:53
I think you need to show more of what you want to do. The stream you gave so far just makes no sense (it will never emit anything).

**Comment by notxcain** [comment] 2017-02-21 12:53
I know, Patrik asked for minimal reproducer, so I removed anything domain specific.

**Comment by notxcain** [comment] 2017-02-21 12:55
The original is [here](https://github.com/notxcain/aecor/pull/16/files#diff-04b1679960ac0abb561059c4bf62a79cR72)

**Comment by jrudolph** [comment] 2017-02-21 13:01
I think we would still need a reproducer to help you with that, just one that does something useful ;)

I guess the main question is if and why you need to run two or more streams at the same time. If you say that the new stream "depends on the previous stream", what does that mean exactly? Could you just run that stream to completion before starting the new stream? That would fix it.

If you have some cyclic logic, you could also create a cyclic graph with the new information feeding back to the start.

**Comment by notxcain** [comment] 2017-02-21 13:07
@jrudolph here is a source that scans a table
```scala
def entriesFrom(from: LocalDateTime): Source[ScheduleEntry, NotUsed] = {
  val now = LocalDateTime.now(clock)
  repository
    .getEntries(from, now)
    .concat(
      Source
      .tick(refreshInterval, refreshInterval, ())
      .take(1)
      .flatMapConcat { _ =>
        entriesFrom(now.minus(eventualConsistencyDelay.toMillis, ChronoUnit.MILLIS))
      }
    )
}
```

**Comment by jrudolph** [comment] 2017-02-22 10:06
Maybe something like:

```
   Source
      .tick(refreshInterval, refreshInterval, ())
      .statefulMapConcat { () =>
         var last = from
         {  _ => // ignore tick
           val start = last
           last = LocalDateTime.now(clock)
           List(repository.getEntries(start, last)) // List[Source[...]]
         }
      }.flatMapConcat(e => e)
```

**Comment by jrudolph** [comment] 2017-02-27 10:00
I'm closing this for now. I don't think this is a bug or problem in Akka. Still, it's an interesting case, so feel free to continue discussing it here on our other channels.

**Closed by jrudolph** 2017-02-27 10:00 UTC
Labels: 0 - new, t:stream

**Comment by notxcain** [comment] 2017-02-27 10:04
Sure, thanks!

**Comment by jrudolph** [comment] 2017-12-07 16:49
An incidental comment to a closed ticket ;)

I recently tried to understand why [linking](https://github.com/scala/scala/blob/2.13.x/src/library/scala/concurrent/impl/Promise.scala#L39) is necessary in the Futures implementation and that reminded me of this issue. Linking in the future implementation is necessary in a similar case than the one shown here: if you have a recursive chain of `flatMaps` with futures this could [lead to memory leaks](https://github.com/scala/bug/issues/7336) in Scala < 2.10.3. To fix that those links were introduced. The idea is that in an expression

```scala
val resFuture = 
  future1.flatMap {  x => 
    val future2 = 
       f(x).flatMap { y => 
          val future3 = g(y)
          future3
       }
    future2
  }
```

`resFuture`, `future2`, and `future3` can be used interchangibly. They represent the same eventual value (but are actually different `DefaultPromise` instances). Before the fix, `resFuture` was subscribed to `future2` and `future2` to `future3`. It's easy to see how that will lead to a memory leak if the chain of flatMaps is getting longer and longer in a recursive setup. After the fix the promises are reconnected so that (most of) the intermediary promises can be garbage collected.

In the end, this is basically tail-call optimization on the future level. If the result of a function call is the same as the result of the function it tail-calls, it's not necessary to keep the intermediary stack frame.

So, if we would want to solve the case in this ticket, it would probably be a similar solution in which an intermediary `flatMapConcat` stage would need to be able to remove itself out of the picture when it knows that it will only be passing elements back and forth.

That's easy to say but hard to be done because there's 1) no API to do this dynamic reconnecting of a stream layout and 2) even worse the implementation will be challenging because the links to be reconnected span multiple `GraphInterpreters` of the same `ActorGraphInterpreter` so an actual fix would have to be able to in-place refactor the state of the multiple interpreters of an `ActorGraphInterpreter`.
