### ISSUE TITLE
[akka-stream] Cycle detected although graph is cycle-free

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#16713] opened 2015-01-23 16:51 UTC
See https://github.com/hseeberger/roxxy/blob/master/src/main/scala/de/heikoseeberger/roxxy/Roxxy.scala#L63

**Comment by hseeberger** [comment] 2015-01-23 16:54
I have created the following Git tag, because I might change the respective code: https://github.com/hseeberger/roxxy/releases/tag/akka-issue-16713

**Comment by hseeberger** [comment] 2015-01-23 16:56
The error can be reproduced with the even simplified and obviously linear graph:

``` scala
    Flow() { implicit b =>
      import akka.stream.scaladsl.FlowGraphImplicits._
      //      b.allowCycles() // Needed to avoid cycle error, even though there's no cycle!
      source ~> proxyFlow ~> sink
      (source, sink)
    }
```

**Comment by drewhk** [comment] 2015-01-23 16:59
To clarify, obviously after the flow has been wired to the bind, i.e. the above code snippet is not the whole reproducer.

**Comment by hseeberger** [comment] 2015-01-23 17:06
Thanks, @drewhk, I have updated the above with some description.

**Comment by drewhk** [comment] 2015-01-26 11:10
Interesting, it only reports the cycle if the Httpoutgoing flow is used, but not for a dummy flow. Which is strange since the surrounding graph only wires the inputs and ouputs of the flow to an undefined sink or source

**Comment by drewhk** [comment] 2015-01-26 11:19
Ok, this is a duplicate of https://github.com/akka/akka/issues/16571

**Closed** 2015-01-29 12:28 UTC
Labels: bug, t:http, t:stream
