### ISSUE TITLE
nodes can talk after quarantine

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17555] opened 2015-05-22 10:49 UTC
Reproduced (does not always happen) with the remote-sample.

Start:

    sbt "run-main sample.remote.calculator.LookupApplication Calculator"
    sbt "run-main sample.remote.calculator.LookupApplication Lookup"

The log from the Lookup:

    [info] Running sample.remote.calculator.LookupApplication Lookup
    [INFO] [05/22/2015 09:41:16.648] [run-main-0] [Remoting] Starting remoting
    [INFO] [05/22/2015 09:41:16.845] [run-main-0] [Remoting] Remoting started; listening on addresses :[akka.tcp://LookupSystem@127.0.0.1:2553]
    [INFO] [05/22/2015 09:41:16.848] [run-main-0] [Remoting] Remoting now listens on addresses: [akka.tcp://LookupSystem@127.0.0.1:2553]
    Started LookupSystem
    Sub result: 77 - 89 = -12
    Sub result: 4 - 50 = -46
    Sub result: 15 - 88 = -73
    Sub result: 50 - 63 = -13
    Add result: 36 + 0 = 36
    Add result: 44 + 27 = 71
    Add result: 74 + 36 = 110
    Add result: 90 + 3 = 93
    Sub result: 41 - 7 = 34
    Add result: 28 + 45 = 73

    ### HERE I denied access to port 2552 with 
    (sudo pfctl -sr 2>/dev/null; echo "block drop quick on lo0 proto tcp from any to any port = 2552") | sudo pfctl -f - 2>/dev/null
    ###

    [WARN] [05/22/2015 09:41:38.878] [LookupSystem-akka.remote.default-remote-dispatcher-5] [akka.tcp://LookupSystem@127.0.0.1:2553/system/remote-watcher] Detected unreachable: [akka.tcp://CalculatorSystem@127.0.0.1:2552]
    [WARN] [05/22/2015 09:41:38.882] [LookupSystem-akka.remote.default-remote-dispatcher-6] [Remoting] Association to [akka.tcp://CalculatorSystem@127.0.0.1:2552] having UID [-1495856266] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote actorsystem must be restarted to recover from this situation.
    Calculator terminated
    [INFO] [05/22/2015 09:41:38.900] [LookupSystem-akka.actor.default-dispatcher-2] [akka://LookupSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FCalculatorSystem%40127.0.0.1%3A2552-0] Message [akka.remote.ReliableDeliverySupervisor$AttemptSysMsgRedelivery$] from Actor[akka://LookupSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FCalculatorSystem%40127.0.0.1%3A2552-0#-1956596514] to Actor[akka://LookupSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FCalculatorSystem%40127.0.0.1%3A2552-0#-1956596514] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    [WARN] [05/22/2015 09:41:53.946] [LookupSystem-akka.remote.default-remote-dispatcher-5] [akka.tcp://LookupSystem@127.0.0.1:2553/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FCalculatorSystem%40127.0.0.1%3A2552-1] Association with remote system [akka.tcp://CalculatorSystem@127.0.0.1:2552] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://CalculatorSystem@127.0.0.1:2552]] Caused by: [connection timed out: /127.0.0.1:2552]
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Not ready yet
    Not ready yet
    Not ready yet
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    [WARN] [05/22/2015 09:41:56.937] [LookupSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://LookupSystem@127.0.0.1:2553/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FCalculatorSystem%40127.0.0.1%3A2552-2] Association with remote system [akka.tcp://CalculatorSystem@127.0.0.1:2552] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://CalculatorSystem@127.0.0.1:2552]] Caused by: [connection timed out: /127.0.0.1:2552]
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Not ready yet
    Not ready yet
    Not ready yet
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    [WARN] [05/22/2015 09:42:18.136] [LookupSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://LookupSystem@127.0.0.1:2553/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FCalculatorSystem%40127.0.0.1%3A2552-2] Association with remote system [akka.tcp://CalculatorSystem@127.0.0.1:2552] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://CalculatorSystem@127.0.0.1:2552]] Caused by: [connection timed out: /127.0.0.1:2552]
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Not ready yet
    Not ready yet
    Not ready yet
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    Not ready yet
    [ERROR] [05/22/2015 09:42:35.525] [LookupSystem-akka.remote.default-remote-dispatcher-6] [Remoting] Association to [akka.tcp://CalculatorSystem@127.0.0.1:2552] with UID [-1495856266] irrecoverably failed. Quarantining address.
    java.lang.IllegalStateException: Error encountered while processing system message acknowledgement buffer: [1 {0, 1}] ack: ACK[3, {}]
        at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:288)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:188)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    Caused by: java.lang.IllegalArgumentException: Highest SEQ so far was 1 but cumulative ACK is 3
        at akka.remote.AckedSendBuffer.acknowledge(AckedDelivery.scala:103)
        at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:284)
        ... 11 more

    [WARN] [05/22/2015 09:42:35.525] [LookupSystem-akka.remote.default-remote-dispatcher-6] [Remoting] Association to [akka.tcp://CalculatorSystem@127.0.0.1:2552] having UID [-1495856266] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote actorsystem must be restarted to recover from this situation.
    Calculator terminated
    [WARN] [05/22/2015 09:42:35.537] [LookupSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://LookupSystem@127.0.0.1:2553/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FCalculatorSystem%40127.0.0.1%3A2552-4/endpointWriter] AssociationError [akka.tcp://LookupSystem@127.0.0.1:2553] -> [akka.tcp://CalculatorSystem@127.0.0.1:2552]: Error [Invalid address: akka.tcp://CalculatorSystem@127.0.0.1:2552] [
    akka.remote.InvalidAssociation: Invalid address: akka.tcp://CalculatorSystem@127.0.0.1:2552
    Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system has a UID that has been quarantined. Association aborted.
    ]
    [WARN] [05/22/2015 09:42:35.538] [LookupSystem-akka.remote.default-remote-dispatcher-6] [Remoting] Tried to associate with unreachable remote address [akka.tcp://CalculatorSystem@127.0.0.1:2552]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: [The remote system has a UID that has been quarantined. Association aborted.]
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Not ready yet
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Not ready yet
    Not ready yet
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Not ready yet
    Remote actor not available: akka.tcp://CalculatorSystem@127.0.0.1:2552/user/calculator
    Not ready yet
    Not ready yet

    ### HERE I allowed access to port 2552 with 
    sudo pfctl -f /etc/pf.conf
    ###

    Add result: 42 + 86 = 128
    Sub result: 1 - 43 = -42
    Add result: 74 + 17 = 91
    Add result: 75 + 45 = 120
    Add result: 63 + 42 = 105
    Add result: 34 + 53 = 87
    Sub result: 87 - 69 = 18
    Add result: 46 + 67 = 113
    Add result: 48 + 35 = 83
    Sub result: 93 - 4 = 89
    Sub result: 43 - 49 = -6

Log from the Calculator:

    [info] Loading global plugins from /Users/patrik/.sbt/0.13/plugins
    [info] Loading project definition from /Users/patrik/dev/akka-2.3/akka-samples/akka-sample-remote-scala/project
    [info] Set current project to akka-sample-remote-scala (in build file:/Users/patrik/dev/akka-2.3/akka-samples/akka-sample-remote-scala/)
    [info] Running sample.remote.calculator.LookupApplication Calculator
    [INFO] [05/22/2015 09:41:12.805] [run-main-0] [Remoting] Starting remoting
    [INFO] [05/22/2015 09:41:13.008] [run-main-0] [Remoting] Remoting started; listening on addresses :[akka.tcp://CalculatorSystem@127.0.0.1:2552]
    [INFO] [05/22/2015 09:41:13.011] [run-main-0] [Remoting] Remoting now listens on addresses: [akka.tcp://CalculatorSystem@127.0.0.1:2552]
    Started CalculatorSystem - waiting for messages
    Calculating 77 - 89
    Calculating 4 - 50
    Calculating 15 - 88
    Calculating 50 - 63
    Calculating 36 + 0
    Calculating 44 + 27
    Calculating 74 + 36
    Calculating 90 + 3
    Calculating 41 - 7
    Calculating 28 + 45

    ### HERE I denied access to port 2552 with 
    (sudo pfctl -sr 2>/dev/null; echo "block drop quick on lo0 proto tcp from any to any port = 2552") | sudo pfctl -f - 2>/dev/null
    ###

    [INFO] [05/22/2015 09:41:49.023] [CalculatorSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://CalculatorSystem@127.0.0.1:2552/system/transports/akkaprotocolmanager.tcp0/akkaProtocol-tcp%3A%2F%2FCalculatorSystem%40127.0.0.1%3A58358-1] No response from remote. Handshake timed out or transport failure detector triggered.
    [WARN] [05/22/2015 09:41:49.044] [CalculatorSystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://CalculatorSystem@127.0.0.1:2552/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FLookupSystem%40127.0.0.1%3A2553-0] Association with remote system [akka.tcp://LookupSystem@127.0.0.1:2553] has failed, address is now gated for [5000] ms. Reason: [Disassociated]
    [INFO] [05/22/2015 09:42:35.536] [CalculatorSystem-akka.actor.default-dispatcher-2] [akka://CalculatorSystem/system/transports/akkaprotocolmanager.tcp0/akkaProtocol-tcp%3A%2F%2FCalculatorSystem%40127.0.0.1%3A58365-4] Message [akka.remote.transport.ProtocolStateActor$HandleListenerRegistered] from Actor[akka://CalculatorSystem/system/transports/akkaprotocolmanager.tcp0/akkaProtocol-tcp%3A%2F%2FCalculatorSystem%40127.0.0.1%3A58365-4#-1786127047] to Actor[akka://CalculatorSystem/system/transports/akkaprotocolmanager.tcp0/akkaProtocol-tcp%3A%2F%2FCalculatorSystem%40127.0.0.1%3A58365-4#-1786127047] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
    [ERROR] [05/22/2015 09:42:35.540] [CalculatorSystem-akka.remote.default-remote-dispatcher-5] [akka.tcp://CalculatorSystem@127.0.0.1:2552/system/endpointManager/endpointWriter-akka.tcp%3A%2F%2FLookupSystem%40127.0.0.1%3A2553-2] AssociationError [akka.tcp://CalculatorSystem@127.0.0.1:2552] <- [akka.tcp://LookupSystem@127.0.0.1:2553]: Error [Invalid address: akka.tcp://LookupSystem@127.0.0.1:2553] [
    akka.remote.InvalidAssociation: Invalid address: akka.tcp://LookupSystem@127.0.0.1:2553
    Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system has quarantined this system. No further associations to the remote system are possible until this system is restarted.
    ]
    [WARN] [05/22/2015 09:42:35.545] [CalculatorSystem-akka.remote.default-remote-dispatcher-5] [Remoting] Tried to associate with unreachable remote address [akka.tcp://LookupSystem@127.0.0.1:2553]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: [The remote system has quarantined this system. No further associations to the remote system are possible until this system is restarted.]

    ### HERE I allowed access to port 2552 with 
    sudo pfctl -f /etc/pf.conf
    ###

    Calculating 42 + 86
    Calculating 1 - 43
    Calculating 74 + 17
    Calculating 75 + 45
    Calculating 63 + 42
    Calculating 34 + 53
    Calculating 87 - 69
    Calculating 46 + 67
    Calculating 48 + 35
    Calculating 93 - 4
    Calculating 43 - 49

**Comment by drewhk** [comment] 2015-05-27 10:17
Ok, I can reproduce it with a multi-jvm test.

**Comment by drewhk** [comment] 2015-05-27 10:47
Wait a minute. The firewall rule that you used only blocks one direction right? An existing outgoing connection is not affected right? Maybe that is where I should look.

**Comment by patriknw** [comment] 2015-05-27 10:53
Yes, I blocked all to one port

**Comment by patriknw** [comment] 2015-05-27 10:55
Perhaps the real scenario was caused by quarentine on one side?

**Comment by drewhk** [comment] 2015-05-27 11:56
what is interesting is the log line 

    Caused by: java.lang.IllegalArgumentException: Highest SEQ so far was 1 but cumulative ACK is 3

**Comment by drewhk** [comment] 2015-05-27 12:44
I cannot reproduce this no matter how I try given the tools I have. I give this back, someone that has a proper local firewall (non-Windows) should take a look.

**Comment by patriknw** [comment] 2015-09-03 11:28
@drewhk I guess we can't close this, since we have not really reproduced it and can't explain the seq nr issues

**Comment by drewhk** [comment] 2015-09-03 11:31
Yes, definitely. There is still something else lurking here.

**Comment by patriknw** [comment] 2016-03-15 12:35
Might be related to https://github.com/akka/akka/pull/20033 but since I can't see that we restart the actor system in these tests it might be something else.

**Comment by marekzebrowski** [comment] 2016-03-23 08:30
Maybe I just encountered this (on production of course)
```
04:22:09.911 [sgActors-akka.actor.default-dispatcher-72] ERROR a.r.Remoting: Association to [akka.tcp://sgActors@app-backend1.sgrouples.com:2552] with UID [1391076812] irrecoverably failed.
 Quarantining address.
java.util.concurrent.TimeoutException: Remote system has been silent for too long. (more than 120.0 hours)
        at akka.remote.ReliableDeliverySupervisor$$anonfun$idle$1.applyOrElse(Endpoint.scala:367) ~[akka-remote_2.11-2.4.2.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.2.jar:na]
        at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:192) ~[akka-remote_2.11-2.4.2.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.2.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
04:22:09.911 [sgActors-akka.actor.default-dispatcher-72] WARN  a.r.Remoting: Association to [akka.tcp://sgActors@app-backend1.sgrouples.com:2552] having UID [1391076812] is irrecoverably fa
iled. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote actorsystem must be restarted to recover from this situation.
04:22:09.911 [sgActors-akka.actor.default-dispatcher-72] WARN  m.s.l.r.QuarantineListener: Actorsystem akka.tcp://sgActors@app-backend1.sgrouples.com:2552 has been quarantined, please resta
rt it
04:22:10.116 [sgActors-akka.actor.default-dispatcher-105] WARN  a.r.ReliableDeliverySupervisor: Association with remote system [akka.tcp://sgActors@app-backend1.sgrouples.com:2552] has fail
ed, address is now gated for [1000] ms. Reason: [Disassociated]
04:22:10.128 [sgActors-akka.actor.default-dispatcher-11642] ERROR a.r.Remoting: Association to [akka.tcp://sgActors@app-backend1.sgrouples.com:2552] with UID [950432683] irrecoverably faile
d. Quarantining address.
java.lang.IllegalStateException: Error encountered while processing system message acknowledgement buffer: [-1 {}] ack: ACK[6, {}]
        at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:291) ~[akka-remote_2.11-2.4.2.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.2.jar:na]
        at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:192) ~[akka-remote_2.11-2.4.2.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.2.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.2.jar:na]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: java.lang.IllegalArgumentException: Highest SEQ so far was -1 but cumulative ACK is 6
        at akka.remote.AckedSendBuffer.acknowledge(AckedDelivery.scala:103) ~[akka-remote_2.11-2.4.2.jar:na]
        at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:287) ~[akka-remote_2.11-2.4.2.jar:na]
        ... 11 common frames omitted
```
on the other node:
```
04:22:09.202 [sgActors-akka.actor.default-dispatcher-41] INFO  m.s.s.r.SearchRefresherPosts$RefreshWorker: Removing 3 records...
04:22:10.850 [sgActors-akka.actor.default-dispatcher-51] ERROR a.r.EndpointWriter: AssociationError [akka.tcp://sgActors@app-backend1.sgrouples.com:2552] <- [akka.tcp://sgActors@app2.sgroup
les.com:2552]: Error [Invalid address: akka.tcp://sgActors@app2.sgrouples.com:2552] [
akka.remote.InvalidAssociation: Invalid address: akka.tcp://sgActors@app2.sgrouples.com:2552
Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system has quarantined this system. No further associations to the remote system are possible until this system is restarted.
]
04:22:10.851 [sgActors-akka.actor.default-dispatcher-51] WARN  a.r.Remoting: Tried to associate with unreachable remote address [akka.tcp://sgActors@app2.sgrouples.com:2552]. Address is now gated for 1000 ms, all messages to this address will be delivered to dead letters. Reason: [The remote system has quarantined this system. No further associations to the remote system are possible until this system is restarted.]
04:22:10.852 [sgActors-akka.actor.default-dispatcher-51] ERROR m.s.l.r.QuarantineListener: This Actor system become quarantined by akka.tcp://sgActors@app2.sgrouples.com:2552, no future work is possible on this node, restart
04:22:11.113 [sgActors-akka.actor.default-dispatcher-51] ERROR a.r.EndpointWriter: AssociationError [akka.tcp://sgActors@app-backend1.sgrouples.com:2552] <- [akka.tcp://sgActors@app2.sgrouples.com:2552]: Error [Invalid address: akka.tcp://sgActors@app2.sgrouples.com:2552] [
akka.remote.InvalidAssociation: Invalid address: akka.tcp://sgActors@app2.sgrouples.com:2552
Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system has quarantined this system. No further associations to the remote system are possible until this system is restarted.
```
until node gets restarted...

It might be https://github.com/akka/akka/issues/19780 as well

**Comment by drewhk** [comment] 2016-03-23 08:40
This does not seem similar to me. This is one system quarantining the other because:
 - there were system message traffic between the two systems before, so there is state to be preserved (sequence number state)
 - there were no communication between these systems for 5 days, so to avoid memory leaks caused by keeping state forever one system drops the resend state and then quarantines the other system.

You can change this 5 day timeout to a larger value if you want,

**Comment by drewhk** [comment] 2016-04-11 12:06
This seems to be related to the fixed issue: https://github.com/akka/akka/issues/19780

I close this for now and see if it happens again.

**Closed by drewhk** 2016-04-11 12:06 UTC
Labels: 1 - triaged, bug, t:remoting
