### ISSUE TITLE
Error handling only Resumes on first Exception, following exception causes IllegalStateException

### ISSUE THREAD

**Issue by l15k4** [akka/akka#16979] opened 2015-03-02 15:49 UTC
```
[info]     Cause: java.lang.IllegalStateException: Processor actor terminated abruptly
[info]     at akka.stream.impl.fusing.ActorInterpreter.postStop(ActorInterpreter.scala:288)
[info]     at akka.actor.Actor$class.aroundPostStop(Actor.scala:475)
[info]     at akka.stream.impl.fusing.ActorInterpreter.aroundPostStop(ActorInterpreter.scala:271)
[info]     at akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)
[info]     at akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)
[info]     at akka.actor.ActorCell.terminate(ActorCell.scala:369)
[info]     at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
[info]     at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
[info]     at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
[info]     at akka.dispatch.Mailbox.run(Mailbox.scala:220)
[info]     at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by l15k4** [comment] 2015-03-02 17:01
I reproduced it, it is not ActorPublisher related, it just happens when any *second* element processing throws exception... So that the first exception is handled, stream is resumed, but following exception leads to `IllegalStateException: Processor actor terminated abruptly` : 

```scala
    case class FlowEx(i: Int) extends Exception

    val decider: Supervision.Decider = {
      case FlowEx(i) =>
        println("supervisor " + i)
        Supervision.Resume
      case ex =>
        Supervision.Stop
    }

    implicit val materializer = ActorFlowMaterializer(
      ActorFlowMaterializerSettings(system).withSupervisionStrategy(decider)
    )

    val f = Source(List(2,3,3,3,3,3,3,3,3,3,4)).map { i =>
      if (i % 2 == 0)
        throw new FlowEx(i)
      else
        i
    }.runWith(Sink.fold(0)(_ + _) )

    whenReady(f) { r =>
      println("result " + r)
    }
```

**Comment by patriknw** [comment] 2015-03-03 07:49
Thanks for reporting

**Comment by bantonsson** [comment] 2015-03-03 11:00
@l15k4 Sorry for creating the duplicate. The root cause and discussion is in the other ticket so I'll close this one.

**Closed by bantonsson** 2015-03-03 11:00 UTC
Labels: 1 - triaged, bug, t:stream
