### ISSUE TITLE
move AkkaProvider for SecureRandom into akka-actor

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#13254] opened 2013-04-19 11:22 UTC
imported from https://www.assembla.com/spaces/akka/tickets/3254

* needed for test of SslTlsSupport which is currently in akka-remote for that reason
* we need to implement our own RNG to get rid of the uncommons-math dependency in this case

**Comment by patriknw** [comment] 2016-05-11 19:58
Closing as duplicate of #12636

**Closed by patriknw** 2016-05-11 19:58 UTC
Labels: t:core
