### ISSUE TITLE
Not possible to consume databytes of failing request after switch to akka 2.4.3

### ISSUE THREAD

**Issue by kstokoz** [akka/akka#20238] opened 2016-04-05 12:54 UTC
After upgrade from akka 2.4.2 to 2.4.3 future to consume body of failing request never complete.

Here is a small reproducer which failis with AccessDenied error in 2.4.2 and with future timeout in 2.4.3.

```
object ReproducerClientApp extends App {
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer(ActorMaterializerSettings.create(system).withDebugLogging(true))(system)
  import system.dispatcher

  val request =
    HttpRequest()
      .withMethod(HttpMethods.PUT)
      .withUri("https://bucketname.s3.amazonaws.com/key")
      .withEntity(HttpEntity.apply(ContentTypes.`application/json`, "{}"))

  val response =
    Http().singleRequest(request).flatMap { rs =>
      if (rs.status.isSuccess())
        Future.successful(Done)
      else
        rs.entity.dataBytes.runWith(Sink.reduce[ByteString](_ ++ _)).map { responseBytes =>
          throw new RuntimeException(s"""Error: status code ${rs.status} ${responseBytes.utf8String}""")
        }
    }

  import scala.concurrent.duration._
  println(Await.result(response, 10 seconds))
}
```

**Comment by johanandren** [comment] 2016-04-11 09:42
Probably a misleading title, request bodies are not handled differently because of the status code. I think this is something about TLS (possibly in connection to truncation). if I run the request unencrypted it works, although giving me a warning about truncation.

**Comment by johanandren** [comment] 2016-04-11 11:28
Turns out to be a duplicate of #20236 which is fixed and will be in the next release

**Closed by johanandren** 2016-04-11 11:28 UTC
Labels: 3 - in progress, bug, t:http

**Comment by ktoso** [comment] 2016-04-14 14:25
2.4.4 was just released, please upgrade @kstokoz
