### ISSUE TITLE
In place error consumers

### ISSUE THREAD

**Issue by Yeitijem** [akka/akka#29996] opened 2021-02-04 12:55 UTC
Currently it is not easily possible to handle an error in specific places on a stream. IMO it would be beneficial to introduce a doOnError methode on streams, to do some simple side effects like error counting. 

With the current api I see no other way than doing something like this:
```flow.alsoTo(Sink.onComplete(tried => tried.toEither.swap.foreach(_ => errorCounter.increment()))))```
better IMO would be:
```flow.doOnError(_ => errorCounter.increment())```

**Comment by Yeitijem** [comment] 2021-02-04 13:29
A `workaround` in java would be AFAICS:

```flow.watchTermination((notUsed, cs) -> {
	cs.exceptionally(ignored -> {
		errorCounter.increment();
		return Done.getInstance();
	});
	return notUsed;
})```

**Comment by raboof** [comment] 2021-02-04 14:33
Perhaps this would be better-suited for https://discuss.akka.io . In any case, I'm not sure what you mean by "in specific places" - could you elaborate on that? Have you seen https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/recover.html and https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/recoverWith.html?

**Comment by Yeitijem** [comment] 2021-02-04 16:44
I do provide a source and want to gather some metrics in the layer it was created in. It's possible to handle the error when running the source with a sink attached to it, but I need to place the error side effect upstream.

**Comment by Yeitijem** [comment] 2021-02-04 16:47
It would be possible to implement the side effect with recover or recoverWith but this is ment to 'send one last element downstream when a failure has happened upstream'. It would obfuscate the intent and I need to define and potentially handle the extra element. The resulting code would be larger than with my proposal.

**Comment by johanandren** [comment] 2021-02-05 11:16
Duplicate of https://github.com/akka/akka/issues/29053

**Closed** 2021-02-19 16:14 UTC
Labels: 0 - new
