### ISSUE TITLE
InetAddressDnsResolver.scala should not use sun.net.* , will cause future problems

### ISSUE THREAD

**Issue by okrische** [akka/akka#23108] opened 2017-06-06 12:22 UTC
Hey,

just started akka with openjdk9, which checks module access by default. I know, its an ongoing discussion, what the default for this will be in the future. Nonetheless, access to sun-classes was always discouraged and by scanning over the code, this scala class seems to be the only offender. Maybe there is a way to write this differently?

The stacktrace:

`
09:08:30.489 [apiServer-akka.actor.default-dispatcher-2] ERROR akka.actor.OneForOneStrategy - class akka.io.InetAddressDnsResolver (in unnamed module @0x5f29b99c) cannot access class sun.net.InetAddressCachePolicy (in module java.base) because module java.base does not export sun.net to unnamed module @0x5f29b99c
akka.actor.ActorInitializationException: akka://apiServer/system/IO-DNS/inet-address/$c: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:191)
        at akka.actor.ActorCell.create(ActorCell.scala:600)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:454)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:476)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9 internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-internal/Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-internal/NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-internal/DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(java.base@9-internal/Constructor.java:453)
        at akka.util.Reflect$.instantiate(Reflect.scala:65)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
        at akka.actor.Props.newActor(Props.scala:213)
        at akka.actor.ActorCell.newActor(ActorCell.scala:555)
        at akka.actor.ActorCell.create(ActorCell.scala:581)
        ... 7 common frames omitted
Caused by: java.lang.IllegalAccessError: class akka.io.InetAddressDnsResolver (in unnamed module @0x5f29b99c) cannot access class sun.net.InetAddressCachePolicy (in module java.base) because module java.base does not export sun.net to unnamed module @0x5f29b99c
        at akka.io.InetAddressDnsResolver.getTtl(InetAddressDnsResolver.scala:20)
        at akka.io.InetAddressDnsResolver.<init>(InetAddressDnsResolver.scala:30)
        ... 16 common frames omitted
`

**Comment by johanandren** [comment] 2017-06-07 13:41
No public APIs available as alternatives as far as I can see.

**Comment by chbatey** [comment] 2017-09-25 18:35
Looks to be a duplicate of #23404 that Konrad has a fix for. https://github.com/ktoso/akka/commit/d0be62eb2bd4a0507f77977b243bead5ea329fa6

Please reopen if I am mistaken @ktoso

**Closed by chbatey** 2017-09-25 18:35 UTC
Labels: 0 - new, 2 - pick next, t:core, t:jdk9

**Comment by ktoso** [comment] 2017-09-27 13:11
Correct, seems to be a duplicate, thanks for noticing :)
