### ISSUE TITLE
`Source.actorRefWithAck` can only receive one element at a time

### ISSUE THREAD

**Issue by otto-dev** [akka/akka#27447] opened 2019-08-01 17:25 UTC
After hours and hours of debugging tracked down this problem.

If you create a source using `Source.actorRefWithAck`, then `.preMaterialize()` the `actorRef`, the resulting `source` will not support parallelism. Instead, if it receives elements from a concurrent source, it will crash with the following exception: 

```
IllegalStateException: Received new element before ack was signaled back
```

And

```
 Error in stage [MapError(<function1>)]: Actor watched by [ask()] has terminated!
```

If you reduce parallelism to `1`, then it works.

Code to produce the error:

```scala
      sealed trait Ack
      case object Ack extends Ack
      val parallelism = 10
      val (actorWithAck, actorSource) = Source.actorRefWithAck[Int](Ack).preMaterialize()
      actorSource
          .log("error logging")
          .runWith(Sink.foreach(v => println("Received" + v)))
      Source(1 to 1000)
          .map(v => { println("Sent" + v); v })
          .ask[Ack](parallelism)(actorWithAck)
          .runWith(Sink.ignore)
```

You can set `parallelism` to `1` to make the code work. It also works if you don't `preMaterialize` - then you can leave `parallelism > 1`.

This makes the `actorRefWithAck` practially unusable in situations where you *have to* `preMaterialize` - for example when used in `flatMapConcat`.

---
Edit: Turns out this problem also occurs in other situations unrelated to `preMaterialize`, such as when using `.toMat`. The exact conditions are still unclear to me, but the above example is a good reproducible example.

**Comment by otto-dev** [comment] 2019-08-05 01:48
Here is a test suite that demonstrates the problem:

```scala
import akka.actor.{ActorSystem, Status}
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.{Keep, Sink, Source}
import akka.testkit.{ImplicitSender, TestKit}
import akka.util.Timeout
import org.scalatest.{BeforeAndAfterAll, FlatSpecLike, Matchers}

import scala.collection.mutable.ListBuffer
import scala.concurrent.{Await, Awaitable}
import scala.concurrent.duration._


class MaterializedActorRefTest extends TestKit(ActorSystem("ActorTest")) with FlatSpecLike with Matchers with BeforeAndAfterAll with ImplicitSender {

  sealed trait Ack
  case object Ack extends Ack

  implicit val materializer: ActorMaterializer = ActorMaterializer()
  implicit val timeout: Timeout = 1.second

  override def afterAll: Unit = TestKit.shutdownActorSystem(system)

  def await[T](future: Awaitable[T]): T = Await.result[T](future, 10.second)

  it should "work with preMaterialize" in {
    // fails
    val parallelism = 10
    val (actorWithAck, actorSource) = Source.actorRefWithAck[Int](Ack).preMaterialize()
    val result = actorSource.runWith(Sink.seq)
    Source(1 to 1000).ask[Ack](parallelism)(actorWithAck).runWith(Sink.onComplete(_ => actorWithAck ! Status.Success()))
    await(result) should be (1 to 1000)
  }

  it should "work with preMaterialize, without parallelism" in {
    // works
    val parallelism = 1
    val (actorWithAck, actorSource) = Source.actorRefWithAck[Int](Ack).preMaterialize()
    val result = actorSource.runWith(Sink.seq)
    Source(1 to 1000).ask[Ack](parallelism)(actorWithAck).runWith(Sink.onComplete(_ => actorWithAck ! Status.Success()))
    await(result) should be (1 to 1000)
  }

  it should "work with toMat" in {
    // works
    val parallelism = 10
    val (actor, result) = Source.actorRefWithAck[Int](Ack).toMat(Sink.seq)(Keep.both).run()
    Source(1 to 1000).ask[Ack](parallelism)(actor).runWith(Sink.onComplete(_ => actor ! Status.Success()))
    await(result) should be (1 to 1000)
  }

  it should "work with toMat and mapAsyncUnordered" in {
    // works
    import akka.pattern.ask
    val parallelism = 10
    val (actor, result) = Source.actorRefWithAck[Int](Ack).toMat(Sink.seq)(Keep.both).run()
    Source(1 to 1000).mapAsyncUnordered(parallelism)(actor ? _).runWith(Sink.onComplete(_ => actor ! Status.Success()))
    await(result) should be (1 to 1000)
  }

  it should "work without toMat/preMaterialize" in {
    // works
    val parallelism = 10
    val result = ListBuffer[Int]()
    val actor = Source.actorRefWithAck[Int](Ack).to(Sink.foreach(result += _)).run()
    val done = Source(1 to 1000).ask[Ack](parallelism)(actor).runWith(Sink.ignore)
    await(done)
    result should be (1 to 1000)
  }

  it should "be usable inside of flatMapConcat" in {
    // fails
    val parallelism = 10
    val result = Source(1 to 1000).sliding(10, 10).flatMapConcat { numbers =>
      val (actorRef, actorSource) = Source.actorRefWithAck[Int](Ack).preMaterialize()
      // otherActor ! actorRef
      // --- INSIDE OTHER ACTOR ---
      Source(numbers).ask(parallelism)(actorRef).runWith(Sink.onComplete(_ => actorRef ! Status.Success()))
      // --- /END OTHER ACTOR ---
      actorSource
    }.runWith(Sink.seq)
    await(result) should contain theSameElementsAs (1 to 1000)
  }
}

```

![Screenshot_2019-08-05_11-47-47](https://user-images.githubusercontent.com/44302748/62433219-dfc89800-b776-11e9-8879-b11adbe0350c.png)

**Comment by raboof** [comment] 2019-08-05 15:24
Thanks for the in-depth reports!

In its current implementation, this is intended behavior: as both [the documentation](https://doc.akka.io/docs/akka/current/stream/operators/Source/actorRefWithAck.html) and the [scaladocs](https://doc.akka.io/api/akka/current/akka/stream/javadsl/Source$.html#actorRefWithAck[T](ackMessage:Any):akka.stream.javadsl.Source[T,akka.actor.ActorRef]) mention, "The stream will complete with failure if a message is sent before the acknowledgement has been replied back."

In general I'd typically only use `Source.actorRefWithAck` when the goal is interoperability with Actor-based code. For purely streaming code, I would probably use `Source.queue` with `OverflowStrategy.backpressure`, which allows setting a buffer. Would that help in the situations where you ran into this limitation?

**Comment by otto-dev** [comment] 2019-08-09 15:04
Thanks @raboof for the reply. The use case is that there is an actor that manages a database connection. Now it should be possible for other actors to steam inserts into the database, i.e. an Akka Streams `Sink`, and read from the database as a `Source`. To facilitate this, the database actor can materialize a `Sink` or `Source` `actorRef` that is connected to the database, and send that reference via message to the producing/consuming actor. The producing/consuming actor may in turn also use Akka Streams to communicate with the `actorRef` that it has received from the database actor. So in effect, an `actorRef` is used to as a bridge to make access to the database via Akka Streams possible from other actors. Hope it makes sense.

The problem I'd see with using `Source.queue` is that, unlike an `ActorRef`, the queue is not materializable. So you'd lose location transparency.

If you have any other ideas how this could be solved, I'd gladly welcome any input.

On a different note, I'm kind of surprised that `actorRefWithAck` forces 'synchronous' processing. My understanding is that this goes fundamentally against the philosophy and strengths of Akka.

**Comment by raboof** [comment] 2019-08-09 15:23
Thanks for following up!

> the queue is not materializable

I think you mean 'serializable' - good point. Would https://doc.akka.io/docs/akka/current/stream/stream-refs.html fit here?

> I'm surprised that `actorRefWithAck` forces 'synchronous' processing. My understanding is that this goes fundamentally against the philosophy and strengths of Akka

If we don't find an alternative approach that fits naturally, it might make sense to introduce a buffer here as well (like in `Source.queue`), though I want to make sure this added complexity pulls its weight before adding it. Often there's a different solution rather than relying on Actors in an otherwise stream-oriented use case.

**Comment by otto-dev** [comment] 2019-08-09 16:04
>  Would https://doc.akka.io/docs/akka/current/stream/stream-refs.html fit here?

Yes,  that's an implementation of the very thing I was looking for. I didn't know it existed! Thanks again.

There is only one requirement I'm not sure about. I have to dive into it a bit and see if it is possible to implement retry logic for lost elements using `stream-refs`. Using `actorRefWithAck` it was straight forward of course if an `ack` was not received back. The `stream-refs` docs mention a `dropped element signal` that fails the stream, so I could imagine a solution involving `RestartSources`/`Sinks` to achieve effectively the same. Have to see.

**Comment by otto-dev** [comment] 2019-08-10 11:54
After further long investigation, here are my conclusions.

First of all, personally I think the limitations of `actorRefWithAck` are a design flaw, and I consider it a bug. To make a case I'd argue that the current implementation breaks Reactive Principles. It also goes against general principles of the Actor model. Concurrency is fundamental to `Akka`. An actor should not care how many other actors are talking to it, and in what order, and at what level of concurrency. An actor can wait until the current message has been processed before processing the next one, but should not fail if it receives new messages on a non-empty mailbox.

It turned out that retry-logic using `StreamRefs` is not practical. In a nutshell, because once an element passes downstream it is "forgotten" if the flow fails.

I can get around the limitations of `actorRefWithAck` by writing my own `Source.queue` based `Actor` implementation.

**Comment by patriknw** [comment] 2019-12-10 14:31
Closing this since the observed behavior is how the protocol for actorRefWithAck is designed. It's supposed to be used as a one-by-one protocol. Typically it's used by one single actor emitting to the stream and keeping track of current pending request.

**Closed by patriknw** 2019-12-10 14:31 UTC
