### ISSUE TITLE
FAILED: TCK VirtualProcessorSingleTest

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20539] opened 2016-05-17 10:14 UTC
If I remember correctly this should not give false errors even though stochastic hm...
```
[info] - stochastic_spec103_mustSignalOnMethodsSequentially *** FAILED ***
[info]   java.lang.AssertionError: Illegal concurrent access detected (entering critical section)! Thread[pool-191-thread-1,5,main] emited onNext(0) signal, before null finished its onSubscribe() signal.
[info]   at org.testng.Assert.fail(Assert.java:89)
[info]   at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:117)
[info]   at org.reactivestreams.tck.PublisherVerification$5$1$1$ConcurrentAccessBarrier.enterSignal(PublisherVerification.java:270)
[info]   at org.reactivestreams.tck.PublisherVerification$5$1$1.onNext(PublisherVerification.java:303)
[info]   at akka.stream.impl.VirtualProcessor.rec$5(StreamLayout.scala:647)
[info]   at akka.stream.impl.VirtualProcessor.onNext(StreamLayout.scala:666)
[info]   at org.reactivestreams.example.unicast.AsyncIterablePublisher$SubscriptionImpl.doSend(AsyncIterablePublisher.java:161)
[info]   at org.reactivestreams.example.unicast.AsyncIterablePublisher$SubscriptionImpl.doRequest(AsyncIterablePublisher.java:91)
[info]   at org.reactivestreams.example.unicast.AsyncIterablePublisher$SubscriptionImpl.run(AsyncIterablePublisher.java:204)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by ktoso** [comment] 2016-05-17 10:15
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3827/consoleFull

**Comment by 2m** [comment] 2016-05-24 06:35
Duplicate of #20224

**Closed by 2m** 2016-05-24 06:35 UTC
Labels: 1 - triaged, failed, t:stream
