### ISSUE TITLE
[failed] ClusterShardingQueriesSpec

### ISSUE THREAD

**Issue by octonato** [akka/akka#29997] opened 2021-02-04 14:18 UTC
https://jenkins.akka.io:8498/job/akka-nightly-2.13/794/consoleFull

```scala
 - must return shard state of sharding regions if one or more shards timeout, versus all as empty (on node 'third', class akka.cluster.sharding.Cluster│
   3 did not equal 2 (ClusterShardingQueriesSpec.scala:145)                                                                                            │
 - must return shard state of sharding regions if one or more shards timeout, versus all as empty (on node 'second', class akka.cluster.sharding.Cluste│
   1 did not equal 2 (ClusterShardingQueriesSpec.scala:145)                                                                                            │
 [ERROR] [01/29/2021 22:20:47.734] [ClusterShardingQueriesSpec-akka.actor.default-dispatcher-35] [akka://ClusterShardingQueriesSpec/system/controller/b│
 - must return shard state of sharding regions if one or more shards timeout, versus all as empty (on node 'controller', class akka.cluster.sharding.Cl│
   java.lang.RuntimeException: barrier failed: done                                                                                                    │
   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:245)                                                                     │
   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:219)                                                                     │
   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)                                                                    │
   at akka.actor.FSM.processEvent(FSM.scala:804)                                                                                                       │
   at akka.actor.FSM.processEvent$(FSM.scala:801)                                                                                                      │
   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:172)                                                  │
   at akka.actor.LoggingFSM.processEvent(FSM.scala:944)                                                                                                │
   at akka.actor.LoggingFSM.processEvent$(FSM.scala:926)                                                                                               │
   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:172)                                                                               │
   at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)                                                                                         │
   ...                                                                                                                                                 │
 - must return shard state of sharding regions if one or more shards timeout, versus all as empty (on node 'busy', class akka.cluster.sharding.ClusterS│
   java.lang.RuntimeException: barrier failed: done                                                                                                    │
   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:245)                                                                     │
   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:219)                                                                     │
   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)                                                                    │
   at akka.actor.FSM.processEvent(FSM.scala:804)                                                                                                       │
   at akka.actor.FSM.processEvent$(FSM.scala:801)                                                                                                      │
   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:172)                                                  │
   at akka.actor.LoggingFSM.processEvent(FSM.scala:944)                                                                                                │
   at akka.actor.LoggingFSM.processEvent$(FSM.scala:926)                                                                                               │
   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:172)                                                                               │
   at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)
```

**Comment by patriknw** [comment] 2022-02-22 08:59
Looks like a duplicate of https://github.com/akka/akka/issues/30961

**Closed by patriknw** 2022-02-22 08:59 UTC
Labels: failed
