### ISSUE TITLE
Report cause of bind and connect failures

### ISSUE THREAD

**Issue by richdougherty** [akka/akka#16620] opened 2015-01-07 02:19 UTC
When a bind fails in Play we'd like to tell users the reason for the failure. At the moment Akka HTTP gives an `akka.stream.BindFailedException` with a fixed error message. This makes it difficult to debug bind failures without enabling logging. It would be useful to include the error reason or cause in the exception so that it is not necessary to enable logging. I realise this may require changes to the Akka IO protocol so that Akka IO can return error information to Akka HTTP.

At the moment Play only cares about bind errors, but in the future we will use Akka HTTP for outgoing messages, so it would be good to make sure that Akka HTTP returns error information for outgoing connection failures too.

**Comment by patriknw** [comment] 2015-01-07 10:20
cc @sirthias @jrudolph

**Comment by jrudolph** [comment] 2015-01-07 10:22
See #13861.

**Comment by jrudolph** [comment] 2015-01-07 10:24
And there's also #16425 and #16507 filed for streams and http.

**Comment by richdougherty** [comment] 2015-01-07 23:11
So I'm not the only one. :)

**Comment by drewhk** [comment] 2015-01-26 12:47
The cause reporting needs to be first fixed at the IO level. Retargeting this ticket to 2.3.x. If this cannot be done in a binary compatible fashion this needs to be retargetad at 2.4-M1

**Comment by richdougherty** [comment] 2015-01-28 20:59
Makes sense. Play's Akka HTTP support will be part of Play 2.4 and Play 2.4 will target Akka 2.4.

Apart from giving users better errors, we want better error information because we occasionally see a class of bind errors that we haven't been able to diagnose, even with logging turned on. We have been able to fix "normal" bind errors, like when the address is already in use, but there are other bind errors that we don't understand yet. The errors could be caused by a bug in Akka, or they could be a bug in Play's Akka backend or its test code. I'm not sure yet. Once we get better error reporting hopefully we can diagnose it properly.

**Comment by rkuhn** [comment] 2015-02-17 20:14
While reviewing @skisel’s PR I realized that we will likely not be able to perform the proposed changes in the 2.x timeframe (since we want to retain binary compatibility). Another line of reasoning is that making IO exceptions part of the API sounds like a bad idea because these exceptions are so ill-specified and unreliable in their interpretation (O/S-, version- and locale-dependent).

Hence I am (strongly) leaning in the direction of solving this via logging only—we need to make sure that every failure case does lead to a log event and that gives users the visibility they need without contaminating our API.

**Comment by bantonsson** [comment] 2015-03-06 10:21
Closed by #16895

**Closed by bantonsson** 2015-03-06 10:21 UTC
Labels: 2 - pick next, t:http, t:http:core, t:http:next, t:io, t:stream

**Comment by richdougherty** [comment] 2015-03-09 00:07
I don't need a typed exception, just a string error message would be fine. But I understand the reasoning, so no worries. I think logging an error message instead, like you propose, should give users enough visibility to sort out bind problems if they occurs in Play apps.
