### ISSUE TITLE
Serializing Props throws error if `sun.io.serialization.extendedDebugInfo` is on.

### ISSUE THREAD

**Issue by ScrapCodes** [akka/akka#16735] opened 2015-01-28 11:45 UTC
Here is a reproducer https://github.com/ScrapCodes/reproducer
Just clone and run, `sbt test`

This is related to  https://github.com/typesafehub/config/issues/176

**Comment by rkuhn** [comment] 2015-01-29 13:47
Do I understand correctly that fixing the related typesafehub/config issue will fix this as well? In that case we don’t have to do anything and can just count on having recorded the cause for this failure here, thanks for that!

**Comment by ScrapCodes** [comment] 2015-01-30 05:22
That is correct, and akka needs to upgrade to the fixed release ofc. Not sure, but wish it could happen soon though.

**Comment by rkuhn** [comment] 2015-01-30 09:23
Thanks for confirming, we’ll upgrade to the next config library version as soon as it comes out.

**Comment by tIGO** [comment] 2015-11-28 22:26
Seems like this issue was resolved in `com.typesafe.config=1.3.0` (which Akka already depends on).

**Comment by rkuhn** [comment] 2015-12-02 08:18
Thanks for the reminder, you’re right.

**Closed by rkuhn** 2015-12-02 08:18 UTC
Labels: 1 - triaged, t:core
