### ISSUE TITLE
FAILED: SurviveNetworkInstabilitySpec

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#15439] opened 2014-06-25 05:09 UTC
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1133

```
[JVM-1] - must down and remove quarantined node *** FAILED *** (59 seconds, 730 milliseconds)
[JVM-1]   Set(akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a5.moxie:37927, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a6.moxie:50250, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a5.moxie:33423, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a5.moxie:38122, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a6.moxie:60022, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a3.moxie:46616, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a6.moxie:50969) contained element akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a5.moxie:38122 (SurviveNetworkInstabilitySpec.scala:314)
[JVM-1]   org.scalatest.exceptions.TestFailedException:
[JVM-1]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-1]   at org.scalatest.words.ResultOfNotWordForAny.contain(ResultOfNotWordForAny.scala:527)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$31$$anonfun$apply$mcV$sp$32$$anonfun$apply$mcV$sp$39$$anonfun$apply$mcV$sp$40.apply$mcV$sp(SurviveNetworkInstabilitySpec.scala:314)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$31$$anonfun$apply$mcV$sp$32$$anonfun$apply$mcV$sp$39$$anonfun$apply$mcV$sp$40.apply(SurviveNetworkInstabilitySpec.scala:314)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$31$$anonfun$apply$mcV$sp$32$$anonfun$apply$mcV$sp$39$$anonfun$apply$mcV$sp$40.apply(SurviveNetworkInstabilitySpec.scala:314)
[JVM-1]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:263)
[JVM-1]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:274)
[JVM-1]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:728)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$31$$anonfun$apply$mcV$sp$32$$anonfun$apply$mcV$sp$39.apply$mcV$sp(SurviveNetworkInstabilitySpec.scala:314)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$31$$anonfun$apply$mcV$sp$32.apply$mcV$sp(SurviveNetworkInstabilitySpec.scala:312)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$31$$anonfun$apply$mcV$sp$32.apply(SurviveNetworkInstabilitySpec.scala:265)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$31$$anonfun$apply$mcV$sp$32.apply(SurviveNetworkInstabilitySpec.scala:265)
[JVM-1]   at akka.testkit.TestKitBase$class.within(TestKit.scala:305)
[JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:728)
[JVM-1]   at akka.testkit.TestKitBase$class.within(TestKit.scala:319)
[JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:728)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$31.apply$mcV$sp(SurviveNetworkInstabilitySpec.scala:265)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$31.apply(SurviveNetworkInstabilitySpec.scala:265)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$31.apply(SurviveNetworkInstabilitySpec.scala:265)
[JVM-1]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[JVM-1]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[JVM-1]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-1]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-1]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:945)
[JVM-1]   at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec.akka$cluster$MultiNodeClusterSpec$$super$withFixture(SurviveNetworkInstabilitySpec.scala:88)
[JVM-1]   at akka.cluster.MultiNodeClusterSpec$class.withFixture(MultiNodeClusterSpec.scala:169)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec.withFixture(SurviveNetworkInstabilitySpec.scala:88)
[JVM-1]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:942)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:954)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:954)
[JVM-1]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[JVM-1]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:954)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec.runTest(SurviveNetworkInstabilitySpec.scala:88)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1013)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1013)
[JVM-1]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[JVM-1]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[JVM-1]   at scala.collection.immutable.List.foreach(List.scala:318)
[JVM-1]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[JVM-1]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[JVM-1]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[JVM-1]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[JVM-1]   at scala.collection.immutable.List.foreach(List.scala:318)
[JVM-1]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[JVM-1]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[JVM-1]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[JVM-1]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1013)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec.runTests(SurviveNetworkInstabilitySpec.scala:88)
[JVM-1]   at org.scalatest.Suite$class.run(Suite.scala:1423)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec.org$scalatest$WordSpecLike$$super$run(SurviveNetworkInstabilitySpec.scala:88)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1059)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1059)
[JVM-1]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[JVM-1]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1059)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec.org$scalatest$BeforeAndAfterAll$$super$run(SurviveNetworkInstabilitySpec.scala:88)
[JVM-1]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[JVM-1]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec.run(SurviveNetworkInstabilitySpec.scala:88)
[JVM-1]   at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
[JVM-1]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
[JVM-1]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
[JVM-1]   at scala.collection.immutable.List.foreach(List.scala:318)
[JVM-1]   at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
[JVM-1]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
[JVM-1]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
[JVM-1]   at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
[JVM-1]   at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
[JVM-1]   at org.scalatest.tools.Runner$.main(Runner.scala:860)
[JVM-1]   at org.scalatest.tools.Runner.main(Runner.scala)
```

**Comment by drewhk** [comment] 2015-01-01 09:54
Another one: https://jenkins.akka.io:8498/job/akka-nightly/1838/consoleFull

**Comment by patriknw** [comment] 2015-01-05 16:07
and one more: https://jenkins.akka.io:8498/job/akka-nightly/1869/consoleFull

**Comment by patriknw** [comment] 2015-01-13 08:32
I took a look at this one again. We have two types of failures reported here. 
"must heal after unreachable when ring is changed" and "must down and remove quarantined node". Let's begin with the latter.

I think it can be some wrong assumptions in how the test has been written.

* We want to simulate quarantine from third to second. 
* system-message-buffer-size=20
* We remote deploy 21 children from second to third. That is done "slowly" one-by-one to not exceed the system message buffer by sending and awaiting a ping-pong "hello" message in between each child deployment. See L281.
* There is a quarantine from third to second too early, before all children have been deployed completely, and therefore the pong "hello" is not received.
* Logs show that `Supervise` sys msg go to deadLetters on third.

What I think is that "synchronization" with the "hello" message is not always working as expected and the buffer is filled up to early.

@drewhk WDYT

**Comment by drewhk** [comment] 2015-01-13 08:59
That buffer seems a bit tight, creation involves a few system messages. Btw, if you want to force a quarantine this way, you can always cast an actorRef down and send system messages directly to a fake location like I do in the stresstest.

**Comment by patriknw** [comment] 2015-01-13 09:15
I can confirm by some printlns that the resendBuffers are actually growing during the deployment phase of this test, which is not intended. We should rewrite that part of the test.

**Comment by bantonsson** [comment] 2015-01-26 09:43
This is still failing:

https://jenkins.akka.io:8498/job/akka-nightly/1933
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1995
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1996
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1998
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1999

**Comment by patriknw** [comment] 2015-01-26 10:01
Shall I merge https://github.com/akka/akka/pull/16643 but leave this issue open? That PR fixes only one of the two types of failures that we have seen here.

**Comment by patriknw** [comment] 2015-01-26 12:35
I have merged the first part.

**Comment by bantonsson** [comment] 2015-01-27 10:16
One failure tonight:

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2002/consoleFull

**Comment by bantonsson** [comment] 2015-01-30 09:38
Keeps on failing:
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2014/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2016/consoleFull

**Comment by patriknw** [comment] 2015-01-30 09:54
yes, I'll take a look at it now

**Comment by patriknw** [comment] 2015-01-30 11:38
I have found it, and it's rather embarrassing that we have a year old ticket for it. I will describe it there #13875

**Comment by bantonsson** [comment] 2015-01-30 11:48
Great that you found it. What's even funnier is that it's the only other ticket showing up when searching for SurviveNetworkInstabilitySpec :wink:

**Closed** 2015-02-16 09:11 UTC
Labels: failed
