### ISSUE TITLE
Typed Akka withMDC does not set MDC on first message

### ISSUE THREAD

**Issue by martinffx** [akka/akka#29679] opened 2020-09-29 15:23 UTC
I noticed this while writing some unit tests but the first message processed by an actor with MDC does not incl. the MDC values in the logs for that very first message processed by an actor.

```
val behavior = Behaviors.setup[A] { context => 
  Behaviors.withMdc[A]((msg: A) => msg.context.mdc()) {
    Behaviors.receiveMessage {
      case msg: MessageOne =>
        context.log.info("some log")
      case msg: MessageTwo =>
        context.log.info("some other log") 
  }
}
val actor = actorContext.spawn(behavior)
actor  ! MessageOne() // will not incl. MDC in log message
actor  ! MessageOne() // all the next messages will incl. the MDC in the log message.
actor  ! MessageTwo()

**Comment by raboof** [comment] 2020-09-30 09:56
I wonder if this is related to the fact that you're using the 'outer' context in the implementation of the 'inner' behaviour?

**Comment by johanandren** [comment] 2020-09-30 10:08
Those should both refer to the same object so I don't think that is the reason.

**Comment by johanandren** [comment] 2020-10-06 18:18
I tried, but cannot reproduce this, all messages get log entries with MDC set. Please either provide a reproducer or provide some additional detail.

Full try to reproduce:
```scala
import akka.actor.typed.ActorSystem
import akka.actor.typed.scaladsl.Behaviors

object MdcLoggingBug {

  val behavior = Behaviors.setup[String] { context =>
    Behaviors.withMdc[String]((msg: String) => Map("mdc" -> "true")) {
      Behaviors.receiveMessage {
        case "MessageOne" =>
          context.log.info("some log")
          Behaviors.same
        case "MessageTwo" =>
          context.log.info("some other log")
          Behaviors.same
      }
    }
  }

  def main(args: Array[String]): Unit = {
    val actor = ActorSystem(behavior, "ba")
    actor  ! "MessageOne" // will not incl. MDC in log message
    actor  ! "MessageOne" // all the next messages will incl. the MDC in the log message.
    actor  ! "MessageTwo"
  }
}
```

**Comment by patriknw** [comment] 2020-11-16 12:51
@martinffx any thoughts ^ ?

**Comment by johanandren** [comment] 2020-12-22 14:25
Closing this since there was no update, feel free to re-open in the future if there is a reproducer. Also notice there was an actual shortcoming with static mdc when logging from setup #29894

**Closed** 2020-12-22 14:25 UTC
Labels: 0 - new, t:typed
