### ISSUE TITLE
Investigate possible leak in scheduler

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17459] opened 2015-05-12 09:05 UTC
Reported on ML: https://groups.google.com/forum/#!topic/akka-user/PjfLYWi3cu4

Reproducer is here:
https://gist.github.com/jeffsteinmetz/bbccb4815858620ab5a2

"You may need to let it run for about 1 to 2 minutes before you see the "initial" bump in heap usage.  After that, you will see it slowly climb and never back down.
Note - the metrics calls are not required, and do not cause the memory leak - you can watch system memory without this library and see the same issue.

I've tried a few versions of Akka, with the same results.  In production, a similar (real world) application eventually consumes all memory."

**Comment by jeffsteinmetz** [comment] 2015-05-12 14:15
Thank you for moving this to a ticket.  Where you able to reproduce?

**Comment by drewhk** [comment] 2015-05-12 14:18
We have not yet picked up this ticket. I will probably take a look at it tomorrow.

**Comment by jeffsteinmetz** [comment] 2015-05-13 05:02
Looks like it is just the garbage collector taking a long time to clean things up.
If memory is set to 
`-Xms100m -Xmx100m`

GC happens more often with smaller heap.

**Comment by drewhk** [comment] 2015-05-13 07:54
JVM does not give back memory to the system, top is completely irrelevant here.

**Closed** 2015-05-13 07:54 UTC
Labels: t:core
