### ISSUE TITLE
Akka Stream FlexiRoute problem/question about switching state.

### ISSUE THREAD

**Issue by kornstar11** [akka/akka#17920] opened 2015-07-06 15:42 UTC
I seem to be having trouble with switching states in my FlexiRoute. 

This code is quite contrived, but the gist is that the router would receive different types of messages one type of message can go to one outlet (Single), the other must goto all outlets (Broadcast). The router if it is the DemandFromAny and it receives a Broadcast would buffer that message and switch to a DemandFromAll state, once it got a message of any kind it would release it's buffer to all outlets and then determine if it should stay in a DemandFromAll or return to a DemandFromAny state. For simplicity sake I have omitted the buffering part. Running the code below with debug logging enable produced the following output:

*fail due to: requirement failed: emit to [out1] not allowed when no demand available*

Please let me know if I am misunderstanding something or if I have a bug in my code. 

Here is a quick test to replicate the behavior:

The flexiRoute impl:
```scala
package com.kornstar.streamy.stage

import akka.stream._
import akka.stream.scaladsl.FlexiRoute

/**
 * Created by ben on 7/2/15.
 */

object TheFlexiRoute {
  trait RouteMessage
  case object Single extends RouteMessage
  case object Broadcast extends RouteMessage

}//
class TheFlexiRoute(outs:Int) extends FlexiRoute[TheFlexiRoute.RouteMessage,UniformFanOutShape[TheFlexiRoute.RouteMessage, TheFlexiRoute.RouteMessage]](
  shape = UniformFanOutShape(
    inlet = new Inlet[TheFlexiRoute.RouteMessage]("flexIn"),
    outlets = {
      (0 until outs).map { i =>
        println(s"Creating out-$i")
        new Outlet[TheFlexiRoute.RouteMessage](s"out${i}")
      }.toSeq
    }:_*
  ),
  attributes = Attributes.name("streamyBalance")
)  {
  import FlexiRoute._
  override def createRouteLogic(p: PortT) = new RouteLogic[TheFlexiRoute.RouteMessage] {
    //protected var lastM:Option[Mes] = None

    val broadcastState = {
      State(DemandFromAll(p.outlets)) {
        (ctx, _, element) =>
          element match {
            case TheFlexiRoute.Broadcast =>
              p.outArray.foreach{o =>
                ctx.emit(o)(element)
              }
              SameState
            case TheFlexiRoute.Single =>
              normalState


          }
      }
    }

    val normalState:State[OutPort] = {
      State(DemandFromAny(p.outlets)) {
        (ctx, out, element) =>
          element match {
            case TheFlexiRoute.Broadcast =>
              broadcastState

            case TheFlexiRoute.Single =>
              ctx.emit(out.asInstanceOf[Outlet[TheFlexiRoute.RouteMessage]])(element)
              SameState


          }
      }
    }

    override def initialState = normalState
  }
}
```

And then here is my test code (ScalaTest):

```scala
package com.kornstar.streamy.stage

import akka.testkit.{TestProbe, TestKit}
import com.typesafe.config.{ConfigFactory, Config}
import org.scalatest.{Matchers, FlatSpecLike}

import akka.actor.ActorSystem
import akka.stream.scaladsl._
import akka.stream.testkit.{TestSubscriber, StreamTestKit, TestPublisher}
import akka.stream._
import akka.stream.testkit.scaladsl.{TestSink, TestSource}
/**
 * Created by ben on 7/2/15.
 */
class TheFlexiRouteTest extends TestKit(ActorSystem("Streamy")) with FlatSpecLike with Matchers with Logging {
  val srcId = SourceId("test",0)

  "TheFlexiRoute" should "Route messages correctly based on type" in {
    try {


      implicit val materializer: Materializer = ActorMaterializer()
      val messageProbe = TestProbe()

      val src = TestSource.probe[TheFlexiRoute.RouteMessage]
      //val sink = TestSink.probe[Message[String]]

      val testSink = Sink.foreach[TheFlexiRoute.RouteMessage]{m =>
        println(s"Sink gets: $m")
      }

      def testFlow(i: Int) = Flow.apply[TheFlexiRoute.RouteMessage].map { m =>
        println(s"Messages-$i: ${m}")
        m
      }

      val flow = Flow() { implicit b =>
        import FlowGraph.Implicits._
        val router = b.add(new TheFlexiRoute(2))
        val merge = b.add(Merge[TheFlexiRoute.RouteMessage](2))

        router ~> testFlow(0) ~> merge
        router ~> testFlow(1) ~> merge

        (router.in, merge.out)
      }

      val runableFlow = src.via(flow).to(testSink).run()


      runableFlow.sendNext(TheFlexiRoute.Single)

      runableFlow.sendNext(TheFlexiRoute.Single)
      runableFlow.sendNext(TheFlexiRoute.Broadcast)
      runableFlow.sendNext(TheFlexiRoute.Broadcast)

      runableFlow.sendNext(TheFlexiRoute.Single)
      runableFlow.sendNext(TheFlexiRoute.Single)
      runableFlow.sendNext(TheFlexiRoute.Broadcast)
      runableFlow.sendNext(TheFlexiRoute.Broadcast)

      runableFlow.sendNext(TheFlexiRoute.Single)
      runableFlow.sendNext(TheFlexiRoute.Single)
      runableFlow.sendNext(TheFlexiRoute.Broadcast)
      runableFlow.sendNext(TheFlexiRoute.Broadcast)

      Thread.sleep(15000L)
      println("sending complete")
      runableFlow.sendComplete()
      Thread.sleep(1000L)


    } catch {
      case e:Throwable =>
        logger.error("OHNO", e)
        throw e
    }
  }


}
```

The error itself is coming from the following line:

```scala
p.outArray.foreach{o =>
   ctx.emit(o)(element)
 }
```

# potential fix?
After looking into this issue I think the error take place in the following code: 
https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/impl/FlexiRouteImpl.scala#L135

From what I can tell precondition on gets read once, even though the behavior var does change. To Fix this I have made a additional class that closes over the behavior var so that updates can be propigated to the Pump.

I have a proposed fix here:
https://github.com/kornstar11/akka/commit/a66c30cc19e1d8b857bb2038c1d0be405e668239#diff-f57483f18cb0c1f89d98c8a7ec93ed4fR106

Please let me know your thoughts.

**Comment by kornstar11** [comment] 2015-07-06 17:16
fyi using akka-stream-experimental - 1.0-RC4

**Comment by 2m** [comment] 2015-08-05 12:46
I think the problem is that you are creating outlets by yourself and also outlets are created in the [UniformFanOutShape](https://github.com/akka/akka/blob/6e527c29df33a470df4df0760251538dc3fff1fb/akka-stream/src/main/boilerplate/akka/stream/FanOutShape.scala.template#L61).

I have tried reproducing your example and it works as expected. You can find my code [here](https://github.com/2m/akka-stream-sandbox/blob/6fd90e8e80a2827aa954179fbc1b7477d3c92bae/src/test/scala/StreamyBalance.scala).

I am going to close this issue now, but feel free to comment or open another one if you find further issues.

**Closed by 2m** 2015-08-05 12:46 UTC
Labels: 1 - triaged, t:stream

**Comment by kornstar11** [comment] 2015-08-27 19:19
Thanks for the feedback. Got it working. Thanks.
