### ISSUE TITLE
Consider improving error message for missing implicits on `ParameterDirectives`

### ISSUE THREAD

**Issue by gregbeech** [akka/akka#16637] opened 2015-01-12 12:24 UTC
With the current `ParameterDirectives` class if you use any of the types that require an implicitly available `ExecutionContext` (such as optional parameters) but don't have one yet because you're bootstrapping a minimal implementation, e.g.

~~~scala
class HttpApi extends Directives {
  val route: Route = get {
    parameters("foo".?) { foo =>
      complete(OK)
    }
  }
}
~~~

Then the error message isn't very helpful, indicating a type mismatch:

~~~
Error:(23, 22) type mismatch;
 found   : akka.http.common.NameOptionReceptacle[String]
 required: akka.http.server.directives.ParameterDirectives.ParamMagnet
    parameters("foo".?) { foo =>
                     ^
~~~

However, the real error is that the service needs an implicitly available execution context. This probably isn't a _huge_ issue as most real services will have one, but it caught me out until I had a look through the source so would be nice to fix.

**Comment by rkuhn** [comment] 2015-01-20 15:57
Thanks for reporting, I hope that scalac allows nicer reporting.

**Comment by sirthias** [comment] 2015-02-11 14:13
Maybe we can improve things by providing a solution for the most frequent root cause, missing an implicit `ExecutionContext` (as @gregbeech described). If we introduce a wrapper type we could attach an `@implicitNotFound` annotation.

**Comment by Tvaroh** [comment] 2015-09-11 21:28
+1

Was struggling with this last half an hour.

**Comment by ktoso** [comment] 2015-09-14 14:26
This concrete example case is actually solved thanks to @jrudolph's PR: https://github.com/akka/akka/pull/17500/files#diff-ae9f8a366c478a21d705a030560ed44cR71 which removed the use of the implicit execution context from here :-)

Closing as these errors won't happen with 1.1.

**Closed by ktoso** 2015-09-14 14:26 UTC
Labels: 3 - in progress, t:http, t:http:server, t:http:server:dsl
