### ISSUE TITLE
Reconnect outgoing connection docs / pattern or sugar

### ISSUE THREAD

**Issue by ktoso** [akka/akka#16882] opened 2015-02-16 23:11 UTC
Users may want to reconnect outgoing connections once they die. 
We should either provide a pattern (cookbook style) or explain it in the docs how to listen for completion or perhaps provide a sugar for this. 

A cookbook would be the best way to start here.
It can be based on: https://gist.github.com/ktoso/4dda7752bf6f4393d1ac 
but be improved by having a small timeout before triggering the reconnect.

related:
* Related akka-user question: https://groups.google.com/forum/#!topic/akka-user/0IwqWGX5mXg
* @wsargent also had this question and had an `scheduleReconnect` based impl.

**Comment by ktoso** [comment] 2015-03-30 09:20
An initial version was implemented for akka-contrib-extra: https://github.com/typesafehub/akka-contrib-extra/pull/17 https://github.com/typesafehub/akka-contrib-extra/pull/22

It solves parts of the problem, reconnecting on completion and error.

**Comment by rkuhn** [comment] 2015-03-30 09:21
This is a (spiritual) duplicate of #16985.

**Closed** 2015-03-30 09:21 UTC
Labels: 1 - triaged, t:docs, t:stream
