### ISSUE TITLE
SubscriptionWithCancelException.NoMoreElementsNeeded does not have stack trace

### ISSUE THREAD

**Issue by amo12937** [akka/akka#31106] opened 2022-02-04 05:57 UTC
I'm researching some error occurred in our system.

Our system is failed with `SubscriptionWithCancelException.NoMoreElementsNeeded` exception but it does not have stack trace so I could not find out where it happened.

Is there any reason why it implements `scala.util.control.NoStackTrace`?

if I'm allowed, I intend to make a PR to change the codes to something like below:

```diff
object SubscriptionWithCancelException {

  /**
   * Not for user extension
   */
  @DoNotInherit
- sealed abstract class NonFailureCancellation extends RuntimeException with NoStackTrace
+ sealed abstract class NonFailureCancellation extends RuntimeException
- case object NoMoreElementsNeeded extends NonFailureCancellation
+ class NoMoreElementsNeeded extends NonFailureCancellation
+ def NoMoreElementsNeeded = new NoMoreElementsNeeded
  case object StageWasCompleted extends NonFailureCancellation
}
```

**Comment by johanandren** [comment] 2022-02-04 10:27
It's an exception used as a non-error-cancellation signal, designed like that to be able to fit the cancellation-with-cause onto streams in a binary compatible fashion, so that Akka 2.5 and 2.6 both works with older other libraries not knowing about the stream cancellation cause propagation.

Since stack traces are costly, non-error cancellation common and that it is not really an exception, we don't want to add stacktraces to those.

**Comment by johanandren** [comment] 2022-02-10 07:42
I'll close this since it works as intended, please re-open if you disagree and we can discuss further.

**Closed by johanandren** 2022-02-10 07:42 UTC
