### ISSUE TITLE
TLSActor causes `IllegalArgumentException` with non-LDH ASCII hostnames.

### ISSUE THREAD

**Issue by trbngr** [akka/akka#21708] opened 2016-10-21 09:01 UTC
When making a request using akka-http to this url: `https://open_nsfw.gitlab.io/`. The following exception is thrown.

```
Caused by: java.lang.IllegalArgumentException: Contains non-LDH ASCII characters
    at java.net.IDN.toASCIIInternal(IDN.java:296)
    at java.net.IDN.toASCII(IDN.java:122)
    at javax.net.ssl.SNIHostName.<init>(SNIHostName.java:99)
    at akka.stream.impl.io.TLSActor$$anonfun$applySNI$1$$anonfun$apply$3.apply(TLSActor.scala:497)
    at akka.stream.impl.io.TLSActor$$anonfun$applySNI$1$$anonfun$apply$3.apply(TLSActor.scala:482)
    at scala.Option$WithFilter.map(Option.scala:207)
    at akka.stream.impl.io.TLSActor$$anonfun$applySNI$1.apply(TLSActor.scala:482)
    at akka.stream.impl.io.TLSActor$$anonfun$applySNI$1.apply(TLSActor.scala:481)
    at scala.Option.flatMap(Option.scala:171)
    at akka.stream.impl.io.TLSActor.applySNI(TLSActor.scala:481)
    at akka.stream.impl.io.TLSActor.applySessionParameters(TLSActor.scala:177)
    at akka.stream.impl.io.TLSActor.<init>(TLSActor.scala:164)
    at akka.stream.impl.io.TLSActor$$anonfun$props$1.apply(TLSActor.scala:37)
    at akka.stream.impl.io.TLSActor$$anonfun$props$1.apply(TLSActor.scala:37)
    at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
    at akka.actor.Props.newActor(Props.scala:213)
    at akka.actor.ActorCell.newActor(ActorCell.scala:562)
    at akka.actor.ActorCell.create(ActorCell.scala:588)
    ... 9 more
```

It seems like changing [TLSActor](https://github.com/akka/akka/blob/4a7cd147313404eb8137e56163e54f06c23640d0/akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala#L497) here to

`clone.setServerNames(Collections.singletonList(new SNIHostName(hostname.getBytes)))` works around the issue.

Are there any other issues this change would raise?

**Comment by ktoso** [comment] 2016-10-21 09:04
This seems like avoiding validation which most likely does the right thing though.
This should be a domain name AFAIR, could you remove the `https://` and `/` from it and try? Those are not part of a domain name.

**Comment by trbngr** [comment] 2016-10-21 09:07
using http bypasses SNIHostName and does work.  But I can't guarantee that my users will do that. And if they do - or I do programmatically - I can be assured that a site will respond to http traffic. ;)

**Comment by ktoso** [comment] 2016-10-21 09:11
That's not what I'm saying - a HostName is`open_nsfw.gitlab.io`, the rest is URI stuff. Since you're in there, could you please try passing in a clean hostname. Solution would be then to get the hostname, and not slap entire uri into this object.

**Comment by trbngr** [comment] 2016-10-21 09:14
I believe, and I'm going to find out for sure right now, that the issue is rooted at `Uri(url)`. By the time I get to `http.singleRequest` I need a fully formed `Uri`.

If I'm still not understanding what you're asking. ;)

Are you saying I could build the Uri piece by piece?

**Comment by ktoso** [comment] 2016-10-21 09:18
No, I was asking you to try the following:

```
scala> new SNIHostName("https://open_nsfw.gitlab.io/")
java.lang.IllegalArgumentException: Contains non-LDH ASCII characters
  at java.net.IDN.toASCIIInternal(IDN.java:296)
  at java.net.IDN.toASCII(IDN.java:122)
  at javax.net.ssl.SNIHostName.<init>(SNIHostName.java:99)
  ... 32 elided

scala> new SNIHostName("open_nsfw.gitlab.io")
java.lang.IllegalArgumentException: Contains non-LDH ASCII characters
  at java.net.IDN.toASCIIInternal(IDN.java:296)
  at java.net.IDN.toASCII(IDN.java:122)
  at javax.net.ssl.SNIHostName.<init>(SNIHostName.java:99)
  ... 32 elided

scala> new SNIHostName("opennsfw.gitlab.io")
res8: javax.net.ssl.SNIHostName = type=host_name (0), value=opennsfw.gitlab.io

scala> new SNIHostName("open_nsfw.gitlab.io".getBytes)
res10: javax.net.ssl.SNIHostName = type=host_name (0), value=open_nsfw.gitlab.io

```

But sadly it turns out that it's not the `/` that causes the problem but the underscore.

It seems the `.getBytes` style should be fine though, please submit a PR :)

**Comment by trbngr** [comment] 2016-10-21 09:19
Will do. My first for Akka!

Look ma, I'm a Hakker now ;)

**Comment by jrudolph** [comment] 2016-10-27 16:59
Host names are not allowed to contain underscores. That's what LDH means: letter, digits, hyphens. See http://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it for more information about the difference between domain names and host names and which characters are allowed in which.

**Comment by ktoso** [comment] 2016-10-27 17:54
So yeah, I know and both agree on "not allowed", however the open_nsfw.gitlab.io domain still exists and _works_. So...

**Comment by trbngr** [comment] 2016-10-27 18:57
@ktoso  Is running `validatePullRequest` necessary on something so small as this? My machine keeps barfing up memory running that. ;)

**Comment by ktoso** [comment] 2016-10-28 09:06
Please make sure your changes don't break things :) Can be done via that task or more selectively.
Thanks!

**Comment by richard-imaoka** [comment] 2017-03-09 05:42
Hi I was reading through this issue and came up with one idea. @trbngr could I suggest using a new flag in config if you are still working on this?
If the flag is turned on, use `getBytes`. If the flag is off, retain the current behavior so that you don't break existing things. Does it make sense?

**Comment by jrudolph** [comment] 2017-03-09 09:07
I think we need to understand what this change exactly means. Just passing in bytes where before a string was passed in means we need to apply some encoding. And there might be other encodings like punycode which might come into play here.

**Comment by farico** [comment] 2020-04-29 07:59
Hi! Is there any workaround for this? We're using `Http().singleRequest())` which throws exception rather than completing a Future with a failure. Here is full reproducable example:

```import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.HttpRequest

import scala.io.StdIn

object DomainPlayground {
  def main(args: Array[String]): Unit = {
    implicit val sys = ActorSystem("LDHSubdomainTest")
    implicit val ec  = sys.dispatcher

    val uri = "https://google_earth.tr.downloadastro.com/ads.txt"
    try {
      val request  = HttpRequest(uri = uri)
      val response = Http().singleRequest(request)
      response.map(println)
      response.failed.map { e => println(s"Cannot fetch content: $e") }
    } catch {
      case e: Exception =>
        println(s"Ooops: $e")
    }

    StdIn.readLine("press RETURN to exit..")
  }
}
```


Neither "Cannot fetch content" nor "Ooops" are being printed, instead exception is being thrown:
```2020-04-29 10:55:50,343 [domains-akka.actor.default-dispatcher-5] ERROR akka.actor.OneForOneStrategy - Contains non-LDH ASCII characters
akka.actor.ActorInitializationException: akka://domains/system/Materializers/StreamSupervisor-1/flow-1-1: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
	at akka.actor.ActorCell.create(ActorCell.scala:657)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalArgumentException: Contains non-LDH ASCII characters
	at java.base/java.net.IDN.toASCIIInternal(IDN.java:296)
	at java.base/java.net.IDN.toASCII(IDN.java:122)
	at java.base/javax.net.ssl.SNIHostName.<init>(SNIHostName.java:99)
	at akka.stream.scaladsl.TLS$.$anonfun$apply$2(TLS.scala:104)
	at akka.stream.impl.io.TLSActor.liftedTree1$1(TLSActor.scala:159)
	at akka.stream.impl.io.TLSActor.<init>(TLSActor.scala:159)
	at akka.stream.impl.io.TLSActor$.$anonfun$props$1(TLSActor.scala:38)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
	at akka.actor.Props.newActor(Props.scala:226)
	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
	at akka.actor.ActorCell.create(ActorCell.scala:635)
	... 10 more
```

Currently it seems that there is no way to recover from such failure?

**Comment by jrudolph** [comment] 2020-04-29 08:36
> Neither "Cannot fetch content" nor "Ooops" are being printed, instead exception is thrown:

Ah, you are saying that the stream is just left hanging even if the Actor has crashed. That's bad indeed, there's even a FIXME in there:

https://github.com/akka/akka/blob/0e4d41ad33dbeb00b598cb75b4d29899371bdc8c/akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala#L460-L464

When the actor crashes it should at least close all the ports.

**Comment by johanandren** [comment] 2020-11-23 16:43
Have tried to repeat this directly with the `Tcp.outgoingConnectionWithTls` API but that seems to fail the stream correctly with invalid hostnames however I try on both JDK 11 and 8 (and that specific hostname resolves fine on both btw)

**Comment by patriknw** [comment] 2023-03-07 06:57
@johanandren What do you think about this issue? Close or investigate?
The `FIXME: what happens if this actor dies unexpectedly?` still exists.

**Comment by johanandren** [comment] 2023-03-07 08:25
Not more info and as we couldn't reproduce I think we can close. Turning that "what happens" FIXME into something like an abrupt stream termination with details sounds like a good idea though.

**Comment by patriknw** [comment] 2023-03-07 08:26
Thanks, can you fix the FIXME and then close this.

**Comment by johanandren** [comment] 2023-03-07 08:56
Just closing this and addressing that FIXME separately as it is not entirely related to the problem here (which was thrown in constructor of actor and did clearly end up in logs)

**Closed by johanandren** 2023-03-07 08:56 UTC
Labels: 1 - triaged, help wanted, bug, t:io, t:io:tls
