### ISSUE TITLE
Stale samples in FlowDoc{Test|Spec}?

### ISSUE THREAD

**Issue by 2beaucoup** [akka/akka#20450] opened 2016-05-04 12:23 UTC
I was unable to find a reference to these:
- `#compound-source-is-not-keyed-runWith`
- `#compound-source-is-not-keyed-run`

**Comment by drewhk** [comment] 2016-05-05 08:15
I vaguely recall that we kept some tests around even though that we do not reference them from the docs, but it is worth investigating.

**Comment by Captain1653** [comment] 2021-08-04 19:58
The issue is really old. These example aren't used for long time. Is it worth to close the issue as is or change some documentation?

**Comment by raboof** [comment] 2021-08-10 15:07
> The issue is really old. These example aren't used for long time. Is it worth to close the issue as is or change some documentation?

The snipped in the source has a FIXME linking it to an issue that has long been closed:

https://github.com/akka/akka/blob/master/akka-docs/src/test/scala/docs/stream/FlowDocSpec.scala#L76

It's not obvious to me what (if anything) would need to be 'fixed' there, so unless someone remembers I think it'd make sense to remove those snippets and close this issue. Would you like to do that?

**Comment by Captain1653** [comment] 2021-08-10 16:54
Yes, I'll do it tomorrow.

**Closed** 2021-08-18 10:49 UTC
Labels: 1 - triaged, t:docs
