### ISSUE TITLE
Failed HubSpec: must complete after draining control is invoked and all connected producers complete

### ISSUE THREAD

**Issue by andreaTP** [akka/akka#30581] opened 2021-08-26 13:35 UTC
https://github.com/akka/akka/runs/3433084770?check_suite_focus=true#step:5:6689

```
[info] - must complete after draining control is invoked and all connected producers complete *** FAILED *** (2 seconds, 27 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected class akka.stream.testkit.TestSubscriber$OnNext, found class akka.stream.testkit.TestSubscriber$OnComplete$ (OnComplete)
```

**Comment by marcospereira** [comment] 2021-08-30 15:19
https://github.com/akka/akka/runs/3462372094?check_suite_focus=true#step:5:16628

**Comment by nivox** [comment] 2021-08-31 19:21
@andreaTP I just had a quick look at the test (since I worked on it before) and my impression is that the issue is caused by some unfortunate scheduling…

I believe what happen is that the draining of the `MergeHub` is applied before the 2 streams had a chance to register themselves as producers hence completing immediately the stream.

I think the issue is the same as #30464. So the solution @raboof applied there can be applied also here.

Personally I dislike the use of delays is test code as it seems brittle, so instead I would suggest this approach:
- Use `TestSource` Instead of real sources
- Send one marker element in each source
- Wait for those element to be received (thus ensuring that the streams are completely initialized)
- At this point start the draining
- Send the remaining elements and complete the `TestSource`s

This approach should guarantee the correct ordering of events even on CI systems under pressure.

I might be able to prepare a PR using this approach in the next days (applying it also to the test @raboof already fixed) in case you guys think is a good idea.

**Comment by andreaTP** [comment] 2021-08-31 20:37
@nivox go for it, it makes totally sense.
Thanks a lot for the explanation!

**Comment by raboof** [comment] 2021-09-01 09:03
> I dislike the use of delays is test code

I agree! :)

> * At this point start the draining
> * Send the remaining elements and complete the TestSources

Sounds like a great solution here! I'm not sure it'd also make work for the "immediately cancel new producers while draining" case though, since once the 'marker element' has been accepted it is not a "new producer" anymore.

**Comment by nivox** [comment] 2021-09-01 18:59
@raboof indeed you’re right.

This was the reason why in my original implementation I had the draining method return a future which completed as soon as the draining request was registered by the `MergeHub` (Which was then removed as it was not deemed useful in the general use case) .  

Sadly without this kind of feedback mechanism I cannot think of a way to make the test robust to scheduling issues, so I think your delay based solution is the best we can aim for without changing the API.

That said I’ll still prepare the PR (hopefully tomorrow) focusing only on the test mentioned in this issue.

**Comment by nivox** [comment] 2021-09-02 13:02
I've published the PR.

In the end I did modify the test @raboof fixed as I noticed that the delay was added to allow the sources to register to the `MergeHub` which can now be properly verified using the `TestPublisher`s. 

I still ended up using the delay but to give time to the drain command to actually be processed by the `MergeHub` before proceeding.

**Comment by patriknw** [comment] 2021-09-06 09:19
https://github.com/akka/akka/pull/30640/checks?check_run_id=3522715576#step:5:6674

**Comment by octonato** [comment] 2021-09-06 20:21
Did #30624 fix this? Shall we close it?

**Closed** 2021-09-07 06:31 UTC
Labels: failed
