### ISSUE TITLE
Wrong next chapter in doc

### ISSUE THREAD

**Issue by jamesanto** [akka/akka#19960] opened 2016-03-07 18:08 UTC
In the [akka scala documentation page](http://doc.akka.io/docs/akka/2.4.2/scala/typed.html) where the typed actors are explained, the next chapter points to 'External Contributions' where as it should point to 'Fault Tolerance' as per TOC.

<img width="1436" alt="akka_typed_ _akka_documentation" src="https://cloud.githubusercontent.com/assets/4387216/13578379/9ea60c16-e4bd-11e5-88f4-701aa6b1c27a.png">

**Comment by ktoso** [comment] 2016-03-07 18:11
I never really understood how Sphinx decides on those, thanks for reporting.
I have no immediate fix for this, any help would be welcome!

**Comment by patriknw** [comment] 2016-03-08 07:57
let's reserve the bug label for serious bugs in the code

**Comment by ktoso** [comment] 2016-03-08 09:27
Okey, and @rkuhn is about to fix this one too AFAIR

**Comment by rkuhn** [comment] 2016-03-08 09:31
Nope, this was not on my radar and I have no clue how Sphinx generates these links.

**Comment by ktoso** [comment] 2016-03-08 09:32
Duh, sorry mistook this ticket for https://github.com/akka/akka/issues/19964#issue-139124684

**Comment by richard-imaoka** [comment] 2016-03-08 20:25
I think we can fix this issue by removing "Akka Typed" from "Experimental Modules" in the [table of contents for Scala](http://doc.akka.io/docs/akka/2.4.2/scala.html).

**Is it ok?** If so, I will send a pull request.

"Akka Typed" belongs to both ["Actors"](https://raw.githubusercontent.com/akka/akka/master/akka-docs/rst/scala/index-actors.rst)(-> typed) and ["Experimental Modules"]( https://raw.githubusercontent.com/akka/akka/master/akka-docs/rst/experimental/index.rst)( -> ../scala/typed). I think the link to the next chapter was overwritten by the latter.

The [Java doc](http://doc.akka.io/docs/akka/2.4.2/java.html) doesn't have this problem.

**Comment by ktoso** [comment] 2016-03-08 20:50
Well, akka typed IS indeed experimental so I don't think we can do that hm

**Comment by richard-imaoka** [comment] 2016-03-08 21:50
Hmm, do we instead remove it from ["Actors"](https://raw.githubusercontent.com/akka/akka/master/akka-docs/rst/scala/index-actors.rst)(-> typed) then? I think the problem is because it belongs to the two parts.

Otherwise, I'll need to really understand how prev/next links are generated.

**Comment by jamesanto** [comment] 2016-03-10 17:40
Instead of removing we can rename the files(Not the titles). These files are referred in the TOC::Tree in Sphinx. You can find them starting from index.rst. Renaming the files should solve the problem.

**Comment by richard-imaoka** [comment] 2016-03-16 19:49
Correct me if I'm wrong, but isn't the problem that the two documents:

- [akka-docs/rst/scala/index-actors.rst](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/index-actors.rst) ( -> [Raw file](https://raw.githubusercontent.com/akka/akka/master/akka-docs/rst/scala/index-actors.rst) -> typed) ) and 

- [akka-docs/rst/experimental/index.rst](https://github.com/akka/akka/blob/master/akka-docs/rst/experimental/index.rst)( -> [Raw file](https://raw.githubusercontent.com/akka/akka/master/akka-docs/rst/experimental/index.rst) -> ../scala/typed)

pointing to the same document, [akka-docs/rst/scala/typed.rst](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/typed.rst) ?

Or which file should we rename?

**Comment by richard-imaoka** [comment] 2016-03-21 09:22
@jamesanto as you pointed out, next/prev links are auto generated from [toctree directive](http://www.sphinx-doc.org/en/stable/markup/toctree.html) in Sphinx. 
It works on an assumption that no single page is referred twice in different toctree directives.

The problem is that above two pages, I mentioned, refer to the same [akka-docs/rst/scala/typed.rst](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/typed.rst). 
Renaming [akka-docs/rst/scala/typed.rst](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/typed.rst) wouldn't help.

**Comment by richard-imaoka** [comment] 2016-03-21 12:20
Actually I found another instance of this issue. The same issue happens whenever **a single page is referenced multiple times in different toctree** directives.

[Java documentation](http://doc.akka.io/docs/akka/2.4.2/java.html) -> go to [What is Akka](http://doc.akka.io/docs/akka/2.4.2/intro/what-is-akka.html) -> look at previous link = "Introduction". You realize it is pointing to the Scala documentation, not Java.
![wrong-prev-link](https://cloud.githubusercontent.com/assets/7414320/13918393/522e153e-efaa-11e5-960a-6e88a28ca5b7.png)

**Comment by Captain1653** [comment] 2021-06-30 12:02
The issue is really old. Akka 2.4 is outdated and not supported. The [new documentation](https://doc.akka.io/docs/akka/2.6.15/typed/actors.html#first-example) has different structure (Am I wrong?). Is it worth to close the issue?

Kind regards

**Comment by johanandren** [comment] 2021-06-30 12:12
Yes, let's close it, thanks for digging in the issue archives :)

**Closed by johanandren** 2021-06-30 12:12 UTC
Labels: 1 - triaged, help wanted, t:docs
