### ISSUE TITLE
Clarify / fix closing semantics of collect / filter like combinators

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18170] opened 2015-08-10 14:37 UTC
Collect and filter don't report stream completion eagerly (i.e. without demand) if the last element doesn't match the predicate.

That's because in case of upstream completion an element that is already available buffered in the input buffer isn't pushed through the user provided predicate/collection function to find out if completion can already be reported to downstream.

If eager close semantics are required a simple subsequent `buffer(1, OverflowStrategy.backpressure)` will currently work around the problem as demonstrated in #16583.

**Comment by drewhk** [comment] 2015-08-10 14:41
I guess this is a bug (unless proven otherwise ;) )

**Comment by jrudolph** [comment] 2015-08-10 14:47
Hard to say as there are almost no tests regarding details of filter and collect semantics and the scaladoc doesn't say much either.

**Comment by drewhk** [comment] 2015-08-11 10:41
These are tested through the scripted tests, unfortunately those do not cover closing behavior completely ("lazy" or "eager" close).

**Comment by drewhk** [comment] 2015-09-02 11:15
@jrudolph I'm a bit confused, the following passes both for filter and collect:

      val upstream = TestPublisher.probe[Int]()
      val downstream = TestSubscriber.probe[Int]()
      implicit val materializer = ActorMaterializer(settings)

      Source(upstream).filter(_ != 0).runWith(Sink(downstream))

      downstream.request(2)

      upstream.sendNext(1)
      downstream.expectNext(1)

      upstream.sendNext(0)
      downstream.expectNoMsg()

      upstream.sendComplete()
      downstream.expectComplete()

The second and last element does not match the predicate, but completion propagates even without pending demand.

**Comment by jrudolph** [comment] 2015-09-02 12:00
Yes, the problem is, that it could report completion already with `.request(1)`.

**Comment by jrudolph** [comment] 2015-09-02 12:01
(but doesn't).

**Comment by drewhk** [comment] 2015-09-02 12:17
I don't understand. It cannot signal completion until the upstream signals completion, obviously. Can you change the above test case to show what you meant?

**Comment by drewhk** [comment] 2015-09-02 12:22
Ah, got it, you mean setting the initial request to 1.

**Comment by jrudolph** [comment] 2015-09-02 12:27
Yep :)

**Comment by drewhk** [comment] 2015-09-02 12:41
So, this is something that is not easy to fix (if it should be fixed at all). The events are:

 - downstream requests 1
 - interpreter pulls filter
 - upstream sends 1
 - interpreter pushes filter
 - interpreter sends onNext to downstream. At this point there is 0 pending demand.
 - upstream sends 0 (*)
 - upstream sends onComplete

At this point nothing happens, since in order to be able to push the 0 into the filter it should be pulled, but there is no pending demand downstream, and of course you never know that a filter will emit or not, so you need at least one demand to pull it. Adding an extra buffer space (or making Filter detached) just pushes the problem a few elements away since the line (*) can be repeated n+1 
times if the buffer space is n.

**Comment by drewhk** [comment] 2015-09-02 12:42
I.e. there is really no eager close possible here, but it is possible to have "eager close up to X possibly filtered elements, but not for X+1"

**Comment by drewhk** [comment] 2015-09-02 12:43
(Currently X=0)

**Comment by drewhk** [comment] 2015-09-02 15:09
Actually my explanation is slightly wrong, but that does not really change anything here. My current conclusion is that:
 - this is not a bug per se, but a rather surprising behavior
 - I am not sure how to "fix it by documenting" as the behavior to be documented here is quite low-level (most users will not deal with the RS requests directly, and all Akka stages do prefetch automagically)

Can you explain how this surprising behavior materialized in the Http case? I am looking for a high-level observable symptom that helps me with *what* to document without going into RS details (too much).

**Comment by jrudolph** [comment] 2015-09-02 19:18
> Adding an extra buffer space (or making Filter detached) just pushes the problem a few elements away since the line (*) can be repeated n+1
> times if the buffer space is n.

Without even considering any downstream demand you can find out that the filtered stream contains zero elements with a buffer of size 1:

 * request 1 element from upstream
 * receive `0` which is filtered out
 * repeat until you get complete in which case downstream can be completed

It may be difficult in the current implementation (I'm not sure) because even if buffering happens without downstream demand, the actual implementation of a stage is not able to run without downstream demand (buffer is on the input and not on the output side). But all of this is an implementation artefact.

The missing explanation is that completion may be blocked behind a filtered-out element if there is no demand in which case you need an extra buffer behind the element to make sure to receive completion even without demand.

Also, we have a very similar problem with TCP where completion is also only reported if there's demand. The solution discussed in #17122 was to introduce a buffer of size 1 to be able to report connection closure as soon as possible.

**Comment by drewhk** [comment] 2015-09-03 08:37
> Without even considering any downstream demand you can find out that the filtered stream contains zero elements with a buffer of size 1:

The issue here is that any "budget of 1" gives you a lookahead of one, until there is a matching element (because that depletes the budget). This budget can be:
 - a demand
 - an extra lookahead buffer in the interpreter
 - making the filter detached (a buffer on its own)

But all of these are completely isomorphic, so I don't really see an improvement here to be honest. Especially since Akka stream stages do prefetch, so they trigger this lookahead. This is exactly why I am interested in why this was a problem in HTTP, because this seems to be caused by lack of proper prefetch.

**Comment by jrudolph** [comment] 2015-09-03 09:20
The buffer in the HTTP server implementation was added in [this commit](https://github.com/spray/akka/commit/422b0b36615370b56a94b0221618e0709578809b) so maybe you ask @rkuhn what the exact reason was.

Anyway, thanks for the explanation. I agree that it is unlikely to that one will run into this behavior if you just use the akka-stream combinator API. If akka-stream combinators are the only API consumers to be concerned about, the described behavior detail will not matter. However, there may be other users or usages that do not use akka-stream and which will run into this behavior as well. (In this case, it surfaced in a test which uses the testkit which doesn't provide extra demand when checking for completion).

So, if this cannot be fixed easily (because there are no output buffers in akka-stream combinator implementations), maybe just add a note to these kind of combinators that completion is only reported when there is demand and that adding demand can be as simple as adding a `.buffer(1)` behind the element.

**Comment by drewhk** [comment] 2015-09-03 09:44
It is not that it cannot be "fixed", but there is always one-more lookahead that you might need :) The other issue is just a design cleanliness one. In the case of Akka Streams we put the responsibility of prefetching/lookahead/pipelining to the consumer, and "fixing this" would require to put this responsibility to the producer now. 

> maybe just add a note to these kind of combinators that completion is only reported when there is demand 

But that is the thing, it *can* be reported even if there is no demand (request 1, send matching element, send complete), what it cannot do is report completion if there is no demand, and there are non-matching elements in the buffer. Let's rephrase it maybe "completion might not be reported when there is no demand and there are buffered elements in the stage even if all those elements would be filtered out."

> and that adding demand can be as simple as adding a .buffer(1) behind the element.

Increasing the input buffer of the second stage should have the same effect, at least in principle ;) Are we sure that this filter/collect issue is the only reason why that extra buffer space is needed in the original HTTP issue? I think I'll ask @rkuhn because I have a bad feeling about this and want to be sure that I completely understand what is going on here.

**Comment by rkuhn** [comment] 2015-09-03 12:27
I don’t know whether this is the reason for the HTTP workaround, but I don’t think we should “fix” anything for this ticket: precisely when it can be known that the stream will not emit more elements is a question that may not even be decidable, it will always be best effort. The current behavior qualifies for this label, it is the best that we can reasonably do without completely reworking the internals—and the result of doing that would not be perfect either. If the Subscriber does not signal demand then it cannot be terribly interested in completion, but that may just be my opinion.

**Comment by hepin1989** [comment] 2015-09-03 14:11
Come back to the RS specification 2.9
>A Subscriber MUST be prepared to receive an onComplete signal with or without a preceding Subscription.request(long n) call.

And the collect/filter in fact have not override the ```  def onUpstreamFinish(ctx: Ctx): TerminationDirective = ctx.finish()``` ,how could it block the completion?

**Comment by drewhk** [comment] 2015-09-03 14:19
@hepin1989, this has nothing to do with rule 2.9, since it is about receiving an onComplete, not about sending it. Here the situation is the following: let's say our filter is _ != 0. In that case it can happen that:
 - input buffer contains a 0, and it already marked as completed (onComplete has been processed already, but have not been dispatched downstream since 0 is still in the queue)
 - demand from downstream is currently zero
 - at this point, we, from the outside see that the zero will be filtered out anyway and therefore conclude that onComplete could be dispatched
 - the Filter stage on the other hand can only look at the element if it has been pulled, but it is not pulled because there is no demand
 - you are never allowed to pull a filter if there is no demand, because you never know if the element will be filtered or not.

The only thing that you can do, is to "peek", i.e. pull the filter even when you have zero demand, and if it happens to be not filtered out, then store it in a one-element buffer. However this is isomorphic to having just one more demand, the only difference is that the extra buffer space is at the Publisher or at the Subscriber.

There is nothing in the spec that requires a Publisher to signal onComplete without demand though.

**Comment by hepin1989** [comment] 2015-09-03 14:30
@drewhk Thanks,so the real problem is that the singnal exchanged in akka-stream's implement is via message and the message is in the actor's mailbox right?I seem ,so here like the current implement don't have a quick path ,eg :mergePrefered ,for the ```OnComplete or OnError``` right?
If so ,will the OnError need a additional demand in scme case too?

**Comment by drewhk** [comment] 2015-09-03 14:36
No, no, that is a misunderstanding. Shorter summary:
 - since filter might or might not emit after pulled, you always need at least one demand to pull it
 - the only way to determine whether the element will be dropped or emitted by filter is by actually pulling the filter
 
Even shorter, the only way a Processor is allowed to process upstream messages if wether it emits or not depends on the element itself is to have demand.

Even shorter, I believe this is not a bug at all. (although can be surprising, therefore this needs to be documented)

**Comment by hepin1989** [comment] 2015-09-03 14:48
thank you very much,I am wrong,I see:
>an onComplete signal when no more elements are available—all as long as the Subscription is not cancelled.

So yes,this is not a bug at all .can't believe you implement the akka stream,and then akka-http:)

**Comment by viktorklang** [comment] 2015-10-01 10:32
>If the Subscriber does not signal demand then it cannot be terribly interested in completion, but that may just be my opinion.

I strongly disagree with that sentiment. Not being able to receive elements does not imply disinterest in being able to deal with termination.

**Comment by drewhk** [comment] 2015-10-01 10:44
@viktorklang in this case there is no termination. There is no demand, therefore filter is not able to process elements *ahead*. Even if it would peek, there would be a potential, yet-another-element-ahead. I.e. filter properly reports completion after it has processed all upstream elements and received upstream completion.

**Comment by viktorklang** [comment] 2015-10-08 20:48
@drewhk How is that a problem, as long as something has passed the filter and is ready for consumption from the downstream it is not OK to signal completion just yet. This does seem like a weirdness given that Akka Streams famously prefetches, don't you think?

**Comment by rkuhn** [comment] 2015-10-08 21:29
This is all a very tiny detail of that part of the Akka Streams behavior which is defined to be outside of user control anyway, I’m not sure I understand why this is important. We have a large number of stages now that are coded in a certain way and we have not carefully made sure that we propagate termination at the earliest possible moment (in the strict mathematical sense); I also do not see that as a meaningful use of our time, but I may be missing something.

**Comment by viktorklang** [comment] 2015-10-09 07:02
Here's my reasoning:

* Sending onComplete as timely as possible is a desirable quality (as discussed in Reactive Streams specwork)
* Akka Streams the means of sending onComplete more timely (prefetch)
* Nobody has said **Who** is going to improve this behavior, ideally someone reading this message feels compelled to help out

**Comment by drewhk** [comment] 2015-10-09 07:32
@viktorklang I explained already in detail in this ticket, but OK, I repeat myself:

 - filter is a processor just like everything else
 - in order to filter to consume an element from the upstream **it needs at least one demand** from the downstream since it does not know whether it will emit an element or not **without inspecting the element itself**
 - "fixing" this issue would be to add one buffer space to filter, which unfortunately:
 - A: Equivalent to the downstream simply having one more buffer space
 - B: it only shifts the problem one element away
 - C: turns filter itself to a detached op which have surprising semantics if ever used in a fused island

**Comment by viktorklang** [comment] 2015-10-09 07:37
Clearly I am missing out on something fundamental here, let's try to find
5mins sometime next week and see if we can amend that?

**Comment by drewhk** [comment] 2015-10-09 07:41
This ticket contains all the information in the discussion. Please read all my comments carefully.

**Closed** 2015-11-03 11:02 UTC
Labels: bug, t:stream

**Comment by He-Pin** [comment] 2022-10-11 14:58
@patriknw @johanandren Should we apply the same to `dropWhile` and `takeWhile`?

**Comment by johanandren** [comment] 2022-10-12 08:46
On the fence, but given that we went down this path already with `filter` and `collect` I think it could be best to align those as well.
