### ISSUE TITLE
Bring back Flow Log

### ISSUE THREAD

**Issue by patriknw** [akka/akka#15708] opened 2014-08-21 09:35 UTC
Was removed here: https://github.com/akka/akka/pull/15701

**Comment by rkuhn** [comment] 2015-01-22 09:25
will be done together with #13709

**Comment by drewhk** [comment] 2015-04-30 09:25
This has been fixed, right?

**Comment by ktoso** [comment] 2015-04-30 09:26
Correct, closing as duplicate of https://github.com/akka/akka/issues/16378

**Closed** 2015-04-30 09:27 UTC
Labels: 1 - triaged, t:stream
