### ISSUE TITLE
[failed] ArteryUpdSendConsistencyWithThreeLanesSpec

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30085] opened 2021-03-09 11:07 UTC
(multiple tests failures in that spec)

- Artery must be able to identify a remote actor and ping it
- Artery must be able to send messages concurrently preserving order
- Artery  must be able to send messages with actorSelection concurrently  preserving order

https://jenkins.akka.io:8498/job/akka-nightly-2.13/830/

**Comment by johanandren** [comment] 2021-03-10 08:06
Duplicate of #27954

**Closed by johanandren** 2021-03-10 08:06 UTC
Labels: failed
