### ISSUE TITLE
Failed: RollingUpgradeSpec timeout during ContainerCreating step

### ISSUE THREAD

**Issue by seglo** [akka/akka#29601] opened 2020-09-14 17:42 UTC
Maybe a docker image pull timeout.

```
[info] RollingUpgradeSpec:
[info] Rolling upgrade
[info] - should build images
[info] - should deploy an initial cluster then upgrade through all the versions
[info] - should upgrade to version 2.6.5
[info] - should upgrade to version 2.6.9+11-51e32412 *** FAILED ***
[info]   akka-upgrade-testing-blue-5f564cf7c8-dnk5v    1/1     Running             0          2m6s
[info]   akka-upgrade-testing-blue-5f564cf7c8-dvxj5    1/1     Running             0          2m44s
[info]   akka-upgrade-testing-blue-5f564cf7c8-lqskz    1/1     Running             0          56s
[info]   akka-upgrade-testing-green-688d9c79b5-2gjpn   0/1     ContainerCreating   0          0s The code passed to eventually never returned normally. Attempted 44 times over 3.0611979124 minutes. Last failure message: false did not equal true. (RollingUpgradeSpec.scala:173)
[info] Run completed in 8 minutes, 48 seconds.
```

https://travis-ci.com/github/akka/akka-upgrade-testing/builds/184247591#L1831

**Comment by patriknw** [comment] 2020-09-14 17:49
wrong repo and duplicate of https://github.com/akka/akka-upgrade-testing/issues/19

**Closed by patriknw** 2020-09-14 17:49 UTC
