### ISSUE TITLE
Issue with RestartSink.withBackoff and akka-streams-kafka

### ISSUE THREAD

**Issue by juanjoDiaz** [akka/akka#23642] opened 2017-09-15 08:47 UTC
I have a very simple producer:
```
    Source(1 to 8)
      .map(new ProducerRecord[Array[Byte], Int](topic, _))
      .runWith(
        RestartSink.withBackoff(3 seconds, 30 seconds, 0.2) { () => Producer.plainSink(producerSettings)}
      )
```

It work flawlessly when I run it as an app. However, if I run the exact same code within a test I get `java.lang.IllegalStateException: cannot create children while terminating or terminated`

It's interesting that when I run it without the Retry logic it seems to work perfectly.
```
    Source(1 to 8)
      .map(new ProducerRecord[Array[Byte], Int](topic, _))
      .runWith(
        Producer.plainSink(producerSettings)
      )
```

Here is the full error
```
Error during preStart in [akka.stream.scaladsl.RestartWithBackoffSink@747cf70e]: cannot create children while terminating or terminated
java.lang.IllegalStateException: cannot create children while terminating or terminated
	at akka.actor.dungeon.Children.makeChild(Children.scala:270)
	at akka.actor.dungeon.Children.attachChild(Children.scala:48)
	at akka.actor.dungeon.Children.attachChild$(Children.scala:47)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:370)
	at akka.stream.impl.ExtendedActorMaterializer.actorOf(ActorMaterializerImpl.scala:60)
	at akka.stream.impl.GraphStageIsland.onIslandReady(PhasedFusingActorMaterializer.scala:742)
	at akka.stream.impl.IslandTracking.allNestedIslandsReady(PhasedFusingActorMaterializer.scala:330)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:508)
	at akka.stream.impl.SubFusingActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:112)
	at akka.stream.impl.SubFusingActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:101)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:496)
	at akka.stream.scaladsl.Source.runWith(Source.scala:83)
	at akka.stream.scaladsl.RestartWithBackoffSink$$anon$2.startGraph(Restart.scala:136)
	at akka.stream.scaladsl.RestartWithBackoffLogic.preStart(Restart.scala:353)
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:290)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:540)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:659)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:707)
	at akka.actor.Actor.aroundPreStart(Actor.scala:522)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:522)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:650)
	at akka.actor.ActorCell.create(ActorCell.scala:591)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

Any help is more than welcome!

**Comment by johanandren** [comment] 2017-09-18 07:31
This likely means that you are shutting down the actor system in the test before the stream has completed, this can happen for example if you materialize a stream and then just let the test case complete. The restart stages are a bit surprising in that they will try to restart both on failure and upstream completion, this means that if you want to control shutdown with a KillSwitch for example you would have to do that downstream of the restart stage.

**Comment by juanjoDiaz** [comment] 2017-09-18 12:23
Just to add some more info the issue has vanished from my code.

I use [docker-it-scala](https://github.com/whisklabs/docker-it-scala) to spin up [Kafka](https://hub.docker.com/r/spotify/kafka/) for my test and all I've changed is the Timeout for accessing Kafka. Also, I've given some more memory to the tests. So I think that the issue has to do with timing maybe?

In any case, the fact that it worked without `Restart.withBackoff` points to it as the root cause of the actor system shutting down andI would expect that `Restart.withBackoff` doesn't shut down the actor system.

**Comment by jrudolph** [comment] 2019-06-25 15:08
Closing this for lack of enough information to reproduce. Thanks for opening this issue, @juanjoDiaz, please request reopening this issue if you are still affected (but since this ticket is so old, you may also consider opening a new issue).

**Closed by jrudolph** 2019-06-25 15:08 UTC
Labels: 0 - new, t:stream
