### ISSUE TITLE
FAILED: GroupByTest (TCK)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19386] opened 2016-01-08 13:39 UTC
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4737/

```
[info] - required_spec309_requestZeroMustSignalIllegalArgumentException *** FAILED ***
[info]   java.lang.AssertionError: Expected onError(java.lang.IllegalArgumentException) within 500 ms
[info]   at org.testng.Assert.fail(Assert.java:78)
[info]   at org.reactivestreams.tck.TestEnvironment.flopAndFail(TestEnvironment.java:180)
[info]   at org.reactivestreams.tck.TestEnvironment$Receptacle.expectError(TestEnvironment.java:930)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectError(TestEnvironment.java:484)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectError(TestEnvironment.java:476)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectErrorWithMessage(TestEnvironment.java:464)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectErrorWithMessage(TestEnvironment.java:459)
[info]   at org.reactivestreams.tck.PublisherVerification$21.run(PublisherVerification.java:862)
[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1092)
[info]   at org.reactivestreams.tck.PublisherVerification.required_spec309_requestZeroMustSignalIllegalArgumentException(PublisherVerification.java:858)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:497)
[info]   at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
[info]   at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
[info]   at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
[info]   at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
[info]   at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[info]   at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[info]   at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
[info]   at org.testng.TestRunner.privateRun(TestRunner.java:749)
[info]   at org.testng.TestRunner.run(TestRunner.java:600)
[info]   at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
[info]   at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
[info]   at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
[info]   at org.testng.SuiteRunner.run(SuiteRunner.java:223)
[info]   at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[info]   at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[info]   at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
[info]   at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
[info]   at org.testng.TestNG.run(TestNG.java:900)
[info]   at org.scalatest.testng.TestNGSuiteLike$class.run(TestNGSuiteLike.scala:131)
[info]   at akka.stream.tck.AkkaPublisherVerification.run(AkkaPublisherVerification.scala:21)
[info]   at org.scalatest.testng.TestNGSuiteLike$class.runTestNG(TestNGSuiteLike.scala:118)
[info]   at akka.stream.tck.AkkaPublisherVerification.runTestNG(AkkaPublisherVerification.scala:21)
[info]   at org.scalatest.testng.TestNGSuiteLike$class.run(TestNGSuiteLike.scala:63)
[info]   at akka.stream.tck.AkkaPublisherVerification.run(AkkaPublisherVerification.scala:21)
```

**Comment by patriknw** [comment] 2016-02-05 12:41
Marking this as duplicate of #19385

**Closed** 2016-02-05 12:41 UTC
Labels: failed
