### ISSUE TITLE
FAILED: MultiNodeClusterSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#22126] opened 2017-01-10 11:42 UTC
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/380/consoleFull

[JVM-1] - must reach initial convergence *** FAILED *** (25 seconds, 173 milliseconds)
[JVM-1]   4 did not equal 5 (MultiNodeClusterSpec.scala:311)
[JVM-1]   org.scalatest.exceptions.TestFailedException:
[JVM-1]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-1]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[JVM-1]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$3.apply(MultiNodeClusterSpec.scala:311)
[JVM-1]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$3.apply(MultiNodeClusterSpec.scala:311)
[JVM-1]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:303)
[JVM-1]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:314)
[JVM-1]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:814)
[JVM-1]   at

**Comment by patriknw** [comment] 2017-01-10 14:23
This was SurviveNetworkInstabilitySpec and it's caused by
```
channel "aeron:udp?endpoint=a5.moxie:40178" : java.net.BindException: Address already in use
```

We grab the port by binding and closing a socket, so there is a chance that someone else grabs the same port. Not much we can do about that.

**Closed** 2017-10-30 02:41 UTC
Labels: 1 - triaged, failed, t:cluster
