### ISSUE TITLE
Spray based HTTP server crash

### ISSUE THREAD

**Issue by shrenikd** [akka/akka#21795] opened 2016-11-04 08:12 UTC
We have a Spray/Akka based HTTP server that crashed due to an out of memory issue. We analyzed the heap dump and noticed that there are a bunch of akka internal classes that are holding most of the memory. Can someone tell us whether this is a telltale sign of an akka bug?

We're using akka 2.10-2.3.15. Our server creates a bunch of actors (about 8) on every request and shuts down the actors once the request is done. We double checked that all the actors are correctly closing; a cumulative sum of the actor lifecycle "started" and "stopped" logs show near-equal values just before the crash. The JVM was assigned a 2GB heap.

Here's the heap dump analysis (using MAT):
<img width="1067" alt="screen shot 2016-11-04 at 1 00 08 am" src="https://cloud.githubusercontent.com/assets/1895472/19998640/3271c860-a22b-11e6-93c8-205e156cf44e.png">
<img width="739" alt="screen shot 2016-11-04 at 1 00 36 am" src="https://cloud.githubusercontent.com/assets/1895472/19998641/3271d486-a22b-11e6-99e6-24787d8fb5d5.png">

**Comment by drewhk** [comment] 2016-11-04 08:21
> Can someone tell us whether this is a telltale sign of an akka bug?

Very unlikely. These parts are rather solid and we have seen very few bugs in the core area in the last two years. While it is not impossible that you have uncovered an Akka core bug that has been lurking unnoticed during these years, it is very unlikely.

> We double checked that all the actors are correctly closing; a cumulative sum of the actor lifecycle "started" and "stopped" logs show near-equal values just before the crash. The JVM was assigned a 2GB heap.

From your heap dump screenshots I don't really see which object instances are actually leaking. I see the RedBlackTree, which is basically a TreeSet holding children of an actor. However, retained heap is not helping here because it is the aggregation of the objects accessible from this tree. How many Envelope instances do you see? Is it possible that one of your actors accumulate messages in its mailbox faster than it can process it? That is the 99% reason of memory leaks reported by users.

**Comment by ktoso** [comment] 2016-11-10 01:39
Also not really the right place to report these things I think.
Closing - if you could prep self contained reproducer that shows Akka leaks that would be something, but so far I think same as Endre - that part is very unlikely to be leaking.

**Closed by ktoso** 2016-11-10 01:39 UTC
Labels: 0 - new
