### ISSUE TITLE
FAILED: LeaderDowningNodeThatIsUnreachableWithAccrualFailureDetector

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17814] opened 2015-06-23 16:13 UTC
Timeouts in https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2560/consoleFull

```
[JVM-4] LeaderDowningNodeThatIsUnreachableWithAccrualFailureDetectorMultiJvmNode4:
[JVM-2] LeaderDowningNodeThatIsUnreachableWithAccrualFailureDetectorMultiJvmNode2:
[JVM-4] The Leader in a 4 node cluster
[JVM-2] The Leader in a 4 node cluster
[JVM-1] [INFO] [06/20/2015 07:00:40.004] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://LeaderDowningNodeThatIsUnreachableSpec)] Cluster Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034] - Leader is moving node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034] to [Up]
[JVM-1] [INFO] [06/20/2015 07:00:40.287] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://LeaderDowningNodeThatIsUnreachableSpec)] Cluster Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034] - Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a5.moxie:42363] is JOINING, roles []
[JVM-1] [INFO] [06/20/2015 07:00:40.293] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://LeaderDowningNodeThatIsUnreachableSpec)] Cluster Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034] - Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a6.moxie:42711] is JOINING, roles []
[JVM-1] [INFO] [06/20/2015 07:00:40.297] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://LeaderDowningNodeThatIsUnreachableSpec)] Cluster Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034] - Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a5.moxie:37533] is JOINING, roles []
[JVM-1] [INFO] [06/20/2015 07:00:40.397] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://LeaderDowningNodeThatIsUnreachableSpec)] Cluster Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034] - Leader is moving node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a5.moxie:37533] to [Up]
[JVM-1] [INFO] [06/20/2015 07:00:40.398] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://LeaderDowningNodeThatIsUnreachableSpec)] Cluster Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034] - Leader is moving node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a5.moxie:42363] to [Up]
[JVM-1] [INFO] [06/20/2015 07:00:40.398] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://LeaderDowningNodeThatIsUnreachableSpec)] Cluster Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034] - Leader is moving node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a6.moxie:42711] to [Up]
[JVM-3] [INFO] [06/20/2015 07:00:40.419] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://LeaderDowningNodeThatIsUnreachableSpec)] Cluster Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a6.moxie:42711] - Welcome from [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034]
[JVM-4] [INFO] [06/20/2015 07:00:40.425] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://LeaderDowningNodeThatIsUnreachableSpec)] Cluster Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a5.moxie:42363] - Welcome from [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034]
[JVM-2] [INFO] [06/20/2015 07:00:40.434] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-14] [akka.cluster.Cluster(akka://LeaderDowningNodeThatIsUnreachableSpec)] Cluster Node [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a5.moxie:37533] - Welcome from [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034]
[JVM-4] [WARN] [06/20/2015 07:00:40.580] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-3] [akka://LeaderDowningNodeThatIsUnreachableSpec/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FLeaderDowningNodeThatIsUnreachableSpec%40a6.moxie%3A42711-1] unhandled message from Actor[akka://LeaderDowningNodeThatIsUnreachableSpec/system/endpointManager#684969920]: Ungate
[JVM-3] [WARN] [06/20/2015 07:00:40.588] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-14] [akka://LeaderDowningNodeThatIsUnreachableSpec/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FLeaderDowningNodeThatIsUnreachableSpec%40a5.moxie%3A42363-1] unhandled message from Actor[akka://LeaderDowningNodeThatIsUnreachableSpec/system/endpointManager#-679890759]: Ungate
[JVM-4] Heap
[JVM-4]  PSYoungGen      total 76288K, used 64566K [0x00000000f5580000, 0x00000000fea80000, 0x0000000100000000)
[JVM-4]   eden space 65536K, 82% used [0x00000000f5580000,0x00000000f8a124d8,0x00000000f9580000)
[JVM-4]   from space 10752K, 99% used [0x00000000f9580000,0x00000000f9ffb5f0,0x00000000fa000000)
[JVM-4]   to   space 10752K, 0% used [0x00000000fe000000,0x00000000fe000000,0x00000000fea80000)
[JVM-4]  ParOldGen       total 175104K, used 1803K [0x00000000e0000000, 0x00000000eab00000, 0x00000000f5580000)
[JVM-4]   object space 175104K, 1% used [0x00000000e0000000,0x00000000e01c2f20,0x00000000eab00000)
[JVM-4]  Metaspace       used 26508K, capacity 26984K, committed 27136K, reserved 1073152K
[JVM-4]   class space    used 3854K, capacity 3980K, committed 4096K, reserved 1048576K
[JVM-1] [WARN] [06/20/2015 07:00:41.035] [LeaderDowningNodeThatIsUnreachableSpec-akka.remote.default-remote-dispatcher-6] [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a3.moxie:54034/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FLeaderDowningNodeThatIsUnreachableSpec%40a5.moxie%3A42363-0] Association with remote system [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a5.moxie:42363] has failed, address is now gated for [5000] ms. Reason: [Disassociated] 
[JVM-2] [WARN] [06/20/2015 07:00:41.039] [LeaderDowningNodeThatIsUnreachableSpec-akka.remote.default-remote-dispatcher-5] [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a5.moxie:37533/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FLeaderDowningNodeThatIsUnreachableSpec%40a5.moxie%3A42363-2] Association with remote system [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a5.moxie:42363] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a5.moxie:42363]] Caused by: [The remote system explicitly disassociated (reason unknown).]
[JVM-3] [WARN] [06/20/2015 07:00:41.050] [LeaderDowningNodeThatIsUnreachableSpec-akka.remote.default-remote-dispatcher-5] [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a6.moxie:42711/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FLeaderDowningNodeThatIsUnreachableSpec%40a5.moxie%3A42363-1] Association with remote system [akka.tcp://LeaderDowningNodeThatIsUnreachableSpec@a5.moxie:42363] has failed, address is now gated for [5000] ms. Reason: [Disassociated] 
[JVM-3] [WARN] [06/20/2015 07:00:41.054] [LeaderDowningNodeThatIsUnreachableSpec-akka.actor.default-dispatcher-4] [akka://LeaderDowningNodeThatIsUnreachableSpec/system/endpointManager/endpointWriter-akka.tcp%3A%2F%2FLeaderDowningNodeThatIsUnreachableSpec%40a5.moxie%3A42363-3] received dead letter from Actor[akka://LeaderDowningNodeThatIsUnreachableSpec/system/endpointManager/endpointWriter-akka.tcp%3A%2F%2FLeaderDowningNodeThatIsUnreachableSpec%40a5.moxie%3A42363-3#1359607954]: AckIdleCheckTimer
[JVM-3] - must be able to DOWN a 'last' node that is UNREACHABLE *** FAILED *** (5 seconds, 769 milliseconds)
[JVM-3]   java.util.concurrent.TimeoutException: Futures timed out after [5000 milliseconds]
[JVM-3]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[JVM-3]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[JVM-3]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[JVM-3]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[JVM-3]   at scala.concurrent.Await$.result(package.scala:190)
[JVM-3]   at akka.remote.testkit.MultiNodeSpec$AwaitHelper.await(MultiNodeSpec.scala:263)
[JVM-3]   at akka.remote.testkit.MultiNodeSpec.node(MultiNodeSpec.scala:364)
[JVM-3]   at akka.cluster.MultiNodeClusterSpec$class.address(MultiNodeClusterSpec.scala:156)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec.address(LeaderDowningNodeThatIsUnreachableSpec.scala:37)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LeaderDowningNodeThatIsUnreachableSpec.scala:52)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(LeaderDowningNodeThatIsUnreachableSpec.scala:49)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(LeaderDowningNodeThatIsUnreachableSpec.scala:49)
[JVM-3]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[JVM-3]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-3]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[JVM-3]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec.akka$cluster$MultiNodeClusterSpec$$super$withFixture(LeaderDowningNodeThatIsUnreachableSpec.scala:37)
[JVM-3]   at akka.cluster.MultiNodeClusterSpec$class.withFixture(MultiNodeClusterSpec.scala:171)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec.withFixture(LeaderDowningNodeThatIsUnreachableSpec.scala:37)
[JVM-3]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
```

**Comment by patriknw** [comment] 2015-06-24 12:09
This is a duplicate of #16890

**Closed by patriknw** 2015-06-24 12:09 UTC
Labels: failed, t:cluster
