### ISSUE TITLE
FAILED RemoteDeploymentDeathWatchSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20220] opened 2016-04-04 13:07 UTC
https://jenkins.akka.io:8498/job/akka-nightly/3201/consoleFull

```
[JVM-2] - must be able to shutdown when remote node crash *** FAILED *** (20 seconds, 50 milliseconds)
[JVM-2]   Failed to stop [RemoteDeploymentDeathWatchSpec] within [8882865461 nanoseconds] 
[JVM-2]   -> / LocalActorRefProvider$$anon$1 class akka.actor.LocalActorRefProvider$Guardian status=0 2 children
[JVM-2]      ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 9 children
[JVM-2]      |   ⌊-> deadLetterListener RepointableActorRef class akka.event.DeadLetterListener status=0 no children
[JVM-2]      |   ⌊-> endpointManager RepointableActorRef class akka.remote.EndpointManager status=0 no children
[JVM-2]      |   ⌊-> eventStreamUnsubscriber-1 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
[JVM-2]      |   ⌊-> log1-TestEventListener RepointableActorRef class akka.testkit.TestEventListener status=0 no children
[JVM-2]      |   ⌊-> remote-deployment-watcher RepointableActorRef class akka.remote.RemoteDeploymentWatcher status=0 no children
[JVM-2]      |   ⌊-> remote-watcher RepointableActorRef class akka.remote.RemoteWatcher status=0 no children
[JVM-2]      |   ⌊-> remoting-terminator RepointableActorRef class akka.remote.RemoteActorRefProvider$RemotingTerminator status=0 no children
[JVM-2]      |   ⌊-> testActor-1 RepointableActorRef class akka.testkit.TestActor status=0 no children
[JVM-2]      |   ⌊-> transports RepointableActorRef class akka.remote.Remoting$TransportSupervisor status=0 1 children
[JVM-2]      |       ⌊-> akkaprotocolmanager.tcp0 LocalActorRef class akka.remote.transport.AkkaProtocolManager status=0 no children
[JVM-2]      ⌊-> user LocalActorRef class akka.actor.LocalActorRefProvider$Guardian status=0 1 children
[JVM-2]          ⌊-> TestConductorClient RepointableActorRef class akka.remote.testconductor.ClientFSM status=0 no children (RemoteDeploymentDeathWatchSpec.scala:84)
[JVM-2]   org.scalatest.exceptions.TestFailedException:
[JVM-2]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:495)
[JVM-2]   at akka.remote.RemoteDeploymentDeathWatchSpec.newAssertionFailedException(RemoteDeploymentDeathWatchSpec.scala:55)
[JVM-2]   at org.scalatest.Assertions$class.fail(Assertions.scala:1328)
```

**Comment by patriknw** [comment] 2016-04-05 13:38
The cause is:
```
[JVM-1]   akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://RemoteDeploymentDeathWatchSpec/user/controller#-110366658]] after [5000 ms]. Sender[null] sent message of type "akka.remote.testconductor.Terminate".
```

Something with `testConductor.exit` or `testConductor.shutdown` that doesn't complete in time.

Leaving it for now.

**Comment by drewhk** [comment] 2016-08-02 10:06
Have not reoccured since 4 months, closing.

**Closed by drewhk** 2016-08-02 10:06 UTC
Labels: 1 - triaged, failed
