### ISSUE TITLE
The doc links are out dated on this page

### ISSUE THREAD

**Issue by CodeCombiner** [akka/akka#24047] opened 2017-11-22 22:56 UTC
Hi guys!
The doc links are out dated on this page
https://doc.akka.io/docs/akka-http/current/scala/http/client-side/client-https-support.html

**Comment by ktoso** [comment] 2017-11-23 01:33
Thanks for the report; to be specific though -- the link to lightbend ssl config is outdated, yeah.
This is fixed already on master in 4d6095b30e37a9fbeed4c6e0db7e1be05d303bdb and will be published with 10.0.11 shortly.

I'll close this ticket since the issue is resolved on master and about to be released.
Thanks for reporting though :)

**Comment by ktoso** [comment] 2017-11-23 01:34
Please do notice that when you opened the ticket there's an explanation about akka-http issues to be reported in http://github.com/akka/akka-http please open tickets about akka http over there next time -- thanks!

**Closed by ktoso** 2017-11-23 01:34 UTC

**Comment by ktoso** [comment] 2017-11-23 01:35
Copied the ticket to https://github.com/akka/akka-http/issues/1546 so it can be assigned to the right milestone
