### ISSUE TITLE
[FAIL] NodeChurnSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23319] opened 2017-07-10 06:49 UTC
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/13946/consoleFull

```
[JVM-2] - must join and remove transient nodes without growing gossip payload (on node 'second', class akka.cluster.NodeChurnMultiJvmNode2) *** FAILED *** (39 seconds, 249 milliseconds)
[JVM-2]   java.lang.AssertionError: assertion failed: received unexpected message New maximum payload size for [akka.cluster.GossipEnvelope] is [1324] bytes
[JVM-2]   at scala.Predef$.assert(Predef.scala:170)
[JVM-2]   at akka.testkit.TestKitBase$class.expectNoMsg_internal(TestKit.scala:633)
[JVM-2]   at akka.testkit.TestKitBase$class.expectNoMsg(TestKit.scala:629)
[JVM-2]   at akka.testkit.TestKit.expectNoMsg(TestKit.scala:831)
[JVM-2]   at akka.cluster.NodeChurnSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6.apply$mcVI$sp(NodeChurnSpec.scala:144)
[JVM-2]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
```

**Comment by johanandren** [comment] 2017-07-10 06:49
Could possibly be related to multi-dc as the multi-dc is where it failed but the message sounds like it is something else.

**Comment by patriknw** [comment] 2017-08-15 14:01
Duplicate of https://github.com/akka/akka/issues/23369

**Closed by patriknw** 2017-08-15 14:01 UTC
Labels: 1 - triaged, failed, t:cluster, t:cluster:dc
