### ISSUE TITLE
[akka-http 2.0.3] `akka.http.host-connection-pool.max-connections = 1` causes exception

### ISSUE THREAD

**Issue by jadlr** [akka/akka#19867] opened 2016-02-24 14:24 UTC
The documentation states that the value must be greater than 0.

```
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:172) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:606) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:223) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: java.lang.IllegalArgumentException: requirement failed: A Merge must have more than 1 input port
	at scala.Predef$.require(Predef.scala:219) ~[scala-library-2.11.7.jar:na]
	at akka.stream.scaladsl.Merge.<init>(Graph.scala:40) ~[akka-stream-experimental_2.11-2.0.3.jar:na]
	at akka.stream.scaladsl.Merge$.apply(Graph.scala:23) ~[akka-stream-experimental_2.11-2.0.3.jar:na]
	at akka.http.impl.engine.client.PoolFlow$$anonfun$apply$1.apply(PoolFlow.scala:81) ~[akka-http-core-experimental_2.11-2.0.3.jar:na]
	at akka.http.impl.engine.client.PoolFlow$$anonfun$apply$1.apply(PoolFlow.scala:73) ~[akka-http-core-experimental_2.11-2.0.3.jar:na]
	at akka.stream.scaladsl.GraphApply$class.create(GraphApply.scala:16) ~[akka-stream-experimental_2.11-2.0.3.jar:na]
	at akka.stream.scaladsl.GraphDSL$.create(Graph.scala:707) ~[akka-stream-experimental_2.11-2.0.3.jar:na]
	at akka.http.impl.engine.client.PoolFlow$.apply(PoolFlow.scala:73) ~[akka-http-core-experimental_2.11-2.0.3.jar:na]
	at akka.http.impl.engine.client.PoolInterfaceActor.initConnectionFlow(PoolInterfaceActor.scala:71) ~[akka-http-core-experimental_2.11-2.0.3.jar:na]
	at akka.http.impl.engine.client.PoolInterfaceActor.<init>(PoolInterfaceActor.scala:59) ~[akka-http-core-experimental_2.11-2.0.3.jar:na]
	at akka.http.impl.engine.client.PoolGateway$$anonfun$1.apply(PoolGateway.scala:43) ~[akka-http-core-experimental_2.11-2.0.3.jar:na]
	at akka.http.impl.engine.client.PoolGateway$$anonfun$1.apply(PoolGateway.scala:43) ~[akka-http-core-experimental_2.11-2.0.3.jar:na]
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.Props.newActor(Props.scala:214) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.newActor(ActorCell.scala:562) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:588) ~[akka-actor_2.11-2.4.2.jar:na]
	... 9 common frames omitted
```

**Comment by ktoso** [comment] 2016-02-24 14:26
Please upgrade to the latest version: 2.4.2 (at time of writing), where this is fixed: https://github.com/akka/akka/issues/19549

**Comment by ktoso** [comment] 2016-02-24 14:26
Thanks for reporting though I think that's a duplicate of https://github.com/akka/akka/issues/19549 which is resolved, so I'd like close the ticket if you don't mind :)

**Closed** 2016-02-24 14:31 UTC
Labels: t:stream

**Comment by jadlr** [comment] 2016-02-24 14:33
sure, looks like my search was not thorough enough.

**Comment by ktoso** [comment] 2016-02-24 14:34
No problem, thanks for reporting! :-)
