### ISSUE TITLE
ambiguous persist overload with Java when using Scala 2.12 artifacts

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22218] opened 2017-01-25 09:27 UTC
How to reproduce:

```
sbt -Dakka.build.scalaVersion=2.12.1 -D akka-docs/test:compile
```

```
[error] /Users/patrik/dev/akka/akka-docs/rst/java/code/docs/persistence/LambdaPersistenceDocTest.java:194:  error: reference to persist is ambiguous
[error]               persist(new MsgSent(s), evt -> updateState(evt));
[error]               ^
[error] /Users/patrik/dev/akka/both method <A#1>persist(A#1,Function1<A#1,BoxedUnit>) in AbstractPersistentActor and method <A#2>persist(A#2,Procedure<A#2>) in AbstractPersistentActor match
[error]   where A#1,A#2 are type-variables:A#1 extends Object declared in method <A#1>persist(A#1,Function1<A#1,BoxedUnit>)
[error]     A#2 extends Object declared in method <A#2>persist(A#2,Procedure<A#2>)
[error] /Users/patrik/dev/akka/akka-docs/rst/java/code/docs/persistence/LambdaPersistenceDocTest.java:194:  error: incompatible types: cannot infer type-variable(s) A
[error]               persist(new MsgSent(s), evt -> updateState(evt));
[error]
```

The methods are:

https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala#L319

https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/PersistentActor.scala#L206

**Comment by lrytz** [comment] 2017-01-25 09:49
Tricky one.. In 2.11, the Java compiler picks the `Procedure` overload because `Function1` is not a SAM (ue to the trait compilation scheme, the interface `Function1` has an abstract method `compose` in 2.11).

In 2.12, with default methods, `Function1` is a SAM, so both types now work for the (Java) lambda.

**Comment by lrytz** [comment] 2017-01-25 09:59
Minimized example for reference:

```
$ cat Test.scala
trait Procedure[-T] { def apply(t: T): Unit }
class C {
  def m[A](a: A, p: Procedure[A]): Unit  = p(a)
  def m[A](a: A)(f: A => Unit): Unit = f(a)
}

$ cat A.java
public class A {
  public static void foo() {
    C c = new C();
    c.m("", s -> System.out.println(s));
  }
}

$ scalac12 Test.scala && javac -cp .:/Users/luc/scala/scala-2.12/lib/scala-library.jar A.java
A.java:4: error: reference to m is ambiguous
    c.m("", s -> System.out.println(s));
     ^
  both method <A#1>m(A#1,Procedure<A#1>) in C and method <A#2>m(A#2,Function1<A#2,BoxedUnit>) in C match
  where A#1,A#2 are type-variables:
    A#1 extends Object declared in method <A#1>m(A#1,Procedure<A#1>)
    A#2 extends Object declared in method <A#2>m(A#2,Function1<A#2,BoxedUnit>)
1 error
```

**Comment by patriknw** [comment] 2017-01-25 09:59
So the proper fix would be to remove the Java API method in PersistentActor.scala for the Scala 2.12 build? That would still be source compatible, and not influence Scala API users.

**Comment by lrytz** [comment] 2017-01-25 10:01
If you remove the `Procedure` overload in the example you get
```
A.java:4: error: incompatible types: cannot infer type-variable(s) A
    c.m("", s -> System.out.println(s));
       ^
    (argument mismatch; bad return type in lambda expression
      void cannot be converted to BoxedUnit)
  where A is a type-variable:
    A extends Object declared in method <A>m(A,Function1<A,BoxedUnit>)
1 error
```

This is very annoying for the Java API, I don't have a solution at hand right now.

**Comment by lrytz** [comment] 2017-01-25 13:14
One idea would be to only keep the alternative with the `Procedure` argument (with two argument lists, to help Scala's type inference). For better Scala compatibility, `Procedure` should extend `Function1`. The problem is that if you write the `Procedure` class in Scala, this won't work - I don't know if this is a bug in Scala's code generation?

```
$ cat Test.scala
trait Procedure[-T] extends (T => Unit) { def apply(t: T): Unit }
class C {
  def m[A](a: A)(p: Procedure[A]): Unit  = p(a)
  def test = m("hi")(s => println(s))
}

$ cat A.java
public class A {
  public static void foo() {
    C c = new C();
    c.m("", s -> System.out.println(s));
  }
}

$ scalac12 Test.scala && javac -cp .:/Users/luc/scala/scala-2.12/lib/scala-library.jar A.java
A.java:4: error: method m in class C cannot be applied to given types;
    c.m("", s -> System.out.println(s));
     ^
  required: A,Procedure<A>
  found: String,(s)->Syste[...]ln(s)
  reason: cannot infer type-variable(s) A
    (argument mismatch; incompatible function descriptors found in interface Procedure
        descriptor: void apply(T)
        descriptor: R apply(T1))
  where A,T,T1,R are type-variables:
    A extends Object declared in method <A>m(A,Procedure<A>)
    T extends Object declared in interface Procedure
    T1 extends Object declared in interface Function1
    R extends Object declared in interface Function1
1 error
```

You can instead write the `Procedure` class in Java, then things work. Note that this is exactly the `JProcedure1` interface provided by [scala-java8-compat](https://github.com/scala/scala-java8-compat/blob/master/src/test/java/scala/compat/java8/LambdaTest.java#L85-L96):

```
$ cat Procedure.java
import scala.runtime.BoxedUnit;
public interface Procedure<T1> extends scala.Function1<T1, BoxedUnit> {
  void applyVoid(T1 t1);
  default BoxedUnit apply(T1 t1) { applyVoid(t1); return BoxedUnit.UNIT; }
}

$ cat Test.scala
class C {
  def m[A](a: A)(p: Procedure[A]): Unit  = p(a)
  def test = m("hi")(s => println(s))
}

$ cat A.java
public class A {
  public static void foo() {
    C c = new C();
    c.m("", s -> System.out.println(s));
  }
}
$ javac -cp .:/Users/luc/scala/scala-2.11/lib/scala-library.jar Procedure.java
$ scalac12 Test.scala && javac -cp .:/Users/luc/scala/scala-2.12/lib/scala-library.jar A.java
$
```

But then you have issues in Scala's type system:

```
scala> val p: Procedure[Object] = null
p: Procedure[Object] = null

scala> val sp: Procedure[String] = p // nope, it's invariant
<console>:12: error: type mismatch;
 found   : Procedure[Object]
 required: Procedure[String]
Note: Object >: String, but Java-defined trait Procedure is invariant in type T1.
You may wish to investigate a wildcard type such as `_ >: String`. (SLS 3.2.10)
       val sp: Procedure[String] = p // nope, it's invariant
                                   ^

scala> val f: Object => Unit = p // nope, it's BoxedUnit
<console>:12: error: type mismatch;
 found   : Procedure[Object]
 required: Object => Unit
       val f: Object => Unit = p // nope, it's BoxedUnit
                               ^

scala> val f: Object => scala.runtime.BoxedUnit = p // ok
f: Object => scala.runtime.BoxedUnit = null

scala> val f: String => scala.runtime.BoxedUnit = p // ok
f: String => scala.runtime.BoxedUnit = null
```

No satisfying solution yet.. cc @retronym

**Comment by adriaanm** [comment] 2017-01-25 19:06
> The problem is that if you write the Procedure class in Scala, this won't work - I don't know if this is a bug in Scala's code generation?

I guess this is because Function1 has `public abstract R apply(T1);`, which cannot be matched by `Procedure`'s `public abstract void apply(T);`, because `R = void` is not valid in Java. We could/should(?) emit a bridge method.

> For better Scala compatibility, Procedure should extend Function1

If you remove the `extends` clause, it compiles. True, you can't pass `Procedure[T]` instances into other higher-order methods that expect a `Function1[T, Unit]`, but maybe that trade off is ok?

```
trait Procedure[-T] { def apply(t: T): Unit }
class C {
  def m[A](a: A)(p: Procedure[A]): Unit  = p(a)
  def test = m("hi")(s => println(s))
}
```

```
public class A {
  public static void foo() {
    C c = new C();
    c.m("", s -> System.out.println(s));
  }
}
```

**Comment by patriknw** [comment] 2017-01-26 12:55
Thanks for investigations. The options are limited by that we should be binary backwards compatible for the Scala API method. We can break binary compatibility for the Java API method in this case, but we should preferably still be source compatible.

**Comment by johanandren** [comment] 2017-02-20 13:51
Yay, merged!

**Closed** 2017-02-20 13:51 UTC
Labels: 3 - in progress, t:persistence

**Comment by GHogChi** [comment] 2017-07-20 15:38
Similar illegal overload problem in the Http class. Here's IDEA's decompilation of the offending code (lines 69-75, akka-http-core_2.12-10.0.9):

  public static Http get(ActorSystem var0) {
        return Http$.MODULE$.get(var0);
    }

    public static Extension get(ActorSystem var0) {
        return Http$.MODULE$.get(var0);
    }

This causes a red flag in the IDEA editor panes for callers of the method, but no other compile problems and it works okay at runtime.

**Comment by johanandren** [comment] 2017-07-20 19:42
Please don't comment on an old and closed ticket, open a new ticket for this in the akka-http issue tracker over here: https://github.com/akka/akka-http/issues Thanks!
