### ISSUE TITLE
Typed `ActorRef.apply(future: Future[ActorRef[_]])` fails when run on an adapted ActorSystem

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23669] opened 2017-09-20 14:30 UTC
With an exception like this:

```
[info]   at akka.typed.internal.adapter.ActorRefAdapter$.toUntyped(ActorRefAdapter.scala:32)
[info]   at akka.typed.internal.adapter.ActorRefAdapter$.sendSystemMessage(ActorRefAdapter.scala:43)
[info]   at akka.typed.internal.adapter.ActorRefAdapter.sendSystem(ActorRefAdapter.scala:22)
[info]   at akka.typed.internal.FutureRef$$anonfun$1.apply(ActorRefImpl.scala:180)
[info]   at akka.typed.internal.FutureRef$$anonfun$1.apply(ActorRefImpl.scala:172)
[info]   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
[info]   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[info]   at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73)
[info]   at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:78)
[info]   at akka.dispatch.BatchingExecutor$class.execute(BatchingExecutor.scala:120)
[info]   at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:77)
[info]   at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:44)
[info]   at scala.concurrent.impl.Promise$KeptPromise.onComplete(Promise.scala:337)
[info]   at akka.typed.internal.FutureRef.<init>(ActorRefImpl.scala:186)
[info]   at akka.typed.ActorRef$.apply(ActorRef.scala:68)

```

**Comment by jrudolph** [comment] 2017-09-21 08:49
More generally, there should be a way to adapt ActorRefs both ways. Right now, the implicit assumption is that in an AdaptedActorSystem every typed ActorRef is necessarily a wrapped adapted untyped one that just need to be unwrapped. However, this is not true like for the `FutureRef` here.

**Comment by jrudolph** [comment] 2017-09-21 09:05
The original issue will be fixed by this commit: The original issue will be fixed by this: https://github.com/akka/akka/pull/23677/commits/07b22708be309e0439fdde316d73797cc25a3e71.

**Comment by ktoso** [comment] 2017-10-30 07:31
FYI: I investigated this a bit but was unconclusive about how to best address this without having to write the entire adapter dance for the other side, which I'm not sure we want to invest in now hm...

**Comment by johanandren** [comment] 2017-12-13 13:07
I think one may be a duplicate or at least closely related ticket: #22640

**Comment by patriknw** [comment] 2017-12-13 13:59
Closing as duplicate of #22640
and perhaps somewhat not relevant if we do #24149

**Closed by patriknw** 2017-12-13 13:59 UTC
Labels: 1 - triaged, bug, t:core, t:typed
