### ISSUE TITLE
Akka-http: The first character of utf-8 strings in json is not unmarshalled properly

### ISSUE THREAD

**Issue by moricard** [akka/akka#18856] opened 2015-11-04 18:54 UTC
When the first character of a string property in a json object is accented (é, à, è, etc...), it does not get unmarshalled properly. Given the following test:

```scala
class Utf8UnmarshallingSpec extends FlatSpec with Matchers with ScalaFutures with ScalatestRouteTest with DefaultJsonProtocol {
  override def testConfigSource = "akka.loglevel = WARNING"

  it should "unmarshal utf-8 strings with the first accented character" in {
    import json._
    val jsonArray = "[\"électronique\"]".parseJson
    val entityFuture = Marshal(jsonArray).to[MessageEntity]
    val entity = Await.result(entityFuture, 1 second)

   // This case fails
    whenReady(Unmarshal(entity).to[List[String]]) {
      case head :: Nil => head shouldBe "électronique"
    }

    whenReady(Unmarshal(entity).to[String]) {
      case string => string shouldBe "[\"électronique\"]"
    }
  }

  it should "unmarshal utf-8 strings with any accented character" in {
    import json._
    val jsonArray = "[\"dépôt\"]".parseJson
    val entityFuture = Marshal(jsonArray).to[MessageEntity]
    val entity = Await.result(entityFuture, 1 second)

    whenReady(Unmarshal(entity).to[List[String]]) {
      case head :: Nil => head shouldBe "dépôt"
    }
  }
}
```

The first assertion fails with the following message: `"[Ã�]lectronique" was not equal to "[é]lectronique"`

**Comment by ktoso** [comment] 2015-11-04 19:23
Thanks for reporting!

**Comment by ktoso** [comment] 2015-11-04 19:34
I can confirm it works on HEAD now, which is using `spray-json_2.10-1.3.2.jar`. 

We had a related bug fixed recently, first here: https://github.com/akka/akka/pull/18390 and then by fixing `spray-json` itself (and this PR https://github.com/akka/akka/pull/18836 bringing back the usual method inside the impl).

In other words – this is fixed on HEAD, and the fix will be released as part of `2.0-M1`, which we're aiming to release this week (maybe tomorrow even).

**Comment by ktoso** [comment] 2015-11-04 19:35
Duplicate of https://github.com/akka/akka/issues/18389

**Closed by ktoso** 2015-11-04 19:34 UTC
Labels: t:http

**Comment by moricard** [comment] 2015-11-04 19:59
I can confirm that forcing the spray-json version to `"io.spray" %% "spray-json" % "1.3.2"` in my build works. Thanks for the quick response.

**Comment by ktoso** [comment] 2015-11-04 20:00
happy hakking!
