### ISSUE TITLE
Warning while deserializing HandshakeReq when a RemoteInstrument is present

### ISSUE THREAD

**Issue by SimunKaracic** [akka/akka#29911] opened 2020-12-18 15:04 UTC
When using Akka cluster, a warning is thrown on a node that receives a HandshakeReq **_and_** has a RemoteInstrument.
Warning (i'm assuming it's there 4 times for 4 retries of the reques):
```
[2020-12-18 15:37:21,717] [WARN] [akka.remote.artery.Deserializer] [] [ClusterSystem-akka.actor.default-dispatcher-6] - Failed to deserialize message from [unknown] with serializer id [17] and manifest [d]. java.lang.IllegalArgumentException
[2020-12-18 15:37:21,717] [WARN] [akka.remote.artery.Deserializer] [] [ClusterSystem-akka.actor.default-dispatcher-6] - Failed to deserialize message from [unknown] with serializer id [17] and manifest [d]. java.lang.IllegalArgumentException
[2020-12-18 15:37:21,718] [WARN] [akka.remote.artery.Deserializer] [] [ClusterSystem-akka.actor.default-dispatcher-6] - Failed to deserialize message from [unknown] with serializer id [17] and manifest [d]. java.lang.IllegalArgumentException
[2020-12-18 15:37:21,718] [WARN] [akka.remote.artery.Deserializer] [] [ClusterSystem-akka.actor.default-dispatcher-6] - Failed to deserialize message from [unknown] with serializer id [17] and manifest [d]. java.lang.IllegalArgumentException
```

Reproduction steps: 
1. Download the akka-cluster sample https://developer.lightbend.com/start/?group=akka&project=akka-samples-cluster-scala
2. Create a new class `DummyRemoteInstrument` in package `sample.cluster.simple` 
3. Copy `DummyRemoteInstrument` from  https://github.com/akka/akka/blob/a4acf23d0541471ecf81b9ba5dd97c2e97670814/akka-bench-jmh/src/main/scala/akka/remote/artery/CodecBenchmark.scala#L291 into the newly created class, adding imports as needed. I'll paste the file contents below for convenience.
4. Add `akka.remote.artery.advanced.instruments += "sample.cluster.simple.DummyRemoteInstrument"` to the end of `application.conf`
5. Open 2 console windows, running `sbt "runMain sample.cluster.simple.App 25251"` in one and `sbt "runMain sample.cluster.simple.App 25252"` in the other.

Pretty sure the error occurs in `deserializeRaw` in `RemoteInstrument`. 
It's either being called when it shouldn't be (no metadata to be deserialized), or RemoteInstruments are not being attached before a `HandshakeReq` is sent.
Or something else, I'll leave the debugging to the experts :)

DummyRemoteInstrument contents:
```
package sample.cluster.simple

import akka.actor.ActorRef
import akka.remote.artery.RemoteInstrument

import java.io.IOException
import java.nio.ByteBuffer
import scala.annotation.tailrec

class DummyRemoteInstrument extends RemoteInstrument {
  private val Metadata = "slevin".getBytes

  override def identifier: Byte = 7 // Lucky number slevin

  override def remoteWriteMetadata(
    recipient: ActorRef,
    message: Object,
    sender: ActorRef,
    buffer: ByteBuffer): Unit = {

    buffer.putInt(Metadata.length)
    buffer.put(Metadata)
  }

  override def remoteReadMetadata(
    recipient: ActorRef,
    message: Object,
    sender: ActorRef,
    buffer: ByteBuffer): Unit = {
    val length = Metadata.length
    val metaLength = buffer.getInt

    @tailrec
    def compare(pos: Int): Boolean = {
      if (pos == length) true
      else if (Metadata(pos) == buffer.get()) compare(pos + 1)
      else false
    }

    if (metaLength != length || !compare(0))
      throw new IOException(s"DummyInstrument deserialization error. Expected ${Metadata.toString}")
  }

  override def remoteMessageSent(
    recipient: ActorRef,
    message: Object,
    sender: ActorRef,
    size: Int,
    time: Long): Unit = ()

  override def remoteMessageReceived(
    recipient: ActorRef,
    message: Object,
    sender: ActorRef,
    size: Int,
    time: Long): Unit = ()
}
```

**Comment by johanandren** [comment] 2020-12-21 08:30
Hi @SimunKaracic, Note that the `RemoteInstrument` is marked as internal API and not intended as a user extension point of Akka. I think the reason you are seeing deserialization failure is because you are not copying enough of the config from the CodecBenchmark.

**Comment by SimunKaracic** [comment] 2020-12-21 09:31
I know it's not intended to be extended :/
Is there another way to attach arbitrary things to messages sent between nodes?

> you are not copying enough of the config

Can you elaborate on what I missed in the config?
I tried the same thing with my own remote instrument, and (except for the warning on HandshakeReq) it works! Messages are getting serialized and deserialized correctly

**Comment by johanandren** [comment] 2020-12-21 09:41
The supported way to attach arbitrary things to messages is to include the arbitrary objects in the messages.

From you instruction, copying the DummyMessageSerializer and the config enabling it from the benchmark was not mentioned so I guessed that was it, but maybe you copied that as well but didn't mention.

**Comment by SimunKaracic** [comment] 2020-12-21 09:52
What if I want to hook into all messages being sent between akka nodes?
I'm guessing that's not supported though :/

> copying the DummyMessageSerializer and the config enabling it from the benchmark

For whoever ends up debugging this, I did not copy it at first, but I just tried adding the DummyMessageSerializer and the remaining config, but it didn't make a difference

**Comment by johanandren** [comment] 2020-12-21 11:32
That is correct, there is no user API for hooking into all messages including internal Akka messages sent over remoting. You could achieve it with the `RemoteInstrument` but there is no guarantee that API does not chang between patch versions of Akka.

I'm going to close this issue, but for the error you are seeing, I'd guess it is something with serializer config so trying to debug that and verifying the serializer is defined on both sides, and exactly where in the serialization infra it fails is what I'd recommend.

**Comment by johanandren** [comment] 2020-12-21 11:33
Feel free to ask the same question in the forums if you like though. https://discuss.akka.io

**Comment by ivantopo** [comment] 2021-01-06 00:42
Hey @johanandren, hello from the Kamon Team!

I was digging into this issue today and found something interesting: during the handshaking process, a few `ByteBuffer` instances inside `InboundEnvelope` are set to BigEndian, even though all the `ByteBuffer` instances created by the Artery implementation are explicitly set to LittleEndian:
https://github.com/akka/akka/blob/73a9bbb2643bc25a7a50683b4c7e80c02572704e/akka-remote/src/main/scala/akka/remote/artery/EnvelopeBufferPool.scala#L34-L36

Those few BigEndian buffers are causing the deserialization failures for remote instruments, because all lengths and key-length values are read wrong. Digging a bit deeper, I think the source of the problem is on the implementation of the `EnvelopeBuffer.copy` method:

https://github.com/akka/akka/blob/73a9bbb2643bc25a7a50683b4c7e80c02572704e/akka-remote/src/main/scala/akka/remote/artery/EnvelopeBufferPool.scala#L555-L564

The `ByteBuffer` returned on line 560 is marked as BigEndian by default. Explicitly marking it as LittleEndian right after creation should fix the issue we are seeing (and maybe others too!). I also tracked down usages of `EnvelopeBuffer.copy` to `ReusableInboundEnvelope.copyForLane`, and the only known use of `copyForLane` is here:

https://github.com/akka/akka/blob/73a9bbb2643bc25a7a50683b4c7e80c02572704e/akka-remote/src/main/scala/akka/remote/artery/Codecs.scala#L755-L771

I don't fully understand all the inner workings of handshaking or why it needs to be copied, but given the code and the context we are seeing, I think this explains why deserialization only breaks a few handshakes and then works normally.

Does this make sense? And if so, would you be willing to accept a PR with this tiny fix?

**Comment by patriknw** [comment] 2021-01-07 07:28
Thanks for investigating and finding that issue @ivantopo 
Makes sense and a PR would be much welcome.

**Comment by johanandren** [comment] 2021-01-19 13:26
I went ahead and made a PR from the suggestion, thanks for the detailed investigation/description though :)

**Comment by ivantopo** [comment] 2021-01-28 13:10
Hey guys, thanks a lot for moving forward with the PR! Happy to help :smile:

**Comment by patriknw** [comment] 2021-02-01 15:25
We have merged the fix. Would be great if @SimunKaracic or @ivantopo could try tomorrow's snapshot build to verify that it fixes the problem. See https://doc.akka.io/docs/akka/current/project/links.html#snapshots-repository

**Closed** 2021-02-01 15:25 UTC
Labels: bug, t:remoting:artery
