### ISSUE TITLE
FAILED: ReplicatedServiceRegistrySpecMultiJvmNode2

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17848] opened 2015-06-26 10:32 UTC
```
[JVM-2] - must remove terminated service *** FAILED *** (169 milliseconds)
[JVM-2]   Set("a1", "a2") was not equal to Set("a1") (ReplicatedServiceRegistrySpec.scala:239)
[JVM-2]   org.scalatest.exceptions.TestFailedException:
[JVM-2]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-2]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6231)
[JVM-2]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6265)
[JVM-2]   at sample.datareplication.ReplicatedServiceRegistrySpec$$anonfun$1$$anonfun$apply$mcV$sp$10$$anonfun$apply$mcV$sp$12.apply$mcV$sp(ReplicatedServiceRegistrySpec.scala:239)
[JVM-2]   at sample.datareplication.ReplicatedServiceRegistrySpec$$anonfun$1$$anonfun$apply$mcV$sp$10$$anonfun$apply$mcV$sp$12.apply(ReplicatedServiceRegistrySpec.scala:238)
[JVM-2]   at sample.datareplication.ReplicatedServiceRegistrySpec$$anonfun$1$$anonfun$apply$mcV$sp$10$$anonfun$apply$mcV$sp$12.apply(ReplicatedServiceRegistrySpec.scala:238)
[JVM-2]   at akka.testkit.TestKitBase$class.within(TestKit.scala:311)
[JVM-2]   at akka.testkit.TestKit.within(TestKit.scala:738)
[JVM-2]   at akka.testkit.TestKitBase$class.within(TestKit.scala:325)
[JVM-2]   at akka.testkit.TestKit.within(TestKit.scala:738)
[JVM-2]   at sample.datareplication.ReplicatedServiceRegistrySpec$$anonfun$1$$anonfun$apply$mcV$sp$10.apply$mcV$sp(ReplicatedServiceRegistrySpec.scala:238)
[JVM-2]   at sample.datareplication.ReplicatedServiceRegistrySpec$$anonfun$1$$anonfun$apply$mcV$sp$10.apply(ReplicatedServiceRegistrySpec.scala:228)
[JVM-2]   at sample.datareplication.ReplicatedServiceRegistrySpec$$anonfun$1$$anonfun$apply$mcV$sp$10.apply(ReplicatedServiceRegistrySpec.scala:228)
[JVM-2]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[JVM-2]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85
```

**Comment by patriknw** [comment] 2015-06-26 11:24
Duplicate of #17796

**Closed by patriknw** 2015-06-26 11:24 UTC
Labels: failed, t:distributed-data
