### ISSUE TITLE
Order of Terminated and messages with Artery

### ISSUE THREAD

**Issue by gbrd** [akka/akka#28695] opened 2020-03-05 16:36 UTC
Could you just consider again Bug #25361 ?
It was not solved on netty stack (which is still maintained ?) and migrating to artery seems not always very easy.

Our product is built on the principle that no messages are lost until Terminated is received (our actors are in stopping strategy) AND terminated is the last message received from one actorRef. With artery Terminated can be received before last messages from actorRef (because out of band...)

**Comment by patriknw** [comment] 2020-03-09 15:57
I don't understand how the order of the Terminated message is related to the original #25361?

Do you mean that you can't migrate to Artery because of the changed behavior of that Terminated may arrive before other messages that were sent before the actor stopped? If that is the case this issue should be renamed and describe that problem instead. Fixing classic remoting is not an option.

**Comment by gbrd** [comment] 2020-03-10 07:43
> Do you mean that you can't migrate to Artery because of the changed behavior of that Terminated may arrive before other messages that were sent before the actor stopped? 

Yes

> If that is the case this issue should be renamed and describe that problem instead. 

Ok ! Even better for me.

**Comment by patriknw** [comment] 2020-03-10 09:34
We'll look into if there is a way to deliver the Terminated message after other application messages.

**Comment by patriknw** [comment] 2020-07-03 07:56
@gbrd it took me a while to complete this, but in upcoming Akka 2.6.7 the Terminated message will be received after other messages

**Comment by johanandren** [comment] 2020-07-10 07:56
Just FYI @gbrd we had to back out of that fix for now, as we found issues we haven't been able to resolve yet with it.

**Comment by gbrd** [comment] 2020-07-28 14:50
> Just FYI @gbrd we had to back out of that fix for now, as we found issues we haven't been able to resolve yet with it.

ok thanks for informing.
I will wait for next version :)

**Comment by gbrd** [comment] 2020-09-10 08:13
Thus no more milestone for this ? :(

**Comment by raboof** [comment] 2020-09-10 08:30
> Thus no more milestone for this ? :(

We typically add a milestone when we merge the PR, so when you find a closed issue it is clear in what version the issue was resolved. That's why we added the 2.6.7 milestone just after merging #28940 .

Unfortunately we had to revert that PR since it caused test failures that seemed legitimate. At that point it'd have been most consistent to remove the milestone, but we probably expected it to be a quick fix and we bumped it to the next version instead. Unfortunately that didn't happen, it looks like #29502 is the latest iteration here?

**Comment by patriknw** [comment] 2020-09-10 08:49
Yes, #29502 should solve it but required some more review testing so it didn't make it into 2.6.9. Hopefully it will be included in 2.6.10.

**Comment by gbrd** [comment] 2020-09-10 09:06
it's a good news! thanks.

**Comment by patriknw** [comment] 2020-09-25 15:53
Fixed in https://github.com/akka/akka/pull/29502
Target 2.6.10.

**Closed by patriknw** 2020-09-25 15:53 UTC
Labels: 3 - in progress, t:remoting:artery

**Comment by gbrd** [comment] 2020-10-16 16:55
tested in 2.6.10 
Is this intended to work with remote deployment of child actor ? It sometimes fails in my load tests

I have a actor that create remote deployed child actors and save its address in a local data structure.
When all is ok the child send an applicative grafullterminated message (with useful data) to parent  before stopping when all is ok.
I sometimes receive terminated before gracefullterminated

```
16:38:13.909UTC WARN  [MySystem-akka.actor.default-dispatcher-21]akka://MySystem/system/sharding/Namespace/59/myapp-load/nsRoot/userdata-0/loadTest-0/-list-rooms-0- Terminated child but it is Alive in childInfoMap ! Actor[akka://MySystem@127.0.0.1:2552/remote/akka/MySystem@127.0.0.1:2551/system/sharding/Namespace/59/myapp-load/nsRoot/userdata-0/loadTest-0/-list-rooms-0/cxCdvM7NjC2uwizdVl8x-0#-1336243369] => GracefullyTerminated not received !
```
and just after :
```
16:38:13.922UTC ERROR [MySystem-akka.actor.default-dispatcher-5] manageGracefullyTerminated
 key not found: Actor[akka://MySystem@127.0.0.1:2552/remote/akka/MySystem@127.0.0.1:2551/system/sharding/Namespace/59/myapp-load/nsRoot/userdata-0/loadTest-0/-list-rooms-0/cxCdvM7NjC2uwizdVl8x-0#-1336243369]


```

**Comment by patriknw** [comment] 2020-10-19 08:34
@gbrd I think it should be the same message paths for that scenario so I'm surprised if that wouldn't work, although I typically recommend against using remote deployment in general.

I wrote another test that is creating 1000 remote deployed children. Stopping them all at about the same time, and each is sending 10 messages when stopping. Couldn't reproduce the problem.

Could you run your test with debug level logging and look for debug message starting with "Flush timeout".
The timeout is by default 3 seconds, and after that it continues anyway. Setting can be adjusted with
```
akka.remote.artery.advanced.death-watch-notification-flush-timeout = 3s
```

**Comment by gbrd** [comment] 2020-10-21 10:08
Thanks for your help @patriknw .
I made a test again and I can indeed find "flush timeout" debug messages (that may be understandable in a load test). 
I'm still investigating.
