### ISSUE TITLE
Unable to use `Accept-Encoding: gzip` with a `204` response

### ISSUE THREAD

**Issue by stjohnb** [akka/akka#20793] opened 2016-06-16 11:46 UTC
Accessing a resource which produces a 204 response and using the `Accept-Encoding: gzip` request header leads to a `IllegalArgumentException: requirement failed: Responses with this status code must have an empty entity`. If the gzip header is not requested, then the request succeeds with a 204 and an empty body

I've created a [repository](https://github.com/QuanTemplate/akka-issue) which [reproduces the issue](https://circleci.com/gh/QuanTemplate/akka-issue/4)

**Comment by pjazdzewski1990** [comment] 2016-06-16 16:49
I took a quick look (out of curiosity) and I see the error too. 
The requirement `fails` on condition in `HttpMessage` - `entity.isKnownEmpty || status.allowsEntity`.
For 204 the second one is always false, but that's not a problem. For the first part it really depends on the entity type (think: Strict vs Chunked). When doing `encodeResponse` using the routing DSL the Strict response is being transformed to a Chunked one. Chunked responses are processed using streams. As in streams accessing data is much harder `isKnownEmpty` is defined in terms "Is there any data processing attached?". In your case the answer is `yes` (encoding) so the condition fails. 
Solution that seems to work is making sure encoding is only attached to non-empty (non 204) responses. (in Encoder#encode) 
When somebody from the core contributors ( there are busy with Scala Days ;) ) confirms that this is an bug, we can push this further.
Minimal test to reproduce:
```
    Get() ~> `Accept-Encoding`(gzip) ~> {
        encodeResponse {
          complete { StatusCodes.NoContent }
        }
      } ~> check {
        status shouldBe StatusCodes.NoContent
      }
```

**Comment by gosubpl** [comment] 2016-06-16 20:30
We had a chat with @2beaucoup on a relevant part of RFC7230 quite recently. For the issue above the problem is that `Transfer-Encoding` is disallowed i.a. for 204 by https://tools.ietf.org/html/rfc7230#section-3.3.1. If I correctly recall, compression results in both `Content-Encoding: gzip` and `Transfer-Encoding: chunked` so I am not really sure whether this is actually a bug.

**Comment by pjazdzewski1990** [comment] 2016-06-20 13:03
Do we have a decision on this one?

**Comment by pjazdzewski1990** [comment] 2016-06-27 13:08
I think this ticket did fly under the radar (no labels) cc: @ktoso

**Comment by ktoso** [comment] 2016-06-27 14:04
We talked it over with @gosubpl over the weekend and I think the current behaviour may be correct spec wise. Question is if "spec is right but world is wrong" and we need to do anything more here – part of this ticket is to figure that out (please help ;-))

**Comment by pjazdzewski1990** [comment] 2016-07-01 12:49
I'm not going to fight the spec ;) 
This case looks like route DSL allowing more than it should. Not sure if we can do anything against it. Maybe issue a warning or message that this route makes little sense?

**Comment by stjohnb** [comment] 2016-07-01 13:27
To give the perspective of a consumer of akka-http (I assume it's not that unique)...
 
Our application has quite a lot of different resources, many of which return 204. Adding compression to our responses is something I would like to do at the very top level where all of our routes have been concatenated together. If the current behaviour is not changed, it means we cannot wrap our top-level route in an `encodeResponse` block and now must apply that to each individual resource that we know will never return a 204. 

For us that has made the `encodeResponse` directive essentially useless and we have moved compression out of our application and into our load balancer. IMHO it would be a big usability improvement to relax this requirement on the `HttpResponse` class

**Comment by Astrac** [comment] 2016-07-14 13:31
Is this relevant in deciding about this issue?

> The "identity" content-coding is always acceptable, unless specifically refused because the Accept-Encoding field includes "identity;q=0", or because the field includes "*;q=0" and does not explicitly include the "identity" content-coding. If the Accept-Encoding field-value is empty, then only the "identity" encoding is acceptable.

As taken from: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by ktoso** [comment] 2016-07-14 13:33
Thanks for digging that up @Astrac, that helps in driving the decision to loosen up here.
If someone would like to take stab here–please do. We currently don't have the capacity.

**Comment by Astrac** [comment] 2016-07-22 17:30
I was trying to solve this issue and I wonder where is the best place to do it; the option I found so far is adding another condition for the `DefaultFilter` function defined here:

https://github.com/akka/akka/blob/acb71ac4e53d536fcba0ffe0fb0a48c09a63b108/akka-http/src/main/scala/akka/http/scaladsl/coding/Encoder.scala#L48

The additional condition would be that the status should not belong to a set of not-to-be-compressed status codes like 204, 304 or 1xx.

Would this be acceptable?

**Comment by gosubpl** [comment] 2016-08-01 10:04
@Astrac yes, this is the place where the filter should be implemented. Please note that the code you are quoting is not from `master` as I have changed this to simply `isCompressible _` - https://github.com/akka/akka/blob/master/akka-http/src/main/scala/akka/http/scaladsl/coding/Encoder.scala#L46 while fixing some other bug. Try putting in some tests first - take a look [here](https://github.com/gosubpl/akka/commit/54c99d8184c7a2cbf5f9f05008d26fa8fe4c539c ) and at the related issue for discussion and possible starting points.

**Comment by gosubpl** [comment] 2016-08-29 20:40
Hi @Astrac are you still interested in submitting a PR for this issue?

**Comment by 2beaucoup** [comment] 2016-09-06 12:32
@stjohnb: Why are you completing with a future ([here](https://github.com/QuanTemplate/akka-issue/blob/master/src/main/scala/com/quantemplate/akka/issue/Server.scala#L29))? It should succeed with a `complete(HttpResponse(StatusCodes.NoContent))` as that is guaranteed to be empty.

**Comment by jrudolph** [comment] 2016-09-06 13:03
The problem seems to be how `PredefinedToResponseMarshallers.fromStatusCode` is creating responses:

```scala
  implicit val fromStatusCode: TRM[StatusCode] =
    Marshaller.withOpenCharset(`text/plain`) { (status, charset) ⇒
      HttpResponse(status, entity = HttpEntity(ContentType(`text/plain`, charset), status.defaultMessage))
    }
```

which is probably a bad idea for StatusCodes with `allowEntity = false`.

**Comment by jrudolph** [comment] 2016-09-06 13:11
What happens is that an empty entity announces a content-type of `none/none` which *is not* compressible while `fromStatusCode` creates an empty `text/plain` entity which *is* compressible.

Let's see what we could do:

 * RFC7230 requirement should be checked:

```
     A server MUST NOT send a Transfer-Encoding header field in any
     response with a status code of 1xx (Informational) or 204 (No
     Content).  A server MUST NOT send a Transfer-Encoding header field in
     any 2xx (Successful) response to a CONNECT request (Section 4.3.6 of
     [RFC7231]).
```

 * (known to be) empty entities should never be encoded
 * `fromStatusCode` should be improved to create an empty entity if the status code doesn't allow an entity

WDYT??

**Comment by 2beaucoup** [comment] 2016-09-06 13:15
> A server MUST NOT send a Transfer-Encoding header field in any
>      response with a status code of 1xx (Informational) or 204 (No
>      Content).  A server MUST NOT send a **Transfer-Encoding** header field in
>      any 2xx (Successful) response to a CONNECT request (Section 4.3.6 of
>      [RFC7231]).

But we're talking **Content Encoding** here, right?

**Comment by jrudolph** [comment] 2016-09-06 13:22
> But we're talking Content Encoding here, right?

On one hand, yes, but the problem here is that the GZip encoder produces a Chunked entity which creates a `TransferEncoding`...

**Comment by 2beaucoup** [comment] 2016-09-06 13:23
Workaround for this issue: `complete` with an explicit `HttpResponse(StatusCodes.XXX)` with an empty entity instead of a `complete(StatusCodes.XXX)` which execudes the code posted above by @jrudolph.

**Comment by 2beaucoup** [comment] 2016-09-06 13:24
> On one hand, yes, but the problem here is that the GZip encoder produces a Chunked entity which creates a TransferEncoding...

I see. Does it always do that or only for payloads that exceed a certain threshold?

**Comment by jrudolph** [comment] 2016-09-06 13:24
I wonder if the new check really is necessary because that's basically what in HttpResponse is currently checked by

```scala
require(entity.isKnownEmpty || status.allowsEntity, ...)
```

**Comment by jrudolph** [comment] 2016-09-06 13:31
> Does it always do that or only for payloads that exceed a certain threshold?

Always, because it always goes through the call path that uses the streaming encoder (but we could think about changing that).

**Comment by gosubpl** [comment] 2016-09-06 14:22
will submit PR soon, as per the discussion on `akka/dev` gitter channel

**Comment by jrudolph** [comment] 2016-09-07 17:17
This should be fixed by now. I created #21393 to improve handling in the encoder as well.

**Closed by jrudolph** 2016-09-07 17:17 UTC
Labels: 1 - triaged, community, t:http
