### ISSUE TITLE
FAILED: PersistentActorRecoveryTimeoutSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20906] opened 2016-07-07 11:13 UTC
https://jenkins.akka.io:8498/job/akka-nightly/3482/consoleFull

```
[info] PersistentActorRecoveryTimeoutSpec:
Coroner Thread Count starts at 11 in akka.persistence.PersistentActorRecoveryTimeoutSpec
[info] The recovery timeout
[WARN] [07/06/2016 21:33:50.003] [PersistentActorRecoveryTimeoutSpec-akka.actor.default-dispatcher-3] [akka://PersistentActorRecoveryTimeoutSpec/user/$a] received dead letter from Actor[akka://PersistentActorRecoveryTimeoutSpec/system/testActor-2#699640122]: A
[info] - should fail recovery if timeout is not met when recovering *** FAILED *** (3 seconds, 812 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.persistence.journal.SteppingInmemJournal$.step(SteppingInmemJournal.scala:30)
[info]   at akka.persistence.PersistentActorRecoveryTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(PersistentActorRecoveryTimeoutSpec.scala:76)
[info]   at akka.persistence.PersistentActorRecoveryTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(PersistentActorRecoveryTimeoutSpec.scala:65)
[info]   at akka.persistence.PersistentActorRecoveryTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(PersistentActorRecoveryTimeoutSpec.scala:65)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:57)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:57)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:57)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:57)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:57)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:57)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
[WARN] [07/06/2016 21:33:53.054] [PersistentActorRecoveryTimeoutSpec-akka.actor.default-dispatcher-4] [akka://PersistentActorRecoveryTimeoutSpec/deadLetters] received dead letter from Actor[akka://PersistentActorRecoveryTimeoutSpec/system/akka.persistence.journal.stepping-inmem#-728459192]: TokenConsumed
[info] - should should not interfere with receive timeouts *** FAILED *** (3 seconds, 20 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.persistence.journal.SteppingInmemJournal$.step(SteppingInmemJournal.scala:30)
[info]   at akka.persistence.PersistentActorRecoveryTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(PersistentActorRecoveryTimeoutSpec.scala:109)
[info]   at akka.persistence.PersistentActorRecoveryTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(PersistentActorRecoveryTimeoutSpec.scala:99)
[info]   at akka.persistence.PersistentActorRecoveryTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(PersistentActorRecoveryTimeoutSpec.scala:99)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:57)
```

**Comment by drewhk** [comment] 2016-07-22 09:04
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/416/consoleFull

**Comment by johanandren** [comment] 2016-08-11 09:32
Duplicate of #20728

**Closed by johanandren** 2016-08-11 09:32 UTC
Labels: 1 - triaged, failed
