### ISSUE TITLE
AIOOB exception during shutdown of stage

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#19067] opened 2015-12-02 12:35 UTC
Don't have a reproducer right now:

```
[info] java.lang.ArrayIndexOutOfBoundsException: -1
[info] 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:541)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:509)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$tryAbort(ActorGraphInterpreter.scala:438)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$runBatch(ActorGraphInterpreter.scala:423)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:346)
[info] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:292)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
[info] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
[info] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by drewhk** [comment] 2015-12-02 12:40
The context is important here. What did you do when it happened?

**Comment by jrudolph** [comment] 2015-12-02 12:46
How would I know when it happens exactly, the stack trace contains nothing from my app? I guess it happens here:

https://github.com/jrudolph/akka-http-scala-js-websocket-chat/blob/AIOOB/cli/src/main/scala/example/akkawschat/cli/ConsoleDSL.scala#L73

You can reproduce it by running 

```
cli/run-main example.akkawschat.cli.ConsoleDSLTestApp
```

and then pressing Ctrl-D.

**Comment by drewhk** [comment] 2015-12-02 13:10
I am not sure. Since the stacktrace contains `tryAbort` it is has already encountered an error and tires to process those messages. That is where the error happens.

**Comment by drewhk** [comment] 2015-12-02 13:21
Ok I have no clue, I will need to run this to see what is the problem.

**Comment by ktoso** [comment] 2015-12-03 14:46
Marked as bug so we'll revisit this sooner rather than later, feel free to unmark if deemed not a bug after investigation.

**Comment by drewhk** [comment] 2015-12-14 13:34
@jrudolph I cannot start it, since I have no stty on Windows. Can you create a more standalone reproducer maybe?

**Comment by jrudolph** [comment] 2015-12-14 13:54
You can probably just comment the stty part.

**Comment by drewhk** [comment] 2015-12-14 13:54
ok, I'll try.

**Comment by drewhk** [comment] 2015-12-14 14:07
Hm, now I have trouble making it receive `Ctrl+D`.

**Comment by drewhk** [comment] 2015-12-14 14:09
ok, now got it working.

**Comment by drewhk** [comment] 2015-12-14 14:33
I think I get it. You call `pull()` after you completed the stage (L52 should be `if (!isClosed(characterInput)) pull(characterInput)`). This fires an exception, which forces the ActorGraphInterpreter to try failing the stage. Then there is likely a bug there which causes a second exception. So, one bug is in your code, the second one is in the interpreter in error handling which I can now probably reproduce in isolation.

**Comment by jrudolph** [comment] 2015-12-14 14:47
Can't this be checked automatically and the pull just be ignored in that case?

**Comment by drewhk** [comment] 2015-12-14 14:59
There is usually a logic bug if you try to pull when you shouldn't. Double completion is allowed though. The issue here is that the stage was already stopped, and then it was invalid from the interpreter to try to fail it again. My fix will simply log an error indicating that the stage has failed after being completed.

**Comment by jrudolph** [comment] 2015-12-14 15:08
But this is racy in any case. You may pull just before you were completed or just after, it doesn't really make any difference because you don't control upstream completion.

**Comment by drewhk** [comment] 2015-12-14 15:16
@jrudolph there is no race here. You called `completeStage()` and then `pull()` from the same event handler.

**Comment by jrudolph** [comment] 2015-12-14 15:22
No, of course, I can prevent the issue here. I was arguing that it would make sense to make `pull` idempotent so I don't need to change my code :)

**Comment by drewhk** [comment] 2015-12-14 15:26
we don't make pull/push idempotent or ignoring completion since they usually are logic bugs in the first place. There are the emit/read etc. higher level APIs for more convenience though. In my fix your code will log an ERROR though (since the stage cannot propagate the failure).

**Comment by jrudolph** [comment] 2015-12-14 15:31
Ok, fair enough, I can build my own idempotent pull.

**Comment by drewhk** [comment] 2015-12-16 08:11
Error reporting fixed now.

**Closed by drewhk** 2015-12-16 08:11 UTC
Labels: 3 - in progress, bug, t:stream
