### ISSUE TITLE
FAILED: TlsSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20368] opened 2016-04-20 08:51 UTC
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3744/consoleFull

```
[info] - must emit an error if the TLS handshake fails certificate checks *** FAILED *** (34 milliseconds)
[info]   akka.stream.StreamTcpException: The connection actor has terminated. Stopping now.
```

**Comment by johanandren** [comment] 2016-04-25 15:42
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/5939/consoleFull

**Comment by johanandren** [comment] 2016-06-01 18:03
https://jenkins.akka.io:8498/job/akka-multi-node/1563/consoleFull

**Comment by 2m** [comment] 2016-06-24 05:00
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3941/consoleFull

**Comment by patriknw** [comment] 2016-12-22 09:50
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/572

```
2712.062: [GC remark 2712.062: [Finalize Marking, 0.0285437 secs] 2712.091: [GC ref-proc, 0.0106609 secs] 2712.102: [Unloading, 4.6831449 secs], 4.7342482 secs]
 [Times: user=0.00 sys=155.27, real=4.73 secs] 
2716.800: [GC cleanup 1386M->675M(3072M), 0.0401847 secs]
 [Times: user=0.00 sys=0.00, real=0.04 secs] 
2716.840: [GC concurrent-cleanup-start]
2716.847: [GC concurrent-cleanup-end, 0.0066234 secs]
--- Stream actors debug dump ---
Stream actors alive: List(Actor[akka://TlsSpec/user/StreamSupervisor-65/flow-2-0-unknown-operation#1955217577], Actor[akka://TlsSpec/user/StreamSupervisor-65/flow-2-1-unknown-operation#1755064018], Actor[akka://TlsSpec/user/StreamSupervisor-65/flow-2-2-unknown-operation#-55578855])
[WARN] [12/22/2016 08:03:24.249] [TlsSpec-akka.actor.default-dispatcher-4] [akka://TlsSpec/user/StreamSupervisor-65/flow-2-0-unknown-operation] received dead letter from Actor[akka://TlsSpec/deadLetters]: PrintDebugDump
[WARN] [12/22/2016 08:03:24.251] [TlsSpec-akka.actor.default-dispatcher-4] [akka://TlsSpec/user/StreamSupervisor-65/flow-2-1-unknown-operation] received dead letter from Actor[akka://TlsSpec/deadLetters]: PrintDebugDump
[WARN] [12/22/2016 08:03:24.251] [TlsSpec-akka.actor.default-dispatcher-4] [akka://TlsSpec/user/StreamSupervisor-65/flow-2-2-unknown-operation] received dead letter from Actor[akka://TlsSpec/deadLetters]: PrintDebugDump
[INFO] [12/22/2016 08:03:24.248] [TlsSpec-akka.actor.default-dispatcher-2] [akka://TlsSpec/user/StreamSupervisor-65/flow-2-0-unknown-operation] Message [akka.stream.impl.StreamSupervisor$PrintDebugDump$] from Actor[akka://TlsSpec/deadLetters] to Actor[akka://TlsSpec/user/StreamSupervisor-65/flow-2-0-unknown-operation#1955217577] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [12/22/2016 08:03:24.249] [TlsSpec-akka.actor.default-dispatcher-2] [akka://TlsSpec/user/StreamSupervisor-65/flow-2-1-unknown-operation] Message [akka.stream.impl.StreamSupervisor$PrintDebugDump$] from Actor[akka://TlsSpec/deadLetters] to Actor[akka://TlsSpec/user/StreamSupervisor-65/flow-2-1-unknown-operation#1755064018] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [12/22/2016 08:03:24.249] [TlsSpec-akka.actor.default-dispatcher-2] [akka://TlsSpec/user/StreamSupervisor-65/flow-2-2-unknown-operation] Message [akka.stream.impl.StreamSupervisor$PrintDebugDump$] from Actor[akka://TlsSpec/deadLetters] to Actor[akka://TlsSpec/user/StreamSupervisor-65/flow-2-2-unknown-operation#-55578855] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] - must work in mode ClientInitiates while sending LargeMessages *** FAILED *** (10 seconds, 50 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [8 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.stream.io.TlsSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(TlsSpec.scala:375)
```

**Comment by ktoso** [comment] 2016-12-22 10:38
And again https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/8085/

```
[info] - must work in mode ServerInitiatesViaTcp while sending EmptyBytesFirst *** FAILED *** (6 seconds, 711 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [2 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.stream.io.TlsSpec$$anonfun$1.akka$stream$io$TlsSpec$$anonfun$$server$1(TlsSpec.scala:146)
[info]   at akka.stream.io.TlsSpec$$anonfun$1$ServerInitiatesViaTcp$2$.decorateFlow(TlsSpec.scala:163)
[info]   at akka.stream.io.TlsSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(TlsSpec.scala:354)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
[info]   at akka.stream.io.TlsSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$6$$anonfun$apply$7.apply(TlsSpec.scala:350)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:26)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:59)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:59)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:59)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
```

**Comment by patriknw** [comment] 2017-03-24 07:39
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4757

**Comment by jrudolph** [comment] 2017-03-24 10:09
For many of the cases likely a duplicate of #22124.

**Comment by johanandren** [comment] 2017-03-24 14:47
Hopefully cloud by Johannes fix.

**Closed by johanandren** 2017-03-24 14:47 UTC
Labels: 1 - triaged, failed, t:io, t:io:tls, t:stream

**Comment by 2m** [comment] 2017-03-27 08:44
No more TlsSpec failures in the nightlies during the weekend. Yay!

**Comment by jrudolph** [comment] 2017-03-27 15:22
Woohoo, great!
