### ISSUE TITLE
First seed node not rejoining cluster

### ISSUE THREAD

**Issue by tpantelis** [akka/akka#25361] opened 2018-07-17 23:12 UTC
akka version: 2.5.11

In a 3-node cluster setup, upon killing and restarting the first seed node (as listed in the akka.conf), we sometimes see that the node does not or is not allowed to rejoin the cluster. After the seed node timeout, which we have set to 12s, it joins itself and forms a cluster island. This is automated in a robot test environment.

As an example, we have node1 (first seed node - address 10.30.170.94), node2 (10.30.170.26), and node3 (10.30.170.84). Initially all the nodes are started and connected and the cluster is working correctly. Then a kill -9 is issued to node1.  Both node2 and node3 lose connection and mark node1 as unreachable as expected. On node2, we see:

```
2018-07-16T11:17:14,609 | WARN  | opendaylight-cluster-data-akka.actor.default-dispatcher-20 | ReliableDeliverySupervisor       | 41 - com.typesafe.akka.slf4j - 2.5.11 | Association with remote system [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550]] Caused by: [Connection refused: /10.30.170.94:2550]

2018-07-16T11:17:18,229 | INFO  | opendaylight-cluster-data-akka.actor.default-dispatcher-18 | Cluster(akka://opendaylight-cluster-data) | 41 - com.typesafe.akka.slf4j - 2.5.11 | Cluster Node [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550] - Leader can currently not perform its duties, reachability status: [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550 -> akka.tcp://opendaylight-cluster-data@10.30.170.94:2550: Unreachable [Unreachable] (1), akka.tcp://opendaylight-cluster-data@10.30.170.84:2550 -> akka.tcp://opendaylight-cluster-data@10.30.170.94:2550: Unreachable [Unreachable] (1)], member status: [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550 Up seen=true, akka.tcp://opendaylight-cluster-data@10.30.170.84:2550 Up seen=true, akka.tcp://opendaylight-cluster-data@10.30.170.94:2550 Up seen=false]
```

On node3:

```
2018-07-16T11:18:14,859 | WARN  | opendaylight-cluster-data-akka.actor.default-dispatcher-3 | ReliableDeliverySupervisor       | 41 - com.typesafe.akka.slf4j - 2.5.11 | Association with remote system [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550]] Caused by: [Connection refused: /10.30.170.94:2550]
```

After restarting node1, we see that it sends InitJoin messages to node2 and node3 and actually reports an InitJoinAck from node2 but eventually joins itself after 22s:

```
2018-07-16T11:18:20,251 | INFO  | opendaylight-cluster-data-akka.actor.default-dispatcher-21 | Cluster(akka://opendaylight-cluster-data) | 41 - com.typesafe.akka.slf4j - 2.5.11 | Cluster Node [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550] - Received InitJoinAck message from [Actor[akka.tcp://opendaylight-cluster-data@10.30.170.26:2550/system/cluster/core/daemon#-1596937295]] to [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550]

2018-07-16T11:18:42,585 | INFO  | opendaylight-cluster-data-akka.actor.default-dispatcher-19 | Cluster(akka://opendaylight-cluster-data) | 41 - com.typesafe.akka.slf4j - 2.5.11 | Cluster Node [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550] - Node [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550] is JOINING, roles [member-1, dc-default]

2018-07-16T11:18:42,614 | INFO  | opendaylight-cluster-data-akka.actor.default-dispatcher-19 | Cluster(akka://opendaylight-cluster-data) | 41 - com.typesafe.akka.slf4j - 2.5.11 | Cluster Node [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550] - Leader is moving node [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550] to [Up]
```

On node2, we see InitJoin messages incoming and InitJoinAcks outgoing and that it noticed that node1 was restarted with a new incarnation, marked it as Down, and stated it was removing the previous unreachable incarnation:

```
2018-07-16T11:18:20,105 | INFO  | opendaylight-cluster-data-akka.actor.default-dispatcher-2 | Cluster(akka://opendaylight-cluster-data) | 41 - com.typesafe.akka.slf4j - 2.5.11 | Cluster Node [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550] - Received InitJoin message from [Actor[akka.tcp://opendaylight-cluster-data@10.30.170.94:2550/system/cluster/core/daemon/firstSeedNodeProcess-1#-2094984711]] to [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550]

2018-07-16T11:18:20,106 | INFO  | opendaylight-cluster-data-akka.actor.default-dispatcher-2 | Cluster(akka://opendaylight-cluster-data) | 41 - com.typesafe.akka.slf4j - 2.5.11 | Cluster Node [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550] - Sending InitJoinAck message from node [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550] to [Actor[akka.tcp://opendaylight-cluster-data@10.30.170.94:2550/system/cluster/core/daemon/firstSeedNodeProcess-1#-2094984711]]

2018-07-16T11:18:20,291 | INFO  | opendaylight-cluster-data-akka.actor.default-dispatcher-18 | Cluster(akka://opendaylight-cluster-data) | 41 - com.typesafe.akka.slf4j - 2.5.11 | Cluster Node [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550] - New incarnation of existing member [Member(address = akka.tcp://opendaylight-cluster-data@10.30.170.94:2550, status = Up)] is trying to join. **Existing will be removed from the cluster and then new member will be allowed to join.**

2018-07-16T11:18:20,292 | INFO  | opendaylight-cluster-data-akka.actor.default-dispatcher-18 | Cluster(akka://opendaylight-cluster-data) | 41 - com.typesafe.akka.slf4j - 2.5.11 | Cluster Node [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550] - **Marking unreachable node [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550] as [Down]**

2018-07-16T11:18:21,226 | INFO  | opendaylight-cluster-data-akka.actor.default-dispatcher-22 | Cluster(akka://opendaylight-cluster-data) | 41 - com.typesafe.akka.slf4j - 2.5.11 | Cluster Node [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550] - **Leader is removing unreachable node [akka.tcp://opendaylight-cluster-data@10.30.170.94:2550]**

2018-07-16T11:18:30,564 | INFO  | opendaylight-cluster-data-akka.actor.default-dispatcher-2 | Cluster(akka://opendaylight-cluster-data) | 41 - com.typesafe.akka.slf4j - 2.5.11 | Cluster Node [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550] - Received InitJoin message from [Actor[akka.tcp://opendaylight-cluster-data@10.30.170.94:2550/system/cluster/core/daemon/firstSeedNodeProcess-2#2006731653]] to [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550]

2018-07-16T11:18:30,565 | INFO  | opendaylight-cluster-data-akka.actor.default-dispatcher-2 | Cluster(akka://opendaylight-cluster-data) | 41 - com.typesafe.akka.slf4j - 2.5.11 | Cluster Node [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550] - Sending InitJoinAck message from node [akka.tcp://opendaylight-cluster-data@10.30.170.26:2550] to [Actor[akka.tcp://opendaylight-cluster-data@10.30.170.94:2550/system/cluster/core/daemon/firstSeedNodeProcess-2#2006731653]]
```

followed by several more InitJoin/InitJoinAck sequences...

node3 shows similar InitJoin/InitJoinAck sequences.

I can't see any reason from this output why node1 was not allowed to rejoin. Clearly there was network communication between node1 and node2/node3 after the restart and node2 and node3 remained connected (ie there were no disconnect/disassociation log messages reported).  So the old incarnation of node1 should be removed (as was reported in the logs) and the new incarnation should be allowed to join. 

Note this happens sporadically - most of the time it works as expected.

Also note that this only seems to happen when the node is killed - we haven’t seen it when the node is gracefully shutdown.

**Comment by johanandren** [comment] 2018-07-25 13:21
For reference, same issue in forum: https://discuss.lightbend.com/t/first-seed-node-not-rejoining-cluster/1637

**Comment by tpantelis** [comment] 2018-07-31 12:17
We reproduced it with akka.remote and akka.cluster debug enabled. I've attached the full logs for each  node during the time node1 was restarted. The IPs are:

node1: 172.28.5.1
node2: 172.28.5.2
node3: 172.28.5.3

According to the output, the bottom line is that node1 was able to send messages (InitJoin) to nodes 2 and 3 but no messages from nodes 2 and 3 were received by node1 (IntJoinAck, Heartbeat). This differs slightly from the failure case described above in that node1 did actually receive one InitJoinAck message.


[node1.log](https://github.com/akka/akka/files/2245212/node1.log)
[node2.log](https://github.com/akka/akka/files/2245213/node2.log)
[node3.log](https://github.com/akka/akka/files/2245214/node3.log)

**Comment by patriknw** [comment] 2018-07-31 19:48
@tpantelis Thanks for the logs. I can confirm what you said. node1 doesn't receive the messages from node2 and node3. Since it happens for both node2 and node3 I don't think it's one of those nasty race conditions bugs that we have been hunting over the years in classic remoting.

Perhaps you can try this config:
```
akka.remote.use-passive-connections = off
```

That will open a new tcp connection for the replies from node2 and node3 instead of reusing the inbound tcp connection. Might be a workaround, or we might understand something from other error messages (if any).

Can we completely exclude that this isn't a bug or misconfiguration in the OpenDailight network stack? Could packets be dropped in one direction of a tcp connection for some reason? Could you use tcpdump/wireshark or similar to investigate what is sent/received on a lower level?

**Comment by jluhrsen** [comment] 2018-07-31 19:58
thanks for the reply @patriknw.

I am reproducing this with a 3 node OpenDaylight cluster in 3 docker containers on a single laptop. I
will see if I can grab some packet traces, but might take some time to get right. I have to run this test
in a loop and let it run until it hits (sometimes hours).

I also learned today (from @tpantelis) that artery is using UDP so I can also try with that configuration
separately to see if we can learn anything

We can see if there is something at a lower level in ODL w/ regard to what is sent/received.

This is definitely a fun one :)

**Comment by chbatey** [comment] 2018-08-01 06:40
FYI Artery can use UDP or TCP.

**Comment by tpantelis** [comment] 2018-08-15 15:48
We were able to get a packet capture. It basically shows what we've seen in the logs, ie node1 is sending out InitJoin messages to 2 & 3 and InitJoinAck messages are coming back. Also akka Heartbeat messages are incoming from 2 & 3 along with our (Opendaylight) AppendEntries heartbeats. So node1 is sending out messages and messages from 2 & 3 are getting to node1 (so there's no network issues) but are not getting processed for some reason. 

I attached the zipped pcap file.
[105.pcap.gz](https://github.com/akka/akka/files/2290770/105.pcap.gz)

**Comment by tpantelis** [comment] 2018-08-15 16:48
We've already enabled debug which logs all incoming and outgoing messages. I assume we'd have to get down to the lowest layer which actually reads from the socket.

We also have a packet capture for a successful run where it did re-join (I forgot to include that before). In this case, node1 sent an InternalClusterAction$Join message to node2 after receiving the InitJoinAck.
[104.pcap.gz](https://github.com/akka/akka/files/2290978/104.pcap.gz)

**Comment by patriknw** [comment] 2018-08-15 17:40
Thanks for those traces and that we are able to narrow in on this. Next step would probably be to add some additional logging to Akka and run with a snapshot of that. Such as in https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/transport/netty/TcpSupport.scala#L50 and https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/Endpoint.scala#L938

**Comment by tpantelis** [comment] 2018-11-26 00:01
The problem has not been seen with Artery UDP (was not tried with Artery TCP). It's still a problem with netty TCP but it doesn't seem there's much point in pursuing that code base.

**Comment by patriknw** [comment] 2018-11-26 10:13
Thanks for the update. Closing.

**Closed by patriknw** 2018-11-26 10:13 UTC
Labels: 0 - new, t:cluster

**Comment by gbrd** [comment] 2019-12-18 15:22
> The problem has not been seen with Artery UDP (was not tried with Artery TCP). It's still a problem with netty TCP but it doesn't seem there's much point in pursuing that code base.

... maybe it could be because migrated from netty to artery seems to have code impact in some cases.
Our product is built on the principle that no messages are lost until Terminated is received  (our actors are in stopping strategy) AND terminated is the last message received from one actorRef. With artery Terminated can be received before last messages from actorRef (because out of band...)
